; highlights.scm — Auto-generated by @modelscript/compiler
; Language: step
; Do not edit manually — regenerate with: npm run generate

; ─── Keywords ───────────────────────────────────────────────────────
[
] @keyword

; ─── Type references ──────────────────────────────────────────────
(OwnedFeatureTyping (QualifiedName) @type)
(ConjugatedPortTyping (QualifiedName) @type)
(OwnedReferenceSubsetting (QualifiedName) @type)
(OwnedSubsetting (QualifiedName) @type)
(OwnedRedefinition (QualifiedName) @type)
(Subclassification (QualifiedName) @type)

; ─── Operators ────────────────────────────────────────────────────
[
  "*"
] @operator

; ─── Comments ─────────────────────────────────────────────────────
(BLOCK_COMMENT) @comment

; ─── Literals ─────────────────────────────────────────────────────

; ─── Boolean/null literals ─────────────────────────────────────────

; ─── Identifier fallback ──────────────────────────────────────────
(Name) @variable

