// SPDX-License-Identifier: AGPL-3.0-or-later

import * as fs from "node:fs/promises";

// In a real production system, this worker would integrate with a headless CAM slicer.
// E.g. invoking FreeCAD Path module via python script, or Kiri:Moto node API,
// or CuraEngine CLI. For the purpose of scaffolding the pipeline, we simulate the output.

interface CamJobData {
  stepFilePath: string;
  outputGcodePath: string;
  config: {
    toolDiameter?: number;
    feedRate?: number;
    spindleSpeed?: number;
  };
}

async function runCamJob(data: CamJobData) {
  console.log(`[CamWorker] Starting CAM generation for ${data.stepFilePath}`);

  const toolDiameter = data.config.toolDiameter ?? 3.175;
  const feedRate = data.config.feedRate ?? 1000;
  const plungeRate = Math.round(feedRate * 0.3);
  const spindleSpeed = data.config.spindleSpeed ?? 10000;
  const safeZ = 5.0;
  const stepover = toolDiameter * 0.65;

  // Extract real geometric bounds from STEP Cartesian points if available
  let minX = -25.0,
    maxX = 25.0;
  let minY = -25.0,
    maxY = 25.0;
  let minZ = -5.0,
    maxZ = 0.0;

  try {
    const stepText = await fs.readFile(data.stepFilePath, "utf8");
    const pointMatches = stepText.matchAll(
      /CARTESIAN_POINT\s*\([^,]*,\s*\(\s*([-\d.eE]+)\s*,\s*([-\d.eE]+)\s*,\s*([-\d.eE]+)\s*\)\s*\)/g,
    );
    let count = 0;
    let pMinX = Infinity,
      pMaxX = -Infinity;
    let pMinY = Infinity,
      pMaxY = -Infinity;
    let pMinZ = Infinity,
      pMaxZ = -Infinity;

    for (const match of pointMatches) {
      const x = parseFloat(match[1]!);
      const y = parseFloat(match[2]!);
      const z = parseFloat(match[3]!);
      if (!isNaN(x) && !isNaN(y) && !isNaN(z)) {
        if (x < pMinX) pMinX = x;
        if (x > pMaxX) pMaxX = x;
        if (y < pMinY) pMinY = y;
        if (y > pMaxY) pMaxY = y;
        if (z < pMinZ) pMinZ = z;
        if (z > pMaxZ) pMaxZ = z;
        count++;
      }
    }

    if (count >= 4 && pMaxX - pMinX > 1 && pMaxY - pMinY > 1) {
      minX = pMinX;
      maxX = pMaxX;
      minY = pMinY;
      maxY = pMaxY;
      minZ = pMinZ;
      maxZ = pMaxZ;
    }
  } catch (err) {
    console.warn(`[CamWorker] Could not parse STEP geometry points directly, using stock bounds:`, err);
  }

  const stockWidth = maxX - minX;
  const stockHeight = maxY - minY;
  const targetDepth = Math.min(-1.0, minZ);
  const stepdown = Math.min(1.5, Math.abs(targetDepth) / 2);

  let gcode = `( ============================================================================ )
( Generated by ModelScript CAM Toolpath Engine )
( Model: ${data.stepFilePath} )
( Tool Diameter: ${toolDiameter.toFixed(3)}mm )
( Stock Dimensions: ${stockWidth.toFixed(2)}mm x ${stockHeight.toFixed(2)}mm x ${Math.abs(targetDepth).toFixed(2)}mm )
( ============================================================================ )

G21 ; Metric units
G90 ; Absolute positioning
G17 ; XY plane selection
G94 ; Feed rate in mm/min
M3 S${spindleSpeed} ; Spindle on clockwise
G0 Z${safeZ.toFixed(3)} ; Rapid to clearance plane

( --- Operation 1: Facing Pass --- )
`;

  // 1. Facing pass (zigzag)
  let y = minY;
  let direction = 1;
  while (y <= maxY + stepover * 0.5) {
    const xStart = direction === 1 ? minX - toolDiameter : maxX + toolDiameter;
    const xEnd = direction === 1 ? maxX + toolDiameter : minX - toolDiameter;

    gcode += `G0 X${xStart.toFixed(3)} Y${y.toFixed(3)}\n`;
    gcode += `G1 Z0.000 F${plungeRate}\n`;
    gcode += `G1 X${xEnd.toFixed(3)} F${feedRate}\n`;
    gcode += `G0 Z${safeZ.toFixed(3)}\n`;

    y += stepover;
    direction = -direction;
  }

  process.send?.({ type: "progress", classesProcessed: 35 });

  gcode += `\n( --- Operation 2: 2.5D Profile Contouring --- )\n`;

  // 2. Profile contour with multi-pass depth
  let currentZ = -stepdown;
  const margin = toolDiameter / 2;
  const cMinX = minX - margin;
  const cMaxX = maxX + margin;
  const cMinY = minY - margin;
  const cMaxY = maxY + margin;

  while (currentZ >= targetDepth - 0.001) {
    gcode += `( Pass at Z = ${currentZ.toFixed(3)}mm )\n`;
    gcode += `G0 X${cMinX.toFixed(3)} Y${cMinY.toFixed(3)}\n`;
    gcode += `G1 Z${currentZ.toFixed(3)} F${plungeRate}\n`;
    gcode += `G1 X${cMaxX.toFixed(3)} F${feedRate}\n`;
    gcode += `G1 Y${cMaxY.toFixed(3)}\n`;
    gcode += `G1 X${cMinX.toFixed(3)}\n`;
    gcode += `G1 Y${cMinY.toFixed(3)}\n`;
    gcode += `G0 Z${safeZ.toFixed(3)}\n`;

    currentZ -= stepdown;
  }

  process.send?.({ type: "progress", classesProcessed: 80 });

  gcode += `
( --- End of Toolpath Program --- )
G0 Z${safeZ.toFixed(3)} ; Rapid retract
M5 ; Spindle stop
G0 X0.000 Y0.000 ; Return home
M30 ; End of program
`;

  await fs.writeFile(data.outputGcodePath, gcode);
  console.log(`[CamWorker] Generated GCode written to ${data.outputGcodePath}`);
}

process.on("message", async (data: unknown) => {
  try {
    const jobData = data as CamJobData;
    await runCamJob(jobData);
    process.send?.({ type: "complete", classesProcessed: 100 });
    process.exit(0);
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("[CamWorker] Error running CAM job:", err);
    process.send?.({ type: "error", error: errorMsg });
    process.exit(1);
  }
});
