import * as fs from "node:fs/promises";

// In a real production system, this worker would integrate with a headless CAM slicer.
// E.g. invoking FreeCAD Path module via python script, or Kiri:Moto node API,
// or CuraEngine CLI. For the purpose of scaffolding the pipeline, we simulate the output.

interface CamJobData {
  stepFilePath: string;
  outputGcodePath: string;
  config: {
    toolDiameter?: number;
    feedRate?: number;
    spindleSpeed?: number;
  };
}

async function runCamJob(data: CamJobData) {
  console.log(`[CamWorker] Starting CAM generation for ${data.stepFilePath}`);

  // Example dummy GCode generator for scaffolding the digital thread pipeline
  // It generates a simple spiral toolpath that looks cool in the GCode Viewer.
  let gcode = `
; Generated by ModelScript CAM Worker
; Tool Diameter: ${data.config.toolDiameter ?? 3.175}mm
; Feed Rate: ${data.config.feedRate ?? 1000}mm/min
; Spindle Speed: ${data.config.spindleSpeed ?? 10000}RPM

G21 ; Set units to millimeters
G90 ; Absolute positioning
M3 S${data.config.spindleSpeed ?? 10000} ; Spindle on
G0 Z5.0 ; Rapid retract

; --- Simulated Toolpath ---
`;

  // Generate a spiral toolpath
  const loops = 10;
  const radius = 20;
  for (let i = 0; i <= loops * 36; i++) {
    const angle = i * 10 * (Math.PI / 180);
    const r = radius * (1 - i / (loops * 36));
    const x = r * Math.cos(angle);
    const y = r * Math.sin(angle);
    const z = -2.0 + (i / (loops * 36)) * 2; // ramp up slightly

    if (i === 0) {
      gcode += `G0 X${x.toFixed(3)} Y${y.toFixed(3)}\n`;
      gcode += `G1 Z${z.toFixed(3)} F300\n`;
    } else {
      gcode += `G1 X${x.toFixed(3)} Y${y.toFixed(3)} Z${z.toFixed(3)} F${data.config.feedRate ?? 1000}\n`;
    }

    if (i % 36 === 0) {
      const processed = Math.floor((i / (loops * 36)) * 100);
      process.send?.({ type: "progress", classesProcessed: processed });
    }
  }

  gcode += `
; --- End of Toolpath ---
G0 Z5.0 ; Rapid retract
M5 ; Spindle off
G0 X0 Y0 ; Return home
M30 ; End of program
`;

  await fs.writeFile(data.outputGcodePath, gcode);
  console.log(`[CamWorker] Generated GCode written to ${data.outputGcodePath}`);
}

process.on("message", async (data: unknown) => {
  try {
    const jobData = data as CamJobData;
    await runCamJob(jobData);
    process.send?.({ type: "complete", classesProcessed: 100 });
    process.exit(0);
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("[CamWorker] Error running CAM job:", err);
    process.send?.({ type: "error", error: errorMsg });
    process.exit(1);
  }
});
