; folds.scm — Auto-generated by @modelscript/polyglot
; Language: sysml2

; ─── Foldable blocks ──────────────────────────────────────────────
[
  (MetadataDefinition)
  (Package)
  (LibraryPackage)
  (AttributeDefinition)
  (EnumerationDefinition)
  (OccurrenceDefinition)
  (ItemDefinition)
  (PartDefinition)
  (PortDefinition)
  (ConnectionDefinition)
  (InterfaceDefinition)
  (AllocationDefinition)
  (FlowDefinition)
  (ActionDefinition)
  (ActionBodyParameter)
  (CalculationDefinition)
  (ConstraintDefinition)
  (RequirementDefinition)
  (ConcernDefinition)
  (CaseDefinition)
  (AnalysisCaseDefinition)
  (VerificationCaseDefinition)
  (UseCaseDefinition)
  (StateDefinition)
  (StateUsage)
  (ExhibitStateUsage)
  (ViewDefinition)
  (ViewUsage)
  (ViewpointDefinition)
  (RenderingDefinition)
] @fold

(Comment) @fold

