; highlights.scm — Auto-generated by @modelscript/polyglot
; Language: sysml2
; Do not edit manually — regenerate with: npm run generate

; ─── Keywords ───────────────────────────────────────────────────────
[
  "about" "abstract" "accept" "action" "actor" "alias"
  "all" "allocate" "allocation" "analysis" "assert" "assign"
  "assume" "attribute" "bind" "binding" "by" "calc"
  "case" "comment" "concern" "connect" "connection" "constant"
  "constraint" "crosses" "decide" "def" "default" "defined"
  "dependency" "derived" "do" "doc" "else" "end"
  "entry" "enum" "exhibit" "exit" "false" "filter"
  "first" "flow" "for" "fork" "from" "hastype"
  "if" "import" "in" "include" "individual" "inout"
  "interface" "istype" "item" "join" "language" "library"
  "locale" "loop" "merge" "metadata" "new" "nonunique"
  "null" "objective" "occurrence" "of" "ordered" "out"
  "package" "parallel" "part" "perform" "port" "private"
  "protected" "public" "redefines" "ref" "references" "rendering"
  "rep" "require" "requirement" "return" "satisfy" "send"
  "snapshot" "specializes" "stakeholder" "standard" "state" "subject"
  "subsets" "succession" "then" "timeslice" "to" "transition"
  "true" "until" "use" "variant" "variation" "verification"
  "verify" "via" "view" "viewpoint" "while"
] @keyword

; ─── Definition names ──────────────────────────────────────────────
(MetadataDefinition (Name) @type.definition)
(AttributeDefinition (Name) @type.definition)
(OccurrenceDefinition (Name) @type.definition)
(ItemDefinition (Name) @type.definition)
(PartDefinition (Name) @type.definition)
(PortDefinition (Name) @type.definition)
(ConnectionDefinition (Name) @type.definition)
(InterfaceDefinition (Name) @type.definition)
(AllocationDefinition (Name) @type.definition)
(FlowDefinition (Name) @type.definition)
(ActionDefinition (Name) @type.definition)
(CalculationDefinition (Name) @type.definition)
(ConstraintDefinition (Name) @type.definition)
(RequirementDefinition (Name) @type.definition)
(ConcernDefinition (Name) @type.definition)
(CaseDefinition (Name) @type.definition)
(AnalysisCaseDefinition (Name) @type.definition)
(VerificationCaseDefinition (Name) @type.definition)
(UseCaseDefinition (Name) @type.definition)
(StateDefinition (Name) @type.definition)
(ViewDefinition (Name) @type.definition)
(ViewpointDefinition (Name) @type.definition)
(RenderingDefinition (Name) @type.definition)

; ─── Enumeration names ─────────────────────────────────────────────
(EnumerationDefinition (Name) @type.enum)

; ─── Enumeration values ────────────────────────────────────────────
(EnumeratedValue (Name) @constant)

; ─── Type references ───────────────────────────────────────────────
(Annotation (Name) @variable)
(MetadataTyping (Name) @variable)
(AliasMember (Name) @variable)
(OwnedSubclassification (Name) @variable)
(OwnedFeatureTyping (Name) @variable)
(OwnedSubsetting (Name) @variable)
(OwnedReferenceSubsetting (Name) @variable)
(OwnedCrossSubsetting (Name) @variable)
(OwnedRedefinition (Name) @variable)
(ConjugatedPortTyping (Name) @variable)
(FlowFeature (Name) @variable)
(TransitionUsage (Name) @variable)
(ReferenceTyping (Name) @variable)
(FeatureChainMember (Name) @variable)
(FeatureReferenceMember (Name) @variable)
(ElementReferenceMember (Name) @variable)
(InstantiatedTypeMember (Name) @variable)
(OwnedFeatureChaining (Name) @variable)
(ParameterRedefinition (Name) @variable)

; ─── Package names ────────────────────────────────────────────────
(Package (Name) @module)
(LibraryPackage (Name) @module)

; ─── Import paths ─────────────────────────────────────────────────
(MembershipImport (QualifiedName) @string.special)
(NamespaceImport (QualifiedName) @string.special)

; ─── Alias names ──────────────────────────────────────────────────
(AliasMember (Name) @label)

; ─── Type references ──────────────────────────────────────────────
(OwnedFeatureTyping (QualifiedName) @type)
(ConjugatedPortTyping (QualifiedName) @type)
(OwnedReferenceSubsetting (QualifiedName) @type)
(OwnedSubsetting (QualifiedName) @type)
(OwnedRedefinition (QualifiedName) @type)

; ─── Operators ────────────────────────────────────────────────────
[
  "!=" "!==" "&" "*" "**" "+"
  "-" "->" "." ".." ".?" "/"
  "<" "<=" "=" "==" "===" "=>"
  ">" ">=" "?" "??" "^" "|"
  "~"
] @operator

; ─── Brackets ─────────────────────────────────────────────────────
["(" ")" "[" "]" "{" "}"] @punctuation.bracket

; ─── Delimiters ───────────────────────────────────────────────────
["," ":" ";"] @punctuation.delimiter

; ─── Comments ─────────────────────────────────────────────────────
(Comment) @comment
(REGULAR_COMMENT) @comment

; ─── Literals ─────────────────────────────────────────────────────
(DECIMAL_VALUE) @number
(STRING_VALUE) @string

; ─── Boolean/null literals ─────────────────────────────────────────
"true" @constant.builtin
"false" @constant.builtin
"null" @constant.builtin

; ─── Identifier fallback ──────────────────────────────────────────
(Name) @variable

