// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Standalone C simulation code generator.
 *
 * Generates a self-contained C source file with a `main()` function that:
 *   1. Initializes model state from the DAE
 *   2. Runs either SUNDIALS CVODE (with CVDiag) or an embedded RK4 integration loop
 *   3. Outputs CSV results to stdout
 *
 * Designed for `msc simulate --engine=c` and `msc simulate --engine=wasm`.
 */

import { BinOp, DAEBuilder, EqKind, ExprKind, UnaryOp, Variability } from "@modelscript/language/compiler";
import type { FmiScalarVariable, FmuResult } from "@modelscript/language/fmu";

// ── Public interface ──

export interface SimulationCOptions {
  modelIdentifier: string;
  startTime: number;
  stopTime: number;
  stepSize: number;
  quiet?: boolean | undefined;
  solver?: "rk4" | "cvode" | undefined;
  tolerance?: number | undefined;
}

/**
 * Generate a standalone C simulation source from a DAE.
 */
export function generateSimulationC(dae: DAEBuilder, fmuResult: FmuResult, options: SimulationCOptions): string {
  const { modelIdentifier: id, startTime, stopTime, stepSize } = options;
  const isCvode = options.solver === "cvode";
  const tol = options.tolerance ?? 1e-6;
  const vars = fmuResult.scalarVariables;
  const nVars = vars.length;
  const L: string[] = [];

  // Fast lookup maps: O(1) by name and by VR
  const varByName = new Map<string, FmiScalarVariable>();
  const varByVr = new Map<number, FmiScalarVariable>();
  for (const sv of vars) {
    varByName.set(sv.name, sv);
    varByVr.set(sv.valueReference, sv);
  }

  // Determine state variables and derivatives
  const derVars = vars.filter((sv) => sv.name.startsWith("der("));
  const stateVarRefs: { name: string; vr: number; derVr: number; idx: number }[] = [];
  for (const sv of vars) {
    if (sv.derivative !== undefined) {
      const stateSv = varByVr.get(sv.derivative);
      if (stateSv) {
        stateVarRefs.push({
          name: stateSv.name,
          vr: stateSv.valueReference,
          derVr: sv.valueReference,
          idx: stateVarRefs.length,
        });
      }
    }
  }
  const nStates = stateVarRefs.length;

  const stateRefByVr = new Map<number, { name: string; vr: number; derVr: number; idx: number }>();
  for (const s of stateVarRefs) stateRefByVr.set(s.vr, s);

  // VR map for variable access
  const vrMap = new Map<string, number>();
  for (const sv of vars) vrMap.set(sv.name, sv.valueReference);

  // Derivative equation mapping
  const derMap = new Map<string, number>();
  for (let i = 0; i < derVars.length; i++) {
    const nameMatch = derVars[i]?.name.match(/^der\((.+)\)$/);
    if (nameMatch) derMap.set(nameMatch[1] ?? "", i);
  }

  // ── Header ──
  L.push(`/* Auto-generated by ModelScript CLI — Standalone simulation for ${id} */`);
  L.push("");
  L.push("#include <math.h>");
  L.push("#include <string.h>");
  L.push("#include <stdio.h>");
  L.push("#include <stdint.h>");
  L.push("#include <stdlib.h>");
  L.push("");

  if (isCvode) {
    L.push("/* SUNDIALS CVODE headers & compatibility */");
    L.push("#include <sundials/sundials_config.h>");
    L.push("#include <sundials/sundials_types.h>");
    L.push("#include <cvode/cvode.h>");
    L.push("#include <cvode/cvode_diag.h>");
    L.push("#include <nvector/nvector_serial.h>");
    L.push("");
    L.push("#if defined(SUNDIALS_VERSION_MAJOR) && SUNDIALS_VERSION_MAJOR >= 6");
    L.push("#include <sundials/sundials_context.h>");
    L.push("typedef sunrealtype msc_realtype;");
    L.push("#define MSC_NV_NEW(n, ctx) N_VNew_Serial((n), (ctx))");
    L.push("#define MSC_CVODE_CREATE(lmm, ctx) CVodeCreate((lmm), (ctx))");
    L.push("#else");
    L.push("typedef realtype msc_realtype;");
    L.push("typedef void* SUNContext;");
    L.push("#define MSC_NV_NEW(n, ctx) N_VNew_Serial((n))");
    L.push("#define MSC_CVODE_CREATE(lmm, ctx) CVodeCreate((lmm))");
    L.push("#endif");
    L.push("");
  }

  // ── Constants ──
  L.push(`#define N_VARS ${nVars}`);
  L.push(`#define N_STATES ${nStates}`);
  L.push(`#define START_TIME ${formatCDouble(startTime)}`);
  L.push(`#define STOP_TIME ${formatCDouble(stopTime)}`);
  L.push(`#define STEP_SIZE ${formatCDouble(stepSize)}`);
  if (isCvode) {
    L.push(`#define RTOL ${formatCDouble(tol)}`);
    L.push(`#define ATOL ${formatCDouble(tol)}`);
  }
  L.push("");

  // ── Global model state ──
  L.push("static double g_vars[N_VARS + 1];");
  L.push("static double g_states[N_STATES + 1];");
  L.push("static double g_derivatives[N_STATES + 1];");
  L.push("static double g_time = 0.0;");
  L.push("static int g_isInitPhase = 1;");
  L.push("");
  L.push("/* Event Handling */");
  L.push(`#define N_EVENT_INDICATORS ${dae.eventIndicatorExprIds.length}`);
  L.push("static double g_event_indicators[N_EVENT_INDICATORS > 0 ? N_EVENT_INDICATORS : 1];");
  L.push(`#define N_WHEN_CONDITIONS ${dae.eqCount} /* Overestimate is fine */`);
  L.push("static double g_when_prev[N_WHEN_CONDITIONS > 0 ? N_WHEN_CONDITIONS : 1];");
  L.push("");

  // ── State VR mapping ──
  L.push(`static const int g_state_vr[N_STATES > 0 ? N_STATES : 1] = {`);
  const vrChunks: string[] = [];
  for (let i = 0; i < stateVarRefs.length; i += 20) {
    vrChunks.push(
      "  " +
        stateVarRefs
          .slice(i, i + 20)
          .map((s) => s.vr)
          .join(", "),
    );
  }
  L.push(vrChunks.join(",\n") || "  0");
  L.push("};");
  L.push("");
  L.push("static inline void model_sync_states_to_vars(const double *s) {");
  L.push("  for (int i = 0; i < N_STATES; i++) {");
  L.push("    g_vars[g_state_vr[i]] = s[i];");
  L.push("  }");
  L.push("}");
  L.push("");

  // ── Initialize function ──
  L.push("static void model_initialize(void) {");
  L.push("  memset(g_vars, 0, sizeof(g_vars));");
  L.push("  memset(g_states, 0, sizeof(g_states));");
  L.push("  memset(g_derivatives, 0, sizeof(g_derivatives));");
  L.push("  memset(g_event_indicators, 0, sizeof(g_event_indicators));");
  L.push("  memset(g_when_prev, 0, sizeof(g_when_prev));");
  L.push("  g_time = START_TIME;");
  L.push("  g_isInitPhase = 1;");

  // Set parameter/constant values
  for (let i = 0; i < dae.varCount; i++) {
    if (dae.isVarRemoved(i)) continue;
    const variability = dae.getVarVariability(i);
    if (variability === Variability.Parameter || variability === Variability.Constant) {
      const name = dae.getVarName(i);
      const ref = vrMap.get(name);
      const exprId = dae.getVarExpression(i);
      if (ref !== undefined && typeof exprId === "number" && exprId >= 0) {
        L.push(`  g_vars[${ref}] = ${exprToC(dae, exprId, varByName, derMap)};  /* ${name} */`);
      }
    }
  }

  // Set start values for continuous variables
  for (let i = 0; i < dae.varCount; i++) {
    if (dae.isVarRemoved(i)) continue;
    const variability = dae.getVarVariability(i);
    if (variability === Variability.Continuous || variability === Variability.Discrete) {
      const name = dae.getVarName(i);
      const ref = vrMap.get(name);
      if (ref !== undefined) {
        const startAttr = dae.getVarAttrExprId(i, "start");
        const initExpr = typeof startAttr === "number" && startAttr >= 0 ? startAttr : dae.getVarExpression(i);
        if (typeof initExpr === "number" && initExpr >= 0) {
          L.push(`  g_vars[${ref}] = ${exprToC(dae, initExpr, varByName, derMap)};  /* ${name} */`);
        } else {
          const startVal = dae.getVarStartValue(i);
          if (startVal !== 0) {
            L.push(`  g_vars[${ref}] = ${formatCDouble(startVal)};  /* ${name} */`);
          }
        }
      }
    }
  }

  // Copy initial state values into g_states[]
  for (const sv of stateVarRefs) {
    L.push(`  g_states[${sv.idx}] = g_vars[${sv.vr}];  /* ${sv.name} */`);
  }

  L.push("  g_isInitPhase = 0;");
  L.push("}");
  L.push("");

  // ── getDerivatives function ──
  L.push("static void model_get_derivatives(void) {");

  // Emit derivative equations
  for (let i = 0; i < dae.eqCount; i++) {
    const kind = dae.getEqKind(i);
    if (kind !== EqKind.Simple) continue;
    const lhs = dae.getEqLhs(i);
    const rhs = dae.getEqRhs(i);
    const lhsDer = extractDerName(dae, lhs);
    const rhsDer = extractDerName(dae, rhs);
    if (lhsDer) {
      const idx = derMap.get(lhsDer);
      if (idx !== undefined) {
        L.push(`  g_derivatives[${idx}] = ${exprToC(dae, rhs, varByName, derMap)};  /* der(${lhsDer}) */`);
      }
    } else if (rhsDer) {
      const idx = derMap.get(rhsDer);
      if (idx !== undefined) {
        L.push(`  g_derivatives[${idx}] = ${exprToC(dae, lhs, varByName, derMap)};  /* der(${rhsDer}) */`);
      }
    }
  }

  // Also compute algebraic equations (update g_vars[])
  for (let i = 0; i < dae.eqCount; i++) {
    const kind = dae.getEqKind(i);
    if (kind !== EqKind.Simple) continue;
    const lhs = dae.getEqLhs(i);
    const rhs = dae.getEqRhs(i);
    if (dae.getExprKind(lhs) === ExprKind.Name && !extractDerName(dae, lhs)) {
      const targetName = dae.interner.resolve(dae.getExprData1(lhs));
      if (!targetName.startsWith("der(")) {
        const ref = vrMap.get(targetName);
        if (ref !== undefined) {
          L.push(`  g_vars[${ref}] = ${exprToC(dae, rhs, varByName, derMap)};  /* ${targetName} */`);
        }
      }
    }
  }

  L.push("}");
  L.push("");

  // ── Event Indicators ──
  L.push("/* Compute event indicators for zero-crossing detection */");
  L.push("static void model_get_event_indicators(void) {");
  if (dae.eventIndicatorExprIds.length === 0) {
    L.push("  /* no event indicators */");
  } else {
    for (let i = 0; i < dae.eventIndicatorExprIds.length; i++) {
      const indicator = dae.eventIndicatorExprIds[i];
      if (indicator !== undefined && indicator >= 0) {
        L.push(`  g_event_indicators[${i}] = ${exprToC(dae, indicator, varByName, derMap)};`);
      }
    }
  }
  L.push("}");
  L.push("");

  L.push("/* Event update: evaluate when-equations and discrete changes */");
  L.push("static void model_event_update(void) {");
  const whenEqIdxs: number[] = [];
  for (let idx = 0; idx < dae.eqCount; idx++) {
    if (dae.getEqKind(idx) === EqKind.When) whenEqIdxs.push(idx);
  }

  if (whenEqIdxs.length > 0) {
    let whenIdx = 0;
    for (const eqIdx of whenEqIdxs) {
      const weq = dae.getWhenEquationMeta(eqIdx);
      if (!weq) continue;

      const processBlock = (
        condExprId: number,
        bodyEquations: { kind: EqKind; lhsExprId: number; rhsExprId: number }[],
      ) => {
        const condC = conditionToZeroCrossingC(dae, condExprId, varByName, derMap);
        L.push(`  if (${condC} > 0.0 && g_when_prev[${whenIdx}] <= 0.0) {`);
        for (const bodyEq of bodyEquations) {
          if (bodyEq.kind === EqKind.Simple) {
            const lhsName = extractAssignmentTarget(dae, bodyEq.lhsExprId);
            if (lhsName) {
              const sv = varByName.get(lhsName);
              if (sv) {
                L.push(
                  `    g_vars[${sv.valueReference}] = ${exprToC(dae, bodyEq.rhsExprId, varByName, derMap)};  /* ${lhsName} */`,
                );
                const stateRef = stateRefByVr.get(sv.valueReference);
                if (stateRef) L.push(`    g_states[${stateRef.idx}] = g_vars[${sv.valueReference}];`);
              }
            }
          } else if (bodyEq.kind === EqKind.FunctionCall) {
            if (dae.getExprKind(bodyEq.lhsExprId) === ExprKind.Call) {
              const callId = bodyEq.lhsExprId;
              const fname = dae.interner.resolve(dae.getExprData1(callId));
              if (fname === "reinit") {
                const arg0 = dae.getExprLeft(callId);
                const arg1 = dae.getExprLeft(callId + 1);
                if (dae.getExprKind(arg0) === ExprKind.Name) {
                  const stateName = dae.interner.resolve(dae.getExprData1(arg0));
                  const sv = varByName.get(stateName);
                  if (sv) {
                    L.push(
                      `    g_vars[${sv.valueReference}] = ${exprToC(dae, arg1, varByName, derMap)};  /* reinit(${stateName}) */`,
                    );
                    const stateRef = stateRefByVr.get(sv.valueReference);
                    if (stateRef) L.push(`    g_states[${stateRef.idx}] = g_vars[${sv.valueReference}];`);
                  }
                }
              }
            }
          }
        }
        L.push("  }");
        L.push(`  g_when_prev[${whenIdx}] = ${condC};`);
        whenIdx++;
      };

      processBlock(weq.conditionExprId, weq.bodyEquations);
      for (const clause of weq.elseWhenClauses) {
        processBlock(clause.conditionExprId, clause.bodyEquations);
      }
    }
  }
  L.push("}");
  L.push("");

  if (isCvode) {
    // ── SUNDIALS CVODE RHS Callback ──
    L.push("/* SUNDIALS CVODE RHS evaluation callback */");
    L.push("static int cvode_rhs(msc_realtype t, N_Vector y, N_Vector ydot, void *user_data) {");
    L.push("  (void)user_data;");
    L.push("  msc_realtype *y_data = (msc_realtype*)N_VGetArrayPointer(y);");
    L.push("  msc_realtype *ydot_data = (msc_realtype*)N_VGetArrayPointer(ydot);");
    L.push("  g_time = (double)t;");
    L.push("  for (int i = 0; i < N_STATES; i++) {");
    L.push("    g_states[i] = (double)y_data[i];");
    L.push("  }");
    L.push("  model_sync_states_to_vars(g_states);");
    L.push("  model_get_derivatives();");
    L.push("  for (int i = 0; i < N_STATES; i++) {");
    L.push("    ydot_data[i] = (msc_realtype)g_derivatives[i];");
    L.push("  }");
    L.push("  return 0;");
    L.push("}");
    L.push("");
  } else {
    // ── RK4 stepper ──
    L.push("/* Embedded RK4 integration step */");
    L.push("static void rk4_step(double t_start, double dt) {");
    L.push("  int i;");
    L.push("  double k1[N_STATES + 1], k2[N_STATES + 1], k3[N_STATES + 1], k4[N_STATES + 1];");
    L.push("  double tmp_states[N_STATES + 1];");
    L.push("  double y0[N_STATES + 1];");
    L.push("  double z_prev[N_EVENT_INDICATORS + 1];");
    L.push("  double t = t_start;");
    L.push("  double t_end = t_start + dt;");
    L.push("");
    L.push("  while (t < t_end - 1e-13) {");
    L.push("    double h = t_end - t;");
    L.push("    int step_accepted = 0;");
    L.push("    for (i = 0; i < N_STATES; i++) y0[i] = g_states[i];");
    L.push("    g_time = t;");
    L.push("    model_sync_states_to_vars(y0);");
    L.push("    if (N_EVENT_INDICATORS > 0) {");
    L.push("      model_get_event_indicators();");
    L.push("      for (i = 0; i < N_EVENT_INDICATORS; i++) z_prev[i] = g_event_indicators[i];");
    L.push("    }");
    L.push("    while (!step_accepted) {");
    L.push("      /* k1 */");
    L.push("      g_time = t;");
    L.push("      model_sync_states_to_vars(y0);");
    L.push("      model_get_derivatives();");
    L.push("      for (i = 0; i < N_STATES; i++) k1[i] = g_derivatives[i];");
    L.push("      /* k2 */");
    L.push("      g_time = t + 0.5 * h;");
    L.push("      for (i = 0; i < N_STATES; i++) tmp_states[i] = y0[i] + 0.5 * h * k1[i];");
    L.push("      model_sync_states_to_vars(tmp_states);");
    L.push("      model_get_derivatives();");
    L.push("      for (i = 0; i < N_STATES; i++) k2[i] = g_derivatives[i];");
    L.push("      /* k3 */");
    L.push("      for (i = 0; i < N_STATES; i++) tmp_states[i] = y0[i] + 0.5 * h * k2[i];");
    L.push("      model_sync_states_to_vars(tmp_states);");
    L.push("      model_get_derivatives();");
    L.push("      for (i = 0; i < N_STATES; i++) k3[i] = g_derivatives[i];");
    L.push("      /* k4 */");
    L.push("      g_time = t + h;");
    L.push("      for (i = 0; i < N_STATES; i++) tmp_states[i] = y0[i] + h * k3[i];");
    L.push("      model_sync_states_to_vars(tmp_states);");
    L.push("      model_get_derivatives();");
    L.push("      for (i = 0; i < N_STATES; i++) k4[i] = g_derivatives[i];");
    L.push("      /* Combine */");
    L.push(
      "      for (i = 0; i < N_STATES; i++) tmp_states[i] = y0[i] + (h / 6.0) * (k1[i] + 2.0*k2[i] + 2.0*k3[i] + k4[i]);",
    );
    L.push("      ");
    L.push("      int crossing = 0;");
    L.push("      if (N_EVENT_INDICATORS > 0) {");
    L.push("        g_time = t + h;");
    L.push("        model_sync_states_to_vars(tmp_states);");
    L.push("        model_get_event_indicators();");
    L.push("        for (i = 0; i < N_EVENT_INDICATORS; i++) {");
    L.push("          if (z_prev[i] * g_event_indicators[i] < 0.0) { crossing = 1; break; }");
    L.push("        }");
    L.push("      }");
    L.push("      if (crossing && h > 1e-7) {");
    L.push("        h *= 0.5;");
    L.push("      } else {");
    L.push("        step_accepted = 1;");
    L.push("      }");
    L.push("    }");
    L.push("    t += h;");
    L.push("    for (i = 0; i < N_STATES; i++) g_states[i] = tmp_states[i];");
    L.push("    model_sync_states_to_vars(g_states);");
    L.push("    g_time = t;");
    L.push("    model_event_update();");
    L.push("  }");
    L.push("}");
    L.push("");
  }

  // ── main() ──
  const quiet = !!options.quiet;
  const outputVars = vars.filter((sv) => sv.causality !== "independent" && !sv.name.startsWith("der("));

  L.push("int main(void) {");
  L.push("  model_initialize();");
  L.push("");

  if (!quiet) {
    /* Print CSV header */
    const headerNames = ["time", ...outputVars.map((sv) => sv.name)];
    L.push(`  printf("${headerNames.join(",")}\\n");`);
    L.push("");
  }

  L.push("  double t = START_TIME;");
  L.push("  double dt = STEP_SIZE;");
  L.push("");

  if (!quiet) {
    // Print initial state
    L.push("  /* Print initial state */");
    L.push(generatePrintfLine(outputVars));
    L.push("");
  }

  if (isCvode && nStates > 0) {
    L.push("  /* Initialize SUNDIALS CVODE (with CVDiag for O(N) scaling) */");
    L.push("  SUNContext sunctx = NULL;");
    L.push("#if defined(SUNDIALS_VERSION_MAJOR) && SUNDIALS_VERSION_MAJOR >= 6");
    L.push("  SUNContext_Create(SUN_COMM_NULL, &sunctx);");
    L.push("#endif");
    L.push("  N_Vector y = MSC_NV_NEW(N_STATES, sunctx);");
    L.push("  msc_realtype *y_data = (msc_realtype*)N_VGetArrayPointer(y);");
    L.push("  for (int i = 0; i < N_STATES; i++) {");
    L.push("    y_data[i] = (msc_realtype)g_states[i];");
    L.push("  }");
    L.push("  void *cvode_mem = MSC_CVODE_CREATE(CV_BDF, sunctx);");
    L.push("  CVodeInit(cvode_mem, cvode_rhs, (msc_realtype)START_TIME, y);");
    L.push("  CVodeSStolerances(cvode_mem, (msc_realtype)RTOL, (msc_realtype)ATOL);");
    L.push("  CVDiag(cvode_mem);");
    L.push("  CVodeSetMaxNumSteps(cvode_mem, 1000000);");
    L.push("");
    L.push("  /* Integration loop */");
    L.push("  while (t < STOP_TIME - 1e-15) {");
    L.push("    double t_end = t + dt;");
    L.push("    if (t_end > STOP_TIME) t_end = STOP_TIME;");
    L.push("    msc_realtype tret;");
    L.push("    int flag = CVode(cvode_mem, (msc_realtype)t_end, y, &tret, CV_NORMAL);");
    L.push("    if (flag < 0) {");
    L.push('      fprintf(stderr, "CVODE step error flag: %d\\n", flag);');
    L.push("      break;");
    L.push("    }");
    L.push("    t = (double)tret;");
    L.push("    g_time = t;");
    L.push("    for (int i = 0; i < N_STATES; i++) {");
    L.push("      g_states[i] = (double)y_data[i];");
    L.push("    }");
    L.push("    model_sync_states_to_vars(g_states);");
    L.push("    model_event_update();");
    if (!quiet) {
      L.push("    " + generatePrintfLine(outputVars));
    }
    L.push("  }");
    L.push("");
    L.push("  CVodeFree(&cvode_mem);");
    L.push("  N_VDestroy(y);");
    L.push("#if defined(SUNDIALS_VERSION_MAJOR) && SUNDIALS_VERSION_MAJOR >= 6");
    L.push("  SUNContext_Free(&sunctx);");
    L.push("#endif");
  } else {
    L.push("  /* Integration loop */");
    L.push("  while (t < STOP_TIME - 1e-15) {");
    L.push("    double t_end = t + dt;");
    L.push("    if (t_end > STOP_TIME) t_end = STOP_TIME;");
    if (nStates > 0) {
      L.push("    rk4_step(t, t_end - t);");
    } else {
      L.push("    g_time = t_end;");
      L.push("    model_get_derivatives();");
    }
    L.push("    t = t_end;");
    if (!quiet) {
      L.push("    " + generatePrintfLine(outputVars));
    }
    L.push("  }");
  }

  L.push("");
  L.push("  return 0;");
  L.push("}");
  L.push("");

  return L.join("\n");
}

// ── Printf helper ──

function generatePrintfLine(outputVars: FmiScalarVariable[]): string {
  const formatParts = ["%.17g", ...outputVars.map(() => "%.17g")];
  const valueParts = ["g_time", ...outputVars.map((sv) => `g_vars[${sv.valueReference}]`)];
  return `printf("${formatParts.join(",")}\\n", ${valueParts.join(", ")});`;
}

// ── DAE Analysis Helpers ──

function conditionToZeroCrossingC(
  dae: DAEBuilder,
  id: number,
  vars: FmiScalarVariable[] | Map<string, FmiScalarVariable>,
  derMap?: Map<string, number>,
): string {
  if (id < 0) return "0.0";
  if (dae.getExprKind(id) === ExprKind.Binary) {
    const op = dae.getExprData1(id) as BinOp;
    if (op === BinOp.Lt || op === BinOp.Lte) {
      const lhs = exprToC(dae, dae.getExprLeft(id), vars, derMap);
      const rhs = exprToC(dae, dae.getExprRight(id), vars, derMap);
      return `(${rhs}) - (${lhs})`;
    } else if (op === BinOp.Gt || op === BinOp.Gte) {
      const lhs = exprToC(dae, dae.getExprLeft(id), vars, derMap);
      const rhs = exprToC(dae, dae.getExprRight(id), vars, derMap);
      return `(${lhs}) - (${rhs})`;
    }
  }
  return `(${exprToC(dae, id, vars, derMap)} ? 1.0 : -1.0)`;
}

function extractAssignmentTarget(dae: DAEBuilder, id: number): string | null {
  if (id >= 0 && dae.getExprKind(id) === ExprKind.Name) {
    return dae.interner.resolve(dae.getExprData1(id));
  }
  return null;
}

// ── C Expression Transpiler ──

function sanitizeIdentifier(name: string): string {
  return name
    .replace(/\./g, "_")
    .replace(/\[/g, "_")
    .replace(/\]/g, "")
    .replace(/[^a-zA-Z0-9_]/g, "_");
}

function varToC(
  dae: DAEBuilder,
  name: string,
  vars: FmiScalarVariable[] | Map<string, FmiScalarVariable>,
  derMap?: Map<string, number>,
): string {
  if (name === "time") return "g_time";

  // Handle der(v) and pre(v)
  const isDer = name.startsWith("der(");
  const isPre = name.startsWith("pre(");
  let baseName = name;
  if (isDer) baseName = name.slice(4, -1);
  else if (isPre) baseName = name.slice(4, -1);

  if (isDer && derMap) {
    const idx = derMap.get(baseName);
    if (idx !== undefined) return `g_derivatives[${idx}]`;
  }

  const sv = vars instanceof Map ? vars.get(baseName) : vars.find((v) => v.name === baseName);
  if (!sv) return `0.0 /* unknown ${name} */`;

  return `g_vars[${sv.valueReference}]`;
}

function formatCDouble(value: number): string {
  if (!isFinite(value)) {
    if (value === Infinity) return "INFINITY";
    if (value === -Infinity) return "(-INFINITY)";
    return "NAN";
  }
  const s = value.toString();
  if (!s.includes(".") && !s.includes("e") && !s.includes("E")) return s + ".0";
  return s;
}

function escapeCString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function binaryOpToC(op: BinOp): string {
  switch (op) {
    case BinOp.Add:
    case BinOp.ElemAdd:
      return "+";
    case BinOp.Sub:
    case BinOp.ElemSub:
      return "-";
    case BinOp.Mul:
    case BinOp.ElemMul:
      return "*";
    case BinOp.Div:
    case BinOp.ElemDiv:
      return "/";
    case BinOp.Pow:
    case BinOp.ElemPow:
      return "pow";
    case BinOp.Lt:
      return "<";
    case BinOp.Lte:
      return "<=";
    case BinOp.Gt:
      return ">";
    case BinOp.Gte:
      return ">=";
    case BinOp.Eq:
      return "==";
    case BinOp.Neq:
      return "!=";
    case BinOp.And:
      return "&&";
    case BinOp.Or:
      return "||";
    default:
      return "+";
  }
}

function mapFunctionName(name: string): string {
  const builtins: Record<string, string> = {
    sin: "sin",
    cos: "cos",
    tan: "tan",
    asin: "asin",
    acos: "acos",
    atan: "atan",
    atan2: "atan2",
    sinh: "sinh",
    cosh: "cosh",
    tanh: "tanh",
    exp: "exp",
    log: "log",
    log10: "log10",
    sqrt: "sqrt",
    abs: "fabs",
    sign: "copysign",
    floor: "floor",
    ceil: "ceil",
    min: "fmin",
    max: "fmax",
    mod: "fmod",
    "Modelica.Math.sin": "sin",
    "Modelica.Math.cos": "cos",
    "Modelica.Math.log": "log",
    "Modelica.Math.exp": "exp",
    "Modelica.Math.sqrt": "sqrt",
    "Modelica.Math.atan2": "atan2",
  };
  return builtins[name] ?? sanitizeIdentifier(name);
}

function exprToC(
  dae: DAEBuilder,
  id: number,
  vars: FmiScalarVariable[] | Map<string, FmiScalarVariable>,
  derMap?: Map<string, number>,
): string {
  if (id < 0) return "0.0 /* null */";
  switch (dae.getExprKind(id)) {
    case ExprKind.RealLiteral:
      return formatCDouble(dae.getExprRealValue(id));
    case ExprKind.IntLiteral:
      return `${dae.getExprData1(id)}`;
    case ExprKind.BoolLiteral:
      return dae.getExprData1(id) !== 0 ? "1" : "0";
    case ExprKind.StringLiteral:
      return `"${escapeCString(dae.interner.resolve(dae.getExprData1(id)))}"`;
    case ExprKind.Name:
      return varToC(dae, dae.interner.resolve(dae.getExprData1(id)), vars, derMap);
    case ExprKind.Unary: {
      const uop = dae.getExprData1(id) as UnaryOp;
      const op = uop === UnaryOp.Not ? "!" : "-";
      return `(${op}${exprToC(dae, dae.getExprLeft(id), vars, derMap)})`;
    }
    case ExprKind.Negate:
      return `(-${exprToC(dae, dae.getExprLeft(id), vars, derMap)})`;
    case ExprKind.Der: {
      const arg = dae.getExprData1(id);
      const name = dae.interner.resolve(dae.getExprData1(arg));
      return varToC(dae, `der(${name})`, vars, derMap);
    }
    case ExprKind.Pre: {
      const arg = dae.getExprData1(id);
      const name = dae.interner.resolve(dae.getExprData1(arg));
      return varToC(dae, `pre(${name})`, vars, derMap);
    }
    case ExprKind.Binary: {
      const op = dae.getExprData1(id) as BinOp;
      const lhs = exprToC(dae, dae.getExprLeft(id), vars, derMap);
      const rhs = exprToC(dae, dae.getExprRight(id), vars, derMap);
      const opStr = binaryOpToC(op);
      if (opStr === "pow") return `pow(${lhs}, ${rhs})`;
      return `(${lhs} ${opStr} ${rhs})`;
    }
    case ExprKind.Call: {
      const fname = dae.interner.resolve(dae.getExprData1(id));
      const argCount = dae.getExprRight(id);
      const args: string[] = [];
      for (let i = 0; i < argCount; i++) {
        args.push(exprToC(dae, dae.getExprLeft(id + i), vars, derMap));
      }
      if (fname === "initial") return "g_isInitPhase";
      if (fname === "terminal") return "0";
      if (fname === "assert" && args.length >= 2) {
        return `((${args[0]}) ? 0.0 : 0.0)`;
      }
      return `${mapFunctionName(fname)}(${args.join(", ")})`;
    }
    case ExprKind.IfElse: {
      const cond = exprToC(dae, dae.getExprData1(id), vars, derMap);
      const then = exprToC(dae, dae.getExprLeft(id), vars, derMap);
      const els = exprToC(dae, dae.getExprRight(id), vars, derMap);
      return `(${cond} ? ${then} : ${els})`;
    }
    default:
      return "0.0 /* unknown */";
  }
}

// ── DAE analysis helpers ──

function extractDerName(dae: DAEBuilder, exprId: number): string | null {
  if (exprId < 0) return null;
  const kind = dae.getExprKind(exprId);
  if (kind === ExprKind.Der) {
    const operandId = dae.getExprData1(exprId);
    if (dae.getExprKind(operandId) === ExprKind.Name) {
      return dae.interner.resolve(dae.getExprData1(operandId));
    }
  }
  return null;
}
