// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Standalone C simulation code generator.
 *
 * Generates a self-contained C source file with a `main()` function that:
 *   1. Initializes model state from the DAE
 *   2. Runs an RK4 integration loop
 *   3. Outputs CSV results to stdout
 *
 * Designed for `msc simulate --engine=c` — the generated binary is compiled
 * with `gcc -O3 -lm` and executed as a subprocess.
 *
 * Reuses the expression transpiler patterns from fmu-wasm-codegen.ts
 * but targets a standalone executable rather than a WASM module.
 */

import type { FmuResult } from "@modelscript/fmi";
import { ModelicaBinaryOperator, ModelicaUnaryOperator, ModelicaVariability } from "@modelscript/modelica/ast";
import type { ModelicaDAE, ModelicaExpression } from "@modelscript/symbolics";
import {
  ModelicaArray,
  ModelicaBinaryExpression,
  ModelicaBooleanLiteral,
  ModelicaFunctionCallExpression,
  ModelicaIfElseExpression,
  ModelicaIntegerLiteral,
  ModelicaNameExpression,
  ModelicaRealLiteral,
  ModelicaSimpleEquation,
  ModelicaStringLiteral,
  ModelicaUnaryExpression,
} from "@modelscript/symbolics";

// ── Public interface ──

export interface SimulationCOptions {
  modelIdentifier: string;
  startTime: number;
  stopTime: number;
  stepSize: number;
}

/**
 * Generate a standalone C simulation source from a DAE.
 *
 * The resulting C file can be compiled and executed directly:
 * ```
 * gcc -O3 -Wall model_sim.c -o model_sim -lm
 * ./model_sim
 * ```
 *
 * Output is CSV to stdout with a header row.
 */
export function generateSimulationC(dae: ModelicaDAE, fmuResult: FmuResult, options: SimulationCOptions): string {
  const { modelIdentifier: id, startTime, stopTime, stepSize } = options;
  const vars = fmuResult.scalarVariables;
  const nVars = vars.length;
  const L: string[] = [];

  // Determine state variables and derivatives
  const derVars = vars.filter((sv) => sv.name.startsWith("der("));
  const stateVarRefs: { name: string; vr: number; derVr: number; idx: number }[] = [];
  for (const sv of vars) {
    if (sv.derivative !== undefined) {
      const stateSv = vars.find((v) => v.valueReference === sv.derivative);
      if (stateSv) {
        stateVarRefs.push({
          name: stateSv.name,
          vr: stateSv.valueReference,
          derVr: sv.valueReference,
          idx: stateVarRefs.length,
        });
      }
    }
  }
  const nStates = stateVarRefs.length;

  // VR map for variable access
  const vrMap = new Map<string, number>();
  for (const sv of vars) vrMap.set(sv.name, sv.valueReference);

  // Derivative equation mapping
  const derMap = new Map<string, number>();
  for (let i = 0; i < derVars.length; i++) {
    const nameMatch = derVars[i]?.name.match(/^der\((.+)\)$/);
    if (nameMatch) derMap.set(nameMatch[1] ?? "", i);
  }

  // ── Header ──
  L.push(`/* Auto-generated by ModelScript CLI — Standalone simulation for ${id} */`);
  L.push("");
  L.push("#include <math.h>");
  L.push("#include <string.h>");
  L.push("#include <stdio.h>");
  L.push("#include <stdint.h>");
  L.push("");

  // ── Constants ──
  L.push(`#define N_VARS ${nVars}`);
  L.push(`#define N_STATES ${nStates}`);
  L.push(`#define START_TIME ${formatCDouble(startTime)}`);
  L.push(`#define STOP_TIME ${formatCDouble(stopTime)}`);
  L.push(`#define STEP_SIZE ${formatCDouble(stepSize)}`);
  L.push("");

  // ── VR defines ──
  for (const sv of vars) {
    const cName = sanitizeIdentifier(sv.name).toUpperCase();
    L.push(`#define VR_${cName} ${sv.valueReference}`);
  }
  L.push("");

  // ── Global model state ──
  L.push("static double g_vars[N_VARS + 1];");
  L.push("static double g_states[N_STATES + 1];");
  L.push("static double g_derivatives[N_STATES + 1];");
  L.push("static double g_time = 0.0;");
  L.push("static int g_isInitPhase = 1;");
  L.push("");

  // ── Initialize function ──
  L.push("static void model_initialize(void) {");
  L.push("  memset(g_vars, 0, sizeof(g_vars));");
  L.push("  memset(g_states, 0, sizeof(g_states));");
  L.push("  memset(g_derivatives, 0, sizeof(g_derivatives));");
  L.push("  g_time = START_TIME;");
  L.push("  g_isInitPhase = 1;");

  // Set parameter/constant values
  for (const v of dae.arenaVariables()) {
    if (v.variability === ModelicaVariability.PARAMETER || v.variability === ModelicaVariability.CONSTANT) {
      const ref = vrMap.get(v.name);
      if (ref !== undefined && v.expression) {
        L.push(`  g_vars[${ref}] = ${exprToC(v.expression)};  /* ${v.name} */`);
      }
    }
  }

  // Set start values for continuous variables
  for (const v of dae.arenaVariables()) {
    if (v.variability === null || v.variability === undefined) {
      const ref = vrMap.get(v.name);
      if (ref !== undefined) {
        const startAttr = v.attributes.get("start");
        const initExpr = startAttr ?? v.expression;
        if (initExpr) {
          L.push(`  g_vars[${ref}] = ${exprToC(initExpr)};  /* ${v.name} */`);
        }
      }
    }
  }

  // Copy initial state values into g_states[]
  for (const sv of stateVarRefs) {
    L.push(`  g_states[${sv.idx}] = g_vars[${sv.vr}];  /* ${sv.name} */`);
  }

  L.push("  g_isInitPhase = 0;");
  L.push("}");
  L.push("");

  // ── getDerivatives function ──
  L.push("static void model_get_derivatives(void) {");

  // Collect referenced variable names for local alias emission
  const refNames = new Set<string>();
  for (const eq of dae.equations) {
    if (!("expression1" in eq && "expression2" in eq)) continue;
    const se = eq as { expression1: ModelicaExpression; expression2: ModelicaExpression };
    collectReferencedNames(se.expression1, refNames);
    collectReferencedNames(se.expression2, refNames);
  }

  // Local aliases for referenced variables (read from g_vars[])
  for (const sv of vars) {
    if (sv.causality === "independent") continue;
    if (!refNames.has(sv.name)) continue;
    const cName = varToC(sv.name);
    L.push(`  double ${cName} = g_vars[${sv.valueReference}];`);
  }
  L.push("");

  // Emit derivative equations
  for (const eq of dae.equations) {
    if (!("expression1" in eq && "expression2" in eq)) continue;
    const se = eq as { expression1: ModelicaExpression; expression2: ModelicaExpression };
    const lhsDer = extractDerName(se.expression1);
    const rhsDer = extractDerName(se.expression2);
    if (lhsDer) {
      const idx = derMap.get(lhsDer);
      if (idx !== undefined) {
        L.push(`  g_derivatives[${idx}] = ${exprToC(se.expression2)};  /* der(${lhsDer}) */`);
      }
    } else if (rhsDer) {
      const idx = derMap.get(rhsDer);
      if (idx !== undefined) {
        L.push(`  g_derivatives[${idx}] = ${exprToC(se.expression1)};  /* der(${rhsDer}) */`);
      }
    }
  }

  // Also compute algebraic equations (update g_vars[])
  for (const eq of dae.equations) {
    if (!(eq instanceof ModelicaSimpleEquation)) continue;
    if (
      eq.expression1 instanceof ModelicaNameExpression &&
      !eq.expression1.name.startsWith("der(") &&
      !extractDerName(eq.expression1)
    ) {
      const targetName = eq.expression1.name;
      const ref = vrMap.get(targetName);
      if (ref !== undefined) {
        L.push(`  g_vars[${ref}] = ${exprToC(eq.expression2)};  /* ${targetName} */`);
      }
    }
  }

  L.push("}");
  L.push("");

  // ── RK4 stepper ──
  L.push("static void rk4_step(double t, double dt) {");
  L.push("  int i;");
  L.push("  double k1[N_STATES + 1], k2[N_STATES + 1], k3[N_STATES + 1], k4[N_STATES + 1];");
  L.push("");

  L.push("  /* k1 = f(t, y) */");
  L.push("  g_time = t;");
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  model_get_derivatives();");
  L.push("  for (i = 0; i < N_STATES; i++) k1[i] = g_derivatives[i];");
  L.push("");

  L.push("  /* k2 = f(t + dt/2, y + dt/2 * k1) */");
  L.push("  g_time = t + 0.5 * dt;");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] += 0.5 * dt * k1[i];");
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  model_get_derivatives();");
  L.push("  for (i = 0; i < N_STATES; i++) k2[i] = g_derivatives[i];");
  // Restore states
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] -= 0.5 * dt * k1[i];");
  L.push("");

  L.push("  /* k3 = f(t + dt/2, y + dt/2 * k2) */");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] += 0.5 * dt * k2[i];");
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  model_get_derivatives();");
  L.push("  for (i = 0; i < N_STATES; i++) k3[i] = g_derivatives[i];");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] -= 0.5 * dt * k2[i];");
  L.push("");

  L.push("  /* k4 = f(t + dt, y + dt * k3) */");
  L.push("  g_time = t + dt;");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] += dt * k3[i];");
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  model_get_derivatives();");
  L.push("  for (i = 0; i < N_STATES; i++) k4[i] = g_derivatives[i];");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] -= dt * k3[i];");
  L.push("");

  L.push("  /* Combine: y_new = y + dt/6 * (k1 + 2*k2 + 2*k3 + k4) */");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] += (dt / 6.0) * (k1[i] + 2.0*k2[i] + 2.0*k3[i] + k4[i]);");
  L.push("");

  // Write updated states back to g_vars[]
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  g_time = t + dt;");
  L.push("  model_get_derivatives();");
  L.push("}");
  L.push("");

  // ── main() ──
  // Build the list of output variable names and their VRs
  const outputVars = vars.filter((sv) => sv.causality !== "independent" && !sv.name.startsWith("der("));

  L.push("int main(void) {");
  L.push("  model_initialize();");
  L.push("");
  L.push("  /* Print CSV header */");

  const headerNames = ["time", ...outputVars.map((sv) => sv.name)];
  L.push(`  printf("${headerNames.join(",")}\\n");`);
  L.push("");

  L.push("  double t = START_TIME;");
  L.push("  double dt = STEP_SIZE;");
  L.push("");

  // Print initial state
  L.push("  /* Print initial state */");
  L.push(generatePrintfLine(outputVars));
  L.push("");

  L.push("  /* Integration loop */");
  L.push("  while (t < STOP_TIME - 1e-15) {");
  L.push("    if (t + dt > STOP_TIME) dt = STOP_TIME - t;");
  L.push("    rk4_step(t, dt);");
  L.push("    t += dt;");
  L.push("    " + generatePrintfLine(outputVars));
  L.push("  }");
  L.push("");
  L.push("  return 0;");
  L.push("}");
  L.push("");

  return L.join("\n");
}

// ── Printf helper ──

function generatePrintfLine(outputVars: { name: string; valueReference: number }[]): string {
  const formatParts = ["%.17g", ...outputVars.map(() => "%.17g")];
  const valueParts = ["g_time", ...outputVars.map((sv) => `g_vars[${sv.valueReference}]`)];
  return `printf("${formatParts.join(",")}\\n", ${valueParts.join(", ")});`;
}

// ── C Expression Transpiler ──

function sanitizeIdentifier(name: string): string {
  return name
    .replace(/\./g, "_")
    .replace(/\[/g, "_")
    .replace(/\]/g, "")
    .replace(/[^a-zA-Z0-9_]/g, "_");
}

function varToC(name: string): string {
  if (name === "time") return "g_time";
  const derMatch = name.match(/^der\((.+)\)$/);
  if (derMatch) return `der_${sanitizeIdentifier(derMatch[1] ?? "")}`;
  return `v_${sanitizeIdentifier(name)}`;
}

function formatCDouble(value: number): string {
  if (!isFinite(value)) {
    if (value === Infinity) return "INFINITY";
    if (value === -Infinity) return "(-INFINITY)";
    return "NAN";
  }
  const s = value.toString();
  if (!s.includes(".") && !s.includes("e") && !s.includes("E")) return s + ".0";
  return s;
}

function escapeCString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function binaryOpToC(op: ModelicaBinaryOperator): string {
  switch (op) {
    case ModelicaBinaryOperator.ADDITION:
    case ModelicaBinaryOperator.ELEMENTWISE_ADDITION:
      return "+";
    case ModelicaBinaryOperator.SUBTRACTION:
    case ModelicaBinaryOperator.ELEMENTWISE_SUBTRACTION:
      return "-";
    case ModelicaBinaryOperator.MULTIPLICATION:
    case ModelicaBinaryOperator.ELEMENTWISE_MULTIPLICATION:
      return "*";
    case ModelicaBinaryOperator.DIVISION:
    case ModelicaBinaryOperator.ELEMENTWISE_DIVISION:
      return "/";
    case ModelicaBinaryOperator.EXPONENTIATION:
    case ModelicaBinaryOperator.ELEMENTWISE_EXPONENTIATION:
      return "pow";
    case ModelicaBinaryOperator.LESS_THAN:
      return "<";
    case ModelicaBinaryOperator.LESS_THAN_OR_EQUAL:
      return "<=";
    case ModelicaBinaryOperator.GREATER_THAN:
      return ">";
    case ModelicaBinaryOperator.GREATER_THAN_OR_EQUAL:
      return ">=";
    case ModelicaBinaryOperator.EQUALITY:
      return "==";
    case ModelicaBinaryOperator.INEQUALITY:
      return "!=";
    case ModelicaBinaryOperator.LOGICAL_AND:
      return "&&";
    case ModelicaBinaryOperator.LOGICAL_OR:
      return "||";
    default:
      return "+";
  }
}

function mapFunctionName(name: string): string {
  const builtins: Record<string, string> = {
    sin: "sin",
    cos: "cos",
    tan: "tan",
    asin: "asin",
    acos: "acos",
    atan: "atan",
    atan2: "atan2",
    sinh: "sinh",
    cosh: "cosh",
    tanh: "tanh",
    exp: "exp",
    log: "log",
    log10: "log10",
    sqrt: "sqrt",
    abs: "fabs",
    sign: "copysign",
    floor: "floor",
    ceil: "ceil",
    min: "fmin",
    max: "fmax",
    mod: "fmod",
    "Modelica.Math.sin": "sin",
    "Modelica.Math.cos": "cos",
    "Modelica.Math.log": "log",
    "Modelica.Math.exp": "exp",
    "Modelica.Math.sqrt": "sqrt",
    "Modelica.Math.atan2": "atan2",
  };
  return builtins[name] ?? sanitizeIdentifier(name);
}

function exprToC(expr: ModelicaExpression): string {
  if (expr instanceof ModelicaRealLiteral) return formatCDouble(expr.value);
  if (expr instanceof ModelicaIntegerLiteral) return `${expr.value}`;
  if (expr instanceof ModelicaBooleanLiteral) return expr.value ? "1" : "0";
  if (expr instanceof ModelicaStringLiteral) return `"${escapeCString(expr.value)}"`;
  if (expr instanceof ModelicaNameExpression) return varToC(expr.name);
  if (expr instanceof ModelicaUnaryExpression) {
    const op = expr.operator === ModelicaUnaryOperator.UNARY_MINUS ? "-" : "!";
    return `(${op}${exprToC(expr.operand)})`;
  }
  if (expr instanceof ModelicaBinaryExpression) {
    const lhs = exprToC(expr.operand1);
    const rhs = exprToC(expr.operand2);
    const op = binaryOpToC(expr.operator);
    if (op === "pow") return `pow(${lhs}, ${rhs})`;
    return `(${lhs} ${op} ${rhs})`;
  }
  if (expr instanceof ModelicaFunctionCallExpression) {
    if (expr.functionName === "initial") return "g_isInitPhase";
    if (expr.functionName === "terminal") return "0";
    if (expr.functionName === "assert" && expr.args.length >= 2) {
      const cond = exprToC(expr.args[0] as ModelicaExpression);
      return `((${cond}) ? 0.0 : 0.0)`;
    }
    const args = expr.args.map((a: ModelicaExpression) => exprToC(a)).join(", ");
    return `${mapFunctionName(expr.functionName)}(${args})`;
  }
  if (expr instanceof ModelicaIfElseExpression) {
    const cond = exprToC(expr.condition);
    const then = exprToC(expr.thenExpression);
    const els = exprToC(expr.elseExpression);
    if (expr.elseIfClauses.length > 0) {
      let result = `(${cond} ? ${then} : `;
      for (const clause of expr.elseIfClauses) {
        result += `${exprToC(clause.condition)} ? ${exprToC(clause.expression)} : `;
      }
      return result + `${els})`;
    }
    return `(${cond} ? ${then} : ${els})`;
  }
  if (expr && typeof expr === "object" && "name" in expr) {
    return varToC((expr as { name: string }).name);
  }
  return "0.0";
}

// ── DAE analysis helpers ──

function extractDerName(expr: unknown): string | null {
  if (expr && typeof expr === "object" && "functionName" in expr && "args" in expr) {
    const funcExpr = expr as { functionName: string; args: unknown[] };
    if (funcExpr.functionName === "der" && funcExpr.args.length === 1) {
      const arg0 = funcExpr.args[0];
      if (arg0 && typeof arg0 === "object" && "name" in arg0) {
        const nameVal = (arg0 as { name: unknown }).name;
        if (typeof nameVal === "string") return nameVal;
      }
    }
  }
  if (expr && typeof expr === "object" && "name" in expr) {
    const nameVal = (expr as { name: unknown }).name;
    if (typeof nameVal === "string" && nameVal.startsWith("der(") && nameVal.endsWith(")")) {
      return nameVal.substring(4, nameVal.length - 1);
    }
  }
  return null;
}

function collectReferencedNames(expr: unknown, names: Set<string>): void {
  if (!expr || typeof expr !== "object") return;
  if (expr instanceof ModelicaArray) {
    for (const elem of expr.flatElements) collectReferencedNames(elem, names);
    return;
  }
  if ("name" in expr) {
    const nameVal = (expr as { name: unknown }).name;
    if (typeof nameVal === "string") {
      if (nameVal.startsWith("der(") && nameVal.endsWith(")")) {
        names.add(nameVal.substring(4, nameVal.length - 1));
      } else {
        names.add(nameVal);
      }
    }
  }
  if ("operand" in expr) collectReferencedNames((expr as { operand: unknown }).operand, names);
  if ("operand1" in expr) collectReferencedNames((expr as { operand1: unknown }).operand1, names);
  if ("operand2" in expr) collectReferencedNames((expr as { operand2: unknown }).operand2, names);
  if ("condition" in expr) collectReferencedNames((expr as { condition: unknown }).condition, names);
  if ("thenExpression" in expr) collectReferencedNames((expr as { thenExpression: unknown }).thenExpression, names);
  if ("elseExpression" in expr) collectReferencedNames((expr as { elseExpression: unknown }).elseExpression, names);
  if ("args" in expr) {
    const args = (expr as { args: unknown[] }).args;
    if (Array.isArray(args)) {
      for (const arg of args) collectReferencedNames(arg, names);
    }
  }
  if ("elseIfClauses" in expr) {
    const clauses = (expr as { elseIfClauses: { condition: unknown; expression: unknown }[] }).elseIfClauses;
    if (Array.isArray(clauses)) {
      for (const clause of clauses) {
        collectReferencedNames(clause.condition, names);
        collectReferencedNames(clause.expression, names);
      }
    }
  }
}
