// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Standalone C simulation code generator.
 *
 * Generates a self-contained C source file with a `main()` function that:
 *   1. Initializes model state from the DAE
 *   2. Runs an RK4 integration loop
 *   3. Outputs CSV results to stdout
 *
 * Designed for `msc simulate --engine=c` — the generated binary is compiled
 * with `gcc -O3 -lm` and executed as a subprocess.
 */

import { ArenaDAEBuilder, BinOp, EqKind, ExprKind, UnaryOp, Variability } from "@modelscript/compiler";
import type { FmiScalarVariable, FmuResult } from "@modelscript/fmi";

// ── Public interface ──

export interface SimulationCOptions {
  modelIdentifier: string;
  startTime: number;
  stopTime: number;
  stepSize: number;
}

/**
 * Generate a standalone C simulation source from a DAE.
 */
export function generateSimulationC(dae: ArenaDAEBuilder, fmuResult: FmuResult, options: SimulationCOptions): string {
  const { modelIdentifier: id, startTime, stopTime, stepSize } = options;
  const vars = fmuResult.scalarVariables;
  const nVars = vars.length;
  const L: string[] = [];

  // Determine state variables and derivatives
  const derVars = vars.filter((sv) => sv.name.startsWith("der("));
  const stateVarRefs: { name: string; vr: number; derVr: number; idx: number }[] = [];
  for (const sv of vars) {
    if (sv.derivative !== undefined) {
      const stateSv = vars.find((v) => v.valueReference === sv.derivative);
      if (stateSv) {
        stateVarRefs.push({
          name: stateSv.name,
          vr: stateSv.valueReference,
          derVr: sv.valueReference,
          idx: stateVarRefs.length,
        });
      }
    }
  }
  const nStates = stateVarRefs.length;

  // VR map for variable access
  const vrMap = new Map<string, number>();
  for (const sv of vars) vrMap.set(sv.name, sv.valueReference);

  // Derivative equation mapping
  const derMap = new Map<string, number>();
  for (let i = 0; i < derVars.length; i++) {
    const nameMatch = derVars[i]?.name.match(/^der\((.+)\)$/);
    if (nameMatch) derMap.set(nameMatch[1] ?? "", i);
  }

  // ── Header ──
  L.push(`/* Auto-generated by ModelScript CLI — Standalone simulation for ${id} */`);
  L.push("");
  L.push("#include <math.h>");
  L.push("#include <string.h>");
  L.push("#include <stdio.h>");
  L.push("#include <stdint.h>");
  L.push("");

  // ── Constants ──
  L.push(`#define N_VARS ${nVars}`);
  L.push(`#define N_STATES ${nStates}`);
  L.push(`#define START_TIME ${formatCDouble(startTime)}`);
  L.push(`#define STOP_TIME ${formatCDouble(stopTime)}`);
  L.push(`#define STEP_SIZE ${formatCDouble(stepSize)}`);
  L.push("");

  // ── VR defines ──
  for (const sv of vars) {
    const cName = sanitizeIdentifier(sv.name).toUpperCase();
    L.push(`#define VR_${cName} ${sv.valueReference}`);
  }
  L.push("");

  // ── Global model state ──
  L.push("static double g_vars[N_VARS + 1];");
  L.push("static double g_states[N_STATES + 1];");
  L.push("static double g_derivatives[N_STATES + 1];");
  L.push("static double g_time = 0.0;");
  L.push("static int g_isInitPhase = 1;");
  L.push("");

  // ── Initialize function ──
  L.push("static void model_initialize(void) {");
  L.push("  memset(g_vars, 0, sizeof(g_vars));");
  L.push("  memset(g_states, 0, sizeof(g_states));");
  L.push("  memset(g_derivatives, 0, sizeof(g_derivatives));");
  L.push("  g_time = START_TIME;");
  L.push("  g_isInitPhase = 1;");

  // Set parameter/constant values
  for (let i = 0; i < dae.varCount; i++) {
    if (dae.isVarRemoved(i)) continue;
    const variability = dae.getVarVariability(i);
    if (variability === Variability.Parameter || variability === Variability.Constant) {
      const name = dae.getVarName(i);
      const ref = vrMap.get(name);
      const exprId = dae.getVarExpression(i);
      if (ref !== undefined && typeof exprId === "number" && exprId >= 0) {
        L.push(`  g_vars[${ref}] = ${exprToC(dae, exprId, vars)};  /* ${name} */`);
      }
    }
  }

  // Set start values for continuous variables
  for (let i = 0; i < dae.varCount; i++) {
    if (dae.isVarRemoved(i)) continue;
    const variability = dae.getVarVariability(i);
    if (variability === Variability.Continuous || variability === Variability.Discrete) {
      const name = dae.getVarName(i);
      const ref = vrMap.get(name);
      if (ref !== undefined) {
        const startAttr = dae.getVarAttrExprId(i, "start");
        const initExpr = typeof startAttr === "number" && startAttr >= 0 ? startAttr : dae.getVarExpression(i);
        if (typeof initExpr === "number" && initExpr >= 0) {
          L.push(`  g_vars[${ref}] = ${exprToC(dae, initExpr, vars)};  /* ${name} */`);
        } else {
          const startVal = dae.getVarStartValue(i);
          if (startVal !== 0) {
            L.push(`  g_vars[${ref}] = ${formatCDouble(startVal)};  /* ${name} */`);
          }
        }
      }
    }
  }

  // Copy initial state values into g_states[]
  for (const sv of stateVarRefs) {
    L.push(`  g_states[${sv.idx}] = g_vars[${sv.vr}];  /* ${sv.name} */`);
  }

  L.push("  g_isInitPhase = 0;");
  L.push("}");
  L.push("");

  // ── getDerivatives function ──
  L.push("static void model_get_derivatives(void) {");

  // Collect referenced variable names for local alias emission
  const refNames = new Set<string>();
  for (let i = 0; i < dae.eqCount; i++) {
    const kind = dae.getEqKind(i);
    if (kind === EqKind.Simple) {
      collectReferencedNames(dae, dae.getEqLhs(i), refNames);
      collectReferencedNames(dae, dae.getEqRhs(i), refNames);
    }
  }

  // Local aliases for referenced variables (read from g_vars[])
  for (const sv of vars) {
    if (sv.causality === "independent") continue;
    if (!refNames.has(sv.name)) continue;
    const cName = varToC(dae, sv.name, vars);
    L.push(`  double ${cName} = g_vars[${sv.valueReference}];`);
  }
  L.push("");

  // Emit derivative equations
  for (let i = 0; i < dae.eqCount; i++) {
    const kind = dae.getEqKind(i);
    if (kind !== EqKind.Simple) continue;
    const lhs = dae.getEqLhs(i);
    const rhs = dae.getEqRhs(i);
    const lhsDer = extractDerName(dae, lhs);
    const rhsDer = extractDerName(dae, rhs);
    if (lhsDer) {
      const idx = derMap.get(lhsDer);
      if (idx !== undefined) {
        L.push(`  g_derivatives[${idx}] = ${exprToC(dae, rhs, vars)};  /* der(${lhsDer}) */`);
      }
    } else if (rhsDer) {
      const idx = derMap.get(rhsDer);
      if (idx !== undefined) {
        L.push(`  g_derivatives[${idx}] = ${exprToC(dae, lhs, vars)};  /* der(${rhsDer}) */`);
      }
    }
  }

  // Also compute algebraic equations (update g_vars[])
  for (let i = 0; i < dae.eqCount; i++) {
    const kind = dae.getEqKind(i);
    if (kind !== EqKind.Simple) continue;
    const lhs = dae.getEqLhs(i);
    const rhs = dae.getEqRhs(i);
    if (dae.getExprKind(lhs) === ExprKind.Name && !extractDerName(dae, lhs)) {
      const targetName = dae.interner.resolve(dae.getExprData1(lhs));
      if (!targetName.startsWith("der(")) {
        const ref = vrMap.get(targetName);
        if (ref !== undefined) {
          L.push(`  g_vars[${ref}] = ${exprToC(dae, rhs, vars)};  /* ${targetName} */`);
        }
      }
    }
  }

  L.push("}");
  L.push("");

  // ── RK4 stepper ──
  L.push("static void rk4_step(double t, double dt) {");
  L.push("  int i;");
  L.push("  double k1[N_STATES + 1], k2[N_STATES + 1], k3[N_STATES + 1], k4[N_STATES + 1];");
  L.push("");

  L.push("  /* k1 = f(t, y) */");
  L.push("  g_time = t;");
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  model_get_derivatives();");
  L.push("  for (i = 0; i < N_STATES; i++) k1[i] = g_derivatives[i];");
  L.push("");

  L.push("  /* k2 = f(t + dt/2, y + dt/2 * k1) */");
  L.push("  g_time = t + 0.5 * dt;");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] += 0.5 * dt * k1[i];");
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  model_get_derivatives();");
  L.push("  for (i = 0; i < N_STATES; i++) k2[i] = g_derivatives[i];");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] -= 0.5 * dt * k1[i];");
  L.push("");

  L.push("  /* k3 = f(t + dt/2, y + dt/2 * k2) */");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] += 0.5 * dt * k2[i];");
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  model_get_derivatives();");
  L.push("  for (i = 0; i < N_STATES; i++) k3[i] = g_derivatives[i];");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] -= 0.5 * dt * k2[i];");
  L.push("");

  L.push("  /* k4 = f(t + dt, y + dt * k3) */");
  L.push("  g_time = t + dt;");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] += dt * k3[i];");
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  model_get_derivatives();");
  L.push("  for (i = 0; i < N_STATES; i++) k4[i] = g_derivatives[i];");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] -= dt * k3[i];");
  L.push("");

  L.push("  /* Combine: y_new = y + dt/6 * (k1 + 2*k2 + 2*k3 + k4) */");
  L.push("  for (i = 0; i < N_STATES; i++) g_states[i] += (dt / 6.0) * (k1[i] + 2.0*k2[i] + 2.0*k3[i] + k4[i]);");
  L.push("");

  // Write updated states back to g_vars[]
  for (const sv of stateVarRefs) {
    L.push(`  g_vars[${sv.vr}] = g_states[${sv.idx}];`);
  }
  L.push("  g_time = t + dt;");
  L.push("  model_get_derivatives();");
  L.push("}");
  L.push("");

  // ── main() ──
  const outputVars = vars.filter((sv) => sv.causality !== "independent" && !sv.name.startsWith("der("));

  L.push("int main(void) {");
  L.push("  model_initialize();");
  L.push("");
  L.push("  /* Print CSV header */");

  const headerNames = ["time", ...outputVars.map((sv) => sv.name)];
  L.push(`  printf("${headerNames.join(",")}\\n");`);
  L.push("");

  L.push("  double t = START_TIME;");
  L.push("  double dt = STEP_SIZE;");
  L.push("");

  // Print initial state
  L.push("  /* Print initial state */");
  L.push(generatePrintfLine(outputVars));
  L.push("");

  L.push("  /* Integration loop */");
  L.push("  while (t < STOP_TIME - 1e-15) {");
  L.push("    if (t + dt > STOP_TIME) dt = STOP_TIME - t;");
  L.push("    rk4_step(t, dt);");
  L.push("    t += dt;");
  L.push("    " + generatePrintfLine(outputVars));
  L.push("  }");
  L.push("");
  L.push("  return 0;");
  L.push("}");
  L.push("");

  return L.join("\n");
}

// ── Printf helper ──

function generatePrintfLine(outputVars: FmiScalarVariable[]): string {
  const formatParts = ["%.17g", ...outputVars.map(() => "%.17g")];
  const valueParts = ["g_time", ...outputVars.map((sv) => `g_vars[${sv.valueReference}]`)];
  return `printf("${formatParts.join(",")}\\n", ${valueParts.join(", ")});`;
}

// ── C Expression Transpiler ──

function sanitizeIdentifier(name: string): string {
  return name
    .replace(/\./g, "_")
    .replace(/\[/g, "_")
    .replace(/\]/g, "")
    .replace(/[^a-zA-Z0-9_]/g, "_");
}

function varToC(dae: ArenaDAEBuilder, name: string, vars: FmiScalarVariable[]): string {
  if (name === "time") return "g_time";
  const m = name.match(/^der\((.+)\)$/);
  const baseName = m ? (m[1] ?? "") : name;
  const sv = vars.find((v) => v.name === baseName);
  if (!sv) return `0.0 /* unknown ${name} */`;

  const cName = sanitizeIdentifier(name);
  if (m) return `der_${sanitizeIdentifier(m[1] ?? "")}`;
  return `v_${cName}`;
}

function formatCDouble(value: number): string {
  if (!isFinite(value)) {
    if (value === Infinity) return "INFINITY";
    if (value === -Infinity) return "(-INFINITY)";
    return "NAN";
  }
  const s = value.toString();
  if (!s.includes(".") && !s.includes("e") && !s.includes("E")) return s + ".0";
  return s;
}

function escapeCString(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function binaryOpToC(op: BinOp): string {
  switch (op) {
    case BinOp.Add:
    case BinOp.ElemAdd:
      return "+";
    case BinOp.Sub:
    case BinOp.ElemSub:
      return "-";
    case BinOp.Mul:
    case BinOp.ElemMul:
      return "*";
    case BinOp.Div:
    case BinOp.ElemDiv:
      return "/";
    case BinOp.Pow:
    case BinOp.ElemPow:
      return "pow";
    case BinOp.Lt:
      return "<";
    case BinOp.Lte:
      return "<=";
    case BinOp.Gt:
      return ">";
    case BinOp.Gte:
      return ">=";
    case BinOp.Eq:
      return "==";
    case BinOp.Neq:
      return "!=";
    case BinOp.And:
      return "&&";
    case BinOp.Or:
      return "||";
    default:
      return "+";
  }
}

function mapFunctionName(name: string): string {
  const builtins: Record<string, string> = {
    sin: "sin",
    cos: "cos",
    tan: "tan",
    asin: "asin",
    acos: "acos",
    atan: "atan",
    atan2: "atan2",
    sinh: "sinh",
    cosh: "cosh",
    tanh: "tanh",
    exp: "exp",
    log: "log",
    log10: "log10",
    sqrt: "sqrt",
    abs: "fabs",
    sign: "copysign",
    floor: "floor",
    ceil: "ceil",
    min: "fmin",
    max: "fmax",
    mod: "fmod",
    "Modelica.Math.sin": "sin",
    "Modelica.Math.cos": "cos",
    "Modelica.Math.log": "log",
    "Modelica.Math.exp": "exp",
    "Modelica.Math.sqrt": "sqrt",
    "Modelica.Math.atan2": "atan2",
  };
  return builtins[name] ?? sanitizeIdentifier(name);
}

function exprToC(dae: ArenaDAEBuilder, id: number, vars: FmiScalarVariable[]): string {
  if (id < 0) return "0.0 /* null */";
  switch (dae.getExprKind(id)) {
    case ExprKind.RealLiteral:
      return formatCDouble(dae.getExprRealValue(id));
    case ExprKind.IntLiteral:
      return `${dae.getExprData1(id)}`;
    case ExprKind.BoolLiteral:
      return dae.getExprData1(id) !== 0 ? "1" : "0";
    case ExprKind.StringLiteral:
      return `"${escapeCString(dae.interner.resolve(dae.getExprData1(id)))}"`;
    case ExprKind.Name:
      return varToC(dae, dae.interner.resolve(dae.getExprData1(id)), vars);
    case ExprKind.Unary: {
      const uop = dae.getExprData1(id) as UnaryOp;
      const op = uop === UnaryOp.Not ? "!" : "-";
      return `(${op}${exprToC(dae, dae.getExprLeft(id), vars)})`;
    }
    case ExprKind.Negate:
      return `(-${exprToC(dae, dae.getExprLeft(id), vars)})`;
    case ExprKind.Der: {
      const arg = dae.getExprData1(id);
      const name = dae.interner.resolve(dae.getExprData1(arg));
      return varToC(dae, `der(${name})`, vars);
    }
    case ExprKind.Pre: {
      const arg = dae.getExprData1(id);
      const name = dae.interner.resolve(dae.getExprData1(arg));
      return varToC(dae, `pre(${name})`, vars);
    }
    case ExprKind.Binary: {
      const op = dae.getExprData1(id) as BinOp;
      const lhs = exprToC(dae, dae.getExprLeft(id), vars);
      const rhs = exprToC(dae, dae.getExprRight(id), vars);
      const opStr = binaryOpToC(op);
      if (opStr === "pow") return `pow(${lhs}, ${rhs})`;
      return `(${lhs} ${opStr} ${rhs})`;
    }
    case ExprKind.Call: {
      const fname = dae.interner.resolve(dae.getExprData1(id));
      const argCount = dae.getExprRight(id);
      const args: string[] = [];
      for (let i = 0; i < argCount; i++) {
        args.push(exprToC(dae, dae.getExprLeft(id + i), vars));
      }
      if (fname === "initial") return "g_isInitPhase";
      if (fname === "terminal") return "0";
      if (fname === "assert" && args.length >= 2) {
        return `((${args[0]}) ? 0.0 : 0.0)`;
      }
      return `${mapFunctionName(fname)}(${args.join(", ")})`;
    }
    case ExprKind.IfElse: {
      const cond = exprToC(dae, dae.getExprData1(id), vars);
      const then = exprToC(dae, dae.getExprLeft(id), vars);
      const els = exprToC(dae, dae.getExprRight(id), vars);
      return `(${cond} ? ${then} : ${els})`;
    }
    default:
      return "0.0 /* unknown */";
  }
}

// ── DAE analysis helpers ──

function extractDerName(dae: ArenaDAEBuilder, exprId: number): string | null {
  if (exprId < 0) return null;
  const kind = dae.getExprKind(exprId);
  if (kind === ExprKind.Der) {
    const operandId = dae.getExprData1(exprId);
    if (dae.getExprKind(operandId) === ExprKind.Name) {
      return dae.interner.resolve(dae.getExprData1(operandId));
    }
  }
  return null;
}

function collectReferencedNames(dae: ArenaDAEBuilder, id: number, names: Set<string>): void {
  if (id < 0) return;
  const kind = dae.getExprKind(id);
  switch (kind) {
    case ExprKind.RealLiteral:
    case ExprKind.IntLiteral:
    case ExprKind.BoolLiteral:
    case ExprKind.StringLiteral:
    case ExprKind.Colon:
    case ExprKind.EnumLiteral:
      break;
    case ExprKind.Name: {
      const name = dae.interner.resolve(dae.getExprData1(id));
      names.add(name);
      break;
    }
    case ExprKind.Binary:
      collectReferencedNames(dae, dae.getExprLeft(id), names);
      collectReferencedNames(dae, dae.getExprRight(id), names);
      break;
    case ExprKind.Unary:
    case ExprKind.Negate:
    case ExprKind.Der:
    case ExprKind.Pre:
      collectReferencedNames(dae, dae.getExprData1(id), names);
      break;
    case ExprKind.Subscript: {
      collectReferencedNames(dae, dae.getExprData1(id), names);
      const scount = dae.getExprRight(id);
      for (let i = 0; i < scount; i++) {
        collectReferencedNames(dae, dae.getExprLeft(id + i), names);
      }
      break;
    }
    case ExprKind.ArrayCtor: {
      const count = dae.getExprData1(id);
      if (count > 0) {
        collectReferencedNames(dae, dae.getExprLeft(id), names);
        for (let i = 1; i < count; i++) {
          collectReferencedNames(dae, dae.getExprRight(id + i), names);
        }
      }
      break;
    }
    case ExprKind.Call: {
      const argCount = dae.getExprRight(id);
      for (let i = 0; i < argCount; i++) {
        collectReferencedNames(dae, dae.getExprLeft(id + i), names);
      }
      break;
    }
    case ExprKind.IfElse:
      collectReferencedNames(dae, dae.getExprData1(id), names);
      collectReferencedNames(dae, dae.getExprLeft(id), names);
      collectReferencedNames(dae, dae.getExprRight(id), names);
      break;
  }
}
