// SPDX-License-Identifier: AGPL-3.0-or-later

export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "compiler",
        "dsl",
        "runtime",
        "simulate",
        "modelica",
        "sysml2",
        "step",
        "cad",
        "diagram",
        "exchange",
        "lsp",
        "mcp",
        "cli",
        "api",
        "ide",
        "web",
        "docs",
        "morsel",
        "csv",
        "cfd",
        "fea",
        "scad",
        "ssp",
        "owl2",
        "modelscript",
        "ci",
        "deps",
        "repo",
      ],
    ],
    "subject-case": [0],
  },
};
