import eslint from "@eslint/js";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig([
  {
    ignores: [
      "**/.react-router/**",
      "packages/language/src/codegen/runtime/**",
      "packages/language/tests/wasm/**",
      "packages/language/src/codegen/typescript.mjs",
      "eslint.config.ts",
      "packages/compiler/src/wasm/sundials.js",
      "languages/**/src-gen/**",
      "languages/**/bindings/**",
    ],
  },
  eslint.configs.recommended,
  tseslint.configs.strict,
  tseslint.configs.stylistic,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            "eslint.config.ts",
            "languages/modelica/grammar.js",
            "languages/modelica/bindings/node/index.d.ts",
            "languages/step/grammar.js",
            "languages/step/bindings/node/index.d.ts",
            "languages/csv/grammar.js",
            "languages/csv/bindings/node/index.d.ts",
            "languages/owl2/grammar.js",
            "languages/owl2/bindings/node/index.d.ts",
            "languages/sysml2/grammar.js",
            "languages/sysml2/bindings/node/index.d.ts",
            "scripts/generate-ast.ts",
            "scripts/compare-trajectories.ts",
            "scripts/generate-benchmark.ts",
            "scripts/benchmark-incremental.ts",
            "scripts/fetch-reference-fmus.ts",
            "packages/fmi/scripts/compare-csv.ts",
            "packages/fmi/scripts/fetch-fmusim.ts",
            "packages/fmi/scripts/fmusim-verify.ts",
            "packages/fmi/scripts/omc-verify.ts",
            "packages/fmi/scripts/validate.ts",
            "apps/docs/docs/.vitepress/config.ts",
            "apps/docs/docs/.vitepress/theme/index.ts",
            "languages/example/src/language.ts",
            "apps/api/scripts/check_db.ts",
            "apps/api/scripts/seed-social-db.ts",
            "packages/examples/drone-chassis/cad/drone.mcad.ts",
            "packages/compiler/incremental-bench.ts",
            "packages/compiler/bench-50k.ts",
            "packages/compiler/bench_direct.ts",
            "packages/compiler/bench_stages.ts",
            "packages/examples/drone-chassis/evaluate-manufacturing.ts",
            "packages/language/src/codegen/runtime/engine.ts",
            "packages/language/src/codegen/runtime/arena.ts",
            "packages/language/src/codegen/runtime/array.ts",
            "packages/language/src/codegen/runtime/cursor.ts",
            "packages/language/examples/calc/src/language.ts",
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ["scripts/**/*.ts", "packages/compiler/bench*.ts", "packages/fmi/scripts/**/*.ts"],
    rules: {
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/consistent-generic-constructors": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/prefer-for-of": "off",
      "no-useless-escape": "off",
      "no-useless-assignment": "off",
      "preserve-caught-error": "off",
    },
  },
  {
    files: ["apps/cli/src/commands/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "prefer-const": "off",
      "no-empty": "off",
    },
  },
  {
    files: ["packages/core/tests/debug-*.ts", "packages/core/tests/redeclare_test.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    files: ["apps/morsel/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/class-literal-property-style": "off",
      "@typescript-eslint/no-dynamic-delete": "off",
      "no-useless-assignment": "off",
      "prefer-const": "off",
    },
  },
  {
    files: ["packages/language/src/**/*.ts", "packages/compiler/src/**/*.ts", "packages/fmi/src/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "prefer-const": "off",
      "@typescript-eslint/no-empty-function": "off",
      "no-empty": "off",
      "@typescript-eslint/no-inferrable-types": "off",
      "no-useless-assignment": "off",
      "@typescript-eslint/ban-ts-comment": "off",
    },
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
  },
]);
