import eslint from "@eslint/js";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig([
  {
    ignores: [
      "**/.react-router/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/vendor/**",
      "**/as-pect.config.js",
      "packages/dsl/bin/**",
      "packages/dsl/scripts/**",
      "packages/simulate/scripts/**",
      "packages/runtime/assembly/**",
      "**/assembly/**",
      "packages/runtime/src/wasm/**",
      "packages/runtime/build/**",
      "packages/dsl/src/codegen/runtime/**",
      "packages/runtime/tests/wasm/**",
      "**/scratch*/**",
      "packages/dsl/src/codegen/typescript.mjs",
      "packages/simulate/src/wasm/**",
      "languages/**/src-gen/**",
      "**/src-gen/**",
      "languages/**/bindings/**",
      "**/grammar.js",
    ],
  },
  eslint.configs.recommended,
  tseslint.configs.strict,
  tseslint.configs.stylistic,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          maximumDefaultProjectFileMatchCount_THIS_WILL_SLOW_DOWN_LINTING: 100,
          allowDefaultProject: [
            "eslint.config.ts",
            "languages/modelica/tests/*.ts",
            "scripts/compare-trajectories.ts",
            "scripts/generate-benchmark.ts",
            "scripts/generate-drone-step.ts",
            "scripts/fetch-reference-fmus.ts",
            "packages/exchange/validation/fmi/scripts/compare-csv.ts",
            "packages/exchange/validation/fmi/scripts/fetch-fmusim.ts",
            "packages/exchange/validation/fmi/scripts/fmusim-verify.ts",
            "packages/exchange/validation/fmi/scripts/omc-verify.ts",
            "packages/exchange/validation/fmi/scripts/validate.ts",
            "apps/docs/docs/.vitepress/config.ts",
            "apps/docs/docs/.vitepress/theme/index.ts",
            "apps/api/scripts/*.ts",
            "apps/ide/scripts/*.ts",
            "languages/sysml2/scripts/*.ts",
            "packages/lsp/scripts/*.ts",
            "packages/examples/drone-chassis/cad/drone.mcad.ts",
            "packages/examples/drone-chassis/evaluate-manufacturing.ts",
            "packages/dsl/src/codegen/runtime/engine.ts",
            "packages/dsl/src/codegen/runtime/arena.ts",
            "packages/dsl/src/codegen/runtime/array.ts",
            "packages/dsl/src/codegen/runtime/cursor.ts",
            "packages/dsl/src/codegen/runtime/fmi2_wasm.ts",
            "packages/dsl/src/codegen/runtime/fmi3_wasm.ts",
            "apps/cli/tests/*.ts",
            "packages/exchange/validation/*.ts",
            "apps/cli/jest.config.ts",
            "languages/ssp/tests/*.ts",
            "languages/step/tests/*.ts",
            "languages/sysml2/tests/*.ts",
            "apps/api/tests/*.ts",
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ["scripts/**/*.ts", "packages/exchange/validation/**/*.ts", "apps/cli/tests/**/*.ts"],
    rules: {
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/consistent-generic-constructors": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/prefer-for-of": "off",
      "no-useless-escape": "off",
      "no-useless-assignment": "off",
      "preserve-caught-error": "off",
    },
  },
  {
    files: ["apps/cli/src/commands/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "prefer-const": "off",
      "no-empty": "off",
    },
  },
  {
    files: ["languages/**/tests/**/*.ts", "packages/**/tests/**/*.ts", "apps/**/tests/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "no-empty": "off",
      "prefer-const": "off",
    },
  },
  {
    files: ["apps/morsel/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/class-literal-property-style": "off",
      "@typescript-eslint/no-dynamic-delete": "off",
      "no-useless-assignment": "off",
      "prefer-const": "off",
    },
  },
  {
    files: ["packages/*/src/**/*.ts", "languages/**/src/**/*.ts", "languages/**/transformers/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "prefer-const": "off",
      "@typescript-eslint/no-empty-function": "off",
      "no-empty": "off",
      "@typescript-eslint/no-inferrable-types": "off",
      "no-useless-assignment": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-extraneous-class": "off",
      "@typescript-eslint/consistent-generic-constructors": "off",
      "@typescript-eslint/prefer-for-of": "off",
    },
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
  },
]);
