// SPDX-License-Identifier: AGPL-3.0-or-later

import { type ArenaDAEBuilder, BinOp, EqKind, ExprKind, UnaryOp } from "@modelscript/compiler";

import type { FmuOptions, FmuResult } from "./fmi.js";
import { binaryOpToJs, escapeJsString, mapFunctionNameJs, sanitizeIdentifier } from "./transpiler-utils.js";

/**
 * Generate FMI 2.0 compatible Javascript source file from a DAE and FMU result.
 */
export function generateFmuJsSources(dae: ArenaDAEBuilder, fmuResult: FmuResult, options: FmuOptions): string {
  const id = options.modelIdentifier;
  const vars = fmuResult.scalarVariables;
  const nStates = fmuResult.modelStructure.derivatives.length;
  const nVars = vars.length;

  return generateModelJs(id, nVars, nStates, dae, fmuResult);
}

function exprToJs(dae: ArenaDAEBuilder, id: number): string {
  if (id < 0) return "0.0";
  switch (dae.getExprKind(id)) {
    case ExprKind.RealLiteral:
      return `${dae.getExprRealValue(id)}`;
    case ExprKind.IntLiteral:
      return `${dae.getExprData1(id)}`;
    case ExprKind.BoolLiteral:
      return dae.getExprData1(id) !== 0 ? "1" : "0";
    case ExprKind.StringLiteral:
      return `"${escapeJsString(dae.interner.resolve(dae.getExprData1(id)))}"`;
    case ExprKind.Name:
      return varToJs(dae.interner.resolve(dae.getExprData1(id)));
    case ExprKind.Unary: {
      const uop = dae.getExprData1(id) as UnaryOp;
      const op = uop === UnaryOp.Negate ? "-" : "!";
      return `(${op}${exprToJs(dae, dae.getExprLeft(id))})`;
    }
    case ExprKind.Negate:
      return `(-${exprToJs(dae, dae.getExprLeft(id))})`;
    case ExprKind.Binary: {
      const op = dae.getExprData1(id) as BinOp;
      const lhs = exprToJs(dae, dae.getExprLeft(id));
      const rhs = exprToJs(dae, dae.getExprRight(id));
      const opStr = binaryOpToJs(op);
      if (opStr === "pow") return `Math.pow(${lhs}, ${rhs})`;
      return `(${lhs} ${opStr} ${rhs})`;
    }
    case ExprKind.Call: {
      const fname = dae.interner.resolve(dae.getExprData1(id));
      const argCount = dae.getExprRight(id);
      if (fname === "initial") return "this.isInitPhase";
      if (fname === "terminal") return "0";
      if (fname === "assert" && argCount >= 2) {
        const cond = exprToJs(dae, dae.getExprLeft(id));
        const msgExpr = dae.getExprLeft(id + 1);
        const msg =
          dae.getExprKind(msgExpr) === ExprKind.StringLiteral
            ? dae.interner.resolve(dae.getExprData1(msgExpr)).replace(/"/g, '\\"')
            : "Assertion failed";
        return `((${cond}) ? 0.0 : (console.error("${msg}"), this.terminate = true, 0.0))`;
      }
      const args: string[] = [];
      for (let i = 0; i < argCount; i++) {
        args.push(exprToJs(dae, dae.getExprLeft(id + i)));
      }
      const mappedName = mapFunctionNameJs(fname);
      return `${mappedName}(${args.join(", ")})`;
    }
    case ExprKind.IfElse: {
      const cond = exprToJs(dae, dae.getExprData1(id));
      const then = exprToJs(dae, dae.getExprLeft(id));
      const els = exprToJs(dae, dae.getExprRight(id));
      return `(${cond} ? ${then} : ${els})`;
    }
    default:
      return "0.0";
  }
}

function varToJs(name: string): string {
  if (name === "time") return "this.time";
  return `this.vars[VR_${sanitizeIdentifier(name).toUpperCase()}]`;
}

function generateModelJs(id: string, nVars: number, nStates: number, dae: ArenaDAEBuilder, result: FmuResult): string {
  const lines: string[] = [];
  lines.push("/* Auto-generated by ModelScript — Javascript FMI */");

  // Variable Constants
  for (const sv of result.scalarVariables) {
    const cName = sanitizeIdentifier(sv.name).toUpperCase();
    lines.push(`const VR_${cName} = ${sv.valueReference};`);
  }

  lines.push("");
  lines.push("class FmuModel {");
  lines.push("  constructor() {");
  lines.push(`    this.vars = new Float64Array(${nVars + 1});`);
  lines.push(`    this.states = new Float64Array(${nStates + 1});`);
  lines.push(`    this.derivatives = new Float64Array(${nStates + 1});`);
  lines.push(`    this.time = 0.0;`);
  lines.push(`    this.isInitPhase = 1;`);
  lines.push(`    this.terminate = false;`);

  // Initial parameters
  for (const sv of result.scalarVariables) {
    if (sv.start !== undefined) {
      lines.push(`    this.vars[${sv.valueReference}] = ${sv.start};`);
    }
  }

  lines.push("  }");
  lines.push("");

  lines.push("  getDerivatives() {");

  // Extract state variables and mapping
  const derVRs = result.modelStructure.derivatives;
  const stateVRs: number[] = [];
  const derVars = result.scalarVariables.filter((sv) => sv.name.startsWith("der("));

  for (const dv of derVars) {
    if (dv.derivative !== undefined) {
      stateVRs.push(dv.derivative);
    }
  }

  for (let i = 0; i < stateVRs.length; i++) {
    lines.push(`    this.states[${i}] = this.vars[${stateVRs[i]}];`);
  }

  for (let idx = 0; idx < dae.eqCount; idx++) {
    if (dae.getEqKind(idx) !== EqKind.Simple) continue;
    const lhs = dae.getEqLhs(idx);
    const rhs = dae.getEqRhs(idx);
    if (dae.getExprKind(lhs) === ExprKind.Name) {
      const name = dae.interner.resolve(dae.getExprData1(lhs));
      lines.push(`    ${varToJs(name)} = ${exprToJs(dae, rhs)};`);
    }
  }

  for (let i = 0; i < derVRs.length; i++) {
    lines.push(`    this.derivatives[${i}] = this.vars[${derVRs[i]}];`);
  }

  lines.push("  }");
  lines.push("");
  lines.push("  doStep(currentCommunicationPoint, communicationStepSize) {");
  lines.push("    this.isInitPhase = 0;");
  lines.push("    this.time = currentCommunicationPoint;");
  lines.push("    const dt = communicationStepSize;");
  lines.push("    ");
  lines.push("    // Basic explicit forward Euler step for demo purposes in Javascript");
  lines.push("    this.getDerivatives();");
  for (let i = 0; i < stateVRs.length; i++) {
    lines.push(`    this.vars[${stateVRs[i]}] = this.vars[${stateVRs[i]}] + this.derivatives[${i}] * dt;`);
  }
  lines.push("    this.time += dt;");
  lines.push("    this.getDerivatives();");
  lines.push("  }");
  lines.push("}");

  return lines.join("\n");
}
