; highlights.scm — Auto-generated by @modelscript/compiler
; Language: owl2
; Do not edit manually — regenerate with: npm run generate

; ─── Keywords ───────────────────────────────────────────────────────
[
  "Class" "ClassAssertion" "DataAllValuesFrom" "DataProperty" "DataPropertyAssertion" "DataSomeValuesFrom"
  "Declaration" "DisjointClasses" "EquivalentClasses" "Import" "NamedIndividual" "ObjectAllValuesFrom"
  "ObjectComplementOf" "ObjectIntersectionOf" "ObjectProperty" "ObjectPropertyAssertion" "ObjectSomeValuesFrom" "ObjectUnionOf"
  "Ontology" "Prefix" "SubClassOf" "TransitiveObjectProperty"
] @keyword

; ─── Import paths ─────────────────────────────────────────────────
(ImportDeclaration (QualifiedName) @string.special)

; ─── Operators ────────────────────────────────────────────────────
[
  "="
] @operator

; ─── Brackets ─────────────────────────────────────────────────────
["(" ")"] @punctuation.bracket

; ─── Delimiters ───────────────────────────────────────────────────
[":"] @punctuation.delimiter

; ─── Comments ─────────────────────────────────────────────────────

; ─── Literals ─────────────────────────────────────────────────────

; ─── Boolean/null literals ─────────────────────────────────────────

; ─── Identifier fallback ──────────────────────────────────────────
(Name) @variable

