; highlights.scm — Auto-generated by @modelscript/compiler
; Language: owl2
; Do not edit manually — regenerate with: npm run generate

; ─── Keywords ───────────────────────────────────────────────────────
[
  "Class" "ClassAssertion" "DataAllValuesFrom" "DataProperty" "DataPropertyAssertion" "DataSomeValuesFrom"
  "Declaration" "DisjointClasses" "EquivalentClasses" "NamedIndividual" "ObjectAllValuesFrom" "ObjectComplementOf"
  "ObjectIntersectionOf" "ObjectProperty" "ObjectPropertyAssertion" "ObjectSomeValuesFrom" "ObjectUnionOf" "Ontology"
  "Prefix" "SubClassOf" "TransitiveObjectProperty"
] @keyword

; ─── Operators ────────────────────────────────────────────────────
[
  "="
] @operator

; ─── Brackets ─────────────────────────────────────────────────────
["(" ")"] @punctuation.bracket

; ─── Comments ─────────────────────────────────────────────────────

; ─── Literals ─────────────────────────────────────────────────────

; ─── Boolean/null literals ─────────────────────────────────────────

; ─── Identifier fallback ──────────────────────────────────────────
(Name) @variable

