// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * FMU Harness — FMI 3.0 C source generator.
 *
 * Generates a standalone C program that:
 *   1. Extracts an FMU (.fmu = ZIP) archive to a temp directory
 *   2. dlopen()s the shared library matching the current platform
 *   3. Reads JSON-RPC commands from stdin
 *   4. Calls FMI 3.0 C API functions
 *   5. Writes JSON-RPC responses to stdout
 *   6. Proxies fmi3IntermediateUpdateCallback as JSON-RPC notifications
 *
 * Protocol extensions over FMI 2.0 harness:
 *   - "intermediateUpdate" notifications (FMU → orchestrator)
 *   - "getClocks" / "setClocks" methods
 *   - "updateDiscreteStates" method
 *   - Array-valued get/set for native FMI 3.0 arrays
 */

/**
 * Generate the C source code for the FMI 3.0 FMU harness binary.
 */
export function generateFmi3HarnessC(): string {
  return `/* Auto-generated by ModelScript — FMI 3.0 harness binary */
/* Loads an FMU shared library and serves FMI 3.0 calls via JSON-RPC on stdin/stdout */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#ifdef _WIN32
  #include <windows.h>
  #define DLOPEN(path) LoadLibraryA(path)
  #define DLSYM(handle, name) (void*)GetProcAddress((HMODULE)(handle), name)
  #define DLCLOSE(handle) FreeLibrary((HMODULE)(handle))
  #define PATH_SEP "\\\\\\\\"
#else
  #include <dlfcn.h>
  #include <sys/stat.h>
  #define DLOPEN(path) dlopen(path, RTLD_NOW)
  #define DLSYM(handle, name) dlsym(handle, name)
  #define DLCLOSE(handle) dlclose(handle)
  #define PATH_SEP "/"
#endif

/* ── FMI 3.0 type definitions ── */
typedef unsigned int fmi3ValueReference;
typedef double fmi3Float64;
typedef float fmi3Float32;
typedef int fmi3Int32;
typedef int fmi3Boolean;
typedef const char* fmi3String;
typedef void* fmi3Instance;
typedef void* fmi3FMUState;
typedef unsigned char fmi3Byte;
typedef int fmi3Status;
typedef int fmi3Boolean;
typedef void* fmi3InstanceEnvironment;

#define fmi3OK 0
#define fmi3Warning 1
#define fmi3Discard 2
#define fmi3Error 3
#define fmi3Fatal 4
#define fmi3True 1
#define fmi3False 0
#define fmi3ClockActive 1
#define fmi3ClockInactive 0

/* FMI 3.0 callback types */
typedef void (*fmi3LogMessageCallback)(fmi3InstanceEnvironment, fmi3Status, fmi3String, fmi3String);
typedef void (*fmi3IntermediateUpdateCallback)(
  fmi3InstanceEnvironment, fmi3Float64, fmi3Boolean, fmi3Boolean,
  fmi3Boolean, fmi3Boolean, const fmi3ValueReference*, size_t, fmi3Boolean*);

/* ── FMI 3.0 function pointer types ── */
typedef fmi3Instance (*fmi3InstantiateCoSimulationTF)(
  fmi3String, fmi3String, fmi3String, fmi3Boolean, fmi3Boolean,
  fmi3Boolean, fmi3Boolean, const fmi3ValueReference*, size_t,
  fmi3InstanceEnvironment, fmi3LogMessageCallback, fmi3IntermediateUpdateCallback);

typedef fmi3Instance (*fmi3InstantiateModelExchangeTF)(
  fmi3String, fmi3String, fmi3String, fmi3Boolean, fmi3Boolean,
  fmi3InstanceEnvironment, fmi3LogMessageCallback);

typedef fmi3Status (*fmi3EnterInitializationModeTF)(fmi3Instance, fmi3Boolean, fmi3Float64, fmi3Float64, fmi3Boolean, fmi3Float64);
typedef fmi3Status (*fmi3ExitInitializationModeTF)(fmi3Instance);

typedef fmi3Status (*fmi3DoStepTF)(fmi3Instance, fmi3Float64, fmi3Float64, fmi3Boolean,
  fmi3Boolean*, fmi3Boolean*, fmi3Boolean*, fmi3Float64*);

typedef fmi3Status (*fmi3GetFloat64TF)(fmi3Instance, const fmi3ValueReference*, size_t, fmi3Float64*, size_t);
typedef fmi3Status (*fmi3SetFloat64TF)(fmi3Instance, const fmi3ValueReference*, size_t, const fmi3Float64*, size_t);
typedef fmi3Status (*fmi3GetInt32TF)(fmi3Instance, const fmi3ValueReference*, size_t, fmi3Int32*, size_t);
typedef fmi3Status (*fmi3SetInt32TF)(fmi3Instance, const fmi3ValueReference*, size_t, const fmi3Int32*, size_t);
typedef fmi3Status (*fmi3GetBooleanTF)(fmi3Instance, const fmi3ValueReference*, size_t, fmi3Boolean*, size_t);
typedef fmi3Status (*fmi3SetBooleanTF)(fmi3Instance, const fmi3ValueReference*, size_t, const fmi3Boolean*, size_t);

typedef fmi3Status (*fmi3TerminateTF)(fmi3Instance);
typedef void (*fmi3FreeInstanceTF)(fmi3Instance);
typedef fmi3Status (*fmi3ResetTF)(fmi3Instance);

/* ME function pointer types */
typedef fmi3Status (*fmi3SetTimeTF)(fmi3Instance, fmi3Float64);
typedef fmi3Status (*fmi3SetContinuousStatesTF)(fmi3Instance, const fmi3Float64*, size_t);
typedef fmi3Status (*fmi3GetContinuousStateDerivativesTF)(fmi3Instance, fmi3Float64*, size_t);
typedef fmi3Status (*fmi3GetContinuousStatesTF)(fmi3Instance, fmi3Float64*, size_t);
typedef fmi3Status (*fmi3GetEventIndicatorsTF)(fmi3Instance, fmi3Float64*, size_t);

/* State management */
typedef fmi3Status (*fmi3GetFMUStateTF)(fmi3Instance, fmi3FMUState*);
typedef fmi3Status (*fmi3SetFMUStateTF)(fmi3Instance, fmi3FMUState);
typedef fmi3Status (*fmi3FreeFMUStateTF)(fmi3Instance, fmi3FMUState*);

/* Discrete states */
typedef fmi3Status (*fmi3UpdateDiscreteStatesTF)(fmi3Instance,
  fmi3Boolean*, fmi3Boolean*, fmi3Boolean*, fmi3Boolean*, fmi3Boolean*, fmi3Float64*);

/* ── FMU handle ── */
typedef struct {
  void* lib;
  fmi3Instance inst;
  char modelIdentifier[256];
  char instantiationToken[256];
  char extractDir[1024];

  /* Function pointers */
  fmi3InstantiateCoSimulationTF InstantiateCS;
  fmi3InstantiateModelExchangeTF InstantiateME;
  fmi3EnterInitializationModeTF EnterInitializationMode;
  fmi3ExitInitializationModeTF ExitInitializationMode;
  fmi3DoStepTF DoStep;
  fmi3GetFloat64TF GetFloat64;
  fmi3SetFloat64TF SetFloat64;
  fmi3GetInt32TF GetInt32;
  fmi3SetInt32TF SetInt32;
  fmi3GetBooleanTF GetBoolean;
  fmi3SetBooleanTF SetBoolean;
  fmi3TerminateTF Terminate;
  fmi3FreeInstanceTF FreeInstance;
  fmi3ResetTF Reset;
  fmi3SetTimeTF SetTime;
  fmi3SetContinuousStatesTF SetContinuousStates;
  fmi3GetContinuousStateDerivativesTF GetDerivatives;
  fmi3GetContinuousStatesTF GetContinuousStates;
  fmi3GetEventIndicatorsTF GetEventIndicators;
  fmi3GetFMUStateTF GetFMUState;
  fmi3SetFMUStateTF SetFMUState;
  fmi3FreeFMUStateTF FreeFMUState;
  fmi3UpdateDiscreteStatesTF UpdateDiscreteStates;

  /* State management */
  fmi3FMUState savedStates[64];
  int nextStateId;
  int isME;
} FMU3Handle;

/* ── Simple JSON helpers ── */

static void json_respond_ok(int id) {
  printf("{\\\\"result\\\\":\\\\"ok\\\\",\\\\"id\\\\":%d}\\\\n", id);
  fflush(stdout);
}

static void json_respond_error(int id, const char* msg) {
  printf("{\\\\"error\\\\":{\\\\"code\\\\":-1,\\\\"message\\\\":\\\\"%s\\\\"},\\\\"id\\\\":%d}\\\\n", msg, id);
  fflush(stdout);
}

/* ── Intermediate Update Callback (proxied as JSON-RPC notification) ── */
static void intermediateUpdateCallback(
  fmi3InstanceEnvironment env,
  fmi3Float64 intermediateUpdateTime,
  fmi3Boolean clocksTicked,
  fmi3Boolean intermediateVariableSetRequested,
  fmi3Boolean intermediateVariableGetAllowed,
  fmi3Boolean intermediateStepFinished,
  const fmi3ValueReference requiredIntermediateVariables[],
  size_t nRequiredIntermediateVariables,
  fmi3Boolean* canReturnEarly)
{
  (void)env;
  (void)requiredIntermediateVariables;
  (void)nRequiredIntermediateVariables;
  /* Send a JSON-RPC notification (no id field) to the orchestrator */
  printf("{\\\\"method\\\\":\\\\"intermediateUpdate\\\\",\\\\"params\\\\":{"
         "\\\\"time\\\\":%g,"
         "\\\\"clocksTicked\\\\":%s,"
         "\\\\"intermediateVariableSetRequested\\\\":%s,"
         "\\\\"intermediateVariableGetAllowed\\\\":%s,"
         "\\\\"intermediateStepFinished\\\\":%s"
         "}}\\\\n",
    intermediateUpdateTime,
    clocksTicked ? "true" : "false",
    intermediateVariableSetRequested ? "true" : "false",
    intermediateVariableGetAllowed ? "true" : "false",
    intermediateStepFinished ? "true" : "false");
  fflush(stdout);
  /* For now, never request early return from the notification side */
  *canReturnEarly = fmi3False;
}

/* ── Dummy logger ── */
static void dummyLogger(fmi3InstanceEnvironment env, fmi3Status status, fmi3String category, fmi3String message) {
  (void)env; (void)status; (void)category; (void)message;
}

/* ── Extract FMU (system unzip) ── */
static int extractFmu(const char* fmuPath, const char* destDir) {
  char cmd[2048];
#ifdef _WIN32
  snprintf(cmd, sizeof(cmd), "powershell -Command \\\\"Expand-Archive -Path '%s' -DestinationPath '%s' -Force\\\\"", fmuPath, destDir);
#else
  snprintf(cmd, sizeof(cmd), "unzip -o -q '%s' -d '%s'", fmuPath, destDir);
#endif
  return system(cmd);
}

/* ── Load FMU shared library ── */
static int loadFmu(FMU3Handle* h) {
  char libPath[2048];
#if defined(_WIN32)
  #if defined(_M_X64) || defined(__x86_64__)
    const char* platform = "x86_64-windows";
  #else
    const char* platform = "x86-windows";
  #endif
  snprintf(libPath, sizeof(libPath), "%s" PATH_SEP "binaries" PATH_SEP "%s" PATH_SEP "%s.dll",
    h->extractDir, platform, h->modelIdentifier);
#elif defined(__APPLE__)
  const char* platform = "x86_64-darwin";
  snprintf(libPath, sizeof(libPath), "%s" PATH_SEP "binaries" PATH_SEP "%s" PATH_SEP "%s.dylib",
    h->extractDir, platform, h->modelIdentifier);
#else
  const char* platform = "x86_64-linux";
  snprintf(libPath, sizeof(libPath), "%s" PATH_SEP "binaries" PATH_SEP "%s" PATH_SEP "%s.so",
    h->extractDir, platform, h->modelIdentifier);
#endif

  h->lib = DLOPEN(libPath);
  if (!h->lib) return -1;

  /* Resolve FMI 3.0 functions */
  h->InstantiateCS = (fmi3InstantiateCoSimulationTF)DLSYM(h->lib, "fmi3InstantiateCoSimulation");
  h->InstantiateME = (fmi3InstantiateModelExchangeTF)DLSYM(h->lib, "fmi3InstantiateModelExchange");
  h->EnterInitializationMode = (fmi3EnterInitializationModeTF)DLSYM(h->lib, "fmi3EnterInitializationMode");
  h->ExitInitializationMode = (fmi3ExitInitializationModeTF)DLSYM(h->lib, "fmi3ExitInitializationMode");
  h->DoStep = (fmi3DoStepTF)DLSYM(h->lib, "fmi3DoStep");
  h->GetFloat64 = (fmi3GetFloat64TF)DLSYM(h->lib, "fmi3GetFloat64");
  h->SetFloat64 = (fmi3SetFloat64TF)DLSYM(h->lib, "fmi3SetFloat64");
  h->GetInt32 = (fmi3GetInt32TF)DLSYM(h->lib, "fmi3GetInt32");
  h->SetInt32 = (fmi3SetInt32TF)DLSYM(h->lib, "fmi3SetInt32");
  h->GetBoolean = (fmi3GetBooleanTF)DLSYM(h->lib, "fmi3GetBoolean");
  h->SetBoolean = (fmi3SetBooleanTF)DLSYM(h->lib, "fmi3SetBoolean");
  h->Terminate = (fmi3TerminateTF)DLSYM(h->lib, "fmi3Terminate");
  h->FreeInstance = (fmi3FreeInstanceTF)DLSYM(h->lib, "fmi3FreeInstance");
  h->Reset = (fmi3ResetTF)DLSYM(h->lib, "fmi3Reset");
  h->SetTime = (fmi3SetTimeTF)DLSYM(h->lib, "fmi3SetTime");
  h->SetContinuousStates = (fmi3SetContinuousStatesTF)DLSYM(h->lib, "fmi3SetContinuousStates");
  h->GetDerivatives = (fmi3GetContinuousStateDerivativesTF)DLSYM(h->lib, "fmi3GetContinuousStateDerivatives");
  h->GetContinuousStates = (fmi3GetContinuousStatesTF)DLSYM(h->lib, "fmi3GetContinuousStates");
  h->GetEventIndicators = (fmi3GetEventIndicatorsTF)DLSYM(h->lib, "fmi3GetEventIndicators");
  h->GetFMUState = (fmi3GetFMUStateTF)DLSYM(h->lib, "fmi3GetFMUState");
  h->SetFMUState = (fmi3SetFMUStateTF)DLSYM(h->lib, "fmi3SetFMUState");
  h->FreeFMUState = (fmi3FreeFMUStateTF)DLSYM(h->lib, "fmi3FreeFMUState");
  h->UpdateDiscreteStates = (fmi3UpdateDiscreteStatesTF)DLSYM(h->lib, "fmi3UpdateDiscreteStates");

  return 0;
}

/* ── Main JSON-RPC loop ── */
int main(int argc, char* argv[]) {
  if (argc < 4) {
    fprintf(stderr, "Usage: %s <fmu-path> <model-id> <token>\\\\n", argv[0]);
    return 1;
  }

  FMU3Handle h;
  memset(&h, 0, sizeof(h));
  strncpy(h.modelIdentifier, argv[2], sizeof(h.modelIdentifier) - 1);
  strncpy(h.instantiationToken, argv[3], sizeof(h.instantiationToken) - 1);

  /* Extract FMU */
  snprintf(h.extractDir, sizeof(h.extractDir), "/tmp/fmu3_%s_%d", h.modelIdentifier, (int)getpid());
#ifndef _WIN32
  mkdir(h.extractDir, 0755);
#endif
  if (extractFmu(argv[1], h.extractDir) != 0) {
    fprintf(stderr, "Failed to extract FMU\\\\n");
    return 1;
  }

  if (loadFmu(&h) != 0) {
    fprintf(stderr, "Failed to load FMU library\\\\n");
    return 1;
  }

  /* Signal ready */
  printf("{\\\\"ready\\\\":true,\\\\"fmiVersion\\\\":\\\\"3.0\\\\"}\\\\n");
  fflush(stdout);

  /* Read commands */
  char line[65536];
  while (fgets(line, sizeof(line), stdin)) {
    /* Minimal JSON parsing for the method and id fields */
    int id = 0;
    char method[64] = {0};
    char* mp = strstr(line, "\\\\"method\\\\":\\\\"");
    if (mp) { mp += 10; char* ep = strchr(mp, '"'); if (ep) { size_t len = ep - mp; if (len < sizeof(method)) { memcpy(method, mp, len); method[len] = 0; } } }
    char* ip = strstr(line, "\\\\"id\\\\":");
    if (ip) id = atoi(ip + 5);

    if (strcmp(method, "initialize") == 0) {
      /* Parse startTime, stopTime */
      double startTime = 0, stopTime = 10;
      char* st = strstr(line, "\\\\"startTime\\\\":");
      if (st) startTime = atof(st + 12);
      char* et = strstr(line, "\\\\"stopTime\\\\":");
      if (et) stopTime = atof(et + 11);

      /* Instantiate as Co-Simulation with intermediate update callback */
      if (h.InstantiateCS) {
        h.inst = h.InstantiateCS(
          h.modelIdentifier, h.instantiationToken, h.extractDir,
          fmi3False, fmi3False, fmi3False, fmi3True,
          NULL, 0, NULL, dummyLogger, intermediateUpdateCallback);
      }
      if (!h.inst) { json_respond_error(id, "instantiate failed"); continue; }

      if (h.EnterInitializationMode)
        h.EnterInitializationMode(h.inst, fmi3False, 0, startTime, fmi3True, stopTime);
      if (h.ExitInitializationMode)
        h.ExitInitializationMode(h.inst);

      json_respond_ok(id);

    } else if (strcmp(method, "doStep") == 0) {
      double currentTime = 0, stepSize = 0.01;
      char* ct = strstr(line, "\\\\"currentTime\\\\":");
      if (ct) currentTime = atof(ct + 14);
      char* ss = strstr(line, "\\\\"stepSize\\\\":");
      if (ss) stepSize = atof(ss + 11);

      fmi3Boolean eventHandling = fmi3False, terminate = fmi3False, earlyReturn = fmi3False;
      fmi3Float64 lastTime = currentTime;

      if (h.DoStep) {
        fmi3Status s = h.DoStep(h.inst, currentTime, stepSize, fmi3True,
          &eventHandling, &terminate, &earlyReturn, &lastTime);
        printf("{\\\\"result\\\\":{\\\\"status\\\\":%d,\\\\"earlyReturn\\\\":%s,\\\\"lastTime\\\\":%g},\\\\"id\\\\":%d}\\\\n",
          s, earlyReturn ? "true" : "false", lastTime, id);
        fflush(stdout);
      } else {
        json_respond_error(id, "doStep not available");
      }

    } else if (strcmp(method, "getOutputs") == 0) {
      /* Placeholder: caller provides VR list in params.valueReferences */
      json_respond_ok(id);

    } else if (strcmp(method, "setInputs") == 0) {
      json_respond_ok(id);

    } else if (strcmp(method, "updateDiscreteStates") == 0) {
      if (h.UpdateDiscreteStates) {
        fmi3Boolean needUpdate, term, nomChanged, valChanged, nextEvtDef;
        fmi3Float64 nextEvtTime;
        h.UpdateDiscreteStates(h.inst, &needUpdate, &term, &nomChanged, &valChanged, &nextEvtDef, &nextEvtTime);
        printf("{\\\\"result\\\\":{\\\\"needUpdate\\\\":%s,\\\\"terminate\\\\":%s,\\\\"nextEventTimeDefined\\\\":%s,\\\\"nextEventTime\\\\":%g},\\\\"id\\\\":%d}\\\\n",
          needUpdate ? "true" : "false", term ? "true" : "false",
          nextEvtDef ? "true" : "false", nextEvtTime, id);
        fflush(stdout);
      } else {
        json_respond_error(id, "updateDiscreteStates not available");
      }

    } else if (strcmp(method, "getState") == 0) {
      if (h.GetFMUState && h.nextStateId < 64) {
        fmi3FMUState state = NULL;
        h.GetFMUState(h.inst, &state);
        int sid = h.nextStateId++;
        h.savedStates[sid] = state;
        printf("{\\\\"result\\\\":{\\\\"stateId\\\\":%d},\\\\"id\\\\":%d}\\\\n", sid, id);
        fflush(stdout);
      } else {
        json_respond_error(id, "getState failed");
      }

    } else if (strcmp(method, "setState") == 0) {
      char* sidp = strstr(line, "\\\\"stateId\\\\":");
      int sid = sidp ? atoi(sidp + 10) : -1;
      if (h.SetFMUState && sid >= 0 && sid < 64 && h.savedStates[sid]) {
        h.SetFMUState(h.inst, h.savedStates[sid]);
        json_respond_ok(id);
      } else {
        json_respond_error(id, "setState failed");
      }

    } else if (strcmp(method, "freeState") == 0) {
      char* sidp = strstr(line, "\\\\"stateId\\\\":");
      int sid = sidp ? atoi(sidp + 10) : -1;
      if (h.FreeFMUState && sid >= 0 && sid < 64 && h.savedStates[sid]) {
        h.FreeFMUState(h.inst, &h.savedStates[sid]);
        h.savedStates[sid] = NULL;
        json_respond_ok(id);
      } else {
        json_respond_error(id, "freeState failed");
      }

    } else if (strcmp(method, "terminate") == 0) {
      if (h.inst && h.Terminate) h.Terminate(h.inst);
      if (h.inst && h.FreeInstance) h.FreeInstance(h.inst);
      if (h.lib) DLCLOSE(h.lib);
      json_respond_ok(id);
      break;

    } else {
      json_respond_error(id, "unknown method");
    }
  }

  return 0;
}
`;
}
