/* eslint-disable */
/**
 * generate-highlights.ts — Auto-generates tree-sitter query files from a language config.
 *
 * Produces:
 *   - highlights.scm (syntax highlighting)
 *   - indents.scm (auto-indentation)
 *   - folds.scm (code folding)
 *
 * All data is inferred from the language config's rule structure, def() annotations,
 * ref() annotations, and string literals — no manual annotation needed.
 */

import * as fs from "fs";
import * as path from "path";
import { createSelfProxy } from "./index.js";

// ---------------------------------------------------------------------------
// Rule AST Walking Utilities
// ---------------------------------------------------------------------------

/** Recursively collect all string literals from a rule AST. */
function collectStrings(node: any, acc: Set<string> = new Set()): Set<string> {
  if (typeof node === "string") {
    acc.add(node);
    return acc;
  }
  if (!node || typeof node !== "object") return acc;

  switch (node.type) {
    case "seq":
    case "choice":
      for (const a of node.args) collectStrings(a, acc);
      break;
    case "opt":
    case "rep":
    case "rep1":
    case "token":
    case "token_immediate":
      collectStrings(node.arg, acc);
      break;
    case "field":
      collectStrings(node.arg, acc);
      break;
    case "prec":
    case "prec_left":
    case "prec_right":
    case "prec_dynamic":
      collectStrings(node.arg, acc);
      break;
    case "def":
      collectStrings(node.rule, acc);
      break;
    case "ref":
      collectStrings(node.rule, acc);
      break;
    case "alias":
      collectStrings(node.arg, acc);
      break;
  }
  return acc;
}

/** Check if a rule AST contains braces (indicates a block body). */
function hasBraceBody(node: any): boolean {
  const strings = collectStrings(node);
  return strings.has("{") && strings.has("}");
}

/** Extract def() kind from a rule AST. */
function extractDefKind(node: any): string | null {
  if (!node || node.type !== "def") return null;
  const options = node.options;
  if (!options || typeof options.symbol !== "function") return null;

  try {
    const self = createSelfProxy();
    const config = options.symbol(self);
    return config.kind ?? null;
  } catch {
    return null;
  }
}

/** Check if a rule AST contains a ref() node. */
function hasRef(node: any): boolean {
  if (!node || typeof node !== "object") return false;
  if (node.type === "ref") return true;
  if (node.type === "seq" || node.type === "choice") return node.args.some(hasRef);
  if (
    [
      "opt",
      "rep",
      "rep1",
      "token",
      "token_immediate",
      "field",
      "prec",
      "prec_left",
      "prec_right",
      "prec_dynamic",
    ].includes(node.type)
  )
    return hasRef(node.arg);
  if (node.type === "def") return hasRef(node.rule);
  return false;
}

// ---------------------------------------------------------------------------
// Categorization — Classify string literals
// ---------------------------------------------------------------------------

const BRACKET_CHARS = new Set(["{", "}", "(", ")", "[", "]"]);
const DELIMITER_CHARS = new Set([";", ",", ":"]);
const SINGLE_CHAR_OPERATORS = new Set(["+", "-", "*", "/", "<", ">", "=", "!", "&", "|", "^", "~", "?", "."]);

function isKeyword(s: string): boolean {
  return /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(s) && s.length > 1;
}

function isOperator(s: string): boolean {
  if (s.length === 0) return false;
  // Multi-char operators like !=, ==, >=, **, .., etc.
  if (/^[+\-*/<>=!&|^~?.]+$/.test(s) && s.length <= 4) return true;
  // Named operators
  if (["and", "or", "xor", "not", "implies"].includes(s)) return true;
  return false;
}

function isBracket(s: string): boolean {
  return BRACKET_CHARS.has(s);
}

function isDelimiter(s: string): boolean {
  return DELIMITER_CHARS.has(s);
}

// ---------------------------------------------------------------------------
// highlights.scm Generator
// ---------------------------------------------------------------------------

export function generateHighlights(langConfig: any, $: Record<string, any>, langDir?: string): string {
  const lines: string[] = [];
  lines.push(`; highlights.scm — Auto-generated by @modelscript/polyglot`);
  lines.push(`; Language: ${langConfig.name}`);
  lines.push(`; Do not edit manually — regenerate with: npm run generate`);
  lines.push(``);

  // ----- Collect data from all rules -----

  const allStrings = new Set<string>();
  const defKinds = new Map<string, string>(); // ruleName → kind
  const braceRules: string[] = []; // rules with { ... } body
  const refRules: string[] = []; // rules containing ref()

  for (const [name, fn] of Object.entries<any>(langConfig.rules)) {
    const ast = fn($);
    collectStrings(ast, allStrings);

    const kind = extractDefKind(ast);
    if (kind) defKinds.set(name, kind);

    if (!name.startsWith("_") && hasBraceBody(ast)) {
      braceRules.push(name);
    }

    if (hasRef(ast)) {
      refRules.push(name);
    }
  }

  // ----- Classify string literals -----

  const keywords = [...allStrings].filter((s) => isKeyword(s) && !isOperator(s)).sort();

  const operators = [...allStrings].filter((s) => isOperator(s) && !isKeyword(s)).sort();

  const brackets = [...allStrings].filter(isBracket).sort();
  const delimiters = [...allStrings].filter(isDelimiter).sort();

  // ----- Load valid anonymous node names from node-types.json if available -----
  let validAnonymousNodes: Set<string> | null = null;
  if (langDir) {
    const nodeTypesPath = path.join(langDir, "src", "node-types.json");
    if (fs.existsSync(nodeTypesPath)) {
      try {
        const nodeTypes: any[] = JSON.parse(fs.readFileSync(nodeTypesPath, "utf-8"));
        validAnonymousNodes = new Set<string>();
        // Collect all anonymous node type names used in fields and children
        for (const nt of nodeTypes) {
          if (!nt.named) {
            validAnonymousNodes.add(nt.type);
          }
          // Also check types inside fields
          if (nt.fields) {
            for (const f of Object.values<any>(nt.fields)) {
              for (const t of f.types || []) {
                if (!t.named) validAnonymousNodes.add(t.type);
              }
            }
          }
          // Check children
          if (nt.children) {
            for (const t of nt.children.types || []) {
              if (!t.named) validAnonymousNodes.add(t.type);
            }
          }
        }
        console.log(
          `[generate-highlights] Loaded ${validAnonymousNodes.size} valid anonymous node names from node-types.json`,
        );
      } catch (e) {
        console.warn(`[generate-highlights] Failed to parse node-types.json: ${e}`);
      }
    }
  }

  // Also collect named node types for pattern validation
  let validNamedNodes: Set<string> | null = null;
  if (langDir) {
    const nodeTypesPath = path.join(langDir, "src", "node-types.json");
    if (fs.existsSync(nodeTypesPath)) {
      try {
        const nodeTypes: any[] = JSON.parse(fs.readFileSync(nodeTypesPath, "utf-8"));
        validNamedNodes = new Set<string>();
        for (const nt of nodeTypes) {
          if (nt.named) validNamedNodes.add(nt.type);
        }
      } catch {
        /* ignore */
      }
    }
  }

  // Filter out single-letter strings that are likely not keywords
  // (e.g., "e", "E", "b", "f", "n" are numeric format chars, not keywords)
  let realKeywords = keywords.filter((k) => k.length > 1);
  let realOperators = [...operators];
  let realBrackets = [...brackets];
  let realDelimiters = [...delimiters];

  // Filter strings against valid anonymous nodes if available
  if (validAnonymousNodes) {
    const filterValid = (arr: string[]) => arr.filter((s) => validAnonymousNodes!.has(s));
    realKeywords = filterValid(realKeywords);
    realOperators = filterValid(realOperators);
    realBrackets = filterValid(realBrackets);
    realDelimiters = filterValid(realDelimiters);
  }

  // ----- Emit: Keywords -----
  lines.push(`; ─── Keywords ───────────────────────────────────────────────────────`);
  lines.push(`[`);
  // Wrap in chunks of 6 per line for readability
  for (let i = 0; i < realKeywords.length; i += 6) {
    const chunk = realKeywords.slice(i, i + 6);
    lines.push(`  ${chunk.map((k) => `"${k}"`).join(" ")}`);
  }
  lines.push(`] @keyword`);
  lines.push(``);

  // ----- Emit: Definition names -----
  let definitionRules = [...defKinds.entries()].filter(([_, k]) => k === "Definition");
  if (validNamedNodes) definitionRules = definitionRules.filter(([r]) => validNamedNodes!.has(r));
  if (definitionRules.length > 0) {
    lines.push(`; ─── Definition names ──────────────────────────────────────────────`);
    for (const [ruleName] of definitionRules) {
      lines.push(`(${ruleName} (Name) @type.definition)`);
    }
    lines.push(``);
  }

  // ----- Emit: Enumeration names -----
  let enumRules = [...defKinds.entries()].filter(([_, k]) => k === "Enumeration");
  if (validNamedNodes) enumRules = enumRules.filter(([r]) => validNamedNodes!.has(r));
  if (enumRules.length > 0) {
    lines.push(`; ─── Enumeration names ─────────────────────────────────────────────`);
    for (const [ruleName] of enumRules) {
      lines.push(`(${ruleName} (Name) @type.enum)`);
    }
    lines.push(``);
  }

  // ----- Emit: Enumeration value names -----
  let enumValueRules = [...defKinds.entries()].filter(([_, k]) => k === "EnumerationValue");
  if (validNamedNodes) enumValueRules = enumValueRules.filter(([r]) => validNamedNodes!.has(r));
  if (enumValueRules.length > 0) {
    lines.push(`; ─── Enumeration values ────────────────────────────────────────────`);
    for (const [ruleName] of enumValueRules) {
      lines.push(`(${ruleName} (Name) @constant)`);
    }
    lines.push(``);
  }

  // ----- Emit: Usage names (ref() sites) -----
  const usageRefRules = refRules.filter((r) => !r.startsWith("_"));
  const validRefRules = validNamedNodes ? usageRefRules.filter((r) => validNamedNodes!.has(r)) : usageRefRules;
  if (validRefRules.length > 0) {
    lines.push(`; ─── Type references ───────────────────────────────────────────────`);
    for (const ruleName of validRefRules) {
      lines.push(`(${ruleName} (Name) @variable)`);
    }
    lines.push(``);
  }

  // ----- Emit: Package/Module names -----
  let packageRules = [...defKinds.entries()].filter(([_, k]) => k === "Package");
  if (validNamedNodes) packageRules = packageRules.filter(([r]) => validNamedNodes!.has(r));
  if (packageRules.length > 0) {
    lines.push(`; ─── Package names ────────────────────────────────────────────────`);
    for (const [ruleName] of packageRules) {
      lines.push(`(${ruleName} (Name) @module)`);
    }
    lines.push(``);
  }

  // ----- Emit: Import/Alias names -----
  let importRules = [...defKinds.entries()].filter(([_, k]) => k === "Import");
  if (validNamedNodes) importRules = importRules.filter(([r]) => validNamedNodes!.has(r));
  if (importRules.length > 0) {
    lines.push(`; ─── Import paths ─────────────────────────────────────────────────`);
    for (const [ruleName] of importRules) {
      lines.push(`(${ruleName} (QualifiedName) @string.special)`);
    }
    lines.push(``);
  }

  let aliasRules = [...defKinds.entries()].filter(([_, k]) => k === "Alias");
  if (validNamedNodes) aliasRules = aliasRules.filter(([r]) => validNamedNodes!.has(r));
  if (aliasRules.length > 0) {
    lines.push(`; ─── Alias names ──────────────────────────────────────────────────`);
    for (const [ruleName] of aliasRules) {
      lines.push(`(${ruleName} (Name) @label)`);
    }
    lines.push(``);
  }

  // ----- Emit: Type references (QualifiedName used as type specifiers) -----
  const hardcodedTypeRefs = [
    "OwnedFeatureTyping",
    "ConjugatedPortTyping",
    "OwnedReferenceSubsetting",
    "OwnedSubsetting",
    "OwnedRedefinition",
    "Subclassification",
  ];
  let validHardcodedTypeRefs = validNamedNodes
    ? hardcodedTypeRefs.filter((r) => validNamedNodes!.has(r))
    : hardcodedTypeRefs;
  if (validHardcodedTypeRefs.length > 0) {
    lines.push(`; ─── Type references ──────────────────────────────────────────────`);
    for (const r of validHardcodedTypeRefs) {
      lines.push(`(${r} (QualifiedName) @type)`);
    }
    lines.push(``);
  }

  // ----- Emit: Operators -----
  if (realOperators.length > 0) {
    lines.push(`; ─── Operators ────────────────────────────────────────────────────`);
    lines.push(`[`);
    for (let i = 0; i < realOperators.length; i += 6) {
      const chunk = realOperators.slice(i, i + 6);
      lines.push(`  ${chunk.map((o) => `"${escapeScm(o)}"`).join(" ")}`);
    }
    lines.push(`] @operator`);
    lines.push(``);
  }

  // ----- Emit: Brackets -----
  if (realBrackets.length > 0) {
    lines.push(`; ─── Brackets ─────────────────────────────────────────────────────`);
    lines.push(`[${realBrackets.map((b) => `"${escapeScm(b)}"`).join(" ")}] @punctuation.bracket`);
    lines.push(``);
  }

  // ----- Emit: Delimiters -----
  if (realDelimiters.length > 0) {
    lines.push(`; ─── Delimiters ───────────────────────────────────────────────────`);
    lines.push(`[${realDelimiters.map((d) => `"${escapeScm(d)}"`).join(" ")}] @punctuation.delimiter`);
    lines.push(``);
  }

  // ----- Emit: Comments -----
  lines.push(`; ─── Comments ─────────────────────────────────────────────────────`);
  const commentRules = Object.keys(langConfig.rules).filter((r) => /comment/i.test(r));
  for (const r of commentRules) {
    lines.push(`(${r}) @comment`);
  }
  lines.push(``);

  // ----- Emit: Literals -----
  lines.push(`; ─── Literals ─────────────────────────────────────────────────────`);
  const numberRules = Object.keys(langConfig.rules).filter((r) =>
    /^(Number_VALUE|INTEGER_VALUE|DECIMAL_VALUE|REAL_VALUE|HEX_VALUE)$/i.test(r),
  );
  const stringRules = Object.keys(langConfig.rules).filter((r) => /^(STRING_VALUE|REGULAR_EXPRESSION)$/i.test(r));

  for (const r of numberRules) {
    lines.push(`(${r}) @number`);
  }
  for (const r of stringRules) {
    lines.push(`(${r}) @string`);
  }

  // Also match "true", "false", "null" as builtins
  lines.push(``);
  lines.push(`; ─── Boolean/null literals ─────────────────────────────────────────`);
  if (allStrings.has("true")) lines.push(`"true" @constant.builtin`);
  if (allStrings.has("false")) lines.push(`"false" @constant.builtin`);
  if (allStrings.has("null")) lines.push(`"null" @constant.builtin`);
  lines.push(``);

  // ----- Emit: Name node as identifier fallback -----
  lines.push(`; ─── Identifier fallback ──────────────────────────────────────────`);
  lines.push(`(Name) @variable`);
  lines.push(``);

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// indents.scm Generator
// ---------------------------------------------------------------------------

export function generateIndents(langConfig: any, $: Record<string, any>): string {
  const lines: string[] = [];
  lines.push(`; indents.scm — Auto-generated by @modelscript/polyglot`);
  lines.push(`; Language: ${langConfig.name}`);
  lines.push(``);

  // Find all named rules that are block-containing:
  // 1. Named rules with direct brace bodies
  // 2. Rules with def() annotations that typically have bodies (Definition, Package, etc.)
  const indentRules: string[] = [];
  const seen = new Set<string>();

  for (const [name, fn] of Object.entries<any>(langConfig.rules)) {
    if (name.startsWith("_")) continue;
    const ast = fn($);

    // Direct brace check
    if (hasBraceBody(ast)) {
      if (!seen.has(name)) {
        indentRules.push(name);
        seen.add(name);
      }
      continue;
    }

    // Def-kind heuristic: Definitions, Packages, and Enumerations have bodies
    const kind = extractDefKind(ast);
    if (kind && ["Definition", "Package", "Enumeration"].includes(kind)) {
      if (!seen.has(name)) {
        indentRules.push(name);
        seen.add(name);
      }
    }
  }

  if (indentRules.length > 0) {
    lines.push(`; ─── Indent on block open ─────────────────────────────────────────`);
    lines.push(`[`);
    for (const rule of indentRules) {
      lines.push(`  (${rule})`);
    }
    lines.push(`] @indent.begin`);
    lines.push(``);
  }

  lines.push(`; ─── Dedent on close ──────────────────────────────────────────────`);
  lines.push(`"}" @indent.end`);
  lines.push(`"]" @indent.end`);
  lines.push(`")" @indent.end`);
  lines.push(``);

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// folds.scm Generator
// ---------------------------------------------------------------------------

export function generateFolds(langConfig: any, $: Record<string, any>): string {
  const lines: string[] = [];
  lines.push(`; folds.scm — Auto-generated by @modelscript/polyglot`);
  lines.push(`; Language: ${langConfig.name}`);
  lines.push(``);

  // Same logic as indents: rules with bodies (direct braces or def() kind)
  const foldRules: string[] = [];
  const seen = new Set<string>();

  for (const [name, fn] of Object.entries<any>(langConfig.rules)) {
    if (name.startsWith("_")) continue;
    const ast = fn($);

    if (hasBraceBody(ast)) {
      if (!seen.has(name)) {
        foldRules.push(name);
        seen.add(name);
      }
      continue;
    }

    const kind = extractDefKind(ast);
    if (kind && ["Definition", "Package", "Enumeration"].includes(kind)) {
      if (!seen.has(name)) {
        foldRules.push(name);
        seen.add(name);
      }
    }
  }

  if (foldRules.length > 0) {
    lines.push(`; ─── Foldable blocks ──────────────────────────────────────────────`);
    lines.push(`[`);
    for (const rule of foldRules) {
      lines.push(`  (${rule})`);
    }
    lines.push(`] @fold`);
    lines.push(``);
  }

  // Comments are also foldable
  if (langConfig.rules.Comment) {
    lines.push(`(Comment) @fold`);
    lines.push(``);
  }

  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

/** Escape a string for use in .scm queries. */
function escapeScm(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// ---------------------------------------------------------------------------
// Keyword extraction for Monarch fallback
// ---------------------------------------------------------------------------

/**
 * Extracts keyword lists from a language config for use as Monaco Monarch
 * token provider keywords. This replaces the hardcoded keyword arrays.
 */
export function extractKeywords(
  langConfig: any,
  $: Record<string, any>,
): {
  keywords: string[];
  typeKeywords: string[];
  operators: string[];
} {
  const allStrings = new Set<string>();
  for (const [, fn] of Object.entries<any>(langConfig.rules)) {
    collectStrings(fn($), allStrings);
  }

  const keywords = [...allStrings].filter((s) => isKeyword(s) && !isOperator(s) && s.length > 1).sort();

  // Type keywords: look for common type names
  const typeKeywords = [...allStrings]
    .filter((s) => /^(Real|Integer|Boolean|String|Natural|Positive|Any|Anything|Object|DataType)$/i.test(s))
    .sort();

  const operators = [...allStrings].filter((s) => isOperator(s) && !isKeyword(s)).sort();

  return { keywords, typeKeywords, operators };
}
