import type { QueryDB, SpecializationArgs, SymbolEntry, SymbolId } from "./runtime.js";

/**
 * Base class for all generated pull-up semantic model nodes.
 *
 * Wraps a `SymbolEntry` and delegates to the `QueryDB` for all data access,
 * so pull-up navigation and push-down queries share the same incremental cache.
 *
 * Subclasses are generated by `generate-ast-classes.ts` from `def()` rules
 * that include a `ast` configuration.
 */
export abstract class SemanticNode {
  constructor(
    /** The underlying symbol entry from the index. */
    readonly entry: SymbolEntry,
    /** The query database for lazy, memoized data access. */
    readonly db: QueryDB,
  ) {}

  // =========================================================================
  // Identity
  // =========================================================================

  /** Unique symbol ID (may be negative for virtual/specialized entries). */
  get id(): SymbolId {
    return this.entry.id;
  }

  /** The grammar rule that produced this entry. */
  get ruleName(): string {
    return this.entry.ruleName;
  }

  /** The symbol kind (e.g. "Class", "Component", "Function"). */
  abstract get kind(): string;

  /** Byte range in the source file. */
  get startByte(): number {
    return this.entry.startByte;
  }

  get endByte(): number {
    return this.entry.endByte;
  }

  // =========================================================================
  // Metadata (CST-derived, immutable)
  // =========================================================================

  /**
   * Read a field value extracted from the CST at index time.
   * Returns `null` if the key doesn't exist or has no value.
   */
  field<T = string>(key: string): T | null {
    return (this.entry.metadata[key] as T) ?? null;
  }

  /**
   * Read an attribute value extracted from the CST at index time.
   * Returns `null` if the key doesn't exist or has no value.
   */
  attribute<T = string>(key: string): T | null {
    return (this.entry.metadata[key] as T) ?? null;
  }

  // =========================================================================
  // Navigation
  // =========================================================================

  /** Parent symbol entry, or null for top-level. */
  get parentEntry(): SymbolEntry | null {
    if (this.entry.parentId === null) return null;
    return this.db.symbol(this.entry.parentId) ?? null;
  }

  /** All direct child symbol entries. */
  get childEntries(): SymbolEntry[] {
    return this.db.childrenOf(this.id);
  }

  /**
   * Build the fully-qualified composite name by walking the parent chain.
   * E.g. "Modelica.Electrical.Analog.Basic.Resistor"
   */
  get compositeName(): string {
    const parts: string[] = [this.entry.name];
    let current = this.parentEntry;
    while (current) {
      parts.unshift(current.name);
      current = current.parentId !== null ? (this.db.symbol(current.parentId) ?? null) : null;
    }
    return parts.join(".");
  }

  // =========================================================================
  // Query Access
  // =========================================================================

  /**
   * Execute a named query on this node.
   * Results are memoized by the query engine.
   */
  query<T>(queryName: string): T {
    return this.db.query<T>(queryName, this.id);
  }

  // =========================================================================
  // Specialization (Clone)
  // =========================================================================

  /**
   * Create a specialized clone of this node with the given args.
   * The virtual entry shares the same query hooks but has distinct
   * specialization args (e.g., modifications, type parameters).
   *
   * @returns The SymbolId of the virtual entry.
   */
  specialize<T>(args: SpecializationArgs<T>): SymbolId {
    return this.db.specialize(this.id, args);
  }

  /** Get the specialization args if this is a specialized (virtual) entry. */
  get specializationArgs(): SpecializationArgs | null {
    return this.db.argsOf(this.id);
  }

  /** Get the base symbol ID if this is a specialized entry. */
  get baseId(): SymbolId | null {
    return this.db.baseOf(this.id);
  }

  // =========================================================================
  // Visitor
  // =========================================================================

  /**
   * Accept a visitor. Generated subclasses override this to dispatch
   * to the correct visit method.
   */
  abstract accept<R, A>(visitor: SemanticVisitor<R, A>, arg?: A): R;

  // =========================================================================
  // Serialization
  // =========================================================================

  /**
   * Serialize this node to a plain JSON object.
   * Includes kind, name, metadata, and children.
   */
  toJSON(): Record<string, unknown> {
    return {
      "@type": this.kind,
      id: this.id,
      name: this.entry.name,
      compositeName: this.compositeName,
      metadata: { ...this.entry.metadata },
    };
  }

  /**
   * Content hash for structural comparison.
   * Combines kind + name + metadata + specialization args.
   */
  get hash(): string {
    const parts = [this.kind, this.entry.name, JSON.stringify(this.entry.metadata)];
    const args = this.specializationArgs;
    if (args) parts.push(args.hash);
    return parts.join("|");
  }
}

// ---------------------------------------------------------------------------
// Visitor interface
// ---------------------------------------------------------------------------

/**
 * Base visitor interface for the generated semantic model.
 * Generated subclasses add specific visit methods.
 * This is the minimal contract — language-specific generators extend it.
 */
export interface SemanticVisitor<R, A = void> {
  /** Fallback for unhandled node types. */
  visitNode(node: SemanticNode, arg?: A): R;
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * A factory function type that wraps a SymbolEntry into its typed SemanticNode.
 * The generated output file provides a concrete implementation that dispatches
 * by `entry.kind`.
 */
export type NodeFactory = (entry: SymbolEntry, db: QueryDB) => SemanticNode;

// ---------------------------------------------------------------------------
// GenericNode
// ---------------------------------------------------------------------------

/**
 * Fallback node type for entries whose `kind` doesn't match any generated class.
 */
export class GenericNode extends SemanticNode {
  get kind(): string {
    return this.entry.kind;
  }

  get name(): string {
    return this.entry.name;
  }

  accept<R, A>(visitor: SemanticVisitor<R, A>, arg?: A): R {
    return visitor.visitNode(this, arg);
  }
}
