// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Virtual document provider for `.fmu` files.
 *
 * Renders FMU archives as readonly Modelica block definitions by extracting
 * the `modelDescription.xml` from the ZIP and converting scalar variables
 * into Modelica-style input/output/parameter declarations.
 *
 * Uses a `TextDocumentContentProvider` so the file opens in a regular text
 * editor with full Modelica syntax highlighting.  A `CustomReadonlyEditorProvider`
 * intercepts `.fmu` file clicks and redirects to the virtual document.
 */

import { inflateRaw } from "pako";
import * as vscode from "vscode";

/** URI scheme for virtual FMU documents. */
export const FMU_VIEW_SCHEME = "fmu-view";

/** Parsed FMU variable from modelDescription.xml. */
interface FmuVariable {
  name: string;
  causality: string;
  variability: string;
  type: string;
  description: string;
  start?: string;
  unit?: string;
}

/** Parse modelDescription.xml into structured data. */
function parseModelDescription(xml: string): {
  modelName: string;
  description: string;
  guid: string;
  fmiVersion: string;
  generationTool: string;
  variables: FmuVariable[];
} {
  const attr = (s: string, name: string): string => s.match(new RegExp(`\\b${name}\\s*=\\s*"([^"]*)"`))?.[1] ?? "";

  const headerMatch = xml.match(/<fmiModelDescription([^>]*)>/);
  const header = headerMatch?.[1] ?? "";
  const modelName = attr(header, "modelName") || "FMU";
  const description = attr(header, "description");
  const guid = attr(header, "guid");
  const fmiVersion = attr(header, "fmiVersion");
  const generationTool = attr(header, "generationTool");

  const variables: FmuVariable[] = [];
  const scalarRegex =
    /<ScalarVariable\b([^>]*)\/?>([\s\S]*?)(?:<\/ScalarVariable>|(?=<ScalarVariable|<\/ModelVariables))/g;
  let match: RegExpExecArray | null;

  while ((match = scalarRegex.exec(xml)) !== null) {
    const headerAttrs = match[1] ?? "";
    const body = match[0] ?? "";

    const name = attr(headerAttrs, "name");
    if (!name) continue;

    const causality = attr(headerAttrs, "causality") || "local";
    const variability = attr(headerAttrs, "variability") || "continuous";
    const varDesc = attr(headerAttrs, "description");

    const typeMatch = body.match(/<(Real|Integer|Boolean|String)\b([^>]*)/);
    const type = typeMatch?.[1] ?? "Real";
    const typeAttrs = typeMatch?.[2] ?? "";
    const start = attr(typeAttrs, "start") || undefined;
    const unit = attr(typeAttrs, "unit") || undefined;

    variables.push({ name, causality, variability, type, description: varDesc, start, unit });
  }

  return { modelName, description, guid, fmiVersion, generationTool, variables };
}

/** Generate a Modelica block definition from FMU metadata. */
function generateModelicaBlock(fmu: ReturnType<typeof parseModelDescription>): string {
  const lines: string[] = [];

  lines.push("// ── FMU 2.0 Model Description ──────────────────────────────────────");
  lines.push("// This is a readonly view of the FMU archive contents.");
  lines.push(`// GUID: ${fmu.guid}`);
  if (fmu.generationTool) lines.push(`// Generated by: ${fmu.generationTool}`);
  lines.push("");

  if (fmu.description) {
    lines.push(`block ${fmu.modelName} "${fmu.description}"`);
  } else {
    lines.push(`block ${fmu.modelName}`);
  }

  const inputs = fmu.variables.filter((v) => v.causality === "input");
  const outputs = fmu.variables.filter((v) => v.causality === "output");
  const params = fmu.variables.filter((v) => v.causality === "parameter" || v.causality === "calculatedParameter");
  const locals = fmu.variables.filter((v) => v.causality === "local" || v.causality === "independent");

  for (const v of params) {
    const startStr = v.start !== undefined ? ` = ${v.start}` : "";
    const unitStr = v.unit ? ` /* ${v.unit} */` : "";
    const descStr = v.description ? ` "${v.description}"` : "";
    lines.push(`  parameter ${v.type} ${v.name}${startStr}${descStr};${unitStr}`);
  }

  if (inputs.length > 0 && params.length > 0) lines.push("");
  for (const v of inputs) {
    const startStr = v.start !== undefined ? `(start = ${v.start})` : "";
    const descStr = v.description ? ` "${v.description}"` : "";
    lines.push(`  input ${v.type} ${v.name}${startStr}${descStr};`);
  }

  if (outputs.length > 0 && (inputs.length > 0 || params.length > 0)) lines.push("");
  for (const v of outputs) {
    const startStr = v.start !== undefined ? `(start = ${v.start})` : "";
    const descStr = v.description ? ` "${v.description}"` : "";
    lines.push(`  output ${v.type} ${v.name}${startStr}${descStr};`);
  }

  if (locals.length > 0) {
    lines.push("");
    lines.push("protected");
    for (const v of locals) {
      const startStr = v.start !== undefined ? `(start = ${v.start})` : "";
      const descStr = v.description ? ` "${v.description}"` : "";
      lines.push(`  ${v.type} ${v.name}${startStr}${descStr};`);
    }
  }

  lines.push(`end ${fmu.modelName};`);
  lines.push("");
  return lines.join("\n");
}

// ── Lightweight ZIP reader (browser-safe, uses pako) ──

/**
 * Extract a file from a ZIP archive by name.
 * Supports STORED (method 0) and DEFLATED (method 8) entries.
 */
export function extractFromZip(zipData: Uint8Array, targetName: string): Uint8Array | null {
  // Find End of Central Directory
  let eocdOffset = -1;
  for (let i = zipData.length - 22; i >= 0; i--) {
    if (zipData[i] === 0x50 && zipData[i + 1] === 0x4b && zipData[i + 2] === 0x05 && zipData[i + 3] === 0x06) {
      eocdOffset = i;
      break;
    }
  }
  if (eocdOffset === -1) return null;

  const view = new DataView(zipData.buffer, zipData.byteOffset, zipData.byteLength);
  const cdOffset = view.getUint32(eocdOffset + 16, true);
  const cdSize = view.getUint32(eocdOffset + 12, true);
  const cdEnd = cdOffset + cdSize;

  let pos = cdOffset;
  while (pos < cdEnd) {
    if (view.getUint32(pos, true) !== 0x02014b50) break;
    const compressionMethod = view.getUint16(pos + 10, true);
    const compressedSize = view.getUint32(pos + 20, true);
    const fileNameLength = view.getUint16(pos + 28, true);
    const extraLength = view.getUint16(pos + 30, true);
    const commentLength = view.getUint16(pos + 32, true);
    const localHeaderOffset = view.getUint32(pos + 42, true);
    const fileName = new TextDecoder().decode(zipData.subarray(pos + 46, pos + 46 + fileNameLength));

    if (fileName === targetName) {
      if (view.getUint32(localHeaderOffset, true) !== 0x04034b50) return null;
      const localFileNameLen = view.getUint16(localHeaderOffset + 26, true);
      const localExtraLen = view.getUint16(localHeaderOffset + 28, true);
      const dataStart = localHeaderOffset + 30 + localFileNameLen + localExtraLen;

      if (compressionMethod === 0) {
        return zipData.subarray(dataStart, dataStart + compressedSize);
      } else if (compressionMethod === 8) {
        try {
          return inflateRaw(zipData.subarray(dataStart, dataStart + compressedSize));
        } catch {
          return null;
        }
      }
      return null;
    }
    pos += 46 + fileNameLength + extraLength + commentLength;
  }
  return null;
}

/** Extract modelDescription.xml from FMU bytes and generate Modelica code. */
function fmuBytesToModelica(name: string, fmuBytes: Uint8Array): string {
  try {
    const xmlData = extractFromZip(fmuBytes, "modelDescription.xml");
    if (!xmlData) return `// Error: modelDescription.xml not found in ${name}.fmu\n`;
    const xml = new TextDecoder().decode(xmlData);
    return generateModelicaBlock(parseModelDescription(xml));
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return `// Error reading ${name}.fmu: ${msg}\n`;
  }
}

// ── TextDocumentContentProvider ──

/**
 * Provides virtual readonly text content for FMU files.
 * URIs: `fmu-view:/SineWave` → Modelica block text.
 */
export class FmuContentProvider implements vscode.TextDocumentContentProvider {
  private cache = new Map<string, string>();
  private bytesCache = new Map<string, Uint8Array>();

  /** Register content from raw FMU bytes. */
  registerFmu(name: string, fmuBytes: Uint8Array): void {
    this.cache.set(name, fmuBytesToModelica(name, fmuBytes));
    this.bytesCache.set(name, fmuBytes);
  }

  /** Get pre-registered FMU bytes by name. */
  getFmuBytes(name: string): Uint8Array | undefined {
    return this.bytesCache.get(name);
  }

  provideTextDocumentContent(uri: vscode.Uri): string {
    const name = uri.path.replace(/^\//, "");
    return this.cache.get(name) ?? `// Loading ${name}.fmu...\n`;
  }
}

// ── Custom Editor (redirect to virtual document) ──

/** Minimal custom document for the redirect editor. */
class FmuDocument implements vscode.CustomDocument {
  constructor(
    readonly uri: vscode.Uri,
    readonly name: string,
    readonly fmuBytes: Uint8Array,
  ) {}
  dispose(): void {
    // CustomDocument lifecycle — nothing to clean up
  }
}

/**
 * Custom readonly editor that intercepts `.fmu` file opens and redirects
 * to a `fmu-view:` virtual text document with Modelica syntax highlighting.
 */
export class FmuEditorProvider implements vscode.CustomReadonlyEditorProvider<FmuDocument> {
  static readonly viewType = "modelscript.fmuViewer";

  constructor(private contentProvider: FmuContentProvider) {}

  async openCustomDocument(uri: vscode.Uri): Promise<FmuDocument> {
    const name =
      uri.path
        .split("/")
        .pop()
        ?.replace(/\.fmu$/, "") ?? "FMU";

    // Use pre-registered bytes if available, otherwise read from filesystem
    let fmuBytes = this.contentProvider.getFmuBytes(name);
    if (!fmuBytes) {
      try {
        fmuBytes = await vscode.workspace.fs.readFile(uri);
      } catch (e) {
        console.warn(`[fmu-editor] Failed to read ${uri.toString()}:`, e);
        fmuBytes = new Uint8Array(0);
      }
    }
    return new FmuDocument(uri, name, fmuBytes);
  }

  async resolveCustomEditor(document: FmuDocument, webviewPanel: vscode.WebviewPanel): Promise<void> {
    // Register the content in the virtual document provider
    this.contentProvider.registerFmu(document.name, document.fmuBytes);

    // Open the virtual text document with Modelica syntax highlighting
    const virtualUri = vscode.Uri.parse(`${FMU_VIEW_SCHEME}:/${document.name}`);
    const doc = await vscode.workspace.openTextDocument(virtualUri);
    await vscode.languages.setTextDocumentLanguage(doc, "modelica");
    await vscode.window.showTextDocument(doc, {
      viewColumn: webviewPanel.viewColumn,
      preview: false,
    });

    // Close the webview panel — the text editor has replaced it
    webviewPanel.dispose();
  }
}
