/* eslint-disable */
// =============================================================================
// GENERATED by @modelscript/polyglot — do not edit manually.
// Language: sysml2
// =============================================================================

import type { QueryDB, SpecializationArgs, SymbolEntry } from "@modelscript/polyglot/runtime";
import type { SemanticVisitor } from "@modelscript/polyglot/semantic-node";
import { GenericNode, SemanticNode } from "@modelscript/polyglot/semantic-node";

export class UsageNode extends SemanticNode {
  get kind(): string {
    return "Usage";
  }

  // --- CST Fields ---
  /** Field: ownedRelationship */
  get ownedRelationship(): string | null {
    return this.field("ownedRelationship");
  }
  /** Field: sentItem */
  get sentItem(): string | null {
    return this.field("sentItem");
  }
  /** Field: receiver */
  get receiver(): string | null {
    return this.field("receiver");
  }
  /** Field: assignedValue */
  get assignedValue(): string | null {
    return this.field("assignedValue");
  }
  /** Field: targetFeature */
  get targetFeature(): string | null {
    return this.field("targetFeature");
  }
  /** Field: guard */
  get guard(): string | null {
    return this.field("guard");
  }
  /** Field: effect */
  get effect(): string | null {
    return this.field("effect");
  }

  // --- Metadata ---
  get multiplicityLower(): string | null {
    return this.attribute("multiplicityLower");
  }
  get multiplicityUpper(): string | null {
    return this.attribute("multiplicityUpper");
  }

  // --- Mutable Properties (CST default + runtime override) ---
  #usageKind: string | undefined = undefined;

  get usageKind(): string {
    if (this.#usageKind !== undefined) return this.#usageKind;
    return this.attribute("usageKind") ?? (undefined as unknown as string);
  }

  set usageKind(value: string) {
    this.#usageKind = value;
  }

  #isRef: boolean | undefined = false;

  get isRef(): boolean {
    if (this.#isRef !== undefined) return this.#isRef;
    return (this.attribute("isRef") as unknown as boolean) ?? false;
  }

  set isRef(value: boolean) {
    this.#isRef = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  #isDerived: boolean | undefined = false;

  get isDerived(): boolean {
    if (this.#isDerived !== undefined) return this.#isDerived;
    return (this.attribute("isDerived") as unknown as boolean) ?? false;
  }

  set isDerived(value: boolean) {
    this.#isDerived = value;
  }

  #isEnd: boolean | undefined = false;

  get isEnd(): boolean {
    if (this.#isEnd !== undefined) return this.#isEnd;
    return (this.attribute("isEnd") as unknown as boolean) ?? false;
  }

  set isEnd(value: boolean) {
    this.#isEnd = value;
  }

  #isOrdered: boolean | undefined = false;

  get isOrdered(): boolean {
    if (this.#isOrdered !== undefined) return this.#isOrdered;
    return (this.attribute("isOrdered") as unknown as boolean) ?? false;
  }

  set isOrdered(value: boolean) {
    this.#isOrdered = value;
  }

  #isNonunique: boolean | undefined = false;

  get isNonunique(): boolean {
    if (this.#isNonunique !== undefined) return this.#isNonunique;
    return (this.attribute("isNonunique") as unknown as boolean) ?? false;
  }

  set isNonunique(value: boolean) {
    this.#isNonunique = value;
  }

  #isConstant: boolean | undefined = false;

  get isConstant(): boolean {
    if (this.#isConstant !== undefined) return this.#isConstant;
    return (this.attribute("isConstant") as unknown as boolean) ?? false;
  }

  set isConstant(value: boolean) {
    this.#isConstant = value;
  }

  #direction: string | null | undefined = undefined;

  get direction(): string | null {
    if (this.#direction !== undefined) return this.#direction;
    return this.attribute("direction") ?? (undefined as unknown as string | null);
  }

  set direction(value: string | null) {
    this.#direction = value;
  }

  // --- Computed Properties (query-backed) ---
  get resolvedType(): DefinitionNode | null {
    const entry = this.query<SymbolEntry | null>("resolvedType");
    return entry ? (wrapEntry(entry, this.db) as DefinitionNode | null) : (null as unknown as DefinitionNode | null);
  }

  get ownedFeatures(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get redefinedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("redefinedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get subsettedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("subsettedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "label" },
        ],
        attrs: {
          body: { fill: "#fce4ec", stroke: "#f48fb1", strokeWidth: 1.5, rx: 4, ry: 4, strokeDasharray: "6 3" },
          label: { text: "{{name}}", fill: "#1a1a1a", fontSize: 13, textAnchor: "middle", refX: 0.5, refY: 0.5 },
        },
        size: { width: 140, height: 40 },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): UsageNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new UsageNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitUsageNode(this, arg);
  }
}

export class DefinitionNode extends SemanticNode {
  get kind(): string {
    return "Definition";
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #defKind: string | undefined = undefined;

  get defKind(): string {
    if (this.#defKind !== undefined) return this.#defKind;
    return this.attribute("defKind") ?? (undefined as unknown as string);
  }

  set defKind(value: string) {
    this.#defKind = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  // --- Computed Properties (query-backed) ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedUsages(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedUsages");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedDefinitions(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("ownedDefinitions");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedParts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedParts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedAttributes(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedAttributes");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedPorts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedPorts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedActions(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedActions");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConstraints(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConnections(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConnections");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get superclassifiers(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("superclassifiers");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "header" },
          { tagName: "line", selector: "separator" },
          { tagName: "text", selector: "label" },
          { tagName: "image", selector: "icon" },
        ],
        attrs: {
          body: { fill: "#fce4ec", stroke: "#e91e63", strokeWidth: 2, rx: 4, ry: 4 },
          header: { text: "«attribute def»", fill: "#e91e63", fontSize: 10, textAnchor: "middle", refX: 0.5, refY: 14 },
          separator: { x1: 0, y1: 24, x2: "100%", y2: 24, stroke: "#e91e63", strokeWidth: 1 },
          label: {
            text: "{{name}}",
            fill: "#1a1a1a",
            fontSize: 14,
            fontWeight: "bold",
            textAnchor: "middle",
            refX: 0.5,
            refY: 40,
          },
          icon: {},
        },
        size: { width: 180, height: 60 },
        ports: {
          groups: {
            in: { position: "left", attrs: { circle: { r: 5, fill: "#e91e63", stroke: "#fff", strokeWidth: 1.5 } } },
            out: { position: "right", attrs: { circle: { r: 5, fill: "#e91e63", stroke: "#fff", strokeWidth: 1.5 } } },
          },
        },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): DefinitionNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new DefinitionNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitDefinitionNode(this, arg);
  }
}

export class PackageNode extends SemanticNode {
  get kind(): string {
    return "Package";
  }

  // --- CST Fields ---
  /** Field: isStandard */
  get isStandard(): string | null {
    return this.field("isStandard");
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #isLibrary: boolean | undefined = false;

  get isLibrary(): boolean {
    if (this.#isLibrary !== undefined) return this.#isLibrary;
    return (this.attribute("isLibrary") as unknown as boolean) ?? false;
  }

  set isLibrary(value: boolean) {
    this.#isLibrary = value;
  }

  // --- Computed Properties (query-backed) ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedDefinitions(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("ownedDefinitions");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get ownedUsages(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedUsages");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get allRequirements(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("allRequirements");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get satisfiedRequirements(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("satisfiedRequirements");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get unsatisfiedRequirements(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("unsatisfiedRequirements");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get verifiedRequirements(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("verifiedRequirements");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get unverifiedRequirements(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("unverifiedRequirements");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "group",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "rect", selector: "tab" },
          { tagName: "text", selector: "tabLabel" },
          { tagName: "text", selector: "label" },
        ],
        attrs: {
          body: { fill: "#f0f4ff", stroke: "#4a90d9", strokeWidth: 2, rx: 0, ry: 0 },
          tab: { fill: "#4a90d9", width: 80, height: 20, rx: 0, ry: 0, x: 0, y: 0 },
          tabLabel: { text: "package", fill: "#fff", fontSize: 10, x: 40, y: 13, textAnchor: "middle" },
          label: {
            text: "{{name}}",
            fill: "#1a1a1a",
            fontSize: 14,
            fontWeight: "bold",
            refX: 0.5,
            refY: 34,
            textAnchor: "middle",
          },
        },
        size: { width: 300, height: 200 },
      },
    };
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitPackageNode(this, arg);
  }
}

export class AliasNode extends SemanticNode {
  get kind(): string {
    return "Alias";
  }

  // --- CST Fields ---
  /** Field: memberShortName */
  get memberShortName(): string | null {
    return this.field("memberShortName");
  }
  /** Field: memberName */
  get memberName(): string | null {
    return this.field("memberName");
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitAliasNode(this, arg);
  }
}

export class ImportNode extends SemanticNode {
  get kind(): string {
    return "Import";
  }

  // --- CST Fields ---
  /** Field: ownedRelatedElement */
  get ownedRelatedElement(): string | null {
    return this.field("ownedRelatedElement");
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #importKind: string | undefined = undefined;

  get importKind(): string {
    if (this.#importKind !== undefined) return this.#importKind;
    return this.attribute("importKind") ?? (undefined as unknown as string);
  }

  set importKind(value: string) {
    this.#importKind = value;
  }

  #isImportAll: boolean | undefined = false;

  get isImportAll(): boolean {
    if (this.#isImportAll !== undefined) return this.#isImportAll;
    return (this.attribute("isImportAll") as unknown as boolean) ?? false;
  }

  set isImportAll(value: boolean) {
    this.#isImportAll = value;
  }

  #isRecursive: boolean | undefined = false;

  get isRecursive(): boolean {
    if (this.#isRecursive !== undefined) return this.#isRecursive;
    return (this.attribute("isRecursive") as unknown as boolean) ?? false;
  }

  set isRecursive(value: boolean) {
    this.#isRecursive = value;
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitImportNode(this, arg);
  }
}

export class EnumerationNode extends SemanticNode {
  get kind(): string {
    return "Enumeration";
  }

  // --- Mutable Properties (CST default + runtime override) ---
  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  // --- Computed Properties (query-backed) ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedDefinitions(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("ownedDefinitions");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get ownedUsages(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedUsages");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  // --- Query Accessors ---
  get ownedParts(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedParts");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedAttributes(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedAttributes");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedPorts(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedPorts");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedActions(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedActions");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedConstraints(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConstraints");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedConnections(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConnections");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get superclassifiers(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("superclassifiers");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "header" },
          { tagName: "line", selector: "separator" },
          { tagName: "text", selector: "label" },
          { tagName: "image", selector: "icon" },
        ],
        attrs: {
          body: { fill: "#f3e5f5", stroke: "#7b1fa2", strokeWidth: 2, rx: 4, ry: 4 },
          header: { text: "«enum def»", fill: "#7b1fa2", fontSize: 10, textAnchor: "middle", refX: 0.5, refY: 14 },
          separator: { x1: 0, y1: 24, x2: "100%", y2: 24, stroke: "#7b1fa2", strokeWidth: 1 },
          label: {
            text: "{{name}}",
            fill: "#1a1a1a",
            fontSize: 14,
            fontWeight: "bold",
            textAnchor: "middle",
            refX: 0.5,
            refY: 40,
          },
          icon: {},
        },
        size: { width: 180, height: 60 },
        ports: {
          groups: {
            in: { position: "left", attrs: { circle: { r: 5, fill: "#7b1fa2", stroke: "#fff", strokeWidth: 1.5 } } },
            out: { position: "right", attrs: { circle: { r: 5, fill: "#7b1fa2", stroke: "#fff", strokeWidth: 1.5 } } },
          },
        },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): EnumerationNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new EnumerationNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitEnumerationNode(this, arg);
  }
}

export class EnumerationValueNode extends SemanticNode {
  get kind(): string {
    return "EnumerationValue";
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitEnumerationValueNode(this, arg);
  }
}

export class CalculationDefinitionNode extends SemanticNode {
  get kind(): string {
    return "Definition";
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #defKind: string | undefined = undefined;

  get defKind(): string {
    if (this.#defKind !== undefined) return this.#defKind;
    return this.attribute("defKind") ?? (undefined as unknown as string);
  }

  set defKind(value: string) {
    this.#defKind = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  // --- Computed Properties (query-backed) ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedUsages(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedUsages");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedDefinitions(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("ownedDefinitions");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedParts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedParts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedAttributes(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedAttributes");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedPorts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedPorts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedActions(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedActions");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConstraints(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConnections(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConnections");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get superclassifiers(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("superclassifiers");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get parameters(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("parameters");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get returnParameter(): UsageNode | null {
    const entry = this.query<SymbolEntry | null>("returnParameter");
    return entry ? (wrapEntry(entry, this.db) as UsageNode | null) : (null as unknown as UsageNode | null);
  }

  get resultExpression(): unknown {
    return this.query<unknown>("resultExpression");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "header" },
          { tagName: "line", selector: "separator" },
          { tagName: "text", selector: "label" },
          { tagName: "image", selector: "icon" },
        ],
        attrs: {
          body: { fill: "#e0f7fa", stroke: "#00838f", strokeWidth: 2, rx: 4, ry: 4 },
          header: { text: "«calc def»", fill: "#00838f", fontSize: 10, textAnchor: "middle", refX: 0.5, refY: 14 },
          separator: { x1: 0, y1: 24, x2: "100%", y2: 24, stroke: "#00838f", strokeWidth: 1 },
          label: {
            text: "{{name}}",
            fill: "#1a1a1a",
            fontSize: 14,
            fontWeight: "bold",
            textAnchor: "middle",
            refX: 0.5,
            refY: 40,
          },
          icon: {},
        },
        size: { width: 180, height: 60 },
        ports: {
          groups: {
            in: { position: "left", attrs: { circle: { r: 5, fill: "#00838f", stroke: "#fff", strokeWidth: 1.5 } } },
            out: { position: "right", attrs: { circle: { r: 5, fill: "#00838f", stroke: "#fff", strokeWidth: 1.5 } } },
          },
        },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): CalculationDefinitionNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new CalculationDefinitionNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitCalculationDefinitionNode(this, arg);
  }
}

export class CalculationUsageNode extends SemanticNode {
  get kind(): string {
    return "Usage";
  }

  // --- Metadata ---
  get multiplicityLower(): string | null {
    return this.attribute("multiplicityLower");
  }
  get multiplicityUpper(): string | null {
    return this.attribute("multiplicityUpper");
  }

  // --- Mutable Properties (CST default + runtime override) ---
  #usageKind: string | undefined = undefined;

  get usageKind(): string {
    if (this.#usageKind !== undefined) return this.#usageKind;
    return this.attribute("usageKind") ?? (undefined as unknown as string);
  }

  set usageKind(value: string) {
    this.#usageKind = value;
  }

  #isRef: boolean | undefined = false;

  get isRef(): boolean {
    if (this.#isRef !== undefined) return this.#isRef;
    return (this.attribute("isRef") as unknown as boolean) ?? false;
  }

  set isRef(value: boolean) {
    this.#isRef = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  #isDerived: boolean | undefined = false;

  get isDerived(): boolean {
    if (this.#isDerived !== undefined) return this.#isDerived;
    return (this.attribute("isDerived") as unknown as boolean) ?? false;
  }

  set isDerived(value: boolean) {
    this.#isDerived = value;
  }

  #isEnd: boolean | undefined = false;

  get isEnd(): boolean {
    if (this.#isEnd !== undefined) return this.#isEnd;
    return (this.attribute("isEnd") as unknown as boolean) ?? false;
  }

  set isEnd(value: boolean) {
    this.#isEnd = value;
  }

  #isOrdered: boolean | undefined = false;

  get isOrdered(): boolean {
    if (this.#isOrdered !== undefined) return this.#isOrdered;
    return (this.attribute("isOrdered") as unknown as boolean) ?? false;
  }

  set isOrdered(value: boolean) {
    this.#isOrdered = value;
  }

  #isNonunique: boolean | undefined = false;

  get isNonunique(): boolean {
    if (this.#isNonunique !== undefined) return this.#isNonunique;
    return (this.attribute("isNonunique") as unknown as boolean) ?? false;
  }

  set isNonunique(value: boolean) {
    this.#isNonunique = value;
  }

  #isConstant: boolean | undefined = false;

  get isConstant(): boolean {
    if (this.#isConstant !== undefined) return this.#isConstant;
    return (this.attribute("isConstant") as unknown as boolean) ?? false;
  }

  set isConstant(value: boolean) {
    this.#isConstant = value;
  }

  #direction: string | null | undefined = undefined;

  get direction(): string | null {
    if (this.#direction !== undefined) return this.#direction;
    return this.attribute("direction") ?? (undefined as unknown as string | null);
  }

  set direction(value: string | null) {
    this.#direction = value;
  }

  // --- Computed Properties (query-backed) ---
  get resolvedType(): DefinitionNode | null {
    const entry = this.query<SymbolEntry | null>("resolvedType");
    return entry ? (wrapEntry(entry, this.db) as DefinitionNode | null) : (null as unknown as DefinitionNode | null);
  }

  get ownedFeatures(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get redefinedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("redefinedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get subsettedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("subsettedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get parameters(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("parameters");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get returnParameter(): UsageNode | null {
    const entry = this.query<SymbolEntry | null>("returnParameter");
    return entry ? (wrapEntry(entry, this.db) as UsageNode | null) : (null as unknown as UsageNode | null);
  }

  get resultExpression(): unknown {
    return this.query<unknown>("resultExpression");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "label" },
        ],
        attrs: {
          body: { fill: "#e0f7fa", stroke: "#006064", strokeWidth: 1.5, rx: 4, ry: 4, strokeDasharray: "6 3" },
          label: { text: "{{name}}", fill: "#1a1a1a", fontSize: 13, textAnchor: "middle", refX: 0.5, refY: 0.5 },
        },
        size: { width: 140, height: 40 },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): CalculationUsageNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new CalculationUsageNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitCalculationUsageNode(this, arg);
  }
}

export class ConstraintDefinitionNode extends SemanticNode {
  get kind(): string {
    return "Definition";
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #defKind: string | undefined = undefined;

  get defKind(): string {
    if (this.#defKind !== undefined) return this.#defKind;
    return this.attribute("defKind") ?? (undefined as unknown as string);
  }

  set defKind(value: string) {
    this.#defKind = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  // --- Computed Properties (query-backed) ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedUsages(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedUsages");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedDefinitions(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("ownedDefinitions");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedParts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedParts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedAttributes(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedAttributes");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedPorts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedPorts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedActions(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedActions");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConstraints(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConnections(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConnections");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get superclassifiers(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("superclassifiers");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get constraintResult(): boolean | null {
    return this.query<boolean | null>("constraintResult");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "header" },
          { tagName: "line", selector: "separator" },
          { tagName: "text", selector: "label" },
          { tagName: "image", selector: "icon" },
        ],
        attrs: {
          body: { fill: "#ffebee", stroke: "#c62828", strokeWidth: 2, rx: 4, ry: 4 },
          header: {
            text: "«constraint def»",
            fill: "#c62828",
            fontSize: 10,
            textAnchor: "middle",
            refX: 0.5,
            refY: 14,
          },
          separator: { x1: 0, y1: 24, x2: "100%", y2: 24, stroke: "#c62828", strokeWidth: 1 },
          label: {
            text: "{{name}}",
            fill: "#1a1a1a",
            fontSize: 14,
            fontWeight: "bold",
            textAnchor: "middle",
            refX: 0.5,
            refY: 40,
          },
          icon: {},
        },
        size: { width: 180, height: 60 },
        ports: {
          groups: {
            in: { position: "left", attrs: { circle: { r: 5, fill: "#c62828", stroke: "#fff", strokeWidth: 1.5 } } },
            out: { position: "right", attrs: { circle: { r: 5, fill: "#c62828", stroke: "#fff", strokeWidth: 1.5 } } },
          },
        },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): ConstraintDefinitionNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new ConstraintDefinitionNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitConstraintDefinitionNode(this, arg);
  }
}

export class ConstraintUsageNode extends SemanticNode {
  get kind(): string {
    return "Usage";
  }

  // --- CST Fields ---
  /** Field: isNegated */
  get isNegated(): string | null {
    return this.field("isNegated");
  }

  // --- Metadata ---
  get multiplicityLower(): string | null {
    return this.attribute("multiplicityLower");
  }
  get multiplicityUpper(): string | null {
    return this.attribute("multiplicityUpper");
  }

  // --- Mutable Properties (CST default + runtime override) ---
  #usageKind: string | undefined = undefined;

  get usageKind(): string {
    if (this.#usageKind !== undefined) return this.#usageKind;
    return this.attribute("usageKind") ?? (undefined as unknown as string);
  }

  set usageKind(value: string) {
    this.#usageKind = value;
  }

  #isRef: boolean | undefined = false;

  get isRef(): boolean {
    if (this.#isRef !== undefined) return this.#isRef;
    return (this.attribute("isRef") as unknown as boolean) ?? false;
  }

  set isRef(value: boolean) {
    this.#isRef = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  #isDerived: boolean | undefined = false;

  get isDerived(): boolean {
    if (this.#isDerived !== undefined) return this.#isDerived;
    return (this.attribute("isDerived") as unknown as boolean) ?? false;
  }

  set isDerived(value: boolean) {
    this.#isDerived = value;
  }

  #isEnd: boolean | undefined = false;

  get isEnd(): boolean {
    if (this.#isEnd !== undefined) return this.#isEnd;
    return (this.attribute("isEnd") as unknown as boolean) ?? false;
  }

  set isEnd(value: boolean) {
    this.#isEnd = value;
  }

  #isOrdered: boolean | undefined = false;

  get isOrdered(): boolean {
    if (this.#isOrdered !== undefined) return this.#isOrdered;
    return (this.attribute("isOrdered") as unknown as boolean) ?? false;
  }

  set isOrdered(value: boolean) {
    this.#isOrdered = value;
  }

  #isNonunique: boolean | undefined = false;

  get isNonunique(): boolean {
    if (this.#isNonunique !== undefined) return this.#isNonunique;
    return (this.attribute("isNonunique") as unknown as boolean) ?? false;
  }

  set isNonunique(value: boolean) {
    this.#isNonunique = value;
  }

  #isConstant: boolean | undefined = false;

  get isConstant(): boolean {
    if (this.#isConstant !== undefined) return this.#isConstant;
    return (this.attribute("isConstant") as unknown as boolean) ?? false;
  }

  set isConstant(value: boolean) {
    this.#isConstant = value;
  }

  #direction: string | null | undefined = undefined;

  get direction(): string | null {
    if (this.#direction !== undefined) return this.#direction;
    return this.attribute("direction") ?? (undefined as unknown as string | null);
  }

  set direction(value: string | null) {
    this.#direction = value;
  }

  // --- Computed Properties (query-backed) ---
  get resolvedType(): DefinitionNode | null {
    const entry = this.query<SymbolEntry | null>("resolvedType");
    return entry ? (wrapEntry(entry, this.db) as DefinitionNode | null) : (null as unknown as DefinitionNode | null);
  }

  get ownedFeatures(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get redefinedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("redefinedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get subsettedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("subsettedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get constraintResult(): boolean | null {
    return this.query<boolean | null>("constraintResult");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "label" },
        ],
        attrs: {
          body: { fill: "#ffebee", stroke: "#b71c1c", strokeWidth: 1.5, rx: 4, ry: 4, strokeDasharray: "6 3" },
          label: { text: "{{name}}", fill: "#1a1a1a", fontSize: 13, textAnchor: "middle", refX: 0.5, refY: 0.5 },
        },
        size: { width: 140, height: 40 },
      },
    };
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitConstraintUsageNode(this, arg);
  }
}

export class RequirementDefinitionNode extends SemanticNode {
  get kind(): string {
    return "Definition";
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #defKind: string | undefined = undefined;

  get defKind(): string {
    if (this.#defKind !== undefined) return this.#defKind;
    return this.attribute("defKind") ?? (undefined as unknown as string);
  }

  set defKind(value: string) {
    this.#defKind = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  // --- Computed Properties (query-backed) ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedUsages(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedUsages");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedDefinitions(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("ownedDefinitions");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedParts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedParts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedAttributes(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedAttributes");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedPorts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedPorts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedActions(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedActions");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConstraints(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConnections(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConnections");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get superclassifiers(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("superclassifiers");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get subject(): UsageNode | null {
    const entry = this.query<SymbolEntry | null>("subject");
    return entry ? (wrapEntry(entry, this.db) as UsageNode | null) : (null as unknown as UsageNode | null);
  }

  get assumeConstraints(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("assumeConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get requireConstraints(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("requireConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get actors(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("actors");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get stakeholders(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("stakeholders");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get isSatisfied(): boolean {
    return this.query<boolean>("isSatisfied");
  }

  get satisfiedBy(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("satisfiedBy");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get isVerified(): boolean {
    return this.query<boolean>("isVerified");
  }

  get verifiedBy(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("verifiedBy");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get verificationStatus(): string {
    return this.query<string>("verificationStatus");
  }

  get constraintsMet(): boolean | null {
    return this.query<boolean | null>("constraintsMet");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "header" },
          { tagName: "line", selector: "separator" },
          { tagName: "text", selector: "label" },
          { tagName: "image", selector: "icon" },
        ],
        attrs: {
          body: { fill: "#f3e5f5", stroke: "#9c27b0", strokeWidth: 2, rx: 4, ry: 4 },
          header: {
            text: "«requirement def»",
            fill: "#9c27b0",
            fontSize: 10,
            textAnchor: "middle",
            refX: 0.5,
            refY: 14,
          },
          separator: { x1: 0, y1: 24, x2: "100%", y2: 24, stroke: "#9c27b0", strokeWidth: 1 },
          label: {
            text: "{{name}}",
            fill: "#1a1a1a",
            fontSize: 14,
            fontWeight: "bold",
            textAnchor: "middle",
            refX: 0.5,
            refY: 40,
          },
          icon: {},
        },
        size: { width: 200, height: 70 },
        ports: {
          groups: {
            in: { position: "left", attrs: { circle: { r: 5, fill: "#9c27b0", stroke: "#fff", strokeWidth: 1.5 } } },
            out: { position: "right", attrs: { circle: { r: 5, fill: "#9c27b0", stroke: "#fff", strokeWidth: 1.5 } } },
          },
        },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): RequirementDefinitionNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new RequirementDefinitionNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitRequirementDefinitionNode(this, arg);
  }
}

export class RequirementUsageNode extends SemanticNode {
  get kind(): string {
    return "Usage";
  }

  // --- Metadata ---
  get multiplicityLower(): string | null {
    return this.attribute("multiplicityLower");
  }
  get multiplicityUpper(): string | null {
    return this.attribute("multiplicityUpper");
  }

  // --- Mutable Properties (CST default + runtime override) ---
  #usageKind: string | undefined = undefined;

  get usageKind(): string {
    if (this.#usageKind !== undefined) return this.#usageKind;
    return this.attribute("usageKind") ?? (undefined as unknown as string);
  }

  set usageKind(value: string) {
    this.#usageKind = value;
  }

  #isRef: boolean | undefined = false;

  get isRef(): boolean {
    if (this.#isRef !== undefined) return this.#isRef;
    return (this.attribute("isRef") as unknown as boolean) ?? false;
  }

  set isRef(value: boolean) {
    this.#isRef = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  #isDerived: boolean | undefined = false;

  get isDerived(): boolean {
    if (this.#isDerived !== undefined) return this.#isDerived;
    return (this.attribute("isDerived") as unknown as boolean) ?? false;
  }

  set isDerived(value: boolean) {
    this.#isDerived = value;
  }

  #isEnd: boolean | undefined = false;

  get isEnd(): boolean {
    if (this.#isEnd !== undefined) return this.#isEnd;
    return (this.attribute("isEnd") as unknown as boolean) ?? false;
  }

  set isEnd(value: boolean) {
    this.#isEnd = value;
  }

  #isOrdered: boolean | undefined = false;

  get isOrdered(): boolean {
    if (this.#isOrdered !== undefined) return this.#isOrdered;
    return (this.attribute("isOrdered") as unknown as boolean) ?? false;
  }

  set isOrdered(value: boolean) {
    this.#isOrdered = value;
  }

  #isNonunique: boolean | undefined = false;

  get isNonunique(): boolean {
    if (this.#isNonunique !== undefined) return this.#isNonunique;
    return (this.attribute("isNonunique") as unknown as boolean) ?? false;
  }

  set isNonunique(value: boolean) {
    this.#isNonunique = value;
  }

  #isConstant: boolean | undefined = false;

  get isConstant(): boolean {
    if (this.#isConstant !== undefined) return this.#isConstant;
    return (this.attribute("isConstant") as unknown as boolean) ?? false;
  }

  set isConstant(value: boolean) {
    this.#isConstant = value;
  }

  #direction: string | null | undefined = undefined;

  get direction(): string | null {
    if (this.#direction !== undefined) return this.#direction;
    return this.attribute("direction") ?? (undefined as unknown as string | null);
  }

  set direction(value: string | null) {
    this.#direction = value;
  }

  // --- Computed Properties (query-backed) ---
  get resolvedType(): DefinitionNode | null {
    const entry = this.query<SymbolEntry | null>("resolvedType");
    return entry ? (wrapEntry(entry, this.db) as DefinitionNode | null) : (null as unknown as DefinitionNode | null);
  }

  get ownedFeatures(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get redefinedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("redefinedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get subsettedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("subsettedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get subject(): UsageNode | null {
    const entry = this.query<SymbolEntry | null>("subject");
    return entry ? (wrapEntry(entry, this.db) as UsageNode | null) : (null as unknown as UsageNode | null);
  }

  get assumeConstraints(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("assumeConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get requireConstraints(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("requireConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get isSatisfied(): boolean {
    return this.query<boolean>("isSatisfied");
  }

  get satisfiedBy(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("satisfiedBy");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get isVerified(): boolean {
    return this.query<boolean>("isVerified");
  }

  get verifiedBy(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("verifiedBy");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get verificationStatus(): string {
    return this.query<string>("verificationStatus");
  }

  get constraintsMet(): boolean | null {
    return this.query<boolean | null>("constraintsMet");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "label" },
        ],
        attrs: {
          body: { fill: "#f3e5f5", stroke: "#4a148c", strokeWidth: 1.5, rx: 4, ry: 4, strokeDasharray: "6 3" },
          label: { text: "{{name}}", fill: "#1a1a1a", fontSize: 13, textAnchor: "middle", refX: 0.5, refY: 0.5 },
        },
        size: { width: 140, height: 40 },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): RequirementUsageNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new RequirementUsageNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitRequirementUsageNode(this, arg);
  }
}

export class SatisfyRequirementNode extends SemanticNode {
  get kind(): string {
    return "Usage";
  }

  // --- CST Fields ---
  /** Field: isNegated */
  get isNegated(): string | null {
    return this.field("isNegated");
  }
  /** Field: satisfyingFeature */
  get satisfyingFeature(): string | null {
    return this.field("satisfyingFeature");
  }

  // --- Metadata ---
  get multiplicityLower(): string | null {
    return this.attribute("multiplicityLower");
  }
  get multiplicityUpper(): string | null {
    return this.attribute("multiplicityUpper");
  }

  // --- Mutable Properties (CST default + runtime override) ---
  #usageKind: string | undefined = undefined;

  get usageKind(): string {
    if (this.#usageKind !== undefined) return this.#usageKind;
    return this.attribute("usageKind") ?? (undefined as unknown as string);
  }

  set usageKind(value: string) {
    this.#usageKind = value;
  }

  #isRef: boolean | undefined = false;

  get isRef(): boolean {
    if (this.#isRef !== undefined) return this.#isRef;
    return (this.attribute("isRef") as unknown as boolean) ?? false;
  }

  set isRef(value: boolean) {
    this.#isRef = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  #isDerived: boolean | undefined = false;

  get isDerived(): boolean {
    if (this.#isDerived !== undefined) return this.#isDerived;
    return (this.attribute("isDerived") as unknown as boolean) ?? false;
  }

  set isDerived(value: boolean) {
    this.#isDerived = value;
  }

  #isEnd: boolean | undefined = false;

  get isEnd(): boolean {
    if (this.#isEnd !== undefined) return this.#isEnd;
    return (this.attribute("isEnd") as unknown as boolean) ?? false;
  }

  set isEnd(value: boolean) {
    this.#isEnd = value;
  }

  #isOrdered: boolean | undefined = false;

  get isOrdered(): boolean {
    if (this.#isOrdered !== undefined) return this.#isOrdered;
    return (this.attribute("isOrdered") as unknown as boolean) ?? false;
  }

  set isOrdered(value: boolean) {
    this.#isOrdered = value;
  }

  #isNonunique: boolean | undefined = false;

  get isNonunique(): boolean {
    if (this.#isNonunique !== undefined) return this.#isNonunique;
    return (this.attribute("isNonunique") as unknown as boolean) ?? false;
  }

  set isNonunique(value: boolean) {
    this.#isNonunique = value;
  }

  #isConstant: boolean | undefined = false;

  get isConstant(): boolean {
    if (this.#isConstant !== undefined) return this.#isConstant;
    return (this.attribute("isConstant") as unknown as boolean) ?? false;
  }

  set isConstant(value: boolean) {
    this.#isConstant = value;
  }

  #direction: string | null | undefined = undefined;

  get direction(): string | null {
    if (this.#direction !== undefined) return this.#direction;
    return this.attribute("direction") ?? (undefined as unknown as string | null);
  }

  set direction(value: string | null) {
    this.#direction = value;
  }

  // --- Computed Properties (query-backed) ---
  get resolvedType(): DefinitionNode | null {
    const entry = this.query<SymbolEntry | null>("resolvedType");
    return entry ? (wrapEntry(entry, this.db) as DefinitionNode | null) : (null as unknown as DefinitionNode | null);
  }

  get ownedFeatures(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get redefinedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("redefinedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get subsettedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("subsettedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get satisfiedRequirement(): SemanticNode | null {
    const entry = this.query<SymbolEntry | null>("satisfiedRequirement");
    return entry ? (wrapEntry(entry, this.db) as SemanticNode | null) : (null as unknown as SemanticNode | null);
  }

  get satisfyingSubject(): UsageNode | null {
    const entry = this.query<SymbolEntry | null>("satisfyingSubject");
    return entry ? (wrapEntry(entry, this.db) as UsageNode | null) : (null as unknown as UsageNode | null);
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "edge",
      edge: {
        shape: "edge",
        attrs: { line: { stroke: "#9c27b0", strokeWidth: 1.5, strokeDasharray: "8 4", targetMarker: "classic" } },
        labels: [
          {
            attrs: {
              text: { text: "«satisfy»", fill: "#666", fontSize: 11 },
              rect: { fill: "#fff", stroke: "none", rx: 3, ry: 3 },
            },
            position: { distance: 0.5, offset: 0 },
          },
        ],
        router: "manhattan",
        connector: "rounded",
      },
    };
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitSatisfyRequirementNode(this, arg);
  }
}

export class VerificationCaseDefinitionNode extends SemanticNode {
  get kind(): string {
    return "Definition";
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #defKind: string | undefined = undefined;

  get defKind(): string {
    if (this.#defKind !== undefined) return this.#defKind;
    return this.attribute("defKind") ?? (undefined as unknown as string);
  }

  set defKind(value: string) {
    this.#defKind = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  // --- Computed Properties (query-backed) ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedUsages(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedUsages");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedDefinitions(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("ownedDefinitions");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedParts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedParts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedAttributes(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedAttributes");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedPorts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedPorts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedActions(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedActions");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConstraints(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConnections(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConnections");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get superclassifiers(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("superclassifiers");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get verifiedRequirements(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("verifiedRequirements");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get objective(): SemanticNode | null {
    const entry = this.query<SymbolEntry | null>("objective");
    return entry ? (wrapEntry(entry, this.db) as SemanticNode | null) : (null as unknown as SemanticNode | null);
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "header" },
          { tagName: "line", selector: "separator" },
          { tagName: "text", selector: "label" },
          { tagName: "image", selector: "icon" },
        ],
        attrs: {
          body: { fill: "#e8eaf6", stroke: "#3f51b5", strokeWidth: 2, rx: 4, ry: 4 },
          header: {
            text: "«verification def»",
            fill: "#3f51b5",
            fontSize: 10,
            textAnchor: "middle",
            refX: 0.5,
            refY: 14,
          },
          separator: { x1: 0, y1: 24, x2: "100%", y2: 24, stroke: "#3f51b5", strokeWidth: 1 },
          label: {
            text: "{{name}}",
            fill: "#1a1a1a",
            fontSize: 14,
            fontWeight: "bold",
            textAnchor: "middle",
            refX: 0.5,
            refY: 40,
          },
          icon: {},
        },
        size: { width: 180, height: 60 },
        ports: {
          groups: {
            in: { position: "left", attrs: { circle: { r: 5, fill: "#3f51b5", stroke: "#fff", strokeWidth: 1.5 } } },
            out: { position: "right", attrs: { circle: { r: 5, fill: "#3f51b5", stroke: "#fff", strokeWidth: 1.5 } } },
          },
        },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): VerificationCaseDefinitionNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new VerificationCaseDefinitionNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitVerificationCaseDefinitionNode(this, arg);
  }
}

export class VerificationCaseUsageNode extends SemanticNode {
  get kind(): string {
    return "Usage";
  }

  // --- Metadata ---
  get multiplicityLower(): string | null {
    return this.attribute("multiplicityLower");
  }
  get multiplicityUpper(): string | null {
    return this.attribute("multiplicityUpper");
  }

  // --- Mutable Properties (CST default + runtime override) ---
  #usageKind: string | undefined = undefined;

  get usageKind(): string {
    if (this.#usageKind !== undefined) return this.#usageKind;
    return this.attribute("usageKind") ?? (undefined as unknown as string);
  }

  set usageKind(value: string) {
    this.#usageKind = value;
  }

  #isRef: boolean | undefined = false;

  get isRef(): boolean {
    if (this.#isRef !== undefined) return this.#isRef;
    return (this.attribute("isRef") as unknown as boolean) ?? false;
  }

  set isRef(value: boolean) {
    this.#isRef = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  #isDerived: boolean | undefined = false;

  get isDerived(): boolean {
    if (this.#isDerived !== undefined) return this.#isDerived;
    return (this.attribute("isDerived") as unknown as boolean) ?? false;
  }

  set isDerived(value: boolean) {
    this.#isDerived = value;
  }

  #isEnd: boolean | undefined = false;

  get isEnd(): boolean {
    if (this.#isEnd !== undefined) return this.#isEnd;
    return (this.attribute("isEnd") as unknown as boolean) ?? false;
  }

  set isEnd(value: boolean) {
    this.#isEnd = value;
  }

  #isOrdered: boolean | undefined = false;

  get isOrdered(): boolean {
    if (this.#isOrdered !== undefined) return this.#isOrdered;
    return (this.attribute("isOrdered") as unknown as boolean) ?? false;
  }

  set isOrdered(value: boolean) {
    this.#isOrdered = value;
  }

  #isNonunique: boolean | undefined = false;

  get isNonunique(): boolean {
    if (this.#isNonunique !== undefined) return this.#isNonunique;
    return (this.attribute("isNonunique") as unknown as boolean) ?? false;
  }

  set isNonunique(value: boolean) {
    this.#isNonunique = value;
  }

  #isConstant: boolean | undefined = false;

  get isConstant(): boolean {
    if (this.#isConstant !== undefined) return this.#isConstant;
    return (this.attribute("isConstant") as unknown as boolean) ?? false;
  }

  set isConstant(value: boolean) {
    this.#isConstant = value;
  }

  #direction: string | null | undefined = undefined;

  get direction(): string | null {
    if (this.#direction !== undefined) return this.#direction;
    return this.attribute("direction") ?? (undefined as unknown as string | null);
  }

  set direction(value: string | null) {
    this.#direction = value;
  }

  // --- Computed Properties (query-backed) ---
  get resolvedType(): DefinitionNode | null {
    const entry = this.query<SymbolEntry | null>("resolvedType");
    return entry ? (wrapEntry(entry, this.db) as DefinitionNode | null) : (null as unknown as DefinitionNode | null);
  }

  get ownedFeatures(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get redefinedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("redefinedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get subsettedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("subsettedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get verifiedRequirements(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("verifiedRequirements");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get objective(): SemanticNode | null {
    const entry = this.query<SymbolEntry | null>("objective");
    return entry ? (wrapEntry(entry, this.db) as SemanticNode | null) : (null as unknown as SemanticNode | null);
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "label" },
        ],
        attrs: {
          body: { fill: "#e8eaf6", stroke: "#1a237e", strokeWidth: 1.5, rx: 4, ry: 4, strokeDasharray: "6 3" },
          label: { text: "{{name}}", fill: "#1a1a1a", fontSize: 13, textAnchor: "middle", refX: 0.5, refY: 0.5 },
        },
        size: { width: 140, height: 40 },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): VerificationCaseUsageNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new VerificationCaseUsageNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitVerificationCaseUsageNode(this, arg);
  }
}

export class StateDefinitionNode extends SemanticNode {
  get kind(): string {
    return "Definition";
  }

  // --- CST Fields ---
  /** Field: isParallel */
  get isParallel(): string | null {
    return this.field("isParallel");
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #defKind: string | undefined = undefined;

  get defKind(): string {
    if (this.#defKind !== undefined) return this.#defKind;
    return this.attribute("defKind") ?? (undefined as unknown as string);
  }

  set defKind(value: string) {
    this.#defKind = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  // --- Computed Properties (query-backed) ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedUsages(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedUsages");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedDefinitions(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("ownedDefinitions");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get ownedParts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedParts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedAttributes(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedAttributes");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedPorts(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedPorts");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedActions(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedActions");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConstraints(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConstraints");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get ownedConnections(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConnections");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get superclassifiers(): DefinitionNode[] {
    const entries = this.query<SymbolEntry[]>("superclassifiers");
    return entries.map((e) => wrapEntry(e, this.db)) as DefinitionNode[];
  }

  get entryAction(): SemanticNode | null {
    const entry = this.query<SymbolEntry | null>("entryAction");
    return entry ? (wrapEntry(entry, this.db) as SemanticNode | null) : (null as unknown as SemanticNode | null);
  }

  get doAction(): SemanticNode | null {
    const entry = this.query<SymbolEntry | null>("doAction");
    return entry ? (wrapEntry(entry, this.db) as SemanticNode | null) : (null as unknown as SemanticNode | null);
  }

  get exitAction(): SemanticNode | null {
    const entry = this.query<SymbolEntry | null>("exitAction");
    return entry ? (wrapEntry(entry, this.db) as SemanticNode | null) : (null as unknown as SemanticNode | null);
  }

  get transitions(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("transitions");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "header" },
          { tagName: "line", selector: "separator" },
          { tagName: "text", selector: "label" },
          { tagName: "image", selector: "icon" },
        ],
        attrs: {
          body: { fill: "#fff8e1", stroke: "#f9a825", strokeWidth: 2, rx: 4, ry: 4 },
          header: { text: "«state def»", fill: "#f9a825", fontSize: 10, textAnchor: "middle", refX: 0.5, refY: 14 },
          separator: { x1: 0, y1: 24, x2: "100%", y2: 24, stroke: "#f9a825", strokeWidth: 1 },
          label: {
            text: "{{name}}",
            fill: "#1a1a1a",
            fontSize: 14,
            fontWeight: "bold",
            textAnchor: "middle",
            refX: 0.5,
            refY: 40,
          },
          icon: {},
        },
        size: { width: 180, height: 60 },
        ports: {
          groups: {
            in: { position: "left", attrs: { circle: { r: 5, fill: "#f9a825", stroke: "#fff", strokeWidth: 1.5 } } },
            out: { position: "right", attrs: { circle: { r: 5, fill: "#f9a825", stroke: "#fff", strokeWidth: 1.5 } } },
          },
        },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): StateDefinitionNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new StateDefinitionNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitStateDefinitionNode(this, arg);
  }
}

export class StateUsageNode extends SemanticNode {
  get kind(): string {
    return "Usage";
  }

  // --- CST Fields ---
  /** Field: isParallel */
  get isParallel(): string | null {
    return this.field("isParallel");
  }

  // --- Metadata ---
  get multiplicityLower(): string | null {
    return this.attribute("multiplicityLower");
  }
  get multiplicityUpper(): string | null {
    return this.attribute("multiplicityUpper");
  }

  // --- Mutable Properties (CST default + runtime override) ---
  #usageKind: string | undefined = undefined;

  get usageKind(): string {
    if (this.#usageKind !== undefined) return this.#usageKind;
    return this.attribute("usageKind") ?? (undefined as unknown as string);
  }

  set usageKind(value: string) {
    this.#usageKind = value;
  }

  #isRef: boolean | undefined = false;

  get isRef(): boolean {
    if (this.#isRef !== undefined) return this.#isRef;
    return (this.attribute("isRef") as unknown as boolean) ?? false;
  }

  set isRef(value: boolean) {
    this.#isRef = value;
  }

  #isAbstract: boolean | undefined = false;

  get isAbstract(): boolean {
    if (this.#isAbstract !== undefined) return this.#isAbstract;
    return (this.attribute("isAbstract") as unknown as boolean) ?? false;
  }

  set isAbstract(value: boolean) {
    this.#isAbstract = value;
  }

  #isVariation: boolean | undefined = false;

  get isVariation(): boolean {
    if (this.#isVariation !== undefined) return this.#isVariation;
    return (this.attribute("isVariation") as unknown as boolean) ?? false;
  }

  set isVariation(value: boolean) {
    this.#isVariation = value;
  }

  #isDerived: boolean | undefined = false;

  get isDerived(): boolean {
    if (this.#isDerived !== undefined) return this.#isDerived;
    return (this.attribute("isDerived") as unknown as boolean) ?? false;
  }

  set isDerived(value: boolean) {
    this.#isDerived = value;
  }

  #isEnd: boolean | undefined = false;

  get isEnd(): boolean {
    if (this.#isEnd !== undefined) return this.#isEnd;
    return (this.attribute("isEnd") as unknown as boolean) ?? false;
  }

  set isEnd(value: boolean) {
    this.#isEnd = value;
  }

  #isOrdered: boolean | undefined = false;

  get isOrdered(): boolean {
    if (this.#isOrdered !== undefined) return this.#isOrdered;
    return (this.attribute("isOrdered") as unknown as boolean) ?? false;
  }

  set isOrdered(value: boolean) {
    this.#isOrdered = value;
  }

  #isNonunique: boolean | undefined = false;

  get isNonunique(): boolean {
    if (this.#isNonunique !== undefined) return this.#isNonunique;
    return (this.attribute("isNonunique") as unknown as boolean) ?? false;
  }

  set isNonunique(value: boolean) {
    this.#isNonunique = value;
  }

  #isConstant: boolean | undefined = false;

  get isConstant(): boolean {
    if (this.#isConstant !== undefined) return this.#isConstant;
    return (this.attribute("isConstant") as unknown as boolean) ?? false;
  }

  set isConstant(value: boolean) {
    this.#isConstant = value;
  }

  #direction: string | null | undefined = undefined;

  get direction(): string | null {
    if (this.#direction !== undefined) return this.#direction;
    return this.attribute("direction") ?? (undefined as unknown as string | null);
  }

  set direction(value: string | null) {
    this.#direction = value;
  }

  // --- Computed Properties (query-backed) ---
  get resolvedType(): DefinitionNode | null {
    const entry = this.query<SymbolEntry | null>("resolvedType");
    return entry ? (wrapEntry(entry, this.db) as DefinitionNode | null) : (null as unknown as DefinitionNode | null);
  }

  get ownedFeatures(): UsageNode[] {
    const entries = this.query<SymbolEntry[]>("ownedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as UsageNode[];
  }

  get redefinedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("redefinedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get subsettedFeatures(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("subsettedFeatures");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  // --- Query Accessors ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedDefinitions(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedDefinitions");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedUsages(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedUsages");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedParts(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedParts");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedAttributes(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedAttributes");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedPorts(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedPorts");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedActions(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedActions");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedConstraints(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConstraints");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get ownedConnections(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("ownedConnections");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get superclassifiers(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("superclassifiers");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get entryAction(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("entryAction");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get doAction(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("doAction");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get exitAction(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("exitAction");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  get transitions(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("transitions");
    return entries.map((e) => wrapEntry(e, this.db));
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "label" },
        ],
        attrs: {
          body: { fill: "#fff8e1", stroke: "#fbc02d", strokeWidth: 1.5, rx: 4, ry: 4, strokeDasharray: "6 3" },
          label: { text: "{{name}}", fill: "#1a1a1a", fontSize: 13, textAnchor: "middle", refX: 0.5, refY: 0.5 },
        },
        size: { width: 140, height: 40 },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): StateUsageNode {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new StateUsageNode(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: Sysml2Visitor<R, A>, arg?: A): R {
    return visitor.visitStateUsageNode(this, arg);
  }
}

/**
 * Visitor interface for all generated semantic node types.
 * Extends the base SemanticVisitor with typed visit methods.
 */
export interface Sysml2Visitor<R, A = void> extends SemanticVisitor<R, A> {
  visitUsageNode(node: UsageNode, arg?: A): R;
  visitDefinitionNode(node: DefinitionNode, arg?: A): R;
  visitPackageNode(node: PackageNode, arg?: A): R;
  visitAliasNode(node: AliasNode, arg?: A): R;
  visitImportNode(node: ImportNode, arg?: A): R;
  visitEnumerationNode(node: EnumerationNode, arg?: A): R;
  visitEnumerationValueNode(node: EnumerationValueNode, arg?: A): R;
  visitCalculationDefinitionNode(node: CalculationDefinitionNode, arg?: A): R;
  visitCalculationUsageNode(node: CalculationUsageNode, arg?: A): R;
  visitConstraintDefinitionNode(node: ConstraintDefinitionNode, arg?: A): R;
  visitConstraintUsageNode(node: ConstraintUsageNode, arg?: A): R;
  visitRequirementDefinitionNode(node: RequirementDefinitionNode, arg?: A): R;
  visitRequirementUsageNode(node: RequirementUsageNode, arg?: A): R;
  visitSatisfyRequirementNode(node: SatisfyRequirementNode, arg?: A): R;
  visitVerificationCaseDefinitionNode(node: VerificationCaseDefinitionNode, arg?: A): R;
  visitVerificationCaseUsageNode(node: VerificationCaseUsageNode, arg?: A): R;
  visitStateDefinitionNode(node: StateDefinitionNode, arg?: A): R;
  visitStateUsageNode(node: StateUsageNode, arg?: A): R;
}

/**
 * Wrap a SymbolEntry into its typed SemanticNode subclass.
 * Dispatches by entry.kind to the correct generated class.
 */
export function wrapEntry(entry: SymbolEntry, db: QueryDB): SemanticNode {
  switch (entry.kind) {
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Package":
      return new PackageNode(entry, db);
    case "Package":
      return new PackageNode(entry, db);
    case "Alias":
      return new AliasNode(entry, db);
    case "Import":
      return new ImportNode(entry, db);
    case "Import":
      return new ImportNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Enumeration":
      return new EnumerationNode(entry, db);
    case "EnumerationValue":
      return new EnumerationValueNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new CalculationDefinitionNode(entry, db);
    case "Usage":
      return new CalculationUsageNode(entry, db);
    case "Definition":
      return new ConstraintDefinitionNode(entry, db);
    case "Usage":
      return new ConstraintUsageNode(entry, db);
    case "Usage":
      return new ConstraintUsageNode(entry, db);
    case "Definition":
      return new RequirementDefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new ConstraintUsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new RequirementUsageNode(entry, db);
    case "Usage":
      return new SatisfyRequirementNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new VerificationCaseDefinitionNode(entry, db);
    case "Usage":
      return new VerificationCaseUsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new StateDefinitionNode(entry, db);
    case "Usage":
      return new StateUsageNode(entry, db);
    case "Usage":
      return new StateUsageNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    case "Definition":
      return new DefinitionNode(entry, db);
    case "Usage":
      return new UsageNode(entry, db);
    default:
      return new GenericNode(entry, db);
  }
}
