// =============================================================================
// GENERATED by @modelscript/polyglot — do not edit manually.
// Language: sysml2
// Semantic diffing configuration for automated PLM and impact analysis.
// =============================================================================

import type { DiffConfig } from "@modelscript/polyglot";

export const diffConfig: Record<string, DiffConfig> = {
  PartDefinition: {
    ignore: ["annotationClause", "description"],
    breaking: ["isAbstract"],
  },
  PortDefinition: {
    ignore: ["annotationClause", "description"],
    breaking: ["direction"],
  },
  ConnectionUsage: {
    identity: (self) => self.name || `connection_${self.id}`,
  },
  RequirementDefinition: {
    ignore: ["description", "text"],
    breaking: ["subject", "isAbstract"],
  },
};
