/* eslint-disable */
// =============================================================================
// GENERATED by @modelscript/polyglot — do not edit manually.
// Language: sysml2
// X6-compatible graphics configuration for diagram rendering.
// =============================================================================

import type { GraphicsConfig } from "@modelscript/polyglot";

export const graphicsConfig: Record<string, GraphicsConfig> = {
  Package: {
    role: "group",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "rect",
          selector: "tab",
        },
        {
          tagName: "text",
          selector: "tabLabel",
        },
        {
          tagName: "text",
          selector: "label",
        },
      ],
      attrs: {
        body: {
          fill: "#f0f4ff",
          stroke: "#4a90d9",
          strokeWidth: 2,
          rx: 0,
          ry: 0,
        },
        tab: {
          fill: "#4a90d9",
          width: 80,
          height: 20,
          rx: 0,
          ry: 0,
          x: 0,
          y: 0,
        },
        tabLabel: {
          text: "package",
          fill: "#fff",
          fontSize: 10,
          x: 40,
          y: 13,
          textAnchor: "middle",
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          refX: 0.5,
          refY: 34,
          textAnchor: "middle",
        },
      },
      size: {
        width: 300,
        height: 200,
      },
    },
  },
  LibraryPackage: {
    role: "group",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "rect",
          selector: "tab",
        },
        {
          tagName: "text",
          selector: "tabLabel",
        },
        {
          tagName: "text",
          selector: "label",
        },
      ],
      attrs: {
        body: {
          fill: "#f0f4ff",
          stroke: "#4a90d9",
          strokeWidth: 2,
          rx: 0,
          ry: 0,
        },
        tab: {
          fill: "#4a90d9",
          width: 80,
          height: 20,
          rx: 0,
          ry: 0,
          x: 0,
          y: 0,
        },
        tabLabel: {
          text: "library",
          fill: "#fff",
          fontSize: 10,
          x: 40,
          y: 13,
          textAnchor: "middle",
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          refX: 0.5,
          refY: 34,
          textAnchor: "middle",
        },
      },
      size: {
        width: 300,
        height: 200,
      },
    },
  },
  AttributeDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#fce4ec",
          stroke: "#e91e63",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«attribute def»",
          fill: "#e91e63",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#e91e63",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 180,
        height: 60,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#e91e63",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#e91e63",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
    },
  },
  AttributeUsage: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "label",
        },
      ],
      attrs: {
        body: {
          fill: "#fce4ec",
          stroke: "#f48fb1",
          strokeWidth: 1.5,
          rx: 4,
          ry: 4,
          strokeDasharray: "6 3",
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 13,
          textAnchor: "middle",
          refX: 0.5,
          refY: 0.5,
        },
      },
      size: {
        width: 140,
        height: 40,
      },
    },
  },
  ItemDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#e0f2f1",
          stroke: "#00897b",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«item def»",
          fill: "#00897b",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#00897b",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 180,
        height: 60,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#00897b",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#00897b",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
    },
  },
  ItemUsage: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "label",
        },
      ],
      attrs: {
        body: {
          fill: "#e0f2f1",
          stroke: "#4db6ac",
          strokeWidth: 1.5,
          rx: 4,
          ry: 4,
          strokeDasharray: "6 3",
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 13,
          textAnchor: "middle",
          refX: 0.5,
          refY: 0.5,
        },
      },
      size: {
        width: 140,
        height: 40,
      },
    },
  },
  PartDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#e8f5e9",
          stroke: "#43a047",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«part def»",
          fill: "#43a047",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#43a047",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 180,
        height: 60,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#43a047",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#43a047",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
      portQuery: "ownedPorts",
    },
  },
  PartUsage: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "label",
        },
      ],
      attrs: {
        body: {
          fill: "#e8f5e9",
          stroke: "#66bb6a",
          strokeWidth: 1.5,
          rx: 4,
          ry: 4,
          strokeDasharray: "6 3",
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 13,
          textAnchor: "middle",
          refX: 0.5,
          refY: 0.5,
        },
      },
      size: {
        width: 140,
        height: 40,
      },
    },
  },
  PortUsage: {
    role: "port-owner",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "label",
        },
      ],
      attrs: {
        body: {
          fill: "#fff3e0",
          stroke: "#ef6c00",
          strokeWidth: 2,
          rx: 0,
          ry: 0,
          width: 16,
          height: 16,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 10,
          refX: 0.5,
          refY: 20,
          textAnchor: "middle",
        },
      },
      size: {
        width: 16,
        height: 16,
      },
    },
  },
  ConnectionDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#eceff1",
          stroke: "#546e7a",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«connection def»",
          fill: "#546e7a",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#546e7a",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 180,
        height: 60,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#546e7a",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#546e7a",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
    },
  },
  ConnectionUsage: {
    role: "edge",
    edge: {
      shape: "edge",
      attrs: {
        line: {
          stroke: "#546e7a",
          strokeWidth: 1.5,
          targetMarker: "classic",
        },
      },
      labels: [
        {
          attrs: {
            text: {
              text: "«connect»",
              fill: "#666",
              fontSize: 11,
            },
            rect: {
              fill: "#fff",
              stroke: "none",
              rx: 3,
              ry: 3,
            },
          },
          position: {
            distance: 0.5,
            offset: 0,
          },
        },
      ],
      router: "manhattan",
      connector: "rounded",
    },
  },
  ActionDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#e3f2fd",
          stroke: "#1565c0",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«action def»",
          fill: "#1565c0",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#1565c0",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 180,
        height: 60,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#1565c0",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#1565c0",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
    },
  },
  CalculationDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#e0f7fa",
          stroke: "#00838f",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«calc def»",
          fill: "#00838f",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#00838f",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 180,
        height: 60,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#00838f",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#00838f",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
    },
  },
  ConstraintDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#ffebee",
          stroke: "#c62828",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«constraint def»",
          fill: "#c62828",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#c62828",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 180,
        height: 60,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#c62828",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#c62828",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
    },
  },
  RequirementDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#f3e5f5",
          stroke: "#9c27b0",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«requirement def»",
          fill: "#9c27b0",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#9c27b0",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 200,
        height: 70,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#9c27b0",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#9c27b0",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
    },
  },
  SatisfyRequirementUsage: {
    role: "edge",
    edge: {
      shape: "edge",
      attrs: {
        line: {
          stroke: "#9c27b0",
          strokeWidth: 1.5,
          strokeDasharray: "8 4",
          targetMarker: "classic",
        },
      },
      labels: [
        {
          attrs: {
            text: {
              text: "«satisfy»",
              fill: "#666",
              fontSize: 11,
            },
            rect: {
              fill: "#fff",
              stroke: "none",
              rx: 3,
              ry: 3,
            },
          },
          position: {
            distance: 0.5,
            offset: 0,
          },
        },
      ],
      router: "manhattan",
      connector: "rounded",
    },
  },
  VerificationCaseDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#e8eaf6",
          stroke: "#3f51b5",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«verification def»",
          fill: "#3f51b5",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#3f51b5",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 180,
        height: 60,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#3f51b5",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#3f51b5",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
    },
  },
  VerifyRequirementUsage: {
    role: "edge",
    edge: {
      shape: "edge",
      attrs: {
        line: {
          stroke: "#3f51b5",
          strokeWidth: 1.5,
          strokeDasharray: "4 4",
          targetMarker: "classic",
        },
      },
      labels: [
        {
          attrs: {
            text: {
              text: "«verify»",
              fill: "#666",
              fontSize: 11,
            },
            rect: {
              fill: "#fff",
              stroke: "none",
              rx: 3,
              ry: 3,
            },
          },
          position: {
            distance: 0.5,
            offset: 0,
          },
        },
      ],
      router: "manhattan",
      connector: "rounded",
    },
  },
  StateDefinition: {
    role: "node",
    node: {
      shape: "rect",
      markup: [
        {
          tagName: "rect",
          selector: "body",
        },
        {
          tagName: "text",
          selector: "header",
        },
        {
          tagName: "line",
          selector: "separator",
        },
        {
          tagName: "text",
          selector: "label",
        },
        {
          tagName: "image",
          selector: "icon",
        },
      ],
      attrs: {
        body: {
          fill: "#fff8e1",
          stroke: "#f9a825",
          strokeWidth: 2,
          rx: 4,
          ry: 4,
        },
        header: {
          text: "«state def»",
          fill: "#f9a825",
          fontSize: 10,
          textAnchor: "middle",
          refX: 0.5,
          refY: 14,
        },
        separator: {
          x1: 0,
          y1: 24,
          x2: "100%",
          y2: 24,
          stroke: "#f9a825",
          strokeWidth: 1,
        },
        label: {
          text: "{{name}}",
          fill: "#1a1a1a",
          fontSize: 14,
          fontWeight: "bold",
          textAnchor: "middle",
          refX: 0.5,
          refY: 40,
        },
        icon: {},
      },
      size: {
        width: 180,
        height: 60,
      },
      ports: {
        groups: {
          in: {
            position: "left",
            attrs: {
              circle: {
                r: 5,
                fill: "#f9a825",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
          out: {
            position: "right",
            attrs: {
              circle: {
                r: 5,
                fill: "#f9a825",
                stroke: "#fff",
                strokeWidth: 1.5,
              },
            },
          },
        },
      },
    },
  },
};
