// SPDX-License-Identifier: AGPL-3.0-or-later

import type { QueryDB } from "@modelscript/runtime";
import type { AssumeGuaranteeContract } from "../contract-verifier.js";

export interface NuXmvVarDecl {
  name: string;
  type: string;
}

export interface NuXmvExportOptions {
  moduleName?: string;
  stateMachineName?: string;
  invariants?: string[];
  ltlSpecs?: string[];
  inputVars?: NuXmvVarDecl[];
  outputVars?: NuXmvVarDecl[];
  substates?: Record<string, string[]>;
}

export interface OcraContractSpec {
  name: string;
  assumptions: string[];
  guarantees: string[];
}

export interface OcraComponentSpec {
  name: string;
  inputs?: { name: string; type?: string }[];
  outputs?: { name: string; type?: string }[];
  contracts: OcraContractSpec[];
  subcomponents?: { name: string; type: string }[];
  refinements?: {
    contractName: string;
    subcontracts: string[];
  }[];
}

export interface OcraExportOptions {
  systemName?: string;
  components?: OcraComponentSpec[];
}

/**
 * Normalizes a guard condition into nuXmv propositional / arithmetic syntax.
 * e.g. "fuelLevel > 0" -> "fuelLevel > 0"
 * e.g. "x >= 10 && x <= 20" -> "x >= 10 & x <= 20"
 */
function normalizeGuardToNuXmv(guard: string): string {
  return guard
    .replace(/&&/g, " & ")
    .replace(/\band\b/gi, " & ")
    .replace(/\|\|/g, " | ")
    .replace(/\bor\b/gi, " | ")
    .replace(/!([^=])/g, "!$1")
    .replace(/==/g, "=")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Exports SysML v2 state machines and discrete transition relations into nuXmv (.smv) format.
 * Supports IVAR inputs, output variables, and hierarchical/compound state machines.
 */
export function exportToNuXmv(db: QueryDB, options: NuXmvExportOptions = {}): string {
  const moduleName = options.moduleName || "main";
  const allEntries = db.allEntries();

  // Find all state symbols
  const stateEntries = allEntries.filter(
    (e) => (e.ruleName === "StateDefinition" || e.ruleName === "StateUsage") && e.name,
  );

  const transitionEntries = allEntries.filter((e) => e.ruleName === "TransitionUsage");

  // Determine target state machine
  const targetStates = options.stateMachineName
    ? stateEntries.filter(
        (s) => s.name === options.stateMachineName || db.parentOf(s.id)?.name === options.stateMachineName,
      )
    : stateEntries;

  const stateNames = Array.from(new Set(targetStates.map((s) => s.name!)));
  if (stateNames.length === 0) {
    stateNames.push("Idle", "Active", "Error");
  }

  const lines: string[] = [];
  lines.push(`-- nuXmv (.smv) model generated by ModelScript Formal Verification Bridge`);
  lines.push(`-- Module: ${moduleName}`);
  lines.push(`MODULE ${moduleName}`);
  lines.push("");

  // IVAR declarations (inputs)
  if (options.inputVars && options.inputVars.length > 0) {
    lines.push("IVAR");
    for (const iv of options.inputVars) {
      lines.push(`  ${iv.name} : ${iv.type};`);
    }
    lines.push("");
  }

  // VAR declarations
  lines.push("VAR");
  lines.push(`  state : { ${stateNames.join(", ")} };`);

  // Hierarchical substate variables
  const substateKeys = options.substates ? Object.keys(options.substates) : [];
  for (const sk of substateKeys) {
    const values = options.substates![sk]!;
    if (values.length > 0) {
      lines.push(`  ${sk} : { ${values.join(", ")} };`);
    }
  }

  // Output / internal variables
  if (options.outputVars && options.outputVars.length > 0) {
    for (const ov of options.outputVars) {
      lines.push(`  ${ov.name} : ${ov.type};`);
    }
  }
  lines.push("");

  // ASSIGN declarations
  lines.push("ASSIGN");
  lines.push(`  init(state) := ${stateNames[0]};`);
  lines.push("  next(state) := case");

  // Build transition cases
  for (const t of transitionEntries) {
    const meta = t.metadata as any;
    let source = meta?.source;
    let target = meta?.target;
    let guard = meta?.guard;

    if (!source || !target) {
      const text = db.cstText(t.startByte, t.endByte, t);
      if (text) {
        const match = text.match(/first\s+([a-zA-Z0-9_]+).*?then\s+([a-zA-Z0-9_]+)/);
        if (match) {
          source = source || match[1];
          target = target || match[2];
        }
      }
    }

    if (source && target && stateNames.includes(source) && stateNames.includes(target)) {
      const guardStr = guard ? ` & (${normalizeGuardToNuXmv(guard)})` : "";
      lines.push(`    state = ${source}${guardStr} : ${target};`);
    }
  }

  lines.push("    TRUE : state;");
  lines.push("  esac;");

  // Substate initial and next assignments if provided
  for (const sk of substateKeys) {
    const values = options.substates![sk]!;
    if (values.length > 0) {
      lines.push(`  init(${sk}) := ${values[0]};`);
      lines.push(`  next(${sk}) := case`);
      lines.push(`    TRUE : ${sk};`);
      lines.push("  esac;");
    }
  }
  lines.push("");

  // INVARSPEC safety specifications
  if (options.invariants && options.invariants.length > 0) {
    lines.push("-- Safety Invariants");
    for (const inv of options.invariants) {
      lines.push(`INVARSPEC ${normalizeGuardToNuXmv(inv)}`);
    }
    lines.push("");
  }

  // LTLSPEC temporal logic specifications
  if (options.ltlSpecs && options.ltlSpecs.length > 0) {
    lines.push("-- Temporal LTL Specifications");
    for (const spec of options.ltlSpecs) {
      lines.push(`LTLSPEC ${spec}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Normalizes a contract condition for OCRA .oss format.
 */
function normalizeConditionToOcra(cond: string): string {
  return cond
    .replace(/&&/g, " and ")
    .replace(/\|\|/g, " or ")
    .replace(/==/g, "=")
    .replace(/!=/g, "!=")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Exports assume-guarantee contracts into standard OCRA (.oss) contract files.
 */
export function exportToOcra(
  target: QueryDB | AssumeGuaranteeContract[] | OcraComponentSpec[],
  options: OcraExportOptions = {},
): string {
  const lines: string[] = [];
  lines.push("-- OCRA (.oss) contract model generated by ModelScript Formal Verification Bridge");
  lines.push("");

  let components: OcraComponentSpec[] = [];

  if (Array.isArray(target)) {
    if (target.length > 0 && "contracts" in target[0]!) {
      components = target as OcraComponentSpec[];
    } else {
      // Array of AssumeGuaranteeContract
      const agContracts = target as AssumeGuaranteeContract[];
      const systemName = options.systemName || "System";

      const inputsSet = new Set<string>();
      const outputsSet = new Set<string>();
      for (const c of agContracts) {
        c.inputs?.forEach((i) => inputsSet.add(i));
        c.outputs?.forEach((o) => outputsSet.add(o));
      }

      components.push({
        name: systemName,
        inputs: Array.from(inputsSet).map((i) => ({ name: i, type: "real" })),
        outputs: Array.from(outputsSet).map((o) => ({ name: o, type: "real" })),
        contracts: agContracts.map((c) => ({
          name: c.name,
          assumptions: c.assumptions,
          guarantees: c.guarantees,
        })),
      });
    }
  } else {
    // QueryDB
    const db = target as QueryDB;
    const allEntries = db.allEntries();
    const systemName = options.systemName || "System";

    const extractedContracts: OcraContractSpec[] = [];
    const inputs: { name: string; type?: string }[] = [];
    const outputs: { name: string; type?: string }[] = [];

    for (const e of allEntries) {
      if (e.ruleName === "PortUsage" || e.ruleName === "PortDefinition") {
        const text = db.cstText(e.startByte, e.endByte, e) ?? "";
        const isInput = text.includes("in ") || text.includes("input");
        const isOutput = text.includes("out ") || text.includes("output");
        if (e.name) {
          if (isInput) inputs.push({ name: e.name, type: "real" });
          else if (isOutput) outputs.push({ name: e.name, type: "real" });
        }
      } else if (
        e.ruleName === "RequirementUsage" ||
        e.ruleName === "RequirementDefinition" ||
        e.ruleName === "ConstraintUsage"
      ) {
        const text = db.cstText(e.startByte, e.endByte, e) ?? "";
        const assumeMatch = text.match(/assume\s+(.*?);/);
        const requireMatch = text.match(/require\s+(.*?);/) || text.match(/guarantee\s+(.*?);/);
        if (assumeMatch || requireMatch) {
          extractedContracts.push({
            name: e.name || `contract_${e.id}`,
            assumptions: assumeMatch ? [assumeMatch[1]!] : ["TRUE"],
            guarantees: requireMatch ? [requireMatch[1]!] : ["TRUE"],
          });
        }
      }
    }

    if (extractedContracts.length === 0) {
      extractedContracts.push({
        name: "default_contract",
        assumptions: ["TRUE"],
        guarantees: ["TRUE"],
      });
    }

    components.push({
      name: systemName,
      inputs: inputs.length > 0 ? inputs : undefined,
      outputs: outputs.length > 0 ? outputs : undefined,
      contracts: extractedContracts,
    });
  }

  // Render components
  for (const comp of components) {
    lines.push(`COMPONENT ${comp.name}`);
    lines.push("INTERFACE");

    if (comp.inputs && comp.inputs.length > 0) {
      for (const inp of comp.inputs) {
        lines.push(`  INPUT ${inp.name} : ${inp.type ?? "real"};`);
      }
    }
    if (comp.outputs && comp.outputs.length > 0) {
      for (const out of comp.outputs) {
        lines.push(`  OUTPUT ${out.name} : ${out.type ?? "real"};`);
      }
    }
    if ((!comp.inputs || comp.inputs.length === 0) && (!comp.outputs || comp.outputs.length === 0)) {
      lines.push("  -- No explicit port interfaces specified");
    }

    // Contracts
    for (const contract of comp.contracts) {
      lines.push(`CONTRACT ${contract.name}`);
      const assumeStr =
        contract.assumptions.length > 0 ? contract.assumptions.map(normalizeConditionToOcra).join(" and ") : "TRUE";
      const guaranteeStr =
        contract.guarantees.length > 0 ? contract.guarantees.map(normalizeConditionToOcra).join(" and ") : "TRUE";
      lines.push(`  assume: ${assumeStr};`);
      lines.push(`  guarantee: ${guaranteeStr};`);
    }

    // Refinement section if subcomponents exist
    if (comp.subcomponents && comp.subcomponents.length > 0) {
      lines.push("REFINEMENT");
      for (const sub of comp.subcomponents) {
        lines.push(`  SUB ${sub.name} : ${sub.type};`);
      }
      if (comp.refinements) {
        for (const ref of comp.refinements) {
          lines.push(`  ${ref.contractName} REFINEDBY ${ref.subcontracts.join(", ")};`);
        }
      }
    }

    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}
