// SPDX-License-Identifier: AGPL-3.0-or-later

import type { QueryDB } from "@modelscript/runtime";

export interface NuXmvExportOptions {
  moduleName?: string;
  stateMachineName?: string;
  invariants?: string[];
  ltlSpecs?: string[];
}

/**
 * Normalizes a guard condition into nuXmv propositional / arithmetic syntax.
 * e.g. "fuelLevel > 0" -> "fuelLevel > 0"
 * e.g. "x >= 10 && x <= 20" -> "x >= 10 & x <= 20"
 */
function normalizeGuardToNuXmv(guard: string): string {
  return guard
    .replace(/\s*&&\s*/g, " & ")
    .replace(/\s*\band\b\s*/gi, " & ")
    .replace(/\s*\|\|\s*/g, " | ")
    .replace(/\s*\bor\b\s*/gi, " | ")
    .replace(/!([^=])/g, "!$1")
    .replace(/==/g, "=")
    .trim();
}

/**
 * Exports SysML v2 state machines and discrete transition relations into nuXmv (.smv) format.
 */
export function exportToNuXmv(db: QueryDB, options: NuXmvExportOptions = {}): string {
  const moduleName = options.moduleName || "main";
  const allEntries = db.allEntries();

  // Find all state symbols
  const stateEntries = allEntries.filter(
    (e) => (e.ruleName === "StateDefinition" || e.ruleName === "StateUsage") && e.name,
  );

  const transitionEntries = allEntries.filter((e) => e.ruleName === "TransitionUsage");

  // Determine target state machine
  const targetStates = options.stateMachineName
    ? stateEntries.filter(
        (s) => s.name === options.stateMachineName || db.parentOf(s.id)?.name === options.stateMachineName,
      )
    : stateEntries;

  const stateNames = Array.from(new Set(targetStates.map((s) => s.name!)));
  if (stateNames.length === 0) {
    stateNames.push("Idle", "Active", "Error");
  }

  const lines: string[] = [];
  lines.push(`-- nuXmv (.smv) model generated by ModelScript Formal Verification Bridge`);
  lines.push(`-- Module: ${moduleName}`);
  lines.push(`MODULE ${moduleName}`);
  lines.push("");

  // VAR declarations
  lines.push("VAR");
  lines.push(`  state : { ${stateNames.join(", ")} };`);
  lines.push("");

  // ASSIGN declarations
  lines.push("ASSIGN");
  lines.push(`  init(state) := ${stateNames[0]};`);
  lines.push("  next(state) := case");

  // Build transition cases
  for (const t of transitionEntries) {
    const meta = t.metadata as any;
    let source = meta?.source;
    let target = meta?.target;
    let guard = meta?.guard;

    if (!source || !target) {
      const text = db.cstText(t.startByte, t.endByte, t);
      if (text) {
        const match = text.match(/first\s+([a-zA-Z0-9_]+).*?then\s+([a-zA-Z0-9_]+)/);
        if (match) {
          source = source || match[1];
          target = target || match[2];
        }
      }
    }

    if (source && target && stateNames.includes(source) && stateNames.includes(target)) {
      const guardStr = guard ? ` & (${normalizeGuardToNuXmv(guard)})` : "";
      lines.push(`    state = ${source}${guardStr} : ${target};`);
    }
  }

  lines.push("    TRUE : state;");
  lines.push("  esac;");
  lines.push("");

  // INVARSPEC safety specifications
  if (options.invariants && options.invariants.length > 0) {
    lines.push("-- Safety Invariants");
    for (const inv of options.invariants) {
      lines.push(`INVARSPEC ${normalizeGuardToNuXmv(inv)}`);
    }
    lines.push("");
  }

  // LTLSPEC temporal logic specifications
  if (options.ltlSpecs && options.ltlSpecs.length > 0) {
    lines.push("-- Temporal LTL Specifications");
    for (const spec of options.ltlSpecs) {
      lines.push(`LTLSPEC ${spec}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
