// SPDX-License-Identifier: AGPL-3.0-or-later

import type { QueryDB } from "@modelscript/runtime";
import { type ExtractedConstraint, extractSysML2Constraints } from "../constraint-extractor.js";

export interface SmtLibExportOptions {
  logic?: "QF_LRA" | "QF_IDL" | "ALL";
  scopeFilter?: string;
  produceModels?: boolean;
}

/**
 * Converts an infix comparison expression to prefix SMT-LIB2 syntax.
 * e.g. "x - y <= 5.0" -> "(<= (- x y) 5.0)"
 * e.g. "speed <= 100" -> "(<= speed 100.0)"
 */
export function expressionToSmtLib(c: ExtractedConstraint): string {
  const rhsNum = typeof c.rhs === "number" ? c.rhs : parseFloat(String(c.rhs));
  const rhsStr = Number.isFinite(rhsNum)
    ? Number.isInteger(rhsNum)
      ? `${rhsNum}.0`
      : rhsNum.toString()
    : String(c.rhs);

  const diffMatch = c.lhs.match(/^([a-zA-Z0-9_.]+)\s*-\s*([a-zA-Z0-9_.]+)$/);
  const lhsSmt = diffMatch
    ? `(- ${diffMatch[1].replace(/\./g, "_")} ${diffMatch[2].replace(/\./g, "_")})`
    : c.lhs.replace(/\./g, "_");

  const opMap: Record<string, string> = {
    "<=": "<=",
    "<": "<",
    ">=": ">=",
    ">": ">",
    "==": "=",
    "!=": "distinct",
  };

  const smtOp = opMap[c.operator] || "=";
  return `(${smtOp} ${lhsSmt} ${rhsStr})`;
}

/**
 * Exports SysML v2 extracted constraints into standard SMT-LIB v2 text.
 */
export function exportToSmtLib(db: QueryDB, options: SmtLibExportOptions = {}): string {
  const logic = options.logic || "QF_LRA";
  const constraints = extractSysML2Constraints(db, options.scopeFilter);

  const lines: string[] = [];
  lines.push(`; SMT-LIB v2 generated by ModelScript Formal Verification Bridge`);
  lines.push(`; Scope: ${options.scopeFilter || "global"}`);
  lines.push(`(set-logic ${logic})`);
  lines.push(`(set-option :produce-models ${options.produceModels ?? true})`);
  lines.push("");

  // Collect all unique variables
  const variables = new Set<string>();
  for (const c of constraints) {
    const diffMatch = c.lhs.match(/^([a-zA-Z0-9_.]+)\s*-\s*([a-zA-Z0-9_.]+)$/);
    if (diffMatch) {
      variables.add(diffMatch[1].replace(/\./g, "_"));
      variables.add(diffMatch[2].replace(/\./g, "_"));
    } else {
      variables.add(c.lhs.replace(/\./g, "_"));
    }
  }

  // Declare constants
  lines.push("; Variable Declarations");
  for (const v of Array.from(variables).sort()) {
    lines.push(`(declare-const ${v} Real)`);
  }
  lines.push("");

  // Assert constraints
  lines.push("; Assertions");
  for (const c of constraints) {
    const smtExpr = expressionToSmtLib(c);
    const comment = c.requirementName ? ` ; from requirement ${c.requirementName}` : "";
    lines.push(`(assert ${smtExpr})${comment}`);
  }
  lines.push("");

  // Check satisfiability
  lines.push("(check-sat)");
  if (options.produceModels ?? true) {
    lines.push("(get-model)");
  }

  return lines.join("\n");
}
