// ====================================================================
// AUTO-GENERATED by @modelscript/polyglot — do not edit manually.
// External scanner for error recovery.
// ====================================================================

#include "tree_sitter/parser.h"
#include <string.h>

enum TokenType {
  RECOVERY_CLASS_DEFINITION_BODY,  // 0
  RECOVERY_FUNCTION_DEFINITION_BODY,  // 1
};

static bool is_ws(int32_t c) {
  return c == ' ' || c == '\t' || c == '\r' || c == '\n';
}

static bool is_ident_start(int32_t c) {
  return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_';
}

static bool is_ident_char(int32_t c) {
  return is_ident_start(c) || (c >= '0' && c <= '9');
}

static bool is_digit(int32_t c) {
  return c >= '0' && c <= '9';
}

/**
 * After consuming an identifier, peek at what follows (after whitespace).
 * If the next non-ws char could continue a valid statement, return false
 * to let the grammar handle it.
 * But: if the next word is a sync keyword, that's NOT a valid continuation.
 */
static bool is_valid_continuation(
  TSLexer *lexer,
  const char *sync_kws[], int sync_count
) {
  // Skip whitespace to see what follows
  while (is_ws(lexer->lookahead)) lexer->advance(lexer, false);
  int32_t next = lexer->lookahead;
  
  // Non-ident continuations are always valid
  if (next == '(' || next == '.' || next == '=') return true;
  
  // If next char starts an identifier, read it and check against sync keywords
  if (is_ident_start(next)) {
    char word[64];
    int wlen = 0;
    while (is_ident_char(lexer->lookahead) && wlen < 63) {
      word[wlen++] = (char)lexer->lookahead;
      lexer->advance(lexer, false);
    }
    word[wlen] = '\0';
    
    // If followed by another ident, it's "Type Name" pattern → valid continue
    // But first check if this word is a sync keyword
    for (int i = 0; i < sync_count; i++) {
      if (strcmp(word, sync_kws[i]) == 0) return false;
    }
    return true;
  }
  
  return false;
}

// ── Lifecycle ────────────────────────────────────────────────────────

void  *tree_sitter_modelica_external_scanner_create(void)                                    { return NULL; }
void   tree_sitter_modelica_external_scanner_destroy(void *p)                                { (void)p; }
unsigned tree_sitter_modelica_external_scanner_serialize(void *p, char *b)                   { (void)p; (void)b; return 0; }
void   tree_sitter_modelica_external_scanner_deserialize(void *p, const char *b, unsigned n) { (void)p; (void)b; (void)n; }

// ── Main scan ────────────────────────────────────────────────────────

bool tree_sitter_modelica_external_scanner_scan(
  void *payload, TSLexer *lexer, const bool *valid_symbols
) {
  (void)payload;

  // ── class_definition.body (sync: "end", "initial", ";") ──
  if (valid_symbols[RECOVERY_CLASS_DEFINITION_BODY]) {
    const char *kws[] = {"end", "initial"};
    int kw_count = 2;

    // Skip whitespace
    while (is_ws(lexer->lookahead)) lexer->advance(lexer, true);
    if (lexer->eof(lexer)) return false;

    // Don't match at comment starts
    if (lexer->lookahead == '/') {
      lexer->mark_end(lexer);
      lexer->advance(lexer, false);
      if (lexer->lookahead == '/' || lexer->lookahead == '*') return false;
      // Just a '/' — consume as recovery
      lexer->mark_end(lexer);
      lexer->result_symbol = RECOVERY_CLASS_DEFINITION_BODY;
      return true;
    }

    // Don't match at single-char sync tokens
    if (lexer->lookahead == ';') return false;

    // Try to consume an identifier
    if (is_ident_start(lexer->lookahead)) {
      char buf[64];
      int len = 0;
      while (is_ident_char(lexer->lookahead) && len < 63) {
        buf[len++] = (char)lexer->lookahead;
        lexer->advance(lexer, false);
      }
      buf[len] = '\0';
      // Overflow — just consume
      if (is_ident_char(lexer->lookahead)) {
        while (is_ident_char(lexer->lookahead)) lexer->advance(lexer, false);
      }

      // Mark end to identifier boundary BEFORE peeking ahead
      lexer->mark_end(lexer);

      // Check sync keywords
      if (len == 3 && buf[0] == 'e' && buf[1] == 'n' && buf[2] == 'd') return false;
      if (len == 7 && buf[0] == 'i' && buf[1] == 'n' && buf[2] == 'i' && buf[3] == 't' && buf[4] == 'i' && buf[5] == 'a' && buf[6] == 'l') return false;

      // Check if followed by valid continuation → not garbage, let grammar handle it
      if (is_valid_continuation(lexer, kws, kw_count)) return false;

      // Isolated identifier not matching any sync keyword — it's garbage
      lexer->result_symbol = RECOVERY_CLASS_DEFINITION_BODY;
      return true;
    }

    // Consume a number
    if (is_digit(lexer->lookahead)) {
      while (is_digit(lexer->lookahead)) lexer->advance(lexer, false);
      if (lexer->lookahead == '.') {
        lexer->advance(lexer, false);
        while (is_digit(lexer->lookahead)) lexer->advance(lexer, false);
      }
      lexer->mark_end(lexer);
      lexer->result_symbol = RECOVERY_CLASS_DEFINITION_BODY;
      return true;
    }

    // Consume a string
    if (lexer->lookahead == '"') {
      lexer->advance(lexer, false);
      while (!lexer->eof(lexer) && lexer->lookahead != '"' && lexer->lookahead != '\n') {
        lexer->advance(lexer, false);
      }
      if (lexer->lookahead == '"') lexer->advance(lexer, false);
      lexer->mark_end(lexer);
      lexer->result_symbol = RECOVERY_CLASS_DEFINITION_BODY;
      return true;
    }

    // Consume any other single non-whitespace character
    if (!is_ws(lexer->lookahead) && !lexer->eof(lexer)) {
      lexer->advance(lexer, false);
      lexer->mark_end(lexer);
      lexer->result_symbol = RECOVERY_CLASS_DEFINITION_BODY;
      return true;
    }
  }

  // ── function_definition.body (sync: "end", ";") ──
  if (valid_symbols[RECOVERY_FUNCTION_DEFINITION_BODY]) {
    const char *kws[] = {"end"};
    int kw_count = 1;

    // Skip whitespace
    while (is_ws(lexer->lookahead)) lexer->advance(lexer, true);
    if (lexer->eof(lexer)) return false;

    // Don't match at comment starts
    if (lexer->lookahead == '/') {
      lexer->mark_end(lexer);
      lexer->advance(lexer, false);
      if (lexer->lookahead == '/' || lexer->lookahead == '*') return false;
      // Just a '/' — consume as recovery
      lexer->mark_end(lexer);
      lexer->result_symbol = RECOVERY_FUNCTION_DEFINITION_BODY;
      return true;
    }

    // Don't match at single-char sync tokens
    if (lexer->lookahead == ';') return false;

    // Try to consume an identifier
    if (is_ident_start(lexer->lookahead)) {
      char buf[64];
      int len = 0;
      while (is_ident_char(lexer->lookahead) && len < 63) {
        buf[len++] = (char)lexer->lookahead;
        lexer->advance(lexer, false);
      }
      buf[len] = '\0';
      // Overflow — just consume
      if (is_ident_char(lexer->lookahead)) {
        while (is_ident_char(lexer->lookahead)) lexer->advance(lexer, false);
      }

      // Mark end to identifier boundary BEFORE peeking ahead
      lexer->mark_end(lexer);

      // Check sync keywords
      if (len == 3 && buf[0] == 'e' && buf[1] == 'n' && buf[2] == 'd') return false;

      // Check if followed by valid continuation → not garbage, let grammar handle it
      if (is_valid_continuation(lexer, kws, kw_count)) return false;

      // Isolated identifier not matching any sync keyword — it's garbage
      lexer->result_symbol = RECOVERY_FUNCTION_DEFINITION_BODY;
      return true;
    }

    // Consume a number
    if (is_digit(lexer->lookahead)) {
      while (is_digit(lexer->lookahead)) lexer->advance(lexer, false);
      if (lexer->lookahead == '.') {
        lexer->advance(lexer, false);
        while (is_digit(lexer->lookahead)) lexer->advance(lexer, false);
      }
      lexer->mark_end(lexer);
      lexer->result_symbol = RECOVERY_FUNCTION_DEFINITION_BODY;
      return true;
    }

    // Consume a string
    if (lexer->lookahead == '"') {
      lexer->advance(lexer, false);
      while (!lexer->eof(lexer) && lexer->lookahead != '"' && lexer->lookahead != '\n') {
        lexer->advance(lexer, false);
      }
      if (lexer->lookahead == '"') lexer->advance(lexer, false);
      lexer->mark_end(lexer);
      lexer->result_symbol = RECOVERY_FUNCTION_DEFINITION_BODY;
      return true;
    }

    // Consume any other single non-whitespace character
    if (!is_ws(lexer->lookahead) && !lexer->eof(lexer)) {
      lexer->advance(lexer, false);
      lexer->mark_end(lexer);
      lexer->result_symbol = RECOVERY_FUNCTION_DEFINITION_BODY;
      return true;
    }
  }

  return false;
}
