; highlights.scm — Auto-generated by @modelscript/compiler
; Language: csv
; Do not edit manually — regenerate with: npm run generate

; ─── Keywords ───────────────────────────────────────────────────────
[
] @keyword

; ─── Delimiters ───────────────────────────────────────────────────
["," ";"] @punctuation.delimiter

; ─── Comments ─────────────────────────────────────────────────────

; ─── Literals ─────────────────────────────────────────────────────

; ─── Boolean/null literals ─────────────────────────────────────────

; ─── Identifier fallback ──────────────────────────────────────────
(Name) @variable

