; highlights.scm — Auto-generated by @modelscript/compiler
; Language: step
; Do not edit manually — regenerate with: npm run generate

; ─── Keywords ───────────────────────────────────────────────────────
[
] @keyword

; ─── Comments ─────────────────────────────────────────────────────
(BLOCK_COMMENT) @comment

; ─── Literals ─────────────────────────────────────────────────────

; ─── Boolean/null literals ─────────────────────────────────────────

; ─── Identifier fallback ──────────────────────────────────────────
(Name) @variable

