; highlights.scm — Auto-generated by @modelscript/language
; Language: step
; Do not edit manually — regenerate with: npm run generate

; ─── Keywords ───────────────────────────────────────────────────────
[
  "DATA"
] @keyword

; ─── Type references ───────────────────────────────────────────────
(EntityReference (Name) @variable)

; ─── Operators ────────────────────────────────────────────────────
[
  "="
] @operator

; ─── Brackets ─────────────────────────────────────────────────────
["(" ")"] @punctuation.bracket

; ─── Delimiters ───────────────────────────────────────────────────
["," ";"] @punctuation.delimiter

; ─── Comments ─────────────────────────────────────────────────────
(BLOCK_COMMENT) @comment

; ─── Literals ─────────────────────────────────────────────────────

; ─── Boolean/null literals ─────────────────────────────────────────

; ─── Identifier fallback ──────────────────────────────────────────
(Name) @variable

