; highlights.scm — Auto-generated by @modelscript/compiler
; Language: sysml2
; Do not edit manually — regenerate with: npm run generate

; ─── Keywords ───────────────────────────────────────────────────────
[
  "as" "meta"
] @keyword

; ─── Type references ──────────────────────────────────────────────
(OwnedFeatureTyping (QualifiedName) @type)
(ConjugatedPortTyping (QualifiedName) @type)
(OwnedReferenceSubsetting (QualifiedName) @type)
(OwnedSubsetting (QualifiedName) @type)
(OwnedRedefinition (QualifiedName) @type)
(Subclassification (QualifiedName) @type)

; ─── Operators ────────────────────────────────────────────────────
[
  "*"
] @operator

; ─── Comments ─────────────────────────────────────────────────────
(Comment) @comment
(REGULAR_COMMENT) @comment

; ─── Literals ─────────────────────────────────────────────────────
(DECIMAL_VALUE) @number
(STRING_VALUE) @string

; ─── Boolean/null literals ─────────────────────────────────────────

; ─── Identifier fallback ──────────────────────────────────────────
(Name) @variable

