// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * ModelScript Standalone Embedded C Code Generator.
 *
 * Transpiles a DAEBuilder into zero-dependency, zero-allocation C99 source files
 * (`<model>_standalone.h` and `<model>_standalone.c`) with a clean, strongly-typed
 * `init()`, `setParameters()`, and `step(in, out, dt)` interface suitable for direct embedding into:
 *   - Bare-metal microcontrollers (STM32, ESP32, Teensy, Cortex-M/R)
 *   - RTOS tasks (FreeRTOS, Zephyr, VxWorks)
 *   - Linux RT-PREEMPT loops
 *   - C++ SIL harnesses / unit tests without FMI shared library overhead
 *
 * Adheres strictly to eFMI principles:
 *   - Zero dynamic heap allocation (no malloc/free)
 *   - Static memory footprint defined entirely at compile-time
 *   - Fixed-step 4th-order Runge-Kutta (RK4) numerical integration
 */

import { Causality, EqKind, Variability, type DAEBuilder } from "@modelscript/runtime";
import { generateFmu, type FmuOptions, type FmuResult } from "./fmi.js";
import { generateFmuCSources } from "./fmu-codegen.js";
import { sanitizeIdentifier } from "./transpiler-utils.js";

export interface StandaloneCResult {
  header: string;
  source: string;
  modelIdentifier: string;
  inputNames: string[];
  outputNames: string[];
  parameterNames: string[];
}

export interface StandaloneCOptions extends FmuOptions {
  /** Include a standalone main() harness in the C file for quick CLI testing. */
  includeMain?: boolean;
}

/**
 * Generate standalone, zero-FMI C99 source and header files for a Modelica model.
 */
export function generateStandaloneCSources(dae: DAEBuilder, options: StandaloneCOptions): StandaloneCResult {
  const id = options.modelIdentifier || "Model";
  const fmuResult: FmuResult = generateFmu(dae, options);
  const cSources = generateFmuCSources(dae, fmuResult, options);

  const vars = fmuResult.scalarVariables;
  let maxVr = 0;
  let nStringVars = 0;
  for (const v of vars) {
    maxVr = Math.max(maxVr, v.valueReference);
    if (v.name.includes("_string_")) nStringVars++;
  }
  const nVars = vars.length > 0 ? maxVr + 1 : 0;
  const nStates = fmuResult.modelStructure.derivatives.length;
  const nEvents = fmuResult.numberOfEventIndicators;

  let nWhenConditions = 0;
  for (let idx = 0; idx < dae.eqCount; idx++) {
    if (dae.getEqKind(idx) === EqKind.When) {
      const meta = dae.getWhenEquationMeta(idx);
      if (meta) {
        nWhenConditions += 1 + meta.elseWhenClauses.length;
      }
    }
  }

  // Identify input, output, and parameter variables
  const inputVars: { name: string; vr: number; sanitized: string }[] = [];
  const outputVars: { name: string; vr: number; sanitized: string }[] = [];
  const paramVars: { name: string; vr: number; sanitized: string; defaultVal: number }[] = [];

  for (let i = 0; i < dae.varCount; i++) {
    if (dae.isVarRemoved(i)) continue;
    const c = dae.getVarCausality(i);
    const v = dae.getVarVariability(i);
    const name = dae.getVarName(i);
    if (!name) continue;
    const sanitized = sanitizeIdentifier(name);
    const sv = vars.find((s) => s.name === name);
    const vr = sv ? sv.valueReference : i;

    if (c === Causality.Input) {
      inputVars.push({ name, vr, sanitized });
    } else if (c === Causality.Output) {
      outputVars.push({ name, vr, sanitized });
    }

    if (v === Variability.Parameter) {
      const startVal = dae.getVarStartValue(i) ?? 0.0;
      paramVars.push({ name, vr, sanitized, defaultVal: startVal });
    }
  }

  const prefix = id.toUpperCase();

  // ── 1. Generate <model>_standalone.h ──
  const hLines: string[] = [];
  hLines.push("/* Auto-generated by ModelScript Standalone Embedded Coder */");
  hLines.push("/* Zero-allocation, zero-FMI standalone plant model adhering to eFMI principles */");
  hLines.push(`#ifndef ${prefix}_STANDALONE_H`);
  hLines.push(`#define ${prefix}_STANDALONE_H`);
  hLines.push("");
  hLines.push("#include <math.h>");
  hLines.push("#include <string.h>");
  hLines.push("#include <stdint.h>");
  hLines.push("");
  hLines.push(`#define ${prefix}_MODEL_IDENTIFIER "${id}"`);
  hLines.push(`#define ${prefix}_N_INPUTS ${inputVars.length}`);
  hLines.push(`#define ${prefix}_N_OUTPUTS ${outputVars.length}`);
  hLines.push(`#define ${prefix}_N_PARAMETERS ${paramVars.length}`);
  hLines.push(`#define ${prefix}_N_STATES ${nStates}`);
  hLines.push(`#define ${prefix}_N_VARS ${nVars}`);
  hLines.push("");

  // Variable references
  hLines.push("/* Variable value references */");
  for (const sv of fmuResult.scalarVariables) {
    const cName = sanitizeIdentifier(sv.name).toUpperCase();
    hLines.push(`#define VR_${cName} ${sv.valueReference}`);
  }
  hLines.push("");

  hLines.push("#ifdef __cplusplus");
  hLines.push('extern "C" {');
  hLines.push("#endif");
  hLines.push("");

  // Input struct
  hLines.push(`/* Strongly-typed inputs for ${id} */`);
  hLines.push("typedef struct {");
  if (inputVars.length === 0) {
    hLines.push("  double _unused; /* No top-level inputs */");
  } else {
    for (const iv of inputVars) {
      hLines.push(`  double ${iv.sanitized}; /* Modelica: ${iv.name} */`);
    }
  }
  hLines.push(`} ${id}_Inputs;`);
  hLines.push("");

  // Output struct
  hLines.push(`/* Strongly-typed outputs for ${id} */`);
  hLines.push("typedef struct {");
  if (outputVars.length === 0) {
    hLines.push("  double _unused; /* No top-level outputs */");
  } else {
    for (const ov of outputVars) {
      hLines.push(`  double ${ov.sanitized}; /* Modelica: ${ov.name} */`);
    }
  }
  hLines.push(`} ${id}_Outputs;`);
  hLines.push("");

  // Parameter struct
  hLines.push(`/* Tunable parameters for ${id} */`);
  hLines.push("typedef struct {");
  if (paramVars.length === 0) {
    hLines.push("  double _unused; /* No tunable parameters */");
  } else {
    for (const pv of paramVars) {
      hLines.push(`  double ${pv.sanitized}; /* Modelica parameter: ${pv.name} */`);
    }
  }
  hLines.push(`} ${id}_Parameters;`);
  hLines.push("");

  // Model instance structure (embeds core state vectors, zero heap allocation)
  hLines.push(`/* Static instance state for ${id} (fully static, zero dynamic memory allocation) */`);
  hLines.push("typedef struct {");
  hLines.push(`  double vars[${nVars + 1}];`);
  hLines.push(`  double states[${nStates + 1}];`);
  hLines.push(`  double derivatives[${nStates + 1}];`);
  hLines.push(`  char* stringVars[${nStringVars + 1}];`);
  hLines.push(`  double eventPrev[${nEvents + 1}];`);
  hLines.push(`  double whenPrev[${nWhenConditions + 1}];`);
  hLines.push("  double time;");
  hLines.push("  int isInitialized;");
  hLines.push("  int isInitPhase;");
  hLines.push("  int isDirtyValues;");
  hLines.push(`  ${id}_Parameters params;`);
  hLines.push("  void* fmuInstance;");
  hLines.push("  void (*logger)(void* fmuInstance, const char* category, const char* message);");
  hLines.push("  void (*terminate)(void* fmuInstance);");
  hLines.push(`} ${id}_Instance;`);
  hLines.push("");

  // Function prototypes
  hLines.push(`/**`);
  hLines.push(` * Initialize model state and evaluate initial conditions.`);
  hLines.push(` */`);
  hLines.push(`void ${id}_init(${id}_Instance* inst);`);
  hLines.push("");
  hLines.push(`/**`);
  hLines.push(` * Tune model parameters online during runtime without reinitializing states.`);
  hLines.push(` */`);
  hLines.push(`void ${id}_setParameters(${id}_Instance* inst, const ${id}_Parameters* params);`);
  hLines.push("");
  hLines.push(`/**`);
  hLines.push(` * Advance the model by one time step dt using 4th-order Runge-Kutta (RK4) integration.`);
  hLines.push(` * @param inst Pointer to the static model instance.`);
  hLines.push(` * @param in   Current input values.`);
  hLines.push(` * @param out  Output struct populated by the step calculation.`);
  hLines.push(` * @param dt   Time step size in seconds.`);
  hLines.push(` */`);
  hLines.push(`void ${id}_step(${id}_Instance* inst, const ${id}_Inputs* in, ${id}_Outputs* out, double dt);`);
  hLines.push("");

  // Internal core prototypes
  hLines.push("/* Internal model routines */");
  hLines.push(`void ${id}_initialize(${id}_Instance* inst);`);
  hLines.push(`void ${id}_initializeSolve(${id}_Instance* inst);`);
  hLines.push(`void ${id}_solveAlgebraicLoops(${id}_Instance* inst);`);
  hLines.push(`void ${id}_getDerivatives(${id}_Instance* inst);`);
  hLines.push("");

  hLines.push("#ifdef __cplusplus");
  hLines.push("}");
  hLines.push("#endif");
  hLines.push("");
  hLines.push(`#endif /* ${prefix}_STANDALONE_H */`);

  // ── 2. Generate <model>_standalone.c ──
  const cLines: string[] = [];
  cLines.push("/* Auto-generated by ModelScript Standalone Embedded Coder */");
  cLines.push(`#include "${id}_standalone.h"`);
  cLines.push("#include <stdio.h>");
  cLines.push("#include <stdlib.h>");
  cLines.push("#include <math.h>");
  cLines.push("#include <string.h>");
  cLines.push("");

  // Clean modelC by stripping the separate header include
  const sanitizedModelC = cSources.modelC.replace(`#include "${id}_model.h"`, `/* Embedded ${id} model equations */`);
  cLines.push(sanitizedModelC);
  cLines.push("");

  const stateVRs = fmuResult.modelStructure.derivatives.map((derVR) => {
    const sv = fmuResult.scalarVariables.find((v) => v.valueReference === derVR);
    return sv?.derivative ?? -1;
  });

  // Implement <model>_setParameters
  cLines.push(`void ${id}_setParameters(${id}_Instance* inst, const ${id}_Parameters* params) {`);
  cLines.push("  if (!inst || !params) return;");
  for (const pv of paramVars) {
    cLines.push(`  inst->vars[${pv.vr}] = params->${pv.sanitized};`);
    cLines.push(`  inst->params.${pv.sanitized} = params->${pv.sanitized};`);
  }
  cLines.push(`  ${id}_solveAlgebraicLoops(inst);`);
  cLines.push(`  ${id}_getDerivatives(inst);`);
  cLines.push("}");
  cLines.push("");

  // Implement <model>_init
  cLines.push(`void ${id}_init(${id}_Instance* inst) {`);
  cLines.push("  if (!inst) return;");
  cLines.push("  memset(inst, 0, sizeof(*inst));");
  cLines.push(`  ${id}_initialize(inst);`);
  cLines.push(`  ${id}_initializeSolve(inst);`);
  cLines.push("");
  cLines.push("  /* Initialize default parameter struct values */");
  for (const pv of paramVars) {
    cLines.push(`  inst->params.${pv.sanitized} = inst->vars[${pv.vr}];`);
  }
  cLines.push("");
  cLines.push("  /* Initialize continuous states from initial variables */");
  for (let i = 0; i < stateVRs.length; i++) {
    const vr = stateVRs[i];
    if (vr >= 0) {
      cLines.push(`  inst->states[${i}] = inst->vars[${vr}];`);
    }
  }
  cLines.push("");
  cLines.push(`  ${id}_solveAlgebraicLoops(inst);`);
  cLines.push(`  ${id}_getDerivatives(inst);`);
  cLines.push("  inst->time = 0.0;");
  cLines.push("  inst->isInitialized = 1;");
  cLines.push("}");
  cLines.push("");

  // Implement <model>_step with 4th-order Runge-Kutta (RK4) integration
  cLines.push(`void ${id}_step(${id}_Instance* inst, const ${id}_Inputs* in, ${id}_Outputs* out, double dt) {`);
  cLines.push("  if (!inst) return;");
  if (inputVars.length === 0) cLines.push("  (void)in;");
  if (outputVars.length === 0) cLines.push("  (void)out;");
  cLines.push("  if (!inst->isInitialized) {");
  cLines.push(`    ${id}_init(inst);`);
  cLines.push("  }");
  cLines.push("");

  // 1. Copy inputs into vars
  if (inputVars.length > 0) {
    cLines.push("  /* Copy inputs into model variables */");
    cLines.push("  if (in) {");
    for (const iv of inputVars) {
      cLines.push(`    inst->vars[${iv.vr}] = in->${iv.sanitized};`);
    }
    cLines.push("  }");
    cLines.push("");
  }

  // 2. Numerical Integration
  cLines.push(`  const int n_states = ${nStates};`);
  cLines.push("  if (n_states > 0) {");
  cLines.push(`    double y0[${nStates + 1}];`);
  cLines.push(`    double k1[${nStates + 1}];`);
  cLines.push(`    double k2[${nStates + 1}];`);
  cLines.push(`    double k3[${nStates + 1}];`);
  cLines.push(`    double k4[${nStates + 1}];`);
  cLines.push("    const double t0 = inst->time;");
  cLines.push("");
  cLines.push("    for (int i = 0; i < n_states; i++) y0[i] = inst->states[i];");
  cLines.push("");
  cLines.push("    /* Stage 1: k1 = f(t0, y0) */");
  cLines.push("    inst->time = t0;");
  cLines.push("    for (int i = 0; i < n_states; i++) {");
  cLines.push("      inst->states[i] = y0[i];");
  cLines.push("    }");
  for (let i = 0; i < stateVRs.length; i++) {
    const vr = stateVRs[i];
    if (vr >= 0) cLines.push(`    inst->vars[${vr}] = inst->states[${i}];`);
  }
  cLines.push(`    ${id}_solveAlgebraicLoops(inst);`);
  cLines.push(`    ${id}_getDerivatives(inst);`);
  cLines.push("    for (int i = 0; i < n_states; i++) k1[i] = inst->derivatives[i];");
  cLines.push("");
  cLines.push("    /* Stage 2: k2 = f(t0 + 0.5*dt, y0 + 0.5*dt*k1) */");
  cLines.push("    inst->time = t0 + 0.5 * dt;");
  cLines.push("    for (int i = 0; i < n_states; i++) {");
  cLines.push("      inst->states[i] = y0[i] + 0.5 * dt * k1[i];");
  cLines.push("    }");
  for (let i = 0; i < stateVRs.length; i++) {
    const vr = stateVRs[i];
    if (vr >= 0) cLines.push(`    inst->vars[${vr}] = inst->states[${i}];`);
  }
  cLines.push(`    ${id}_solveAlgebraicLoops(inst);`);
  cLines.push(`    ${id}_getDerivatives(inst);`);
  cLines.push("    for (int i = 0; i < n_states; i++) k2[i] = inst->derivatives[i];");
  cLines.push("");
  cLines.push("    /* Stage 3: k3 = f(t0 + 0.5*dt, y0 + 0.5*dt*k2) */");
  cLines.push("    inst->time = t0 + 0.5 * dt;");
  cLines.push("    for (int i = 0; i < n_states; i++) {");
  cLines.push("      inst->states[i] = y0[i] + 0.5 * dt * k2[i];");
  cLines.push("    }");
  for (let i = 0; i < stateVRs.length; i++) {
    const vr = stateVRs[i];
    if (vr >= 0) cLines.push(`    inst->vars[${vr}] = inst->states[${i}];`);
  }
  cLines.push(`    ${id}_solveAlgebraicLoops(inst);`);
  cLines.push(`    ${id}_getDerivatives(inst);`);
  cLines.push("    for (int i = 0; i < n_states; i++) k3[i] = inst->derivatives[i];");
  cLines.push("");
  cLines.push("    /* Stage 4: k4 = f(t0 + dt, y0 + dt*k3) */");
  cLines.push("    inst->time = t0 + dt;");
  cLines.push("    for (int i = 0; i < n_states; i++) {");
  cLines.push("      inst->states[i] = y0[i] + dt * k3[i];");
  cLines.push("    }");
  for (let i = 0; i < stateVRs.length; i++) {
    const vr = stateVRs[i];
    if (vr >= 0) cLines.push(`    inst->vars[${vr}] = inst->states[${i}];`);
  }
  cLines.push(`    ${id}_solveAlgebraicLoops(inst);`);
  cLines.push(`    ${id}_getDerivatives(inst);`);
  cLines.push("    for (int i = 0; i < n_states; i++) k4[i] = inst->derivatives[i];");
  cLines.push("");
  cLines.push("    /* RK4 Combination: y_next = y0 + (dt/6)*(k1 + 2*k2 + 2*k3 + k4) */");
  cLines.push("    for (int i = 0; i < n_states; i++) {");
  cLines.push("      inst->states[i] = y0[i] + (dt / 6.0) * (k1[i] + 2.0 * k2[i] + 2.0 * k3[i] + k4[i]);");
  cLines.push("    }");
  for (let i = 0; i < stateVRs.length; i++) {
    const vr = stateVRs[i];
    if (vr >= 0) cLines.push(`    inst->vars[${vr}] = inst->states[${i}];`);
  }
  cLines.push("    inst->time = t0 + dt;");
  cLines.push(`    ${id}_solveAlgebraicLoops(inst);`);
  cLines.push(`    ${id}_getDerivatives(inst);`);
  cLines.push("  } else {");
  cLines.push("    inst->time += dt;");
  cLines.push(`    ${id}_solveAlgebraicLoops(inst);`);
  cLines.push("  }");
  cLines.push("");

  // 3. Copy outputs from vars
  if (outputVars.length > 0) {
    cLines.push("  /* Populate output struct */");
    cLines.push("  if (out) {");
    for (const ov of outputVars) {
      cLines.push(`    out->${ov.sanitized} = inst->vars[${ov.vr}];`);
    }
    cLines.push("  }");
  }
  cLines.push("}");
  cLines.push("");

  // 4. Optional standalone main() test runner
  if (options.includeMain) {
    cLines.push("/* Standalone demonstration CLI runner */");
    cLines.push("int main(int argc, char* argv[]) {");
    cLines.push("  (void)argc; (void)argv;");
    cLines.push(`  printf("[ModelScript] Running standalone RK4 simulation for model '${id}'...\\n");`);
    cLines.push(`  ${id}_Instance inst;`);
    cLines.push(`  ${id}_init(&inst);`);
    cLines.push(`  ${id}_Inputs in = {0};`);
    cLines.push(`  ${id}_Outputs out = {0};`);
    cLines.push("  const double dt = 0.01;");
    cLines.push("  for (int step = 1; step <= 100; step++) {");
    cLines.push(`    ${id}_step(&inst, &in, &out, dt);`);
    cLines.push("    if (step % 20 == 0) {");
    if (outputVars.length > 0) {
      const firstOut = outputVars[0].sanitized;
      cLines.push(`      printf("  t=%.2f s | ${firstOut}=%.4f\\n", inst.time, out.${firstOut});`);
    } else if (nStates > 0) {
      cLines.push(`      printf("  t=%.2f s | state[0]=%.4f\\n", inst.time, inst.states[0]);`);
    } else {
      cLines.push(`      printf("  t=%.2f s | step=%d\\n", inst.time, step);`);
    }
    cLines.push("    }");
    cLines.push("  }");
    cLines.push('  printf("[ModelScript] Simulation completed successfully.\\n");');
    cLines.push("  return 0;");
    cLines.push("}");
  }

  return {
    header: hLines.join("\n"),
    source: cLines.join("\n"),
    modelIdentifier: id,
    inputNames: inputVars.map((v) => v.name),
    outputNames: outputVars.map((v) => v.name),
    parameterNames: paramVars.map((v) => v.name),
  };
}
