// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Virtual document provider for `.fmu` files.
 *
 * Renders FMU archives as readonly Modelica block definitions by extracting
 * the `modelDescription.xml` from the ZIP and converting scalar variables
 * into Modelica-style input/output/parameter declarations.
 */

import { unzipSync } from "fflate";
import * as vscode from "vscode";

/** URI scheme for virtual FMU documents. */
export const FMU_VIEW_SCHEME = "fmu-view";

/** Parsed FMU variable from modelDescription.xml. */
interface FmuVariable {
  name: string;
  causality: string;
  variability: string;
  type: string;
  description: string;
  start?: string;
  unit?: string;
}

/** Parse modelDescription.xml into structured data. */
function parseModelDescription(xml: string): {
  modelName: string;
  description: string;
  guid: string;
  fmiVersion: string;
  generationTool: string;
  variables: FmuVariable[];
} {
  const attr = (s: string, name: string): string => s.match(new RegExp(`\\b${name}\\s*=\\s*"([^"]*)"`))?.[1] ?? "";

  const headerMatch = xml.match(/<fmiModelDescription([^>]*)>/);
  const header = headerMatch?.[1] ?? "";
  const modelName = attr(header, "modelName") || "FMU";
  const description = attr(header, "description");
  const guid = attr(header, "guid");
  const fmiVersion = attr(header, "fmiVersion");
  const generationTool = attr(header, "generationTool");

  const variables: FmuVariable[] = [];
  const scalarRegex =
    /<ScalarVariable\b([^>]*)\/?>([\s\S]*?)(?:<\/ScalarVariable>|(?=<ScalarVariable|<\/ModelVariables))/g;
  let match: RegExpExecArray | null;

  while ((match = scalarRegex.exec(xml)) !== null) {
    const headerAttrs = match[1] ?? "";
    const body = match[0] ?? "";

    const name = attr(headerAttrs, "name");
    if (!name) continue;

    const causality = attr(headerAttrs, "causality") || "local";
    const variability = attr(headerAttrs, "variability") || "continuous";
    const varDesc = attr(headerAttrs, "description");

    // Detect type from nested element
    const typeMatch = body.match(/<(Real|Integer|Boolean|String)\b([^>]*)/);
    const type = typeMatch?.[1] ?? "Real";
    const typeAttrs = typeMatch?.[2] ?? "";
    const start = attr(typeAttrs, "start") || undefined;
    const unit = attr(typeAttrs, "unit") || undefined;

    variables.push({ name, causality, variability, type, description: varDesc, start, unit });
  }

  return { modelName, description, guid, fmiVersion, generationTool, variables };
}

/** Generate a Modelica block definition from FMU metadata. */
function generateModelicaBlock(fmu: ReturnType<typeof parseModelDescription>): string {
  const lines: string[] = [];

  // Header comment
  lines.push(`// ── FMU 2.0 Model Description ──────────────────────────────────────`);
  lines.push(`// This is a readonly view of the FMU archive contents.`);
  lines.push(`// GUID: ${fmu.guid}`);
  if (fmu.generationTool) {
    lines.push(`// Generated by: ${fmu.generationTool}`);
  }
  lines.push(``);

  // Block declaration
  if (fmu.description) {
    lines.push(`block ${fmu.modelName} "${fmu.description}"`);
  } else {
    lines.push(`block ${fmu.modelName}`);
  }

  // Group variables by causality
  const inputs = fmu.variables.filter((v) => v.causality === "input");
  const outputs = fmu.variables.filter((v) => v.causality === "output");
  const params = fmu.variables.filter((v) => v.causality === "parameter" || v.causality === "calculatedParameter");
  const locals = fmu.variables.filter((v) => v.causality === "local" || v.causality === "independent");

  // Parameters
  for (const v of params) {
    const startStr = v.start !== undefined ? ` = ${v.start}` : "";
    const unitStr = v.unit ? ` /* ${v.unit} */` : "";
    const descStr = v.description ? ` "${v.description}"` : "";
    lines.push(`  parameter ${v.type} ${v.name}${startStr}${descStr};${unitStr}`);
  }

  // Inputs
  if (inputs.length > 0 && params.length > 0) lines.push(``);
  for (const v of inputs) {
    const startStr = v.start !== undefined ? `(start = ${v.start})` : "";
    const descStr = v.description ? ` "${v.description}"` : "";
    lines.push(`  input ${v.type} ${v.name}${startStr}${descStr};`);
  }

  // Outputs
  if (outputs.length > 0 && (inputs.length > 0 || params.length > 0)) lines.push(``);
  for (const v of outputs) {
    const startStr = v.start !== undefined ? `(start = ${v.start})` : "";
    const descStr = v.description ? ` "${v.description}"` : "";
    lines.push(`  output ${v.type} ${v.name}${startStr}${descStr};`);
  }

  // Local/internal variables (protected)
  if (locals.length > 0) {
    lines.push(``);
    lines.push(`protected`);
    for (const v of locals) {
      const startStr = v.start !== undefined ? `(start = ${v.start})` : "";
      const descStr = v.description ? ` "${v.description}"` : "";
      lines.push(`  ${v.type} ${v.name}${startStr}${descStr};`);
    }
  }

  lines.push(`end ${fmu.modelName};`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Virtual document provider for FMU archives.
 * Renders the FMU's modelDescription.xml as a Modelica block definition.
 */
export class FmuDocumentProvider implements vscode.TextDocumentContentProvider {
  private _onDidChange = new vscode.EventEmitter<vscode.Uri>();
  readonly onDidChangeTextDocument = this._onDidChange.event;

  /** Cache of generated content keyed by URI string. */
  private cache = new Map<string, string>();

  /** Register FMU content from raw bytes. */
  registerFmu(name: string, fmuBytes: Uint8Array): void {
    try {
      const files = unzipSync(fmuBytes);
      const xmlData = files["modelDescription.xml"];
      if (!xmlData) {
        this.cache.set(name, `// Error: modelDescription.xml not found in ${name}.fmu\n`);
        return;
      }
      const xml = new TextDecoder().decode(xmlData);
      const fmu = parseModelDescription(xml);
      this.cache.set(name, generateModelicaBlock(fmu));
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      this.cache.set(name, `// Error reading ${name}.fmu: ${msg}\n`);
    }
  }

  provideTextDocumentContent(uri: vscode.Uri): string {
    const name = uri.path.replace(/^\//, "");
    return this.cache.get(name) ?? `// Loading ${name}.fmu...\n`;
  }
}
