// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * COIN-OR C glue-code generator.
 *
 * Emits standalone C source files that bridge the model instance (from
 * fmu-codegen.ts) to COIN-OR solvers via coinor-interface.c:
 *   - LP/MILP mode:  Generates sparse constraint matrix data + main.c for CLP/CBC
 *   - NLP mode:      Generates AD-based objective/constraint evaluators + main.c for IPOPT
 *
 * The generated code follows the same pattern as sundials-codegen.ts:
 *   1. Allocate model instance
 *   2. Populate CoinorModelCallbacks
 *   3. Call appropriate solver
 *   4. Output results
 */

import { StaticTapeBuilder } from "./ad-codegen.js";
import type { ModelicaExpression } from "./dae.js";
import type { SolverOptions } from "./solver-options.js";

// ── Public interface ──

/** Options for COIN-OR code generation. */
export interface CoinorCodegenOptions {
  /** Model identifier (from FMU codegen). */
  modelIdentifier: string;
  /** Solver to use: "clp", "cbc", or "ipopt". */
  solver: "clp" | "cbc" | "ipopt";
  /** NLP convergence tolerance (default: 1e-8). */
  tolerance?: number;
  /** Maximum iterations (default: 3000). */
  maxIterations?: number;
  /** IPOPT print level: 0-12 (default: 0). */
  printLevel?: number;
  /** Use exact Hessian for IPOPT (default: true). */
  useExactHessian?: boolean;
  /** Generic solver options (overrides specific options). */
  solverOptions?: SolverOptions;
}

/** Generated COIN-OR C files. */
export interface CoinorCodegenResult {
  /** main.c — optimization/LP driver */
  mainC: string;
  /** CMake snippet for COIN-OR dependencies */
  cmakeSnippet: string;
}

/** NLP problem definition for IPOPT codegen. */
export interface NlpProblemDef {
  /** Decision variable names. */
  variables: string[];
  /** Variable lower bounds. */
  variableLB: number[];
  /** Variable upper bounds. */
  variableUB: number[];
  /** Initial guess. */
  x0: number[];
  /** Objective expression (from DAE). */
  objectiveExpr: ModelicaExpression;
  /** Constraint expressions (each evaluates to a residual that should be zero). */
  constraintExprs: ModelicaExpression[];
  /** Constraint lower bounds. */
  constraintLB: number[];
  /** Constraint upper bounds. */
  constraintUB: number[];
}

/** LP/MILP problem definition for CLP/CBC codegen. */
export interface LpProblemDef {
  /** Number of decision variables. */
  nVars: number;
  /** Number of constraints. */
  nConstraints: number;
  /** Objective coefficients (length n_vars). */
  objCoeffs: number[];
  /** Variable lower bounds. */
  variableLB: number[];
  /** Variable upper bounds. */
  variableUB: number[];
  /** Constraint lower bounds. */
  constraintLB: number[];
  /** Constraint upper bounds. */
  constraintUB: number[];
  /** Sparse constraint matrix in CSC format. */
  A: {
    values: number[];
    rowIndices: number[];
    colPointers: number[];
  };
  /** Integer variable flags (for CBC). null = all continuous. */
  isInteger?: boolean[];
}

// ── LP/MILP codegen ──

/**
 * Generate a CLP/CBC optimization driver from a LP/MILP problem definition.
 */
export function generateLpMainC(problem: LpProblemDef, options: CoinorCodegenOptions): CoinorCodegenResult {
  const overrides = options.solverOptions;
  const resolvedSolver =
    overrides?.lpSolver === "clp" || overrides?.lpSolver === "cbc" ? overrides.lpSolver : options.solver;
  // If user asked for ipopt but we are in LP codegen, fallback to clp
  const solver = resolvedSolver === "cbc" ? "cbc" : "clp";
  const tolerance = overrides?.atol ?? options.tolerance ?? 1e-8;
  const maxIter = overrides?.maxNonlinearIterations ?? options.maxIterations ?? 3000;
  const printLevel = options.printLevel ?? 0;

  const lines: string[] = [];

  lines.push("/* Auto-generated by ModelScript — COIN-OR LP/MILP driver */");
  lines.push(`#define HAVE_${solver.toUpperCase()}`);
  lines.push('#include "coinor-interface.c"');
  lines.push("#include <stdio.h>");
  lines.push("#include <stdlib.h>");
  lines.push("");

  // Emit static data arrays
  lines.push("/* Objective coefficients */");
  lines.push(
    `static const double obj_coeffs[${problem.nVars}] = {${problem.objCoeffs.map(formatCDouble).join(", ")}};`,
  );
  lines.push("");

  lines.push("/* Variable bounds */");
  lines.push(`static const double var_lb[${problem.nVars}] = {${problem.variableLB.map(formatCDouble).join(", ")}};`);
  lines.push(`static const double var_ub[${problem.nVars}] = {${problem.variableUB.map(formatCDouble).join(", ")}};`);
  lines.push("");

  lines.push("/* Constraint bounds */");
  lines.push(
    `static const double con_lb[${problem.nConstraints}] = {${problem.constraintLB.map(formatCDouble).join(", ")}};`,
  );
  lines.push(
    `static const double con_ub[${problem.nConstraints}] = {${problem.constraintUB.map(formatCDouble).join(", ")}};`,
  );
  lines.push("");

  lines.push("/* Constraint matrix (CSC) */");
  lines.push(
    `static const double A_values[${problem.A.values.length}] = {${problem.A.values.map(formatCDouble).join(", ")}};`,
  );
  lines.push(`static const int A_row_idx[${problem.A.rowIndices.length}] = {${problem.A.rowIndices.join(", ")}};`);
  lines.push(`static const int A_col_ptr[${problem.A.colPointers.length}] = {${problem.A.colPointers.join(", ")}};`);
  lines.push("");

  // Integer flags for CBC
  if (solver === "cbc" && problem.isInteger) {
    lines.push("/* Integer variable flags */");
    lines.push(
      `static const int is_integer[${problem.nVars}] = {${problem.isInteger.map((b) => (b ? 1 : 0)).join(", ")}};`,
    );
    lines.push("");
  }

  // Main
  lines.push("int main(void) {");
  lines.push("  CoinorModelCallbacks cb;");
  lines.push("  memset(&cb, 0, sizeof(cb));");
  lines.push(`  cb.n_vars = ${problem.nVars};`);
  lines.push(`  cb.n_constraints = ${problem.nConstraints};`);
  lines.push(`  cb.nnz_jacobian = ${problem.A.values.length};`);
  lines.push("  cb.obj_coeffs = obj_coeffs;");
  lines.push("  cb.var_lb = var_lb;");
  lines.push("  cb.var_ub = var_ub;");
  lines.push("  cb.con_lb = con_lb;");
  lines.push("  cb.con_ub = con_ub;");
  lines.push("  cb.A_values = A_values;");
  lines.push("  cb.A_row_idx = A_row_idx;");
  lines.push("  cb.A_col_ptr = A_col_ptr;");
  if (solver === "cbc" && problem.isInteger) {
    lines.push("  cb.is_integer = is_integer;");
  }
  lines.push("");

  lines.push("  CoinorOptions opts;");
  lines.push("  coinor_options_defaults(&opts);");
  lines.push(`  opts.tolerance = ${formatCDouble(tolerance)};`);
  lines.push(`  opts.max_iterations = ${maxIter};`);
  lines.push(`  opts.print_level = ${printLevel};`);
  lines.push("");

  lines.push("  CoinorResult result;");
  lines.push(`  coinor_${solver}_solve(&cb, &opts, &result);`);
  lines.push("");

  lines.push('  printf("Status: %d (%s)\\n", result.status, result.message);');
  lines.push('  printf("Objective: %.15e\\n", result.objective_value);');
  lines.push('  printf("Iterations: %d\\n", result.iterations);');
  lines.push(`  for (int i = 0; i < ${problem.nVars}; i++) {`);
  lines.push('    printf("x[%d] = %.15e\\n", i, result.solution[i]);');
  lines.push("  }");
  lines.push("");
  lines.push("  coinor_result_free(&result);");
  lines.push("  return result.status == 0 ? 0 : 1;");
  lines.push("}");

  const mainC = lines.join("\n");

  const cmakeSnippet = generateCmakeSnippet(solver);

  return { mainC, cmakeSnippet };
}

// ── NLP codegen ──

/**
 * Generate an IPOPT optimization driver from a NLP problem definition.
 * Uses StaticTapeBuilder to emit AD-based objective/gradient/Hessian C code.
 */
export function generateNlpMainC(problem: NlpProblemDef, options: CoinorCodegenOptions): CoinorCodegenResult {
  const overrides = options.solverOptions;
  const tolerance = overrides?.atol ?? options.tolerance ?? 1e-8;
  const maxIter = overrides?.maxNonlinearIterations ?? options.maxIterations ?? 3000;
  const printLevel = options.printLevel ?? 0;

  const nVars = problem.variables.length;
  const nCons = problem.constraintExprs.length;

  // Build AD tapes for objective and constraints
  const objTape = new StaticTapeBuilder();
  const objIdx = objTape.walk(problem.objectiveExpr);

  const conTapes: { tape: StaticTapeBuilder; outputIdx: number }[] = [];
  for (const expr of problem.constraintExprs) {
    const tape = new StaticTapeBuilder();
    const idx = tape.walk(expr);
    conTapes.push({ tape, outputIdx: idx });
  }

  // Variable name → x[i] resolver for C code emission
  const varIndexMap = new Map<string, number>();
  for (let i = 0; i < nVars; i++) {
    const name = problem.variables[i];
    if (name) varIndexMap.set(name, i);
  }
  const varResolver = (name: string): string => {
    const idx = varIndexMap.get(name);
    if (idx !== undefined) return `x[${idx}]`;
    return `0.0 /* ${name} */`;
  };

  const lines: string[] = [];

  lines.push("/* Auto-generated by ModelScript — COIN-OR IPOPT NLP driver */");
  lines.push("#define HAVE_IPOPT");
  lines.push('#include "coinor-interface.c"');
  lines.push("#include <stdio.h>");
  lines.push("#include <stdlib.h>");
  lines.push("");

  // ── Objective evaluation ──
  lines.push("static void model_eval_objective(void* inst, const double* x, double* obj) {");
  lines.push("  (void)inst;");
  const objFwd = objTape.emitForwardC(varResolver);
  lines.push("  " + objFwd.join("\n  "));
  lines.push(`  *obj = t[${objIdx}];`);
  lines.push("}");
  lines.push("");

  // ── Gradient evaluation ──
  lines.push("static void model_eval_gradient(void* inst, const double* x, double* grad) {");
  lines.push("  (void)inst;");
  const gradFwd = objTape.emitForwardC(varResolver);
  const { code: gradRev, gradients: gradMap } = objTape.emitReverseC(objIdx);
  lines.push("  " + gradFwd.join("\n  "));
  lines.push("  " + gradRev.join("\n  "));
  lines.push(`  for (int i = 0; i < ${nVars}; i++) grad[i] = 0.0;`);
  for (const [varName, gradIdx] of gradMap) {
    const vi = varIndexMap.get(varName);
    if (vi !== undefined) {
      lines.push(`  grad[${vi}] = dt[${gradIdx}];  /* d(obj)/d(${varName}) */`);
    }
  }
  lines.push("}");
  lines.push("");

  // ── Constraint evaluation ──
  lines.push("static void model_eval_constraints(void* inst, const double* x, double* g) {");
  lines.push("  (void)inst;");
  for (let i = 0; i < conTapes.length; i++) {
    const ct = conTapes[i];
    if (!ct) continue;
    lines.push(`  { /* Constraint ${i} */`);
    const fwd = ct.tape.emitForwardC(varResolver);
    lines.push("    " + fwd.join("\n    "));
    lines.push(`    g[${i}] = t[${ct.outputIdx}];`);
    lines.push("  }");
  }
  lines.push("}");
  lines.push("");

  // ── Jacobian evaluation (dense, unrolled into sparse CSC) ──
  // For simplicity, use a dense Jacobian — n_cons × n_vars nonzeros
  const nnzJac = nCons * nVars;
  const jacRowIdx: number[] = [];
  const jacColPtr: number[] = [];

  for (let col = 0; col < nVars; col++) {
    jacColPtr.push(col * nCons);
    for (let row = 0; row < nCons; row++) {
      jacRowIdx.push(row);
    }
  }
  jacColPtr.push(nnzJac);

  lines.push("static void model_eval_jacobian(void* inst, const double* x, double* jac) {");
  lines.push("  (void)inst;");
  lines.push(`  /* Dense Jacobian: ${nCons} × ${nVars} = ${nnzJac} entries */`);
  for (let row = 0; row < conTapes.length; row++) {
    const ct = conTapes[row];
    if (!ct) continue;
    lines.push(`  { /* Constraint ${row}: forward + reverse pass */`);
    const fwd = ct.tape.emitForwardC(varResolver);
    const { code: rev, gradients: gMap } = ct.tape.emitReverseC(ct.outputIdx);
    lines.push("    " + fwd.join("\n    "));
    lines.push("    " + rev.join("\n    "));
    for (let col = 0; col < nVars; col++) {
      const varName = problem.variables[col];
      const gIdx = varName ? gMap.get(varName) : undefined;
      const sparseIdx = col * nCons + row;
      if (gIdx !== undefined) {
        lines.push(`    jac[${sparseIdx}] = dt[${gIdx}];`);
      } else {
        lines.push(`    jac[${sparseIdx}] = 0.0;`);
      }
    }
    lines.push("  }");
  }
  lines.push("}");
  lines.push("");

  // Static sparsity arrays
  lines.push(`static const int jac_row_idx[${nnzJac}] = {${jacRowIdx.join(", ")}};`);
  lines.push(`static const int jac_col_ptr[${nVars + 1}] = {${jacColPtr.join(", ")}};`);
  lines.push("");

  // Hessian: for simplicity, use L-BFGS (nnz_hessian = 0)
  lines.push("/* Hessian: using L-BFGS approximation (no exact Hessian emitted) */");
  lines.push(`static const int hess_row_idx[1] = {0};`);
  lines.push(`static const int hess_col_ptr[${nVars + 1}] = {${new Array(nVars + 1).fill(0).join(", ")}};`);
  lines.push("");

  // Bounds
  lines.push("/* Variable bounds */");
  lines.push(`static const double var_lb[${nVars}] = {${problem.variableLB.map(formatCDouble).join(", ")}};`);
  lines.push(`static const double var_ub[${nVars}] = {${problem.variableUB.map(formatCDouble).join(", ")}};`);
  lines.push("");

  if (nCons > 0) {
    lines.push("/* Constraint bounds */");
    lines.push(`static const double con_lb[${nCons}] = {${problem.constraintLB.map(formatCDouble).join(", ")}};`);
    lines.push(`static const double con_ub[${nCons}] = {${problem.constraintUB.map(formatCDouble).join(", ")}};`);
  } else {
    lines.push("static const double con_lb[1] = {0.0};");
    lines.push("static const double con_ub[1] = {0.0};");
  }
  lines.push("");

  // Initial guess
  lines.push("/* Initial guess */");
  lines.push(`static double x0[${nVars}] = {${problem.x0.map(formatCDouble).join(", ")}};`);
  lines.push("");

  // Update state callback (no-op for standalone NLP)
  lines.push("static void model_update_state(void* inst, const double* x) {");
  lines.push("  (void)inst; (void)x;");
  lines.push("}");
  lines.push("");

  // Main
  lines.push("int main(void) {");
  lines.push("  CoinorModelCallbacks cb;");
  lines.push("  memset(&cb, 0, sizeof(cb));");
  lines.push(`  cb.n_vars = ${nVars};`);
  lines.push(`  cb.n_constraints = ${nCons};`);
  lines.push(`  cb.nnz_jacobian = ${nnzJac};`);
  lines.push("  cb.nnz_hessian = 0;");
  lines.push("  cb.eval_objective = model_eval_objective;");
  lines.push("  cb.eval_gradient = model_eval_gradient;");
  lines.push("  cb.eval_constraints = model_eval_constraints;");
  lines.push("  cb.eval_jacobian = model_eval_jacobian;");
  lines.push("  cb.update_state = model_update_state;");
  lines.push("  cb.jac_row_idx = jac_row_idx;");
  lines.push("  cb.jac_col_ptr = jac_col_ptr;");
  lines.push("  cb.hess_row_idx = hess_row_idx;");
  lines.push("  cb.hess_col_ptr = hess_col_ptr;");
  lines.push("  cb.var_lb = var_lb;");
  lines.push("  cb.var_ub = var_ub;");
  lines.push(`  cb.con_lb = ${nCons > 0 ? "con_lb" : "NULL"};`);
  lines.push(`  cb.con_ub = ${nCons > 0 ? "con_ub" : "NULL"};`);
  lines.push("");

  lines.push("  CoinorOptions opts;");
  lines.push("  coinor_options_defaults(&opts);");
  lines.push(`  opts.tolerance = ${formatCDouble(tolerance)};`);
  lines.push(`  opts.max_iterations = ${maxIter};`);
  lines.push(`  opts.print_level = ${printLevel};`);
  lines.push("  opts.use_exact_hessian = 0;  /* Using L-BFGS */");
  lines.push("");

  lines.push("  CoinorResult result;");
  lines.push("  coinor_ipopt_solve(&cb, x0, &opts, &result);");
  lines.push("");

  lines.push('  printf("Status: %d (%s)\\n", result.status, result.message);');
  lines.push('  printf("Objective: %.15e\\n", result.objective_value);');
  for (let i = 0; i < nVars; i++) {
    const name = problem.variables[i] ?? `x[${i}]`;
    lines.push(`  printf("${name} = %.15e\\n", result.solution[${i}]);`);
  }
  lines.push("");
  lines.push("  coinor_result_free(&result);");
  lines.push("  return result.status == 0 ? 0 : 1;");
  lines.push("}");

  const mainC = lines.join("\n");
  const cmakeSnippet = generateCmakeSnippet("ipopt");

  return { mainC, cmakeSnippet };
}

// ── CMake helpers ──

function generateCmakeSnippet(solver: string): string {
  switch (solver) {
    case "clp":
      return `# CLP dependency
find_package(PkgConfig REQUIRED)
pkg_check_modules(CLP REQUIRED clp)
target_include_directories(\${PROJECT_NAME} PRIVATE \${CLP_INCLUDE_DIRS})
target_link_libraries(\${PROJECT_NAME} PRIVATE \${CLP_LIBRARIES})
`;
    case "cbc":
      return `# CBC dependency (includes CLP)
find_package(PkgConfig REQUIRED)
pkg_check_modules(CBC REQUIRED cbc)
target_include_directories(\${PROJECT_NAME} PRIVATE \${CBC_INCLUDE_DIRS})
target_link_libraries(\${PROJECT_NAME} PRIVATE \${CBC_LIBRARIES})
`;
    case "ipopt":
      return `# IPOPT dependency
find_package(PkgConfig REQUIRED)
pkg_check_modules(IPOPT REQUIRED ipopt)
target_include_directories(\${PROJECT_NAME} PRIVATE \${IPOPT_INCLUDE_DIRS})
target_link_libraries(\${PROJECT_NAME} PRIVATE \${IPOPT_LIBRARIES})
`;
    default:
      return "";
  }
}

/** Format a number as a C double literal. */
function formatCDouble(value: number): string {
  if (!isFinite(value)) {
    if (value === Infinity) return "1e30";
    if (value === -Infinity) return "-1e30";
    return "NAN";
  }
  const s = value.toString();
  if (!s.includes(".") && !s.includes("e") && !s.includes("E")) {
    return s + ".0";
  }
  return s;
}
