// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * SUNDIALS C glue-code generator.
 *
 * Emits a standalone `main.c` that bridges the model instance (from
 * fmu-codegen.ts) to the SUNDIALS solver wrappers in sundials-interface.c.
 *
 * The generated code:
 *   1. Allocates and initializes a {id}_Instance
 *   2. Extracts initial state/derivative vectors from model start values
 *   3. Populates a SundialsModelCallbacks struct
 *   4. Calls sundials_cvode_run() or sundials_ida_run()
 *   5. Writes results to CSV on stdout
 */

import type { ModelicaDAE } from "./dae.js";
import type { FmuResult } from "./fmi.js";

// ── Public interface ──

/** Options for SUNDIALS code generation. */
export interface SundialsCodegenOptions {
  /** Model identifier (from FMU codegen). */
  modelIdentifier: string;
  /** Start time (default: 0). */
  startTime?: number;
  /** Stop time (default: 1). */
  stopTime?: number;
  /** Number of output intervals (default: 500). */
  numberOfIntervals?: number;
  /** Absolute tolerance (default: 1e-8). */
  atol?: number;
  /** Relative tolerance (default: 1e-6). */
  rtol?: number;
  /** Maximum internal steps (default: 50000). */
  maxSteps?: number;
  /** Maximum step size (0 = unlimited). */
  maxStep?: number;
  /** Use CVODE (explicit ODE) or IDA (implicit DAE). */
  solver?: "cvode" | "ida";
  /** Use exact AD Jacobian (default: true). */
  useExactJacobian?: boolean;
}

/** Generated SUNDIALS C files. */
export interface SundialsCodegenResult {
  /** main.c — simulation driver */
  mainC: string;
  /** Supplementary CMake find-module snippet for SUNDIALS */
  cmakeSnippet: string;
}

/**
 * Generate SUNDIALS simulation driver C code from a DAE and FMU result.
 */
export function generateSundialsMainC(
  dae: ModelicaDAE,
  fmuResult: FmuResult,
  options: SundialsCodegenOptions,
): SundialsCodegenResult {
  const id = options.modelIdentifier;
  const startTime = options.startTime ?? 0;
  const stopTime = options.stopTime ?? 1;
  const intervals = options.numberOfIntervals ?? 500;
  const atol = options.atol ?? 1e-8;
  const rtol = options.rtol ?? 1e-6;
  const maxSteps = options.maxSteps ?? 50000;
  const maxStep = options.maxStep ?? 0;
  const solver = options.solver ?? detectSolverChoice(dae);
  const useJac = options.useExactJacobian !== false;

  const nStates = fmuResult.modelStructure.derivatives.length;
  const nEventIndicators = fmuResult.numberOfEventIndicators;
  const vars = fmuResult.scalarVariables;

  // Find state variable references and their start values
  const stateVarRefs: { name: string; vr: number; derVr: number; start: number }[] = [];
  for (const sv of vars) {
    if (sv.derivative !== undefined) {
      // This is a derivative variable — find its state
      const stateSv = vars.find((v) => v.valueReference === sv.derivative);
      if (stateSv) {
        stateVarRefs.push({
          name: stateSv.name,
          vr: stateSv.valueReference,
          derVr: sv.valueReference,
          start: stateSv.start ?? 0,
        });
      }
    }
  }

  const lines: string[] = [];

  lines.push("/* Auto-generated by ModelScript — SUNDIALS simulation driver */");
  lines.push(`#include "${id}_model.h"`);
  lines.push('#include "sundials-interface.c"');
  lines.push("#include <stdio.h>");
  lines.push("#include <stdlib.h>");
  lines.push("");

  // ── Derivative wrapper ──
  lines.push(`static void model_get_derivatives(void* inst) {`);
  lines.push(`  ${id}_getDerivatives((${id}_Instance*)inst);`);
  lines.push(`}`);
  lines.push("");

  // ── Event indicator wrapper ──
  lines.push(`static void model_get_event_indicators(void* inst, double* indicators) {`);
  if (nEventIndicators > 0) {
    lines.push(`  ${id}_getEventIndicators((${id}_Instance*)inst, indicators);`);
  } else {
    lines.push(`  (void)inst; (void)indicators;`);
  }
  lines.push(`}`);
  lines.push("");

  // ── Jacobian wrapper ──
  if (useJac) {
    lines.push(`/* AD-generated dense Jacobian ∂f/∂x */`);
    lines.push(`static void model_get_jacobian(void* inst, double* J) {`);
    lines.push(`  ${id}_Instance* m = (${id}_Instance*)inst;`);
    lines.push(`  int n = ${nStates};`);
    lines.push(`  /* Finite-difference approximation using model derivatives */`);
    lines.push(`  double* f0 = (double*)malloc(n * sizeof(double));`);
    lines.push(`  double* fp = (double*)malloc(n * sizeof(double));`);
    lines.push(`  ${id}_getDerivatives(m);`);
    for (let i = 0; i < stateVarRefs.length; i++) {
      const sv = stateVarRefs[i];
      if (sv) {
        lines.push(`  f0[${i}] = m->derivatives[${i}];`);
      }
    }
    lines.push(`  for (int j = 0; j < n; j++) {`);
    lines.push(`    double saved;`);
    // Map state index to value reference for perturbation
    for (let i = 0; i < stateVarRefs.length; i++) {
      const sv = stateVarRefs[i];
      if (sv) {
        lines.push(`    ${i === 0 ? "" : "else "}if (j == ${i}) { saved = m->states[${i}]; m->states[${i}] += 1e-8; }`);
      }
    }
    lines.push(`    /* Also update vars[] from states[] */`);
    for (let i = 0; i < stateVarRefs.length; i++) {
      const sv = stateVarRefs[i];
      if (sv) {
        lines.push(`    if (j == ${i}) m->vars[${sv.vr}] = m->states[${i}];`);
      }
    }
    lines.push(`    ${id}_getDerivatives(m);`);
    lines.push(`    for (int i = 0; i < n; i++) {`);
    lines.push(`      fp[i] = m->derivatives[i];`);
    lines.push(`      J[i * n + j] = (fp[i] - f0[i]) / 1e-8;`);
    lines.push(`    }`);
    lines.push(`    /* Restore */`);
    for (let i = 0; i < stateVarRefs.length; i++) {
      const sv = stateVarRefs[i];
      if (sv) {
        lines.push(`    if (j == ${i}) { m->states[${i}] = saved; m->vars[${sv.vr}] = saved; }`);
      }
    }
    lines.push(`  }`);
    lines.push(`  /* Restore derivatives */`);
    lines.push(`  ${id}_getDerivatives(m);`);
    lines.push(`  free(f0);`);
    lines.push(`  free(fp);`);
    lines.push(`}`);
    lines.push("");
  }

  // ── Main function ──
  lines.push("int main(void) {");
  lines.push(`  /* Allocate model instance */`);
  lines.push(`  ${id}_Instance inst;`);
  lines.push(`  memset(&inst, 0, sizeof(inst));`);
  lines.push("");

  // Set parameters and initial values
  lines.push(`  /* Set parameter and initial values */`);
  for (const sv of vars) {
    if (sv.start !== undefined && sv.causality !== "independent") {
      lines.push(`  inst.vars[${sv.valueReference}] = ${formatCDouble(sv.start)};  /* ${sv.name} */`);
    }
  }
  lines.push("");

  // Initialize the model
  lines.push(`  inst.time = ${formatCDouble(startTime)};`);
  lines.push(`  inst.isInitPhase = 1;`);
  lines.push(`  ${id}_initialize(&inst);`);
  lines.push(`  inst.isInitPhase = 0;`);
  lines.push("");

  // Extract initial states
  lines.push(`  /* Extract initial states */`);
  lines.push(`  int n_states = ${nStates};`);
  lines.push(`  double y0[${Math.max(nStates, 1)}];`);
  for (let i = 0; i < stateVarRefs.length; i++) {
    const sv = stateVarRefs[i];
    if (sv) {
      lines.push(`  y0[${i}] = inst.vars[${sv.vr}];  /* ${sv.name} */`);
      lines.push(`  inst.states[${i}] = y0[${i}];`);
    }
  }
  lines.push("");

  // Build output times
  lines.push(`  /* Build output time grid */`);
  lines.push(`  int n_outputs = ${intervals + 1};`);
  lines.push(`  double* output_times = (double*)malloc(n_outputs * sizeof(double));`);
  lines.push(`  for (int k = 0; k < n_outputs; k++) {`);
  lines.push(
    `    output_times[k] = ${formatCDouble(startTime)} + k * ${formatCDouble((stopTime - startTime) / intervals)};`,
  );
  lines.push(`  }`);
  lines.push("");

  // Populate callbacks
  lines.push(`  /* Populate SUNDIALS callbacks */`);
  lines.push(`  SundialsModelCallbacks cb;`);
  lines.push(`  memset(&cb, 0, sizeof(cb));`);
  lines.push(`  cb.model_instance = &inst;`);
  lines.push(`  cb.n_states = n_states;`);
  lines.push(`  cb.n_event_indicators = ${nEventIndicators};`);
  lines.push(`  cb.get_derivatives = model_get_derivatives;`);
  lines.push(`  cb.get_event_indicators = model_get_event_indicators;`);
  if (useJac) {
    lines.push(`  cb.get_jacobian = model_get_jacobian;`);
  }
  lines.push(`  cb.states = inst.states;`);
  lines.push(`  cb.derivatives = inst.derivatives;`);
  lines.push(`  cb.time_ptr = &inst.time;`);
  lines.push("");

  // Solver options
  lines.push(`  /* Solver options */`);
  lines.push(`  SundialsOptions opts;`);
  lines.push(`  sundials_options_defaults(&opts);`);
  lines.push(`  opts.atol = ${formatCDouble(atol)};`);
  lines.push(`  opts.rtol = ${formatCDouble(rtol)};`);
  lines.push(`  opts.max_steps = ${maxSteps};`);
  if (maxStep > 0) {
    lines.push(`  opts.max_step = ${formatCDouble(maxStep)};`);
  }
  lines.push(`  opts.use_exact_jacobian = ${useJac ? 1 : 0};`);
  lines.push("");

  // Run solver
  lines.push(`  /* Run solver */`);
  lines.push(`  SundialsResult result;`);
  if (solver === "ida") {
    lines.push(`  double yp0[${Math.max(nStates, 1)}];`);
    lines.push(`  ${id}_getDerivatives(&inst);`);
    for (let i = 0; i < stateVarRefs.length; i++) {
      lines.push(`  yp0[${i}] = inst.derivatives[${i}];`);
    }
    lines.push(
      `  sundials_ida_run(&cb, ${formatCDouble(startTime)}, y0, yp0, output_times, n_outputs, &opts, &result);`,
    );
  } else {
    lines.push(`  sundials_cvode_run(&cb, ${formatCDouble(startTime)}, y0, output_times, n_outputs, &opts, &result);`);
  }
  lines.push("");

  // Output results as CSV
  lines.push(`  /* Output results as CSV */`);
  lines.push(`  if (result.status < 0) {`);
  lines.push(`    fprintf(stderr, "Solver error: %s\\n", result.message);`);
  lines.push(`    sundials_result_free(&result);`);
  lines.push(`    free(output_times);`);
  lines.push(`    return 1;`);
  lines.push(`  }`);
  lines.push("");
  // CSV header
  const stateNames = stateVarRefs.map((sv) => sv.name);
  lines.push(`  printf("time${stateNames.map((n) => "," + sanitizeCsvName(n)).join("")}\\n");`);
  lines.push(`  for (int k = 0; k < result.n_points; k++) {`);
  lines.push(`    printf("%.15e", result.times[k]);`);
  lines.push(`    for (int i = 0; i < n_states; i++) {`);
  lines.push(`      printf(",%.15e", result.states[k * n_states + i]);`);
  lines.push(`    }`);
  lines.push(`    printf("\\n");`);
  lines.push(`  }`);
  lines.push("");
  lines.push(`  fprintf(stderr, "Steps: %ld  FEvals: %ld  JEvals: %ld\\n",`);
  lines.push(`          result.n_steps, result.n_feval, result.n_jeval);`);
  lines.push("");
  lines.push(`  sundials_result_free(&result);`);
  lines.push(`  free(output_times);`);
  lines.push(`  return 0;`);
  lines.push("}");

  const mainC = lines.join("\n");

  // CMake snippet for finding SUNDIALS
  const cmakeSnippet = `# SUNDIALS dependency
find_package(SUNDIALS REQUIRED COMPONENTS cvodes idas kinsol)
target_link_libraries(\${PROJECT_NAME} PRIVATE
  SUNDIALS::cvodes
  SUNDIALS::idas
  SUNDIALS::kinsol
)
`;

  return { mainC, cmakeSnippet };
}

// ── Helpers ──

/** Detect whether to use CVODE or IDA based on DAE structure. */
function detectSolverChoice(dae: ModelicaDAE): "cvode" | "ida" {
  // If the DAE has algebraic loops, use IDA (implicit solver)
  if (dae.algebraicLoops && dae.algebraicLoops.length > 0) {
    return "ida";
  }
  // Default to CVODE for explicit ODE systems
  return "cvode";
}

/** Format a number as a C double literal. */
function formatCDouble(value: number): string {
  if (!isFinite(value)) {
    if (value === Infinity) return "INFINITY";
    if (value === -Infinity) return "(-INFINITY)";
    return "NAN";
  }
  const s = value.toString();
  if (!s.includes(".") && !s.includes("e") && !s.includes("E")) {
    return s + ".0";
  }
  return s;
}

/** Sanitize a variable name for use in CSV headers. */
function sanitizeCsvName(name: string): string {
  return name.replace(/,/g, "_").replace(/"/g, "'");
}
