/* eslint-disable */
// =============================================================================
// GENERATED by @modelscript/polyglot — do not edit manually.
// Language: modelica
// =============================================================================

import type { QueryDB, SpecializationArgs, SymbolEntry, SymbolId } from "@modelscript/polyglot/runtime";
import type { SemanticVisitor } from "@modelscript/polyglot/semantic-node";
import { GenericNode, SemanticNode } from "@modelscript/polyglot/semantic-node";
import type { ModelicaModArgs } from "./modification-args.js";

export class ClassDefinition extends SemanticNode {
  get kind(): string {
    return "Class";
  }

  // --- CST Fields ---
  /** Field: redeclare */
  get redeclare(): string | null {
    return this.field("redeclare");
  }
  /** Field: final */
  get final(): string | null {
    return this.field("final");
  }
  /** Field: inner */
  get inner(): string | null {
    return this.field("inner");
  }
  /** Field: outer */
  get outer(): string | null {
    return this.field("outer");
  }
  /** Field: replaceable */
  get replaceable(): string | null {
    return this.field("replaceable");
  }
  /** Field: encapsulated */
  get encapsulated(): string | null {
    return this.field("encapsulated");
  }
  /** Field: classPrefixes */
  get classPrefixes(): string | null {
    return this.field("classPrefixes");
  }
  /** Field: classSpecifier */
  get classSpecifier(): string | null {
    return this.field("classSpecifier");
  }
  /** Field: constrainingClause */
  get constrainingClause(): string | null {
    return this.field("constrainingClause");
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #diagnostics: string[] | undefined = undefined;

  get diagnostics(): string[] {
    if (this.#diagnostics !== undefined) return this.#diagnostics;
    return this.attribute("diagnostics") ?? (undefined as unknown as string[]);
  }

  set diagnostics(value: string[]) {
    this.#diagnostics = value;
  }

  #isPartial: boolean | undefined = false;

  get isPartial(): boolean {
    if (this.#isPartial !== undefined) return this.#isPartial;
    return (this.attribute("isPartial") as unknown as boolean) ?? false;
  }

  set isPartial(value: boolean) {
    this.#isPartial = value;
  }

  #isEncapsulated: boolean | undefined = false;

  get isEncapsulated(): boolean {
    if (this.#isEncapsulated !== undefined) return this.#isEncapsulated;
    return (this.attribute("isEncapsulated") as unknown as boolean) ?? false;
  }

  set isEncapsulated(value: boolean) {
    this.#isEncapsulated = value;
  }

  #isReplaceable: boolean | undefined = false;

  get isReplaceable(): boolean {
    if (this.#isReplaceable !== undefined) return this.#isReplaceable;
    return (this.attribute("isReplaceable") as unknown as boolean) ?? false;
  }

  set isReplaceable(value: boolean) {
    this.#isReplaceable = value;
  }

  #isExpandable: boolean | undefined = false;

  get isExpandable(): boolean {
    if (this.#isExpandable !== undefined) return this.#isExpandable;
    return (this.attribute("isExpandable") as unknown as boolean) ?? false;
  }

  set isExpandable(value: boolean) {
    this.#isExpandable = value;
  }

  #isFinal: boolean | undefined = false;

  get isFinal(): boolean {
    if (this.#isFinal !== undefined) return this.#isFinal;
    return (this.attribute("isFinal") as unknown as boolean) ?? false;
  }

  set isFinal(value: boolean) {
    this.#isFinal = value;
  }

  #isRedeclare: boolean | undefined = false;

  get isRedeclare(): boolean {
    if (this.#isRedeclare !== undefined) return this.#isRedeclare;
    return (this.attribute("isRedeclare") as unknown as boolean) ?? false;
  }

  set isRedeclare(value: boolean) {
    this.#isRedeclare = value;
  }

  // --- Computed Properties (query-backed) ---
  get members(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("members");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get nestedClasses(): ClassDefinition[] {
    const entries = this.query<SymbolEntry[]>("nestedClasses");
    return entries.map((e) => wrapEntry(e, this.db)) as ClassDefinition[];
  }

  get components(): ComponentDeclaration[] {
    const entries = this.query<SymbolEntry[]>("components");
    return entries.map((e) => wrapEntry(e, this.db)) as ComponentDeclaration[];
  }

  get extendsClasses(): ExtendsClause[] {
    const entries = this.query<SymbolEntry[]>("extendsClasses");
    return entries.map((e) => wrapEntry(e, this.db)) as ExtendsClause[];
  }

  get imports(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("imports");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get inputParameters(): ComponentDeclaration[] {
    const entries = this.query<SymbolEntry[]>("inputParameters");
    return entries.map((e) => wrapEntry(e, this.db)) as ComponentDeclaration[];
  }

  get outputParameters(): ComponentDeclaration[] {
    const entries = this.query<SymbolEntry[]>("outputParameters");
    return entries.map((e) => wrapEntry(e, this.db)) as ComponentDeclaration[];
  }

  get parameters(): ComponentDeclaration[] {
    const entries = this.query<SymbolEntry[]>("parameters");
    return entries.map((e) => wrapEntry(e, this.db)) as ComponentDeclaration[];
  }

  get constants(): ComponentDeclaration[] {
    const entries = this.query<SymbolEntry[]>("constants");
    return entries.map((e) => wrapEntry(e, this.db)) as ComponentDeclaration[];
  }

  get connectEquations(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("connectEquations");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get allElements(): SemanticNode[] {
    const entries = this.query<SymbolEntry[]>("allElements");
    return entries.map((e) => wrapEntry(e, this.db)) as SemanticNode[];
  }

  get isConnector(): boolean {
    return this.query<boolean>("isConnector");
  }

  get resolveModification(): unknown {
    return this.query<unknown>("resolveModification");
  }

  get resolveSimpleName(): (name: string, encapsulated?: boolean) => SemanticNode | null {
    return this.query<(name: string, encapsulated?: boolean) => SemanticNode | null>("resolveSimpleName");
  }

  get resolveName(): (qualifiedName: string) => SemanticNode | null {
    return this.query<(qualifiedName: string) => SemanticNode | null>("resolveName");
  }

  get instantiate(): SymbolId[] {
    return this.query<SymbolId[]>("instantiate");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "node",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "header" },
          { tagName: "line", selector: "separator" },
          { tagName: "text", selector: "label" },
        ],
        attrs: {
          body: { fill: "#e3f2fd", stroke: "#1565c0", strokeWidth: 2, rx: 4, ry: 4 },
          header: {
            text: "{{classPrefixes}}",
            fill: "#1565c0",
            fontSize: 10,
            textAnchor: "middle",
            refX: 0.5,
            refY: 14,
          },
          separator: { x1: 0, y1: 24, x2: "100%", y2: 24, stroke: "#1565c0", strokeWidth: 1 },
          label: {
            text: "{{name}}",
            fill: "#0d47a1",
            fontSize: 14,
            fontWeight: "bold",
            textAnchor: "middle",
            refX: 0.5,
            refY: 40,
          },
        },
        size: { width: 200, height: 60 },
        ports: {
          groups: {
            in: { position: "left", attrs: { circle: { r: 5, fill: "#43a047", stroke: "#fff", strokeWidth: 1.5 } } },
            out: { position: "right", attrs: { circle: { r: 5, fill: "#ef6c00", stroke: "#fff", strokeWidth: 1.5 } } },
          },
        },
        portQuery: "components",
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): ClassDefinition {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new ClassDefinition(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: ModelicaVisitor<R, A>, arg?: A): R {
    return visitor.visitClassDefinition(this, arg);
  }
}

export class EnumerationLiteral extends SemanticNode {
  get kind(): string {
    return "EnumerationLiteral";
  }

  // --- CST Fields ---
  /** Field: identifier */
  get identifier(): string | null {
    return this.field("identifier");
  }
  /** Field: description */
  get description(): string | null {
    return this.field("description");
  }
  /** Field: annotationClause */
  get annotationClause(): string | null {
    return this.field("annotationClause");
  }

  // --- Visitor ---
  accept<R, A>(visitor: ModelicaVisitor<R, A>, arg?: A): R {
    return visitor.visitEnumerationLiteral(this, arg);
  }
}

export class SimpleImportClause extends SemanticNode {
  get kind(): string {
    return "Import";
  }

  // --- CST Fields ---
  /** Field: shortName */
  get shortName(): string | null {
    return this.field("shortName");
  }
  /** Field: packageName */
  get packageName(): string | null {
    return this.field("packageName");
  }
  /** Field: description */
  get description(): string | null {
    return this.field("description");
  }
  /** Field: annotationClause */
  get annotationClause(): string | null {
    return this.field("annotationClause");
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #importKind: "simple" | undefined = undefined;

  get importKind(): "simple" {
    if (this.#importKind !== undefined) return this.#importKind;
    return this.attribute("importKind") ?? (undefined as unknown as "simple");
  }

  set importKind(value: "simple") {
    this.#importKind = value;
  }

  // --- Visitor ---
  accept<R, A>(visitor: ModelicaVisitor<R, A>, arg?: A): R {
    return visitor.visitSimpleImportClause(this, arg);
  }
}

export class CompoundImportClause extends SemanticNode {
  get kind(): string {
    return "Import";
  }

  // --- CST Fields ---
  /** Field: packageName */
  get packageName(): string | null {
    return this.field("packageName");
  }
  /** Field: importName */
  get importName(): string | null {
    return this.field("importName");
  }
  /** Field: description */
  get description(): string | null {
    return this.field("description");
  }
  /** Field: annotationClause */
  get annotationClause(): string | null {
    return this.field("annotationClause");
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #importKind: "compound" | undefined = undefined;

  get importKind(): "compound" {
    if (this.#importKind !== undefined) return this.#importKind;
    return this.attribute("importKind") ?? (undefined as unknown as "compound");
  }

  set importKind(value: "compound") {
    this.#importKind = value;
  }

  // --- Visitor ---
  accept<R, A>(visitor: ModelicaVisitor<R, A>, arg?: A): R {
    return visitor.visitCompoundImportClause(this, arg);
  }
}

export class UnqualifiedImportClause extends SemanticNode {
  get kind(): string {
    return "Import";
  }

  // --- CST Fields ---
  /** Field: packageName */
  get packageName(): string | null {
    return this.field("packageName");
  }
  /** Field: description */
  get description(): string | null {
    return this.field("description");
  }
  /** Field: annotationClause */
  get annotationClause(): string | null {
    return this.field("annotationClause");
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #importKind: "unqualified" | undefined = undefined;

  get importKind(): "unqualified" {
    if (this.#importKind !== undefined) return this.#importKind;
    return this.attribute("importKind") ?? (undefined as unknown as "unqualified");
  }

  set importKind(value: "unqualified") {
    this.#importKind = value;
  }

  // --- Visitor ---
  accept<R, A>(visitor: ModelicaVisitor<R, A>, arg?: A): R {
    return visitor.visitUnqualifiedImportClause(this, arg);
  }
}

export class ExtendsClause extends SemanticNode {
  get kind(): string {
    return "Extends";
  }

  // --- CST Fields ---
  /** Field: typeSpecifier */
  get typeSpecifier(): string | null {
    return this.field("typeSpecifier");
  }
  /** Field: classOrInheritanceModification */
  get classOrInheritanceModification(): string | null {
    return this.field("classOrInheritanceModification");
  }
  /** Field: annotationClause */
  get annotationClause(): string | null {
    return this.field("annotationClause");
  }

  // --- Metadata ---

  // --- Mutable Properties (CST default + runtime override) ---
  #visibility: string | null | undefined = undefined;

  get visibility(): string | null {
    if (this.#visibility !== undefined) return this.#visibility;
    return this.attribute("visibility") ?? (undefined as unknown as string | null);
  }

  set visibility(value: string | null) {
    this.#visibility = value;
  }

  // --- Computed Properties (query-backed) ---
  get resolvedBaseClass(): SemanticNode | null {
    const entry = this.query<SymbolEntry | null>("resolvedBaseClass");
    return entry ? (wrapEntry(entry, this.db) as SemanticNode | null) : (null as unknown as SemanticNode | null);
  }

  get effectiveModification(): unknown {
    return this.query<unknown>("effectiveModification");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "edge",
      edge: {
        shape: "edge",
        attrs: {
          line: {
            stroke: "#7b1fa2",
            strokeWidth: 1.5,
            strokeDasharray: "6 3",
            targetMarker: { name: "block", size: 10 },
          },
        },
        labels: [
          {
            attrs: {
              text: { text: "??extends??", fill: "#7b1fa2", fontSize: 11 },
              rect: { fill: "#fff", stroke: "none", rx: 3, ry: 3 },
            },
            position: { distance: 0.5, offset: 0 },
          },
        ],
        router: "manhattan",
        connector: "rounded",
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): ExtendsClause {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new ExtendsClause(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: ModelicaVisitor<R, A>, arg?: A): R {
    return visitor.visitExtendsClause(this, arg);
  }
}

export class ComponentDeclaration extends SemanticNode {
  get kind(): string {
    return "Component";
  }

  // --- CST Fields ---
  /** Field: redeclare */
  get redeclare(): string | null {
    return this.field("redeclare");
  }
  /** Field: final */
  get final(): string | null {
    return this.field("final");
  }
  /** Field: inner */
  get inner(): string | null {
    return this.field("inner");
  }
  /** Field: outer */
  get outer(): string | null {
    return this.field("outer");
  }
  /** Field: replaceable */
  get replaceable(): string | null {
    return this.field("replaceable");
  }
  /** Field: flow */
  get flow(): string | null {
    return this.field("flow");
  }
  /** Field: variability */
  get variability(): string | null {
    return this.field("variability");
  }
  /** Field: causality */
  get causality(): string | null {
    return this.field("causality");
  }
  /** Field: typeSpecifier */
  get typeSpecifier(): string | null {
    return this.field("typeSpecifier");
  }
  /** Field: arraySubscripts */
  get arraySubscripts(): string | null {
    return this.field("arraySubscripts");
  }
  /** Field: componentDeclaration */
  get componentDeclaration(): string | null {
    return this.field("componentDeclaration");
  }
  /** Field: constrainingClause */
  get constrainingClause(): string | null {
    return this.field("constrainingClause");
  }

  // --- Metadata ---
  get modification(): string | null {
    return this.attribute("modification");
  }

  // --- Mutable Properties (CST default + runtime override) ---
  #isFinal: boolean | undefined = false;

  get isFinal(): boolean {
    if (this.#isFinal !== undefined) return this.#isFinal;
    return (this.attribute("isFinal") as unknown as boolean) ?? false;
  }

  set isFinal(value: boolean) {
    this.#isFinal = value;
  }

  #isInner: boolean | undefined = false;

  get isInner(): boolean {
    if (this.#isInner !== undefined) return this.#isInner;
    return (this.attribute("isInner") as unknown as boolean) ?? false;
  }

  set isInner(value: boolean) {
    this.#isInner = value;
  }

  #isOuter: boolean | undefined = false;

  get isOuter(): boolean {
    if (this.#isOuter !== undefined) return this.#isOuter;
    return (this.attribute("isOuter") as unknown as boolean) ?? false;
  }

  set isOuter(value: boolean) {
    this.#isOuter = value;
  }

  #isReplaceable: boolean | undefined = false;

  get isReplaceable(): boolean {
    if (this.#isReplaceable !== undefined) return this.#isReplaceable;
    return (this.attribute("isReplaceable") as unknown as boolean) ?? false;
  }

  set isReplaceable(value: boolean) {
    this.#isReplaceable = value;
  }

  #isProtected: boolean | undefined = false;

  get isProtected(): boolean {
    if (this.#isProtected !== undefined) return this.#isProtected;
    return (this.attribute("isProtected") as unknown as boolean) ?? false;
  }

  set isProtected(value: boolean) {
    this.#isProtected = value;
  }

  #flowPrefix: string | null | undefined = undefined;

  get flowPrefix(): string | null {
    if (this.#flowPrefix !== undefined) return this.#flowPrefix;
    return this.attribute("flowPrefix") ?? (undefined as unknown as string | null);
  }

  set flowPrefix(value: string | null) {
    this.#flowPrefix = value;
  }

  #isRedeclare: boolean | undefined = false;

  get isRedeclare(): boolean {
    if (this.#isRedeclare !== undefined) return this.#isRedeclare;
    return (this.attribute("isRedeclare") as unknown as boolean) ?? false;
  }

  set isRedeclare(value: boolean) {
    this.#isRedeclare = value;
  }

  // --- Computed Properties (query-backed) ---
  get resolvedType(): SemanticNode | null {
    const entry = this.query<SymbolEntry | null>("resolvedType");
    return entry ? (wrapEntry(entry, this.db) as SemanticNode | null) : (null as unknown as SemanticNode | null);
  }

  get effectiveModification(): ModelicaModArgs | null {
    const entry = this.query<SymbolEntry | null>("effectiveModification");
    return entry
      ? (wrapEntry(entry, this.db) as unknown as ModelicaModArgs | null)
      : (null as unknown as ModelicaModArgs | null);
  }

  get isConnectorType(): boolean {
    return this.query<boolean>("isConnectorType");
  }

  get classInstance(): SymbolId | null {
    return this.query<SymbolId | null>("classInstance");
  }

  get arrayDimensions(): Array<
    | { kind: "literal"; value: number }
    | { kind: "flexible" }
    | { kind: "expression"; cstBytes: readonly [number, number] }
  > | null {
    return this.query<Array<
      | { kind: "literal"; value: number }
      | { kind: "flexible" }
      | { kind: "expression"; cstBytes: readonly [number, number] }
    > | null>("arrayDimensions");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "port-owner",
      node: {
        shape: "rect",
        markup: [
          { tagName: "rect", selector: "body" },
          { tagName: "text", selector: "label" },
        ],
        attrs: {
          body: { fill: "#e8f5e9", stroke: "#43a047", strokeWidth: 1.5, rx: 2, ry: 2 },
          label: { text: "{{name}}", fill: "#1b5e20", fontSize: 11, textAnchor: "middle", refX: 0.5, refY: 0.5 },
        },
        size: { width: 120, height: 30 },
      },
    };
  }

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): ComponentDeclaration {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new ComponentDeclaration(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: ModelicaVisitor<R, A>, arg?: A): R {
    return visitor.visitComponentDeclaration(this, arg);
  }
}

export class ShortClassDefinition extends SemanticNode {
  get kind(): string {
    return "Class";
  }

  // --- CST Fields ---
  /** Field: classPrefixes */
  get classPrefixes(): string | null {
    return this.field("classPrefixes");
  }
  /** Field: classSpecifier */
  get classSpecifier(): string | null {
    return this.field("classSpecifier");
  }
  /** Field: constrainingClause */
  get constrainingClause(): string | null {
    return this.field("constrainingClause");
  }

  // --- Metadata ---

  // --- Clone / Specialize ---
  clone<T>(args: SpecializationArgs<T>): ShortClassDefinition {
    const virtualId = this.specialize(args);
    const virtualEntry = this.db.symbol(virtualId)!;
    return new ShortClassDefinition(virtualEntry, this.db);
  }

  // --- Visitor ---
  accept<R, A>(visitor: ModelicaVisitor<R, A>, arg?: A): R {
    return visitor.visitShortClassDefinition(this, arg);
  }
}

export class ConnectEquation extends SemanticNode {
  get kind(): string {
    return "ConnectEquation";
  }

  // --- CST Fields ---
  /** Field: componentReference1 */
  get componentReference1(): string | null {
    return this.field("componentReference1");
  }
  /** Field: componentReference2 */
  get componentReference2(): string | null {
    return this.field("componentReference2");
  }
  /** Field: description */
  get description(): string | null {
    return this.field("description");
  }
  /** Field: annotationClause */
  get annotationClause(): string | null {
    return this.field("annotationClause");
  }

  // --- Metadata ---
  get ref1(): string | null {
    return this.attribute("ref1");
  }
  get ref2(): string | null {
    return this.attribute("ref2");
  }

  // --- Computed Properties (query-backed) ---
  get validateConnect(): { valid: boolean; reason: string | null } {
    return this.query<{ valid: boolean; reason: string | null }>("validateConnect");
  }

  // --- Graphics ---
  get graphics() {
    return {
      role: "edge",
      edge: {
        shape: "edge",
        source: "componentReference1",
        target: "componentReference2",
        attrs: { line: { stroke: "#c62828", strokeWidth: 2, targetMarker: "classic" } },
        labels: [
          {
            attrs: {
              text: { text: "connect", fill: "#c62828", fontSize: 10 },
              rect: { fill: "#fff", stroke: "none", rx: 3, ry: 3 },
            },
            position: { distance: 0.5, offset: 0 },
          },
        ],
        router: "manhattan",
        connector: "rounded",
      },
    };
  }

  // --- Visitor ---
  accept<R, A>(visitor: ModelicaVisitor<R, A>, arg?: A): R {
    return visitor.visitConnectEquation(this, arg);
  }
}

/**
 * Visitor interface for all generated semantic node types.
 * Extends the base SemanticVisitor with typed visit methods.
 */
export interface ModelicaVisitor<R, A = void> extends SemanticVisitor<R, A> {
  visitClassDefinition(node: ClassDefinition, arg?: A): R;
  visitEnumerationLiteral(node: EnumerationLiteral, arg?: A): R;
  visitSimpleImportClause(node: SimpleImportClause, arg?: A): R;
  visitCompoundImportClause(node: CompoundImportClause, arg?: A): R;
  visitUnqualifiedImportClause(node: UnqualifiedImportClause, arg?: A): R;
  visitExtendsClause(node: ExtendsClause, arg?: A): R;
  visitComponentDeclaration(node: ComponentDeclaration, arg?: A): R;
  visitShortClassDefinition(node: ShortClassDefinition, arg?: A): R;
  visitConnectEquation(node: ConnectEquation, arg?: A): R;
}

/**
 * Wrap a SymbolEntry into its typed SemanticNode subclass.
 * Dispatches by entry.kind to the correct generated class.
 */
export function wrapEntry(entry: SymbolEntry, db: QueryDB): SemanticNode {
  switch (entry.kind) {
    case "Class":
      return new ClassDefinition(entry, db);
    case "EnumerationLiteral":
      return new EnumerationLiteral(entry, db);
    case "Import":
      return new SimpleImportClause(entry, db);
    case "Import":
      return new CompoundImportClause(entry, db);
    case "Import":
      return new UnqualifiedImportClause(entry, db);
    case "Extends":
      return new ExtendsClause(entry, db);
    case "Component":
      return new ComponentDeclaration(entry, db);
    case "Class":
      return new ShortClassDefinition(entry, db);
    case "ConnectEquation":
      return new ConnectEquation(entry, db);
    default:
      return new GenericNode(entry, db);
  }
}
