// =============================================================================
// GENERATED by @modelscript/polyglot — do not edit manually.
// Language: modelica
// Semantic diffing configuration for automated PLM and impact analysis.
// =============================================================================

import type { DiffConfig } from "@modelscript/polyglot";

export const diffConfig: Record<string, DiffConfig> = {
  ComponentClause: {
    ignore: ["annotationClause", "description"],
    minor: ["visibility"],
    breaking: ["typeSpecifier", "causality", "isParameter"],
  },
};
