import type { GrammarConflictDiagnostic } from "./automata.js";
import { generateJavaScriptWrapper } from "./bindings/javascript/index.js";
import type { GeneratedFile } from "./codegen/parser.js";
import { generateParser, generateParserTables } from "./codegen/parser.js";
import { generateTextMate } from "./codegen/textmate.js";
import { LanguageOptions, SOURCE_PATH_SYMBOL, SOURCE_TEXT_SYMBOL } from "./dsl.js";

export type { GrammarConflictDiagnostic } from "./automata.js";

/**
 * Options for configuring language parser build and source AST extraction.
 */
export interface BuildOptions {
  /** Source file path for Direct Source AST extraction */
  sourcePath?: string;
  /** Source code text for in-memory Direct Source AST extraction */
  sourceText?: string;
}

/**
 * Metadata about the generated grammar parser.
 */
export interface ParserResult {
  /** The name of the language. */
  name: string;
  /** The root start symbol of the grammar. */
  startSymbol: string;
  /** An array of all non-terminal symbols extracted from the grammar. */
  nonTerminals: string[];
  /** An array of all terminal symbols (tokens) extracted from the grammar. */
  terminals: string[];
  /** The total number of states in the generated GLR action table. */
  statesCount: number;
}

/**
 * The full build output generated by the ModelScript language compiler.
 */
export interface BuildResult {
  /** Metadata and statistics about the generated parser. */
  parserInfo: ParserResult;
  /** The generated AssemblyScript files (action/goto tables, automata, grammar) to be compiled to WASM. */
  assemblyScriptFiles: GeneratedFile[];
  /** The generated JavaScript wrapper code and TypeScript typings to interface with the WASM parser. */
  javascriptWrapper: {
    js: string;
    dts: string;
    syntaxNames?: string[];
    fieldNames?: string[];
    semanticLegend?: { tokenTypes: string[]; tokenModifiers: string[] };
  };
  table?: any;
  /** Any unresolved grammar conflicts (shift/reduce or reduce/reduce). */
  conflicts?: GrammarConflictDiagnostic[];
}

/**
 * Compiles a DSL grammar definition into a set of AssemblyScript source files,
 * JavaScript wrappers, and LR automata tables ready for WASM compilation.
 *
 * @param languageDef The grammar definition created using the DSL functions
 * @returns The final build result containing code strings and parser metadata
 */
export function buildParser(languageDef: LanguageOptions, options?: BuildOptions): BuildResult {
  if (options?.sourcePath) {
    (languageDef as any)[SOURCE_PATH_SYMBOL] = options.sourcePath;
  }
  if (options?.sourceText) {
    (languageDef as any)[SOURCE_TEXT_SYMBOL] = options.sourceText;
  }

  const result = generateParser(languageDef);

  const parserInfo = {
    name: languageDef.name,
    startSymbol: result.grammar.startSymbol,
    nonTerminals: Array.from(result.grammar.nonTerminals),
    terminals: Array.from(result.grammar.terminals),
    statesCount: result.table.actionTable.size,
  };

  const assemblyScriptFiles = generateParserTables(
    languageDef,
    result.grammar,
    result.table,
    languageDef.recovery?.sync || [],
  );

  const javascriptWrapper = generateJavaScriptWrapper(languageDef, result.grammar);

  const textMateContent = generateTextMate(languageDef);
  assemblyScriptFiles.push({ filename: "tmLanguage.json", content: textMateContent.tm });
  assemblyScriptFiles.push({ filename: "monarch.json", content: textMateContent.monarch });

  return {
    parserInfo,
    assemblyScriptFiles,
    javascriptWrapper,
    table: result.table,
    conflicts: result.table.diagnostics || [],
  };
}
