import { generateJavaScriptWrapper } from "./bindings/javascript/index.js";
import { GeneratedFile, generateParser, generateParserTables } from "./codegen/parser.js";
import { LanguageOptions } from "./dsl.js";

/**
 * Metadata about the generated grammar parser.
 */
export interface ParserResult {
  /** The name of the language. */
  name: string;
  /** The root start symbol of the grammar. */
  startSymbol: string;
  /** An array of all non-terminal symbols extracted from the grammar. */
  nonTerminals: string[];
  /** An array of all terminal symbols (tokens) extracted from the grammar. */
  terminals: string[];
  /** The total number of states in the generated GLR action table. */
  statesCount: number;
}

/**
 * The full build output generated by the ModelScript language compiler.
 */
export interface BuildResult {
  /** Metadata and statistics about the generated parser. */
  parserInfo: ParserResult;
  /** The generated AssemblyScript files (action/goto tables, automata, grammar) to be compiled to WASM. */
  assemblyScriptFiles: GeneratedFile[];
  /** The generated JavaScript wrapper code and TypeScript typings to interface with the WASM parser. */
  javascriptWrapper: { js: string; dts: string };
}

/**
 * Compiles a DSL grammar definition into a set of AssemblyScript source files,
 * JavaScript wrappers, and LR automata tables ready for WASM compilation.
 *
 * @param languageDef The grammar definition created using the DSL functions
 * @returns The final build result containing code strings and parser metadata
 */
export function buildParser(languageDef: LanguageOptions): BuildResult {
  const result = generateParser(languageDef);

  const parserInfo = {
    name: languageDef.name,
    startSymbol: result.grammar.startSymbol,
    nonTerminals: Array.from(result.grammar.nonTerminals),
    terminals: Array.from(result.grammar.terminals),
    statesCount: result.table.actionTable.size,
  };

  const assemblyScriptFiles = generateParserTables(languageDef, result.grammar, result.table);

  const javascriptWrapper = generateJavaScriptWrapper(languageDef, result.grammar);

  return { parserInfo, assemblyScriptFiles, javascriptWrapper };
}
