// SPDX-License-Identifier: AGPL-3.0-or-later

import type * as vscode from "vscode";
import { droneStepContent } from "../drone-step-content.js";

function joinPath(base: vscode.Uri, ...pathSegments: string[]): vscode.Uri {
  const globalVsCode = (globalThis as any).vscode;
  if (typeof globalVsCode?.Uri?.joinPath === "function") {
    return globalVsCode.Uri.joinPath(base, ...pathSegments);
  }
  const cleanBase = (base.path || "").replace(/\/+$/, "");
  const relPath = pathSegments.join("/").replace(/^\/+/, "");
  const fullPath = `${cleanBase}/${relPath}`;
  return {
    scheme: base.scheme || "memfs",
    path: fullPath,
    authority: base.authority || "",
    query: base.query || "",
    fragment: base.fragment || "",
    fsPath: fullPath,
    with: (change: any) => ({ ...base, ...change }),
    toJSON: () => ({ scheme: base.scheme, path: fullPath }),
  } as vscode.Uri;
}

export interface IMemoryFileSystemProvider {
  writeFile(uri: vscode.Uri, content: Uint8Array): void;
  writeFiles?(entries: [vscode.Uri, Uint8Array][]): void;
}

export function scaffoldTemplateFiles(memFs: IMemoryFileSystemProvider, workspaceUri: vscode.Uri): void {
  const encoder = new TextEncoder();
  const template = workspaceUri.path.substring(1) || "empty";

  const templates: Record<string, Record<string, string>> = {
    "drone-chassis": {
      "DroneSimulation.mo": [
        'model DroneSimulation "Propeller dynamics linked to procedural CAD geometry"',
        "  // ── Geometry (compiles to STEP for FEA/CFD) ─────────────────────────",
        "  // Propeller prop(",
        "  //   radius = 100,",
        "  //   hubRadius = 10,",
        "  //   bladeWidth = 15,",
        "  //   thickness = 2",
        '  // ) annotation(Shape(export = "drone.step"));',
        "",
        "  // ── Derived physical properties from geometry ───────────────────────",
        '  parameter Real bladeVolume = (100 - 10) * 15 * 2 "Blade volume [mm³]";',
        '  parameter Real hubVolume = 3.14159 * 10^2 * 4 "Hub volume [mm³]";',
        '  parameter Real mass = (2 * bladeVolume + hubVolume) * 1e-9 * 1600 "Propeller mass [kg]";',
        '  parameter Real inertia = (1.0/12.0) * mass * (2 * 100 * 1e-3)^2 "Moment of inertia [kg*m²]";',
        "",
        "  // ── Simulation state ────────────────────────────────────────────────",
        '  Real w(start = 0) "Rotational velocity [rad/s]";',
        '  Real thrust "Thrust generated [N]";',
        "  ",
        '  parameter Real motor_tau = 0.5 "Applied motor torque [N*m]";',
        '  parameter Real torque_coeff = 0.015 "Aerodynamic torque coefficient";',
        '  parameter Real thrust_coeff = 0.11 "Aerodynamic thrust coefficient";',
        "",
        "equation",
        "  inertia * der(w) = motor_tau - torque_coeff * w * abs(w);",
        "  thrust = thrust_coeff * w * abs(w);",
        "end DroneSimulation;",
      ].join("\n"),
      "chassis.sysml": [
        "package DroneArchitecture {",
        "  part def DroneAssembly {",
        "    part chassis : Chassis;",
        "    part rotor1 : Rotor;",
        "    part rotor2 : Rotor;",
        "    part rotor3 : Rotor;",
        "    part rotor4 : Rotor;",
        "",
        "    // Reference CAD geometry",
        "    ref chassisGeometry = DroneCAD::DroneChassis;",
        "  }",
        "",
        "  part def Chassis {}",
        "  part def Rotor {}",
        "}",
      ].join("\n"),
      "DroneCAD.mo": [
        'package DroneCAD "Procedural CAD model of a quadcopter drone chassis"',
        "",
        "  import ModelScript.Geometry.*;",
        "",
        '  record Propeller "Propeller geometry"',
        '    parameter Real radius = 100 "Propeller radius [mm]";',
        '    parameter Real hubRadius = 10 "Hub radius [mm]";',
        '    parameter Real bladeWidth = 15 "Blade width [mm]";',
        '    parameter Real thickness = 2 "Blade thickness [mm]";',
        "",
        "    // Hub",
        "    Cylinder hub(radius = hubRadius, height = thickness*2)",
        "      annotation(material = ABS);",
        "",
        "    // Blade 1",
        "    Box blade1(width = radius - hubRadius, height = thickness, depth = bladeWidth)",
        "      annotation(Placement(origin = {(radius + hubRadius)/2, 0, 0}), material = CarbonFiber);",
        "",
        "    // Blade 2",
        "    Box blade2(width = radius - hubRadius, height = thickness, depth = bladeWidth)",
        "      annotation(Placement(origin = {-(radius + hubRadius)/2, 0, 0}), material = CarbonFiber);",
        "  end Propeller;",
        "",
        '  record DroneChassis "Complete quadcopter drone chassis"',
        "    parameter Real bodySize = 10;",
        "    parameter Real bodyHeight = 3;",
        "    Box body(width = bodySize, height = bodyHeight, depth = bodySize)",
        "      annotation(material = CarbonFiber);",
        "  end DroneChassis;",
        "",
        "end DroneCAD;",
      ].join("\n"),
      "DroneFEA.mo": [
        "model DroneFEA",
        "  extends ModelScript.Studies.StaticStructuralFEA(",
        "    meshResolution = 0.05",
        "  );",
        "  extends DroneSimulation;",
        "end DroneFEA;",
      ].join("\n"),
      "DroneCFD.mo": [
        "model DroneCFD",
        "  extends ModelScript.Studies.SteadyStateCFD(",
        "    meshResolution = 0.05",
        "  );",
        "  extends DroneSimulation;",
        "end DroneCFD;",
      ].join("\n"),
    },
    empty: {
      "HelloWorld.mo": `model HelloWorld "A simple Modelica model"\n  Real x(start = 1);\n  parameter Real a = -1;\nequation\n  der(x) = a * x;\nend HelloWorld;\n`,
    },
    blank: {
      "HelloWorld.mo": `model HelloWorld "A simple Modelica model"\n  Real x(start = 1);\n  parameter Real a = -1;\nequation\n  der(x) = a * x;\nend HelloWorld;\n`,
    },
    "bouncing-ball": {
      "BouncingBall.mo": `model BouncingBall "A bouncing ball"\n  parameter Real e = 0.8 "Coefficient of restitution";\n  parameter Real g = 9.81 "Gravity";\n  Real h(start = 1) "Height";\n  Real v "Velocity";\nequation\n  der(h) = v;\n  der(v) = -g;\n  when h < 0 then\n    reinit(v, -e * pre(v));\n  end when;\nend BouncingBall;\n`,
    },
    "injection-molding-cosim": {
      "Manufacturing.mo": `package Manufacturing
  import Modelica.Fluid.Interfaces.FluidPort_a;
  import Modelica.Fluid.Sources.MassFlowSource_T;
  import ModelScript.Geometry;
  
  // 1. Define the 3D CAD Geometry
  record SnesTopShell
    extends Geometry.Box;
    parameter Real width = 150;
    parameter Real height = 60;
    parameter Real depth = 20;
  end SnesTopShell;

  // 2. Define the 3D CFD Interface Block
  model InjectionCavity "A boundary node that proxies the 3D OpenFOAM solver"
    parameter Geometry.Shape geometry;
    parameter String material = "ABS";
    parameter Real moldTemp = 40.0;
    FluidPort_a gateInlet;
  end InjectionCavity;

  // 3. Define the 1D System Dynamics
  model HydraulicInjectionUnit "1D Lumped parameter model of the injection machine"
    parameter Real targetPressure = 150e6;
    parameter Real barrelTemp = 493.15;
    Modelica.Fluid.Sources.MassFlowSource_T ram(nPorts = 1, m_flow = 0.05, T = barrelTemp);
    FluidPort_a fluidOut;
  equation
    connect(ram.ports[1], fluidOut);
  end HydraulicInjectionUnit;

  // 4. The Full System Orchestration
  model SnesMoldProcess
    HydraulicInjectionUnit injectionMachine(targetPressure = 150e6);
    InjectionCavity mold(
      geometry = SnesTopShell(),
      material = "ABS",
      moldTemp = 40.0
    );
  equation
    connect(injectionMachine.fluidOut, mold.gateInlet);
  end SnesMoldProcess;
end Manufacturing;
`,
    },
    rlc: {
      "RLC.mo": [
        'model RLC "RLC circuit with MSL components"',
        "  Modelica.Electrical.Analog.Sources.SineVoltage Vb(V = 10, f = 50)",
        "    annotation(Placement(transformation(origin = {-70, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 270)));",
        "  Modelica.Electrical.Analog.Basic.Inductor L(L = 0.5)",
        "    annotation(Placement(transformation(origin = {0, 40}, extent = {{-10, -10}, {10, 10}})));",
        "  Modelica.Electrical.Analog.Basic.Capacitor C(C = 1e-4)",
        "    annotation(Placement(transformation(origin = {20, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 270)));",
        "  Modelica.Electrical.Analog.Basic.Resistor R(R = 100)",
        "    annotation(Placement(transformation(origin = {60, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 270)));",
        "  Modelica.Electrical.Analog.Basic.Ground ground",
        "    annotation(Placement(transformation(origin = {-70, -40}, extent = {{-10, -10}, {10, 10}})));",
        "equation",
        "  connect(Vb.p, L.p)",
        "    annotation(Line(points = {{-70, 10}, {-70, 40}, {-10, 40}}, color = {0, 0, 255}));",
        "  connect(L.n, C.p)",
        "    annotation(Line(points = {{10, 40}, {20, 40}, {20, 10}}, color = {0, 0, 255}));",
        "  connect(L.n, R.p)",
        "    annotation(Line(points = {{10, 40}, {60, 40}, {60, 10}}, color = {0, 0, 255}));",
        "  connect(R.n, Vb.n)",
        "    annotation(Line(points = {{60, -10}, {60, -30}, {-70, -30}, {-70, -10}}, color = {0, 0, 255}));",
        "  connect(C.n, Vb.n)",
        "    annotation(Line(points = {{20, -10}, {20, -30}, {-70, -30}, {-70, -10}}, color = {0, 0, 255}));",
        "  connect(Vb.n, ground.p)",
        "    annotation(Line(points = {{-70, -10}, {-70, -30}}, color = {0, 0, 255}));",
        "end RLC;",
        "",
      ].join("\n"),
    },
    "cad-assembly": {
      "RobotAssembly.mo": [
        'model RobotAssembly "3D CAD Robot Assembly"',
        "  // Base of the robot",
        '  Real base_angle = 0 "Base rotation angle";',
        '  Real base annotation(CAD(uri="Fox.glb", position={0, 0, 0}, scale={0.02, 0.02, 0.02}));',
        "",
        "  // A payload block",
        '  Real payload annotation(CAD(uri="BoxTextured.glb", position={2, 0, 2}, scale={0.5, 0.5, 0.5}));',
        "",
        "  // An interactive port attachment point",
        '  Real target annotation(CADPort(feature="TargetArea", offsetPosition={2, 1, 2}));',
        "equation",
        "  base = 0;",
        "  payload = 1;",
        "  target = 2;",
        "end RobotAssembly;",
        "",
      ].join("\n"),
    },
    sysml2: {
      "VehicleSystem.sysml": [
        "package VehicleSystem {",
        "",
        "  // ── Port Definitions ──",
        "  port def TorquePort {",
        "    attribute torqueValue : Real;",
        "  }",
        "",
        "  port def ElectricalPort {",
        "    attribute voltage : Real;",
        "    attribute current : Real;",
        "  }",
        "",
        "  port def FuelPort {",
        "    attribute flowRate : Real;",
        "  }",
        "",
        "  // ── Part Definitions ──",
        "  part def Engine {",
        "    attribute horsePower : Real;",
        "    attribute displacement : Real;",
        "",
        "    port torqueOut : TorquePort;",
        "    port fuelIn : FuelPort;",
        "  }",
        "",
        "  part def Transmission {",
        "    attribute gearRatio : Real;",
        "    attribute numberOfGears : Integer;",
        "",
        "    port torqueIn : TorquePort;",
        "    port torqueOut : TorquePort;",
        "  }",
        "",
        "  part def Battery {",
        "    attribute capacity : Real;",
        "    attribute voltage : Real;",
        "",
        "    port electricalOut : ElectricalPort;",
        "  }",
        "",
        "  part def BrakeSystem {",
        "    attribute maxBrakingForce : Real;",
        "    attribute absEnabled : Boolean;",
        "  }",
        "",
        "  part def Wheel {",
        "    attribute diameter : Real;",
        "    attribute tirePressure : Real;",
        "  }",
        "",
        "  part def FuelTank {",
        "    attribute capacity : Real;",
        "",
        "    port fuelOut : FuelPort;",
        "  }",
        "",
        "  // ── Top-Level Vehicle ──",
        "  part def Vehicle {",
        "    attribute mass : Real;",
        "    attribute topSpeed : Real;",
        "",
        "    part engine : Engine;",
        "    part transmission : Transmission;",
        "    part battery : Battery;",
        "    part brakes : BrakeSystem;",
        "    part frontLeft : Wheel;",
        "    part fuelTank : FuelTank;",
        "",
        "    connect engine.torqueOut to transmission.torqueIn;",
        "    connect fuelTank.fuelOut to engine.fuelIn;",
        "  }",
        "",
        "  // ── Actors & Use Cases ──",
        "",
        "  part def Driver { doc /* Primary operator. */ }",
        "  part def Mechanic { doc /* Service technician. */ }",
        "  part def FleetManager { doc /* Oversees fleet. */ }",
        "  part def Passenger { doc /* Rides vehicle. */ }",
        "  part def ChargingStation { doc /* Recharges battery. */ }",
        "  part def Pedestrian { doc /* External actor. */ }",
        "",
        "  use case def DriveVehicle {",
        "    subject vehicle : Vehicle;",
        "    actor driver : Driver;",
        "    include use case startUp : StartVehicle;",
        "    include use case navigate : NavigateRoute;",
        "  }",
        "",
        "  use case def StartVehicle {",
        "    subject vehicle : Vehicle;",
        "    actor driver : Driver;",
        "  }",
        "",
        "  use case def NavigateRoute {",
        "    subject vehicle : Vehicle;",
        "    actor driver : Driver;",
        "  }",
        "",
        "  use case def PerformMaintenance {",
        "    subject vehicle : Vehicle;",
        "    actor mechanic : Mechanic;",
        "  }",
        "",
        "  use case def MonitorFleet {",
        "    actor manager : FleetManager;",
        "  }",
        "",
        "  use case def ChargeVehicle {",
        "    subject vehicle : Vehicle;",
        "    actor driver : Driver;",
        "    actor station : ChargingStation;",
        "  }",
        "",
        "  use case def UpdateSoftware {",
        "    subject vehicle : Vehicle;",
        "    actor mechanic : Mechanic;",
        "  }",
        "",
        "  use case def AdjustClimateControl {",
        "    subject vehicle : Vehicle;",
        "    actor passenger : Passenger;",
        "  }",
        "",
        "  use case def DetectObstacle {",
        "    subject vehicle : Vehicle;",
        "    actor pedestrian : Pedestrian;",
        "    actor driver : Driver;",
        "  }",
        "}",
        "",
        "// ── Behavior ──",
        "package VehicleBehavior {",
        "",
        "  action def StartEngine {",
        "    in ignitionSignal : Boolean;",
        "    out engineRunning : Boolean;",
        "  }",
        "",
        "  action def Accelerate {",
        "    in throttlePosition : Real;",
        "    out newSpeed : Real;",
        "  }",
        "",
        "  action def Brake {",
        "    in brakeForce : Real;",
        "    out newSpeed : Real;",
        "  }",
        "",
        "  state def VehicleStates {",
        "    state off;",
        "    state idle;",
        "    state driving;",
        "",
        "    transition off_to_idle",
        "      first off",
        "      then idle;",
        "",
        "    transition idle_to_driving",
        "      first idle",
        "      then driving;",
        "  }",
        "",
        "}",
        "",
        "// ── Requirements ──",
        "package VehicleRequirements {",
        "",
        "  requirement def MassRequirement {",
        "    doc /* Total mass shall not exceed 2000 kg. */",
        "    attribute maxMass : Real;",
        "  }",
        "",
        "  requirement def SafetyRequirement {",
        "    doc /* Vehicle shall pass NCAP 5-star rating. */",
        "    attribute minRating : Integer;",
        "  }",
        "",
        "  requirement def PerformanceRequirement {",
        "    doc /* 0-100 km/h in under 6 seconds. */",
        "    attribute targetTime : Real;",
        "  }",
        "",
        "}",
        "",
        "// ── Analysis ──",
        "package VehicleAnalysis {",
        "",
        "  calc def TotalMass {",
        "    in bodyMass : Real;",
        "    in drivetrainMass : Real;",
        "    return : Real;",
        "    bodyMass + drivetrainMass",
        "  }",
        "",
        "  constraint def MaxMassConstraint {",
        "    1500 + 200 <= 2000",
        "  }",
        "",
        "}",
        "",

        "// ── Integration ──",
        "package VehicleIntegration {",
        "  import VehicleRequirements::*;",
        "  part vehicle : VehicleSystem::Vehicle;",
        "  satisfy MassRequirement by vehicle;",
        "  satisfy SafetyRequirement by vehicle;",
        "}",
        "",
      ].join("\n"),
    },
    fmi2: {
      "System.mo":
        [
          'model System "FMI 2.0 Harmonic Oscillator"',
          "  Real x(start=1.0);",
          "  Real v(start=0.0);",
          "equation",
          "  der(x) = v;",
          "  der(v) = -x;",
          "end System;",
        ].join("\n") + "\n",
      "README.md":
        [
          "# FMI 2.0 Standard Exchange",
          "",
          "This workspace demonstrates a physical system designed for **FMI 2.0 export** (Functional Mock-up Interface).",
          "",
          "## Exporting as FMU",
          "",
          "From the terminal, export the model as an FMI 2.0 FMU archive:",
          "```bash",
          "msc fmu System System.mo --fmi-version 2.0",
          "```",
          "",
          "### Supported Targets",
          "- `--type cs`: Co-Simulation (includes embedded numerical integrator)",
          "- `--type me`: Model Exchange (pure differential equations for master solvers)",
          "- `--target wasm`: Edge-ready WebAssembly FMU binary",
          "- `--target c`: Standalone C source package for embedded cross-compilation",
        ].join("\n") + "\n",
    },
    fmi3: {
      "System.mo":
        [
          'model System "FMI 3.0 Dynamic System with Actuation and Telemetry"',
          '  input Real u(start = 0.0) "External actuation input";',
          '  output Real y "Measured system output";',
          '  parameter Real k = 2.0 "Tunable gain parameter";',
          '  parameter Real w = 1.0 "Natural angular frequency [rad/s]";',
          '  Real x(start = 1.0) "Displacement state";',
          '  Real v(start = 0.0) "Velocity state";',
          "equation",
          "  der(x) = v;",
          "  der(v) = -w^2 * x + k * u;",
          "  y = x;",
          "end System;",
        ].join("\n") + "\n",
      "README.md":
        [
          "# FMI 3.0 Next-Generation Simulation Exchange",
          "",
          "This workspace showcases **FMI 3.0** capabilities supported by ModelScript, including:",
          "- **Explicit Causality**: Typed continuous and discrete ports (`input Real u`, `output Real y`)",
          "- **Tunable Parameters**: Real-time parameter reconfiguration during simulation event mode",
          "- **Intermediate Value Callbacks**: Real-time telemetry streaming to WebGL/3D dashboards without interrupting steps",
          "- **Directional & Adjoint Derivatives**: Exact sensitivity propagation for gradient-based optimization loops",
          "",
          "## Exporting as FMI 3.0 FMU",
          "",
          "Export with the ModelScript CLI:",
          "```bash",
          "msc fmu System System.mo --fmi-version 3.0 --target wasm",
          "```",
          "",
          "Inspect the generated FMI 3.0 `modelDescription.xml` schema:",
          "```bash",
          "msc fmu System System.mo --fmi-version 3.0 --xml-only",
          "```",
        ].join("\n") + "\n",
    },
    script: {
      "simulate.mos": `// A simple Modelica script\nloadString("\nmodel HelloWorld\n  Real x(start=1);\nequation\n  der(x) = -x;\nend HelloWorld;\n");\n\nsimulate(HelloWorld, stopTime=5);\n`,
    },
    "simulation-verification": {
      "BatteryArchitecture.sysml": [
        "package BatteryArchitecture {",
        "  requirement def MaxTempReq {",
        "    doc /* Battery cells shall not exceed 65.0 degC */",
        "    attribute maxTemp : Real = 65.0;",
        "  }",
        "",
        "  part def BatteryCell {",
        "    // Bound to Modelica thermal model",
        "  }",
        "",
        "  analysis def VerifyThermalLimit {",
        "    subject cell : BatteryCell;",
        "    objective req : MaxTempReq;",
        "",
        "    constraint cellTempLimit {",
        "      cell::T <= req::maxTemp",
        "    }",
        "  }",
        "}",
      ].join("\n"),
      "BatteryCell.mo": [
        'model BatteryCell "Battery cell thermal model"',
        '  annotation(SysML(implements="BatteryArchitecture::BatteryCell"));',
        "  ",
        '  parameter Real R = 0.1 "Thermal resistance";',
        '  parameter Real C = 50.0 "Thermal capacitance";',
        '  parameter Real P_heat = 500.0 "Heat generation";',
        '  parameter Real T_amb = 25.0 "Ambient temp";',
        "  ",
        '  Real T(start=25.0) "Cell temperature";',
        "equation",
        "  C * der(T) = P_heat - (T - T_amb) / R;",
        "end BatteryCell;",
      ].join("\n"),
    },
    "multi-fidelity-binding": {
      "PropellerDynamics.mo": [
        'model PropellerDynamics "1D Modelica dynamics bound to 3D CFD"',
        '  parameter Real drag_coeff = 0.05 annotation(Binding(source="drone_geometry.step", feature="DragCoefficient", tool="CFD_Extraction"));',
        '  parameter Real inertia = 0.001 annotation(Binding(source="drone_geometry.step", feature="MomentOfInertia", tool="CAD_Extraction"));',
        "",
        '  Real w(start=0.0) "Angular velocity";',
        '  parameter Real torque = 0.5 "Applied torque";',
        "equation",
        "  inertia * der(w) = torque - drag_coeff * w^2;",
        "end PropellerDynamics;",
      ].join("\n"),
    },
    "data-driven-calibration": {
      "Suspension.mo": [
        'model Suspension "Vehicle suspension model for calibration"',
        "  parameter Real stiffness = 15000.0 annotation(calibrate(min=10000.0, max=30000.0));",
        "  parameter Real damping = 1000.0 annotation(calibrate(min=500.0, max=2000.0));",
        "  parameter Real mass = 300.0;",
        "",
        "  Real position(start=0.1);",
        "  Real velocity(start=0.0);",
        "equation",
        "  der(position) = velocity;",
        "  mass * der(velocity) = -stiffness * position - damping * velocity;",
        "end Suspension;",
      ].join("\n"),
      "telemetry_data.csv": [
        "time,position",
        "0.0,0.1",
        "0.1,0.08",
        "0.2,0.03",
        "0.3,-0.02",
        "0.4,-0.05",
        "0.5,-0.04",
        "0.6,-0.01",
        "0.7,0.02",
        "0.8,0.03",
        "0.9,0.02",
        "1.0,0.0",
      ].join("\n"),
    },
    "hardware-ci": {
      "SystemIntegration.mo": [
        'model SystemIntegration "Demonstrates structural singularity detection in CI"',
        "  // Two independent rigid speed sources connected rigidly to the same shaft",
        "  // cause a structural singularity (0 = w1 - w2 over-constraint).",
        '  Real w1(start = 10.0) "Motor 1 angular velocity [rad/s]";',
        '  Real w2(start = 12.0) "Motor 2 angular velocity [rad/s]";',
        '  parameter Real J1 = 0.5 "Inertia 1";',
        '  parameter Real J2 = 0.5 "Inertia 2";',
        "  Real tau1 = 2.0;",
        "  Real tau2 = 3.0;",
        "equation",
        "  J1 * der(w1) = tau1;",
        "  J2 * der(w2) = tau2;",
        "  // Rigid coupling equation creating index-2 DAE / structural over-constraint:",
        "  w1 = w2;",
        "end SystemIntegration;",
      ].join("\n"),
      ".github/workflows/ci.yml": [
        "name: Hardware CI",
        "on: [push, pull_request]",
        "jobs:",
        "  verify:",
        "    runs-on: ubuntu-latest",
        "    steps:",
        "      - uses: actions/checkout@v3",
        "      - name: Run ModelScript Lint",
        "        run: msc lint",
        "      - name: Verify Structural Constraints",
        "        run: msc verify",
      ].join("\n"),
    },
    "mbse-verification": {
      "ThermalVerification.sysml": [
        "package ThermalVerification {",
        "",
        "  requirement def MaxTemperatureReq {",
        "    doc /* Motor temperature shall not exceed 85 degC */",
        "    attribute maxTemp : Real = 85.0;",
        "  }",
        "",
        "  part def MotorSystem {",
        "    // Allocated to Modelica class 'HeatedMotor'",
        "  }",
        "",
        "  analysis def VerifyTemperature {",
        "    subject motor : MotorSystem;",
        "    objective req : MaxTemperatureReq;",
        "",
        "    constraint tempLimit {",
        "      motor::T <= req::maxTemp",
        "    }",
        "  }",
        "}",
        "",
      ].join("\n"),
      "HeatedMotor.mo": [
        'model HeatedMotor "Motor with thermal dynamics"',
        '  annotation(SysML(implements="ThermalVerification::MotorSystem"));',
        "  ",
        '  parameter Real R = 0.5 "Thermal resistance (K/W)";',
        '  parameter Real C_th = 10.0 "Thermal capacitance (J/K)";',
        '  parameter Real P = 200.0 "Power dissipation (W)";',
        '  parameter Real T_amb = 25.0 "Ambient temperature (degC)";',
        "  ",
        '  Real T(start = 25.0) "Motor temperature (degC)";',
        "equation",
        "  C_th * der(T) = P - (T - T_amb) / R;",
        "end HeatedMotor;",
        "",
      ].join("\n"),
      "VerificationReport.md": [
        "# Motor Thermal Verification",
        "",
        "Automated verification of motor thermal constraints.",
        "",
        "## System Requirements",
        '::requirements{target="ThermalVerification"}',
        "",
        "## System Architecture",
        '::diagram{target="HeatedMotor"}',
        "",
        "The maximum allowable motor temperature is: {{ ThermalVerification.MaxTemperatureReq.maxTemp }} °C.",
        "",
      ].join("\n"),
    },
    cad: {
      "drone_architecture.sysml": [
        "package DroneArchitecture {",
        "  import DroneCAD::*;",
        "",
        "  part def DroneAssembly {",
        "    part chassis : Chassis;",
        "    part rotor1 : Rotor;",
        "    part rotor2 : Rotor;",
        "    part rotor3 : Rotor;",
        "    part rotor4 : Rotor;",
        "",
        "    // Reference CAD geometry directly from the STEP file!",
        "    ref chassisGeometry = DroneCAD::ChassisShape;",
        "  }",
        "",
        "  part def Chassis {}",
        "  part def Rotor {}",
        "}",
      ].join("\n"),
      "drone.step": droneStepContent,
    },
    "drone-meshing": {
      "drone.step": droneStepContent,
      "README.md":
        "# Drone Chassis Meshing\n\nRight-click `drone.step` and select **Discretize CAD to FEA Mesh (.inp)** or **Discretize CAD to CFD Mesh (.su2)** to begin configuring your mesh and physical simulation.",
    },
    "drone-fea": {
      "drone.step": droneStepContent,
      "DroneFEA.mo": [
        'model DroneFEA "Static Structural FEA of Drone Chassis"',
        "  extends ModelScript.Studies.StaticStructuralFEA(",
        "    meshResolution = 0.05,",
        "    elementOrder = 2",
        "  );",
        "",
        '  parameter String stepFile = "drone.step" annotation(Dialog(loadSelector=true, filter="STEP Files (*.step *.stp)"));',
        "",
        "  Real maxDisplacementZ;",
        "  Real maxVonMisesStress;",
        "end DroneFEA;",
      ].join("\n"),
      "DroneDynamics.mo": [
        'model DroneDynamics "Drone dynamics consuming FEA results"',
        "  import DroneFEA;",
        '  parameter Real max_displacement = DroneFEA.maxDisplacementZ "Imported from FEA";',
        '  parameter Real max_stress = DroneFEA.maxVonMisesStress "Imported from FEA";',
        "equation",
        "  // Logic using FEA results",
        "end DroneDynamics;",
      ].join("\n"),
    },
    "drone-cfd": {
      "drone.step": droneStepContent,
      "DroneCFD.msim": [
        "{",
        '  "type": "CFD",',
        '  "solver": "OpenFOAM",',
        '  "stepFile": "drone.step",',
        '  "mesh": {',
        '    "size": 0.05',
        "  },",
        '  "exposeProperties": [',
        '    { "name": "maxVelocityMagnitude", "type": "Real" },',
        '    { "name": "maxPressure", "type": "Real" }',
        "  ]",
        "}",
      ].join("\n"),
      "DroneFlight.mo": [
        'model DroneFlight "Drone flight consuming CFD results"',
        "  import DroneCFD;",
        '  parameter Real max_velocity = DroneCFD.maxVelocityMagnitude "Imported from CFD";',
        '  parameter Real max_pressure = DroneCFD.maxPressure "Imported from CFD";',
        "equation",
        "  // Logic using CFD results",
        "end DroneFlight;",
      ].join("\n"),
    },
    "modelica-procedural-cad": {
      "DroneCAD.mo": [
        'package DroneCAD "Procedural CAD model of a quadcopter drone chassis"',
        "",
        "  import Geometry.*;",
        "",
        "  // ─── Reusable sub-assemblies ──────────────────────────────────────────",
        "",
        '  record MotorMount "Cylindrical motor mount with propeller guard ring"',
        '    parameter Real radius = 1.5 "Motor housing radius [mm]";',
        '    parameter Real height = 2 "Motor housing height [mm]";',
        "",
        "    replaceable Cylinder housing(radius = radius, height = height)",
        "      annotation(material = Aluminum);",
        "",
        "    Torus guard(major = radius * 2, minor = 0.1)",
        "      annotation(Placement(origin = {0, height, 0}));",
        "  end MotorMount;",
        "",
        '  record DroneArm "Single arm extending from the body to a motor"',
        '    parameter Real length = 12 "Arm length [mm]";',
        '    parameter Real thickness = 1 "Arm thickness [mm]";',
        '    parameter Real width = 1.5 "Arm width [mm]";',
        '    parameter Real motorRadius = 1.5 "Motor mount radius [mm]";',
        "",
        "    Box beam(width = length, height = thickness, depth = width)",
        "      annotation(material = CarbonFiber);",
        "",
        "    replaceable MotorMount motor(radius = motorRadius)",
        "      annotation(Placement(origin = {length/2, thickness/2 + 0.5, 0}));",
        "  end DroneArm;",
        "",
        '  record LandingGear "Two-skid landing gear with vertical struts"',
        '    parameter Real span = 8 "Distance between skids [mm]";',
        '    parameter Real skidLength = 10 "Skid bar length [mm]";',
        '    parameter Real strutHeight = 4 "Strut height from body to skid [mm]";',
        "",
        "    // Horizontal skid bars",
        "    Box skidL(width = 0.5, height = 0.3, depth = skidLength)",
        "      annotation(",
        "        Placement(origin = {-span/2, -strutHeight, 0}),",
        "        material = Aluminum",
        "      );",
        "    Box skidR(width = 0.5, height = 0.3, depth = skidLength)",
        "      annotation(",
        "        Placement(origin = {span/2, -strutHeight, 0}),",
        "        material = Aluminum",
        "      );",
        "",
        "    // Vertical struts",
        "    Box strutLF(width = 0.3, height = strutHeight, depth = 0.3)",
        "      annotation(Placement(origin = {-span/2, -strutHeight/2, skidLength/3}));",
        "    Box strutLR(width = 0.3, height = strutHeight, depth = 0.3)",
        "      annotation(Placement(origin = {-span/2, -strutHeight/2, -skidLength/3}));",
        "    Box strutRF(width = 0.3, height = strutHeight, depth = 0.3)",
        "      annotation(Placement(origin = {span/2, -strutHeight/2, skidLength/3}));",
        "    Box strutRR(width = 0.3, height = strutHeight, depth = 0.3)",
        "      annotation(Placement(origin = {span/2, -strutHeight/2, -skidLength/3}));",
        "  end LandingGear;",
        "",
        '  record CameraAssembly "Front-mounted camera with gimbal bracket"',
        '    parameter Real gimbalWidth = 2 "Gimbal bracket width [mm]";',
        '    parameter Real lensSize = 1.5 "Camera lens diameter [mm]";',
        "",
        "    Box mount(width = gimbalWidth, height = 0.8, depth = 3)",
        "      annotation(material = ABS);",
        "",
        "    Box lens(width = lensSize, height = lensSize, depth = 1)",
        "      annotation(",
        "        Placement(origin = {0, -0.4, 2}),",
        "        material = ABS",
        "      );",
        "  end CameraAssembly;",
        "",
        "  // ─── Main chassis assembly ────────────────────────────────────────────",
        "",
        '  record DroneChassis "Complete quadcopter drone chassis"',
        '    parameter Real bodySize = 10 "Central body width/depth [mm]";',
        '    parameter Real bodyHeight = 3 "Central body height [mm]";',
        '    parameter Real armLength = 12 "Arm length [mm]";',
        '    parameter Real armAngle = 45 "Diagonal angle from X axis [deg]";',
        "",
        "    // ── Central body ──────────────────────────────────────────",
        "    Box body(width = bodySize, height = bodyHeight, depth = bodySize)",
        "      annotation(material = CarbonFiber);",
        "",
        "    Box topCover(width = bodySize - 2, height = 0.6, depth = bodySize - 2)",
        "      annotation(",
        "        Placement(origin = {0, bodyHeight/2 + 0.3, 0}),",
        "        material = CarbonFiber",
        "      );",
        "",
        "    Box electronicsBay(width = 6, height = 1, depth = 6)",
        "      annotation(",
        "        Placement(origin = {0, -bodyHeight/2 - 0.5, 0}),",
        "        material = ABS",
        "      );",
        "",
        "    // ── Four diagonal arms ────────────────────────────────────",
        "    DroneArm armFR(length = armLength)",
        "      annotation(Placement(origin = {6, 0, 6}, rotation = {0, armAngle, 0}));",
        "",
        "    DroneArm armFL(length = armLength)",
        "      annotation(Placement(origin = {-6, 0, 6}, rotation = {0, -armAngle, 0}));",
        "",
        "    DroneArm armRR(length = armLength)",
        "      annotation(Placement(origin = {6, 0, -6}, rotation = {0, 180 - armAngle, 0}));",
        "",
        "    DroneArm armRL(length = armLength)",
        "      annotation(Placement(origin = {-6, 0, -6}, rotation = {0, -(180 - armAngle), 0}));",
        "",
        "    // ── Landing gear ──────────────────────────────────────────",
        "    LandingGear gear(span = bodySize - 2, strutHeight = 4);",
        "",
        "    // ── Camera ────────────────────────────────────────────────",
        "    CameraAssembly camera",
        "      annotation(Placement(origin = {0, -1, bodySize/2 + 1.5}));",
        "",
        "    // ── Battery ───────────────────────────────────────────────",
        "    Box battery(width = 5, height = 1.2, depth = 8)",
        "      annotation(",
        "        Placement(origin = {0, -bodyHeight/2 - 1.5, 0}),",
        "        material = LiPo",
        "      );",
        "  end DroneChassis;",
        "",
        "  // ─── Parametric variants ──────────────────────────────────────────────",
        "",
        '  record CargoDrone "Heavy-lift drone with larger body and longer arms"',
        "    extends DroneChassis(",
        "      bodySize = 15,",
        "      bodyHeight = 4,",
        "      armLength = 18",
        "    );",
        "  end CargoDrone;",
        "",
        '  record RacingDrone "Lightweight racing drone with compact form"',
        "    extends DroneChassis(",
        "      bodySize = 8,",
        "      bodyHeight = 2,",
        "      armLength = 9,",
        "      armAngle = 50",
        "    );",
        "  end RacingDrone;",
        "",
        "  // Demonstration of redeclare — swap motor mounts for tapered cones",
        "  record TaperedMotorMount",
        "    extends MotorMount(",
        "      redeclare Cone housing(",
        "        radiusBottom = radius * 1.2,",
        "        radiusTop = radius * 0.8,",
        "        height = 2.5",
        "      )",
        "    );",
        "  end TaperedMotorMount;",
        "",
        '  record StealthDrone "Drone with tapered motor housings for aerodynamics"',
        "    extends DroneChassis(",
        "      bodySize = 9,",
        "      armLength = 11,",
        "      // Redeclare the motor mount type inside each arm",
        "      redeclare DroneArm armFR(",
        "        redeclare TaperedMotorMount motor",
        "      ),",
        "      redeclare DroneArm armFL(",
        "        redeclare TaperedMotorMount motor",
        "      ),",
        "      redeclare DroneArm armRR(",
        "        redeclare TaperedMotorMount motor",
        "      ),",
        "      redeclare DroneArm armRL(",
        "        redeclare TaperedMotorMount motor",
        "      )",
        "    );",
        "  end StealthDrone;",
        "",
        "end DroneCAD;",
        "",
      ].join("\n"),
      "README.md":
        "# Modelica Procedural CAD\n\nThis example demonstrates how to build 3D CAD geometries using the Modelica `shape` language extension.\n\nRight click on `DroneCAD.mo` and select **Generate STEP** to compile the procedural design into a standard 3D CAD model.",
    },
    "cfd-verification": {
      "AirflowROM.mo": [
        'model AirflowROM "Reduced-order CFD surrogate for heat exchanger airflow"',
        '  input Real T_inlet(start = 25) "Inlet air temperature [°C]";',
        '  input Real massFlow(start = 0.5) "Mass flow rate [kg/s]";',
        '  output Real T_outlet "Outlet air temperature [°C]";',
        '  output Real pressure_drop "Pressure drop [Pa]";',
        '  parameter Real efficiency = 0.85 "Heat transfer efficiency";',
        '  parameter Real k_drop = 200 "Pressure loss coefficient";',
        "equation",
        "  T_outlet = T_inlet + efficiency * (100 - T_inlet) * (1 - exp(-massFlow));",
        "  pressure_drop = k_drop * massFlow^2;",
        "end AirflowROM;",
        "",
      ].join("\n"),
      "ThermalSystem.mo": [
        'model ThermalSystem "Thermal system with embedded CFD surrogate"',
        '  annotation(SysML(implements="ThermalVerification::ThermalSys"));',
        "",
        "  AirflowROM airflow;",
        '  Real T_room(start = 20) "Room temperature [°C]";',
        '  parameter Real C_room = 5000 "Thermal capacitance [J/°C]";',
        '  parameter Real h_conv = 10 "Convective heat transfer coeff [W/°C]";',
        '  parameter Real A_surface = 2.0 "Heat exchange surface [m²]";',
        "equation",
        "  airflow.T_inlet = 25 + 5 * sin(2 * 3.14159 * time / 3600);",
        "  airflow.massFlow = 0.3 + 0.2 * sin(2 * 3.14159 * time / 1800);",
        "  C_room * der(T_room) = h_conv * A_surface * (airflow.T_outlet - T_room);",
        "end ThermalSystem;",
        "",
      ].join("\n"),
      "ThermalVerification.sysml": [
        "package ThermalVerification {",
        "",
        "  requirement def MaxOutletTempReq {",
        "    doc /* Outlet temperature shall not exceed 85 degC */",
        "    attribute maxTemp : Real = 85.0;",
        "  }",
        "",
        "  requirement def MaxPressureDropReq {",
        "    doc /* Pressure drop shall not exceed 500 Pa */",
        "    attribute maxDrop : Real = 500.0;",
        "  }",
        "",
        "  part def ThermalSys {",
        "    // Allocated to Modelica class ThermalSystem",
        "  }",
        "",
        "  analysis def VerifyThermal {",
        "    subject system : ThermalSys;",
        "    objective tempReq : MaxOutletTempReq;",
        "",
        "    constraint outlet_temp {",
        "      system::airflow::T_outlet <= tempReq::maxTemp",
        "    }",
        "  }",
        "",
        "  analysis def VerifyPressure {",
        "    subject system : ThermalSys;",
        "    objective dropReq : MaxPressureDropReq;",
        "",
        "    constraint max_drop {",
        "      system::airflow::pressure_drop <= dropReq::maxDrop",
        "    }",
        "  }",
        "}",
        "",
      ].join("\n"),
      "VerificationReport.md": [
        "# Thermal System Verification",
        "",
        "Automated verification of a thermal system with an embedded reduced-order CFD model.",
        "",
        "## Requirements",
        '::requirements{target="ThermalVerification"}',
        "",
        "## System Architecture",
        '::diagram{target="ThermalSystem"}',
        "",
        "Maximum outlet temperature limit: {{ ThermalVerification.MaxOutletTempReq.maxTemp }} °C.",
        "",
      ].join("\n"),
    },
    calibration: {
      "SpringDamper.mo": [
        'model SpringDamper "Mass-spring-damper system for parameter calibration"',
        '  parameter Real m = 1.0 "Mass [kg]";',
        '  parameter Real k = 50.0 "Spring stiffness [N/m] (to calibrate)";',
        '  parameter Real c = 2.0 "Damping coefficient [Ns/m] (to calibrate)";',
        '  Real x(start = 1.0) "Displacement [m]";',
        '  Real v(start = 0.0) "Velocity [m/s]";',
        "equation",
        "  der(x) = v;",
        "  m * der(v) = -k * x - c * v;",
        "end SpringDamper;",
        "",
      ].join("\n"),
      "measurements.csv": (() => {
        // Generate synthetic measurement data:
        // True params: k=80, c=5. Simulate manually + add noise.
        const rows = ["time,x"];
        const dt = 0.05;
        const N = 100;
        const k_true = 80,
          c_true = 5,
          m = 1.0;
        let x = 1.0,
          v = 0.0;
        // Simple Euler integration to generate ground truth
        for (let i = 0; i <= N; i++) {
          const t = i * dt;
          // Add small pseudo-random noise (deterministic for reproducibility)
          const noise = 0.02 * Math.sin(t * 137.035999 + 7) * Math.cos(t * 42.7 + 3);
          rows.push(`${t.toFixed(3)},${(x + noise).toFixed(6)}`);
          // Euler step
          const a = (-k_true * x - c_true * v) / m;
          v += a * dt;
          x += v * dt;
        }
        return rows.join("\n") + "\n";
      })(),
      "calibrate.mos": [
        "// Parameter calibration of a spring-damper system",
        "// True parameters: k=80, c=5 — initial guesses: k=50, c=2",
        "//",
        "// METHOD 1: Script-based calibration (this file)",
        "//   Right-click → Run Script, or press the ▶ button.",
        "//",
        "// METHOD 2: Interactive UI panel (recommended)",
        '//   Open SpringDamper.mo, then Ctrl+Shift+P → "ModelScript: Open Calibration Dashboard".',
        "//   The dashboard provides live convergence plots and parameter sliders.",
        "",
        'loadFile("SpringDamper.mo");',
        "",
        "calibrate(SpringDamper,",
        "  stopTime = 5.0,",
        '  parameters = {"k", "c"},',
        "  parameterBounds = [10, 200; 0.1, 20],",
        '  measurementFile = "measurements.csv",',
        '  method = "lm"',
        ");",
        "",
      ].join("\n"),
      "README.md": [
        "# Parameter Calibration Example",
        "",
        "This example demonstrates **parameter calibration** of a spring-damper system against synthetic measurement data.",
        "",
        "## The Model",
        "",
        "`SpringDamper.mo` defines a simple mass-spring-damper system with two unknown parameters:",
        "- `k` — spring stiffness (initial guess: 50 N/m, true value: 80 N/m)",
        "- `c` — damping coefficient (initial guess: 2 Ns/m, true value: 5 Ns/m)",
        "",
        "## Measurement Data",
        "",
        "`measurements.csv` contains synthetic displacement measurements generated from the true system with added noise.",
        "",
        "## Two Ways to Calibrate",
        "",
        "### 1. Script-Based (`calibrate.mos`)",
        "Right-click `calibrate.mos` → **Run Script**. The `calibrate()` function runs the Levenberg–Marquardt optimizer and prints the optimal parameters to the console.",
        "",
        "### 2. Calibration Dashboard (Interactive UI)",
        "1. Open `SpringDamper.mo`",
        '2. `Ctrl+Shift+P` → **"ModelScript: Open Calibration Dashboard"**',
        "3. The dashboard provides:",
        "   - Live convergence plots",
        "   - Measurement vs. simulated overlay",
        "   - One-click export of the optimized parameters as a Modelica `extends` class",
        "",
        "Both methods use the same Levenberg–Marquardt / SQP optimizer under the hood.",
        "",
      ].join("\n"),
    },
    "optimica-polyglot": {
      "RocketSled.mo": [
        'model RocketSled "Energy-optimal rocket sled trajectory"',
        '  Real x(start = 0) "Position [m]";',
        '  Real v(start = 0, max = 10.0) "Velocity [m/s]";',
        '  input Real u(min = -5, max = 5) "Thrust force [N]";',
        '  parameter Real m = 1.0 "Mass [kg]";',
        '  parameter Real drag = 0.1 "Drag coefficient";',
        "equation",
        "  der(x) = v;",
        "  m * der(v) = u - drag * v;",
        "end RocketSled;",
        "",
      ].join("\n"),
      "SafetyConstraints.sysml": [
        "package SafetyConstraints {",
        "",
        "  requirement def MaxVelocityReq {",
        "    doc /* Velocity shall not exceed 10 m/s for structural safety */",
        "    attribute maxVelocity : Real = 10.0;",
        "  }",
        "",
        "  requirement def MinFinalPositionReq {",
        "    doc /* Final position shall be at least 50 m to reach the target */",
        "    attribute minPosition : Real = 50.0;",
        "  }",
        "",
        "  part def RocketSledSys {",
        "    // Allocated to Modelica class RocketSled",
        "  }",
        "",
        "  analysis def OptimalTrajectory {",
        "    subject sled : RocketSledSys;",
        "    objective velReq : MaxVelocityReq;",
        "",
        "    constraint max_v {",
        "      sled::v <= velReq::maxVelocity",
        "    }",
        "  }",
        "}",
        "",
      ].join("\n"),
      "optimize.mos": [
        "// Optimal control with Optimica + SysML2 constraints",
        "//",
        "// Run via CLI: msc optimize RocketSled RocketSled.mo SafetyConstraints.sysml",
        "// Or open RocketSled.mo and press Ctrl+Shift+P → 'ModelScript: Open Optimization Dashboard'",
        "",
        'loadFile("RocketSled.mo");',
        "",
        "optimize(RocketSled,",
        "  startTime = 0,",
        "  stopTime = 20,",
        "  numIntervals = 50,",
        "  tolerance = 1e-6",
        ");",
        "",
      ].join("\n"),
    },
    uncertainty: {
      "Projectile.mo": [
        'model Projectile "Projectile with uncertain drag and mass"',
        '  parameter Real m = 1.0 "Mass [kg] (uncertain)";',
        '  parameter Real Cd = 0.47 "Drag coefficient (uncertain)";',
        '  parameter Real g = 9.81 "Gravitational acceleration [m/s²]";',
        '  parameter Real rho = 1.225 "Air density [kg/m³]";',
        '  parameter Real A = 0.01 "Cross-section area [m²]";',
        '  Real x(start = 0) "Horizontal position [m]";',
        '  Real y(start = 0) "Vertical position [m]";',
        '  Real vx(start = 20) "Horizontal velocity [m/s]";',
        '  Real vy(start = 30) "Vertical velocity [m/s]";',
        '  Real speed "Total speed [m/s]";',
        "equation",
        "  speed = sqrt(vx^2 + vy^2);",
        "  der(x) = vx;",
        "  der(y) = vy;",
        "  m * der(vx) = -0.5 * rho * Cd * A * speed * vx;",
        "  m * der(vy) = -m * g - 0.5 * rho * Cd * A * speed * vy;",
        "end Projectile;",
        "",
      ].join("\n"),
      "uncertainty.mos": [
        "// Monte Carlo uncertainty analysis for a projectile",
        "// Uncertain parameters: drag coefficient (Gaussian) and mass (Uniform)",
        "//",
        "// Run via CLI: msc mc Projectile Projectile.mo --samples 200",
        "// Or open Projectile.mo and press Ctrl+Shift+P → 'ModelScript: Open Uncertainty Analysis'",
        "",
        'loadFile("Projectile.mo");',
        "",
        "montecarlo(Projectile,",
        "  stopTime = 5,",
        "  numberOfIntervals = 200,",
        "  parameters = {",
        '    "Cd ~ normal(0.47, 0.05)",',
        '    "m ~ uniform(0.9, 1.1)"',
        "  },",
        "  numSamples = 200,",
        "  seed = 42,",
        '  method = "lhs"',
        ");",
        "",
      ].join("\n"),
    },
    notebook: {
      "demo.monb": JSON.stringify(
        {
          cells: [
            {
              cell_type: "markdown",
              source: [
                "# Modelica Notebooks",
                "",
                "Welcome to ModelScript Notebooks! Create models and simulate them directly.",
              ],
            },
            {
              cell_type: "code",
              source: ["model Simple", "  Real x(start = 1);", "equation", "  der(x) = -x;", "end Simple;"],
            },
          ],
        },
        null,
        2,
      ),
    },
    surrogate: {
      "BouncingBall.mo": [
        'model BouncingBall "A classic bouncing ball model"',
        '  parameter Real e = 0.8 "Coefficient of restitution";',
        '  parameter Real g = 9.81 "Gravity";',
        '  parameter Real v_0 = 0.0 "Initial velocity";',
        '  Real h(start = 1.0) "Height";',
        '  Real v(start = v_0) "Velocity";',
        "equation",
        "  der(h) = v;",
        "  der(v) = -g;",
        "  when h <= 0.0 and v < 0.0 then",
        "    reinit(v, -e * pre(v));",
        "  end when;",
        "end BouncingBall;",
        "",
      ].join("\n"),
      "README.md": [
        "# AI Surrogate Modeling",
        "",
        "This workspace demonstrates how to orchestrate Design of Experiments (DoE) and train AI surrogate models (Reduced Order Models) directly from Modelica.",
        "",
        "## Training a Surrogate",
        "",
        "1. Open `BouncingBall.mo`",
        "2. Click the **Train Surrogate** icon (robot) in the editor title bar",
        "3. Choose a **DoE Strategy** (e.g., Latin Hypercube) and number of samples",
        "4. Choose an **Architecture** (e.g., MLP Neural Network)",
        "5. Click **Train Surrogate**",
        "",
        "The platform will orchestrate headless simulations to build a dataset, train the neural network, and report the R² accuracy.",
        "",
        "## Exporting to WebAssembly",
        "",
        "Once training is complete, click **Generate WASM** in the Surrogate Editor.",
        "This will instantly generate a self-contained C source code array of the neural network weights and biases, ready for edge deployment!",
      ].join("\n"),
    },
    "assembly-to-multibody": {
      "SimplePendulum.step": [
        "ISO-10303-21;",
        "HEADER;",
        "FILE_DESCRIPTION(('STEP AP242 Assembly'),'2;1');",
        "FILE_NAME('SimplePendulum.step','2026-05-13',('ModelScript'),(''),(''),'','');",
        "FILE_SCHEMA(('AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF { 1 0 10303 442 1 1 4 }'));",
        "ENDSEC;",
        "DATA;",
        "#1=PRODUCT('Assembly','Assembly','',(#2));",
        "#2=PRODUCT_CONTEXT('',#3,'mechanical');",
        "#3=APPLICATION_CONTEXT('automotive design');",
        "#10=PRODUCT('Link','Link','',(#2));",
        "#20=PRODUCT('Bob','Bob','',(#2));",
        "#30=NEXT_ASSEMBLY_USAGE_OCCURRENCE('NAUO1','Link to Bob','',#10,#20,$);",
        "#40=REVOLUTE_PAIR('RevJoint','Joint between Link and Bob',#10,#20);",
        "ENDSEC;",
        "END-ISO-10303-21;",
      ].join("\n"),
      "README.md": [
        "# STEP AP242 to Modelica Multi-Body",
        "",
        "This workspace demonstrates the automated conversion of a 3D CAD assembly into a Modelica Multi-Body simulation.",
        "",
        "## Workflow",
        "",
        "1. Open `SimplePendulum.step`.",
        "2. The 3D Viewer will render the geometric bodies (if OCCT WASM is loaded).",
        "3. Click the **⚙️ Generate Multi-Body Model** button in the top left of the 3D Viewer, or run the command from the Command Palette (`Ctrl+Shift+P` → **ModelScript: Generate Multi-Body Simulation from CAD**).",
        "4. A new `SimplePendulum.mo` file will be generated automatically, containing `Parts.Body` and `Joints.Revolute` components.",
        "5. Open `SimplePendulum.mo` and click **Run Simulation** to simulate the dynamics!",
        "",
        "## CLI Synthesis",
        "",
        "You can also synthesize multi-body models from the terminal using:",
        "```bash",
        "msc polyglot multibody SimplePendulum.step",
        "```",
      ].join("\n"),
      "generate.mos": [
        "// After generating SimplePendulum.mo from SimplePendulum.step via the 3D Viewer",
        "// (or 'msc polyglot multibody SimplePendulum.step'), simulate the synthesized model:",
        'loadFile("SimplePendulum.mo");',
        "simulate(SimplePendulum, stopTime = 10);",
      ].join("\n"),
    },
    cosim: {
      "Controller.mo": [
        'model Controller "Simple PI controller"',
        '  Modelica.Blocks.Interfaces.RealInput u "Measurement input";',
        '  Modelica.Blocks.Interfaces.RealOutput y "Control output";',
        '  parameter Real Kp = 2.0 "Proportional gain";',
        '  parameter Real Ki = 0.5 "Integral gain";',
        '  parameter Real setpoint = 1.0 "Reference setpoint";',
        '  Real error "Tracking error";',
        '  Real integral(start = 0) "Integral of error";',
        "equation",
        "  error = setpoint - u;",
        "  der(integral) = error;",
        "  y = Kp * error + Ki * integral;",
        "end Controller;",
        "",
      ].join("\n"),
      "CosimSetup.mo": [
        'model CosimSetup "Co-simulation wiring diagram"',
        "  Controller controller;",
        "  SineWave sineWave;",
        "equation",
        "  connect(controller.y, sineWave.phase);",
        "  connect(sineWave.y, controller.u);",
        "end CosimSetup;",
        "",
      ].join("\n"),
      "README.md": [
        "# Co-Simulation Example",
        "",
        "This workspace demonstrates co-simulation between a **Modelica model** and a **WASM FMU**.",
        "",
        "## Files",
        "",
        "| File | Type | Description |",
        "|------|------|-------------|",
        "| `Controller.mo` | Modelica | PI controller with setpoint tracking |",
        "| `CosimSetup.mo` | Modelica | Wiring diagram connecting Controller ↔ SineWave |",
        "",
        "## Running the Co-Simulation",
        "",
        "1. Open the **Co-Simulation** panel in the sidebar",
        '2. Click **"Browser-Local"** to enable local mode',
        "3. Create a new session (start=0, stop=10, step=0.01)",
        "4. Open `Controller.mo` and click **Publish Model**",
        "5. Start the coupled simulation",
      ].join("\n"),
    },
    "uns-mqtt": {
      "DigitalTwin.mo": [
        'model DigitalTwin "Real-Time Digital Twin with UNS/MQTT"',
        '  parameter Real target_speed = 10.0 "Override via: .../cmd/DigitalTwin/target_speed";',
        '  Real speed(start=0) "Telemetry published to: .../data/DigitalTwin/speed";',
        "equation",
        "  der(speed) = (target_speed - speed) * 1.5;",
        "end DigitalTwin;\n",
      ].join("\n"),
      "hmi.html": [
        "<!DOCTYPE html>",
        "<html><head><title>HMI</title>",
        '<script src="https://unpkg.com/mqtt/dist/mqtt.min.js"></script>',
        "<style>body{font-family:sans-serif;text-align:center;padding-top:50px;} h1{font-size:3rem;}</style>",
        "</head><body>",
        "<h2>Conveyor Speed</h2>",
        '<h1 id="speed">0.00</h1>',
        "<p>Live telemetry via MQTT Unified Namespace</p>",
        "</body></html>",
      ].join("\n"),
      "README.md": [
        "# UNS / Real-Time MQTT Example",
        "",
        "This workspace demonstrates how to stream live telemetry from a Modelica simulation directly to an external HMI web app.",
      ].join("\n"),
    },
    "owl2-contradiction": {
      "constraints.owl": [
        "Prefix(mo: = <http://modelscript.org/modelica#>)",
        "Ontology(<http://modelscript.org/examples/contradiction>",
        "  Import(<http://modelscript.org/modelica#>)",
        "  Declaration(Class(mo:ElectricalDevice))",
        "  Declaration(Class(mo:MechanicalDevice))",
        "  DisjointClasses(mo:ElectricalDevice mo:MechanicalDevice)",
        "  Declaration(Class(mo:ElectroMechanicalDevice))",
        "  SubClassOf(mo:ElectroMechanicalDevice mo:ElectricalDevice)",
        "  SubClassOf(mo:ElectroMechanicalDevice mo:MechanicalDevice)",
        ")",
      ].join("\n"),
      "system.mo": [
        "// System model with an intentional semantic contradiction",
        "// Motor extends both ElectricalDevice and MechanicalDevice,",
        "// which are declared Disjoint in the OWL2 ontology constraints.owl",
        "",
        "class ElectricalDevice",
        '  parameter Real voltage_rating = 24.0 "Operating voltage [V]";',
        "end ElectricalDevice;",
        "",
        "class MechanicalDevice",
        '  parameter Real max_torque = 10.0 "Max torque [N.m]";',
        "end MechanicalDevice;",
        "",
        "// Contradiction: Motor is both ElectricalDevice and MechanicalDevice",
        "class Motor",
        "  extends ElectricalDevice;",
        "  extends MechanicalDevice;",
        '  parameter Real speed = 3000 "Rated speed [RPM]";',
        "end Motor;",
      ].join("\n"),
      "README.md": [
        "# Cross-Domain Contradiction Detection",
        "",
        "This example demonstrates how the OWL2 reasoner catches **semantic contradictions**",
        "between Modelica physical models and OWL2 domain constraints.",
        "",
        "## Scenario",
        "",
        "A system model defines `Motor` as both an `ElectricalDevice` and a `MechanicalDevice`.",
        "An OWL2 ontology declares these two classes **disjoint** - a component cannot be both.",
        "",
        "When the reasoner classifies the combined polyglot model, it detects the inconsistency",
        "and reports the contradiction with a justification chain.",
      ].join("\n"),
    },
    "owl2-fmea": {
      "control_system.mo": [
        "// Control system architecture for FMEA fault propagation analysis",
        "// Topology: sensor -> controller -> actuator -> plant",
        "",
        "connector Signal",
        "  Real val;",
        "end Signal;",
        "",
        "model Sensor",
        "  Signal out_port;",
        "equation",
        "  out_port.val = 1.0;",
        "end Sensor;",
        "",
        "model Controller",
        "  Signal in_port;",
        "  Signal out_port;",
        "equation",
        "  out_port.val = in_port.val * 2.0;",
        "end Controller;",
        "",
        "model Actuator",
        "  Signal in_port;",
        "  Signal out_port;",
        "equation",
        "  out_port.val = in_port.val * 0.5;",
        "end Actuator;",
        "",
        "model Plant",
        "  Signal in_port;",
        "  Real state;",
        "equation",
        "  der(state) = in_port.val;",
        "end Plant;",
        "",
        "model System",
        "  Sensor sensor1;",
        "  Controller controller1;",
        "  Actuator actuator1;",
        "  Plant plant1;",
        "equation",
        "  connect(sensor1.out_port, controller1.in_port);",
        "  connect(controller1.out_port, actuator1.in_port);",
        "  connect(actuator1.out_port, plant1.in_port);",
        "end System;",
      ].join("\n"),
      "fault_taxonomy.owl": [
        "Prefix(fmea: = <http://modelscript.org/fmea#>)",
        "Prefix(mo: = <http://modelscript.org/modelica#>)",
        "Ontology(<http://modelscript.org/examples/fmea>",
        "  Import(<http://modelscript.org/modelica#>)",
        "  Declaration(Class(fmea:FaultMode))",
        "  Declaration(Class(fmea:SensorDrift))",
        "  Declaration(Class(fmea:ActuatorStuck))",
        "  Declaration(Class(fmea:CommunicationLoss))",
        "  SubClassOf(fmea:SensorDrift fmea:FaultMode)",
        "  SubClassOf(fmea:ActuatorStuck fmea:FaultMode)",
        "  SubClassOf(fmea:CommunicationLoss fmea:FaultMode)",
        "  Declaration(Class(fmea:CriticalityLevel))",
        "  Declaration(NamedIndividual(fmea:High))",
        "  Declaration(NamedIndividual(fmea:Medium))",
        "  Declaration(NamedIndividual(fmea:Low))",
        "  ClassAssertion(fmea:CriticalityLevel fmea:High)",
        "  ClassAssertion(fmea:CriticalityLevel fmea:Medium)",
        "  ClassAssertion(fmea:CriticalityLevel fmea:Low)",
        "  Declaration(ObjectProperty(fmea:hasFaultMode))",
        "  Declaration(ObjectProperty(fmea:hasCriticality))",
        "  Declaration(ObjectProperty(mo:isConnectedTo))",
        "  SubObjectPropertyOf(mo:isConnectedTo mo:propagatesFaultTo)",
        "  TransitiveObjectProperty(mo:propagatesFaultTo)",
        ")",
      ].join("\n"),
      "README.md": [
        "# Fault Propagation Analysis (FMEA)",
        "",
        "This example demonstrates how the OWL2 reasoner traces **fault propagation paths**",
        "through a system's connection topology using transitive closure of the",
        "`isConnectedTo` object property.",
      ].join("\n"),
    },
    "owl2-manufacturing": {
      "drone.sysml": [
        "package DroneSupplyChain {",
        "  private import ScalarValues::*;",
        "",
        "  part def CarbonFiber;",
        "  part def TitaniumAlloy;",
        "  part def Aluminum6061;",
        "",
        "  part def DroneFrame {",
        "    doc /* Lightweight quadcopter frame requiring aerospace-grade materials */",
        "    part spar : TitaniumAlloy;",
        "    part shell : CarbonFiber;",
        "  }",
        "",
        "  part def MotorMount {",
        "    part bracket : Aluminum6061;",
        "  }",
        "",
        "  part def DroneAssembly {",
        "    part frame : DroneFrame;",
        "    part mount1 : MotorMount;",
        "    part mount2 : MotorMount;",
        "    part mount3 : MotorMount;",
        "    part mount4 : MotorMount;",
        "  }",
        "}",
      ].join("\n"),
      "supply_chain.owl": [
        "Prefix(mat: = <http://modelscript.org/materials#>)",
        "Prefix(mfg: = <http://modelscript.org/manufacturing#>)",
        "Prefix(supp: = <http://modelscript.org/suppliers#>)",
        "Prefix(sysml: = <http://modelscript.org/sysml2#>)",
        "Ontology(<http://modelscript.org/examples/supply_chain>",
        "  Import(<http://modelscript.org/sysml2#>)",
        "  Declaration(Class(mat:Material))",
        "  Declaration(Class(mat:Composite))",
        "  Declaration(Class(mat:MetalAlloy))",
        "  SubClassOf(mat:Composite mat:Material)",
        "  SubClassOf(mat:MetalAlloy mat:Material)",
        "  Declaration(Class(mat:CarbonFiber))",
        "  Declaration(Class(mat:TitaniumAlloy))",
        "  Declaration(Class(mat:Aluminum6061))",
        "  SubClassOf(mat:CarbonFiber mat:Composite)",
        "  SubClassOf(mat:TitaniumAlloy mat:MetalAlloy)",
        "  SubClassOf(mat:Aluminum6061 mat:MetalAlloy)",
        "  SubClassOf(sysml:CarbonFiber mat:CarbonFiber)",
        "  SubClassOf(sysml:TitaniumAlloy mat:TitaniumAlloy)",
        "  SubClassOf(sysml:Aluminum6061 mat:Aluminum6061)",
        "  Declaration(Class(supp:Supplier))",
        "  Declaration(Class(supp:ApprovedSupplier))",
        "  SubClassOf(supp:ApprovedSupplier supp:Supplier)",
        "  Declaration(NamedIndividual(supp:TorayAdvancedComposites))",
        "  Declaration(NamedIndividual(supp:ATI_Metals))",
        "  Declaration(NamedIndividual(supp:AlcoaAluminum))",
        "  ClassAssertion(supp:ApprovedSupplier supp:TorayAdvancedComposites)",
        "  ClassAssertion(supp:ApprovedSupplier supp:ATI_Metals)",
        "  ClassAssertion(supp:ApprovedSupplier supp:AlcoaAluminum)",
        "  Declaration(ObjectProperty(supp:suppliesMaterial))",
        "  ObjectPropertyAssertion(supp:suppliesMaterial supp:TorayAdvancedComposites mat:CarbonFiber)",
        "  ObjectPropertyAssertion(supp:suppliesMaterial supp:ATI_Metals mat:TitaniumAlloy)",
        "  ObjectPropertyAssertion(supp:suppliesMaterial supp:AlcoaAluminum mat:Aluminum6061)",
        "  Declaration(Class(mfg:Process))",
        "  Declaration(Class(mfg:AutoclaveCuring))",
        "  Declaration(Class(mfg:CNC_Milling_5Axis))",
        "  Declaration(Class(mfg:CNC_Milling_3Axis))",
        "  SubClassOf(mfg:AutoclaveCuring mfg:Process)",
        "  SubClassOf(mfg:CNC_Milling_5Axis mfg:Process)",
        "  SubClassOf(mfg:CNC_Milling_3Axis mfg:Process)",
        "  Declaration(ObjectProperty(mfg:requiresProcess))",
        "  ObjectPropertyAssertion(mfg:requiresProcess mat:CarbonFiber mfg:AutoclaveCuring)",
        "  ObjectPropertyAssertion(mfg:requiresProcess mat:TitaniumAlloy mfg:CNC_Milling_5Axis)",
        "  ObjectPropertyAssertion(mfg:requiresProcess mat:Aluminum6061 mfg:CNC_Milling_3Axis)",
        ")",
      ].join("\n"),
      "README.md": [
        "# Supply Chain Manufacturability",
        "",
        "This example demonstrates how OWL2 reasoning validates that a system design",
        "is **manufacturable** by checking whether all specified materials and processes",
        "are available in the supply chain ontology.",
      ].join("\n"),
    },
    "owl2-subsumption": {
      "components.mo": [
        "// Actuator component library for subsumption reasoning",
        "",
        "model Actuator",
        '  "Base class for all actuators"',
        '  parameter Real V_supply = 24 "Supply voltage [V]";',
        '  parameter Real I_max = 10 "Maximum current [A]";',
        "end Actuator;",
        "",
        "model ServoMotor",
        '  "High-precision servo motor - high voltage"',
        "  extends Actuator(V_supply = 380, I_max = 5);",
        '  parameter Real resolution = 0.001 "Angular resolution [rad]";',
        '  parameter Real tau_max = 15 "Maximum torque [N.m]";',
        "end ServoMotor;",
        "",
        "model StepperMotor",
        '  "Stepper motor - low voltage"',
        "  extends Actuator(V_supply = 48, I_max = 3);",
        '  parameter Integer steps_per_rev = 200 "Steps per revolution";',
        '  parameter Real tau_hold = 2.5 "Holding torque [N.m]";',
        "end StepperMotor;",
        "",
        "model LinearActuator",
        '  "Linear actuator - medium voltage"',
        "  extends Actuator(V_supply = 120, I_max = 8);",
        '  parameter Real stroke = 0.3 "Maximum stroke [m]";',
        '  parameter Real F_max = 500 "Maximum force [N]";',
        "end LinearActuator;",
      ].join("\n"),
      "requirements.sysml": [
        "package ActuatorRequirements {",
        "  private import ScalarValues::*;",
        "",
        "  requirement def HighVoltageRequirement {",
        "    doc /* Actuator shall operate at high voltage (>= 200V) */",
        "    attribute minVoltage : Real = 200.0;",
        "  }",
        "",
        "  requirement def PrecisionRequirement {",
        "    doc /* Actuator shall provide positioning resolution <= 0.01 rad */",
        "    attribute maxResolution : Real = 0.01;",
        "  }",
        "",
        "  part def HighVoltageActuator {",
        "    attribute voltage : Real;",
        "  }",
        "}",
      ].join("\n"),
      "taxonomy.owl": [
        "Prefix(mo: = <http://modelscript.org/modelica#>)",
        "Prefix(sysml: = <http://modelscript.org/sysml2#>)",
        "Ontology(<http://modelscript.org/examples/subsumption>",
        "  Import(<http://modelscript.org/modelica#>)",
        "  Import(<http://modelscript.org/sysml2#>)",
        "  Declaration(Class(mo:Actuator))",
        "  Declaration(Class(mo:ServoMotor))",
        "  Declaration(Class(mo:StepperMotor))",
        "  Declaration(Class(mo:LinearActuator))",
        "  SubClassOf(mo:ServoMotor mo:Actuator)",
        "  SubClassOf(mo:StepperMotor mo:Actuator)",
        "  SubClassOf(mo:LinearActuator mo:Actuator)",
        "  Declaration(Class(mo:HighVoltageActuator))",
        "  SubClassOf(mo:HighVoltageActuator mo:Actuator)",
        "  SubClassOf(mo:ServoMotor mo:HighVoltageActuator)",
        "  SubClassOf(sysml:HighVoltageActuator mo:HighVoltageActuator)",
        "  Declaration(DataProperty(mo:supplyVoltage))",
        '  DataPropertyAssertion(mo:supplyVoltage mo:ServoMotor "380")',
        '  DataPropertyAssertion(mo:supplyVoltage mo:StepperMotor "48")',
        '  DataPropertyAssertion(mo:supplyVoltage mo:LinearActuator "120")',
        ")",
      ].join("\n"),
      "README.md": [
        "# Automated Component Selection via Subsumption",
        "",
        "This example demonstrates how OWL2 **subsumption reasoning** can automatically",
        "identify which Modelica components satisfy a set of requirements.",
      ].join("\n"),
    },
    "owl2-units": {
      "unit_ontology.owl": [
        "Prefix(mo: = <http://modelscript.org/modelica#>)",
        "Prefix(unit: = <http://modelscript.org/units#>)",
        "Ontology(<http://modelscript.org/examples/units>",
        "  Import(<http://modelscript.org/modelica#>)",
        "  Declaration(Class(unit:SIUnit))",
        "  Declaration(Class(unit:PressureUnit))",
        "  Declaration(Class(unit:TemperatureUnit))",
        "  Declaration(Class(unit:ForceUnit))",
        "  Declaration(Class(unit:LengthUnit))",
        "  SubClassOf(unit:PressureUnit unit:SIUnit)",
        "  SubClassOf(unit:TemperatureUnit unit:SIUnit)",
        "  SubClassOf(unit:ForceUnit unit:SIUnit)",
        "  SubClassOf(unit:LengthUnit unit:SIUnit)",
        "  DisjointClasses(unit:PressureUnit unit:TemperatureUnit)",
        "  DisjointClasses(unit:PressureUnit unit:ForceUnit)",
        "  DisjointClasses(unit:TemperatureUnit unit:LengthUnit)",
        "  Declaration(NamedIndividual(unit:Pascal))",
        "  Declaration(NamedIndividual(unit:Kelvin))",
        "  Declaration(NamedIndividual(unit:Newton))",
        "  Declaration(NamedIndividual(unit:Meter))",
        "  ClassAssertion(unit:PressureUnit unit:Pascal)",
        "  ClassAssertion(unit:TemperatureUnit unit:Kelvin)",
        "  ClassAssertion(unit:ForceUnit unit:Newton)",
        "  ClassAssertion(unit:LengthUnit unit:Meter)",
        "  Declaration(ObjectProperty(mo:hasOutputUnit))",
        "  Declaration(ObjectProperty(mo:hasInputUnit))",
        "  ObjectPropertyAssertion(mo:hasOutputUnit mo:pressureSensor unit:Pascal)",
        "  ObjectPropertyAssertion(mo:hasInputUnit mo:tempController unit:Kelvin)",
        "  Declaration(NamedIndividual(mo:pressureSensor))",
        "  Declaration(NamedIndividual(mo:tempController))",
        ")",
      ].join("\n"),
      "units_model.mo": [
        "// Semantic Unit Verification - Deliberate unit mismatch",
        "// This model connects a pressure output to a temperature input",
        "",
        "connector PressurePort",
        '  Real p "Pressure [Pa]";',
        "end PressurePort;",
        "",
        "connector TemperaturePort",
        '  Real T "Temperature [K]";',
        "end TemperaturePort;",
        "",
        "model PressureSensor",
        '  "Outputs pressure in Pascals"',
        "  PressurePort output_port;",
        "equation",
        "  output_port.p = 101325; // atmospheric pressure",
        "end PressureSensor;",
        "",
        "model TemperatureController",
        '  "Expects temperature input in Kelvins"',
        "  TemperaturePort input_port;",
        '  parameter Real setpoint = 350 "Target temperature [K]";',
        "  Real error;",
        "equation",
        "  error = setpoint - input_port.T;",
        "end TemperatureController;",
        "",
        "model BadSystem",
        '  "Connects pressure output to temperature input - unit mismatch!"',
        "  PressureSensor pressureSensor;",
        "  TemperatureController tempController;",
        "equation",
        "  // This is semantically wrong: Pa != K",
        "  tempController.input_port.T = pressureSensor.output_port.p;",
        "end BadSystem;",
      ].join("\n"),
      "README.md": [
        "# Semantic Unit Verification",
        "",
        "This example demonstrates how OWL2 reasoning can catch **dimensional analysis errors**",
        "by encoding SI unit constraints as class restrictions and verifying that connected",
        "ports have compatible units.",
      ].join("\n"),
    },
  };

  if (template === "stress-test") {
    const massiveModelRows = [];
    massiveModelRows.push('model MassiveModel "A massive model with thousands of elements"');
    for (let i = 0; i < 5000; i++) {
      massiveModelRows.push(`  Real v${i}(start = ${i});`);
    }
    massiveModelRows.push("equation");
    for (let i = 0; i < 4999; i++) {
      massiveModelRows.push(`  der(v${i}) = v${i + 1} - v${i};`);
    }
    massiveModelRows.push(`  der(v4999) = -v4999;`);
    massiveModelRows.push("end MassiveModel;\n");

    const entries: [vscode.Uri, Uint8Array][] = [];
    entries.push([joinPath(workspaceUri, "MassiveModel.mo"), encoder.encode(massiveModelRows.join("\n"))]);

    for (let i = 0; i < 5; i++) {
      // Use SysML2 ':>' syntax for inheritance to avoid syntax errors
      const extendsClause = i > 0 ? `:> Component_${String(i - 1).padStart(3, "0")} ` : "";
      const content = `package Component_${String(i).padStart(3, "0")} {\n  part def Component_${String(i).padStart(3, "0")} ${extendsClause}{\n    attribute localValue : Real = ${i}.0;\n  }\n}\n`;
      entries.push([joinPath(workspaceUri, `Component_${String(i).padStart(3, "0")}.sysml`), encoder.encode(content)]);
    }
    if (memFs.writeFiles) {
      memFs.writeFiles(entries);
    } else {
      for (const [uri, data] of entries) {
        memFs.writeFile(uri, data);
      }
    }
    console.log("[blank-project] Scaffolded stress-test workspace files.");
    return;
  }

  const files = templates[template];
  if (files) {
    for (const [name, content] of Object.entries(files)) {
      const fileUri = joinPath(workspaceUri, name);
      memFs.writeFile(fileUri, encoder.encode(content));
    }
    console.log(`[blank-project] Scaffolded ${Object.keys(files).length} template file(s) for '${template}'`);
  }
}

export function getTemplatePrimaryFile(template: string): string {
  const map: Record<string, string> = {
    // Basic templates
    empty: "HelloWorld.mo",
    blank: "HelloWorld.mo",
    "bouncing-ball": "BouncingBall.mo",
    rlc: "RLC.mo",
    script: "simulate.mos",
    notebook: "demo.monb",
    "stress-test": "MassiveModel.mo",

    // Digital Thread & CAD / CAE
    "drone-chassis": "DroneSimulation.mo",
    cad: "drone_architecture.sysml",
    "cad-assembly": "RobotAssembly.mo",
    "drone-meshing": "README.md",
    "drone-fea": "DroneFEA.mo",
    "drone-cfd": "DroneFlight.mo",
    "modelica-procedural-cad": "DroneCAD.mo",
    "assembly-to-multibody": "SimplePendulum.step",
    "injection-molding-cosim": "Manufacturing.mo",

    // Systems Engineering & MBSE
    sysml2: "VehicleSystem.sysml",
    "simulation-verification": "BatteryArchitecture.sysml",
    "mbse-verification": "VerificationReport.md",
    "hardware-ci": "SystemIntegration.mo",

    // Simulation, Optimization & Surrogate
    fmi2: "System.mo",
    fmi3: "System.mo",
    surrogate: "BouncingBall.mo",
    "cfd-verification": "ThermalSystem.mo",
    calibration: "SpringDamper.mo",
    "data-driven-calibration": "Suspension.mo",
    "multi-fidelity-binding": "PropellerDynamics.mo",
    "optimica-polyglot": "RocketSled.mo",
    uncertainty: "Projectile.mo",
    cosim: "CosimSetup.mo",
    "uns-mqtt": "DigitalTwin.mo",

    // Semantic Web & OWL2
    "owl2-contradiction": "constraints.owl",
    "owl2-fmea": "control_system.mo",
    "owl2-manufacturing": "drone.sysml",
    "owl2-subsumption": "components.mo",
    "owl2-units": "units_model.mo",

    // Backwards-compatibility aliases
    "pendulum-3d": "DoublePendulum.mo",
    "vehicle-architecture": "VehicleSystem.sysml",
  };
  return map[template] ?? "HelloWorld.mo";
}
