; folds.scm — Auto-generated by @modelscript/compiler
; Language: modelica

; ─── Foldable blocks ──────────────────────────────────────────────
[
  (CompoundImportClause)
  (ArrayConstructor)
  (IDENT)
] @fold

