; indents.scm — Auto-generated by @modelscript/language
; Language: modelica

; ─── Indent on block open ─────────────────────────────────────────
[
  (CompoundImportClause)
  (ArrayConstructor)
  (IDENT)
] @indent.begin

; ─── Dedent on close ──────────────────────────────────────────────
"}" @indent.end
"]" @indent.end
")" @indent.end

