// SPDX-License-Identifier: AGPL-3.0-or-later

import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { Interval, TaylorModel, TaylorModelFlowpipeSolver } from "../src/analysis/wasm_taylor_model.js";

describe("Elementary Transcendental Taylor Models & Adaptive Step Control Suite", () => {
  it("should compute validated exponential Taylor models with Lagrange remainder bounds", () => {
    // 1 variable x in [-0.4, 0.4], order 3
    const domain = [new Interval(-0.4, 0.4)];
    const x = TaylorModel.variable(0, domain, 3, 0.0);

    // Compute exp(x)
    const expX = x.exp();

    // Constant term should be 1.0 (e^0)
    assert(Math.abs(expX.get([0]) - 1.0) < 1e-12);
    // Linear term should be 1.0
    assert(Math.abs(expX.get([1]) - 1.0) < 1e-12);
    // Quadratic term should be 0.5
    assert(Math.abs(expX.get([2]) - 0.5) < 1e-12);
    // Cubic term should be 1/6 approx 0.166667
    assert(Math.abs(expX.get([3]) - 1.0 / 6.0) < 1e-12);

    // Remainder interval should be non-zero and tightly bounded
    assert(expX.remainder.width > 0);
    assert(expX.remainder.width < 0.05);

    // Guaranteed range evaluation must contain true values at x = -0.4, 0, 0.4
    const range = expX.evaluateRange();
    assert(range.lo <= Math.exp(-0.4), `range.lo ${range.lo} > exp(-0.4) ${Math.exp(-0.4)}`);
    assert(range.hi >= Math.exp(0.4), `range.hi ${range.hi} < exp(0.4) ${Math.exp(0.4)}`);
  });

  it("should compute validated sine and cosine Taylor models", () => {
    // 1 variable x in [-0.5, 0.5], order 3
    const domain = [new Interval(-0.5, 0.5)];
    const x = TaylorModel.variable(0, domain, 3, 0.0);

    // sin(x) approx x - x^3 / 6
    const sinX = x.sin();
    assert(Math.abs(sinX.get([0]) - 0.0) < 1e-12);
    assert(Math.abs(sinX.get([1]) - 1.0) < 1e-12);
    assert(Math.abs(sinX.get([2]) - 0.0) < 1e-12);
    assert(Math.abs(sinX.get([3]) - -1.0 / 6.0) < 1e-12);

    const sinRange = sinX.evaluateRange();
    assert(sinRange.lo <= Math.sin(-0.5));
    assert(sinRange.hi >= Math.sin(0.5));

    // cos(x) approx 1 - x^2 / 2
    const cosX = x.cos();
    assert(Math.abs(cosX.get([0]) - 1.0) < 1e-12);
    assert(Math.abs(cosX.get([1]) - 0.0) < 1e-12);
    assert(Math.abs(cosX.get([2]) - -0.5) < 1e-12);

    const cosRange = cosX.evaluateRange();
    assert(cosRange.lo <= Math.cos(0.5));
    assert(cosRange.hi >= Math.cos(0.0));
  });

  it("should perform adaptive time-stepping to control remainder box error on nonlinear dynamics", () => {
    // Nonlinear system: dx/dt = -x + 0.5 * x^2
    // Stiff / rapid changes occur near large x
    const initialEnclosure = [new Interval(0.8, 1.2)];
    const nominalInitial = [1.0];
    const tSpan: [number, number] = [0, 1.0];
    const initialDt = 0.1;

    const dynamics = (_t: TaylorModel, y: TaylorModel[]) => {
      // dy/dt = -y + 0.5 * y^2
      const linear = y[0]!.scale(-1.0);
      const quad = y[0]!.mul(y[0]!).scale(0.5);
      return [linear.add(quad)];
    };

    const result = TaylorModelFlowpipeSolver.solve({
      dynamics,
      initialEnclosure,
      nominalInitial,
      tSpan,
      dt: initialDt,
      order: 2,
      adaptive: true,
      tol: 1e-3,
      minDt: 1e-4,
      maxDt: 0.5,
      requirements: [
        {
          stateIndex: 0,
          stateName: "x",
          operator: "<=",
          limitValue: 1.5,
        },
        {
          stateIndex: 0,
          stateName: "x",
          operator: ">=",
          limitValue: 0.0,
        },
      ],
    });

    assert(result.isCertifiedSafe, `Expected certified safe but got: ${result.summary}`);
    assert(result.steps.length > 2, "Expected multiple steps generated by adaptive solver");

    // Check that nominal points stay within tubes throughout
    for (const s of result.steps) {
      assert(s.tubes[0]!.lo <= s.nominal[0]!);
      assert(s.tubes[0]!.hi >= s.nominal[0]!);
    }
  });
});
