// SPDX-License-Identifier: AGPL-3.0-or-later

import { ModelicaUnaryOperator } from "@modelscript/modelica/ast";
import type { ModelicaDAE, ModelicaExpression } from "@modelscript/symbolics";
import {
  ModelicaBinaryExpression,
  ModelicaBooleanLiteral,
  ModelicaFunctionCallExpression,
  ModelicaIfElseExpression,
  ModelicaIntegerLiteral,
  ModelicaNameExpression,
  ModelicaRealLiteral,
  ModelicaSimpleEquation,
  ModelicaStringLiteral,
  ModelicaUnaryExpression,
} from "@modelscript/symbolics";
import type { FmuOptions, FmuResult } from "./fmi.js";
import { binaryOpToJs, mapFunctionNameJs, sanitizeIdentifier } from "./transpiler-utils.js";

/**
 * Generate AssemblyScript compatible source file from a DAE and FMU result.
 * This can be compiled directly in the browser to WebAssembly using the AssemblyScript compiler.
 */
export function generateFmuAsSources(dae: ModelicaDAE, fmuResult: FmuResult, options: FmuOptions): string {
  const id = options.modelIdentifier;
  const vars = fmuResult.scalarVariables;
  const nStates = fmuResult.modelStructure.derivatives.length;
  const nVars = vars.length;

  return generateModelAs(id, nVars, nStates, dae, fmuResult);
}

function exprToAs(expr: ModelicaExpression): string {
  if (expr instanceof ModelicaRealLiteral) {
    const s = expr.value.toString();
    if (!s.includes(".") && !s.includes("e") && !s.includes("E")) return s + ".0";
    return s;
  }
  if (expr instanceof ModelicaIntegerLiteral) return `${expr.value}.0`; // Cast to f64 implicitly via float string
  if (expr instanceof ModelicaBooleanLiteral) return expr.value ? "1.0" : "0.0";
  if (expr instanceof ModelicaStringLiteral) return `0.0 /* string literals unsupported in AS f64 return */`;
  if (expr instanceof ModelicaNameExpression) return varToAs(expr.name);
  if (expr instanceof ModelicaUnaryExpression) {
    const op = expr.operator === ModelicaUnaryOperator.UNARY_MINUS ? "-" : "!";
    return `(${op}${exprToAs(expr.operand)})`;
  }
  if (expr instanceof ModelicaBinaryExpression) {
    const lhs = exprToAs(expr.operand1);
    const rhs = exprToAs(expr.operand2);
    const op = binaryOpToJs(expr.operator);
    if (op === "pow") return `Math.pow(${lhs}, ${rhs})`;
    return `(${lhs} ${op} ${rhs})`;
  }
  if (expr instanceof ModelicaFunctionCallExpression) {
    if (expr.functionName === "initial") return "(isInitPhase ? 1.0 : 0.0)";
    if (expr.functionName === "terminal") return "0.0";
    if (expr.functionName === "assert" && expr.args.length >= 2) {
      const cond = exprToAs(expr.args[0] as ModelicaExpression);
      return `((${cond}) ? 0.0 : (terminate = true, 0.0))`;
    }
    const args = expr.args.map((a: ModelicaExpression) => exprToAs(a)).join(", ");
    const fname = mapFunctionNameJs(expr.functionName);
    return `${fname}(${args})`;
  }
  if (expr instanceof ModelicaIfElseExpression) {
    const cond = exprToAs(expr.condition);
    const then = exprToAs(expr.thenExpression);
    const els = exprToAs(expr.elseExpression);
    if (expr.elseIfClauses.length > 0) {
      let result = `((${cond}) != 0.0 ? ${then} : `;
      for (const clause of expr.elseIfClauses) {
        result += `(${exprToAs(clause.condition)}) != 0.0 ? ${exprToAs(clause.expression)} : `;
      }
      result += `${els})`;
      return result;
    }
    return `((${cond}) != 0.0 ? ${then} : ${els})`;
  }
  if (expr && typeof expr === "object" && "name" in expr) {
    return varToAs((expr as { name: string }).name);
  }
  return "0.0";
}

function varToAs(name: string): string {
  if (name === "time") return "modelTime";
  return `vars[VR_${sanitizeIdentifier(name).toUpperCase()}]`;
}

function generateModelAs(id: string, nVars: number, nStates: number, dae: ModelicaDAE, result: FmuResult): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by ModelScript — AssemblyScript FMI");
  lines.push("");

  // Variable Constants
  for (const sv of result.scalarVariables) {
    const cName = sanitizeIdentifier(sv.name).toUpperCase();
    lines.push(`const VR_${cName}: i32 = ${sv.valueReference};`);
  }

  lines.push("");
  lines.push(`export const vars = new Float64Array(${nVars + 1});`);
  lines.push(`export const states = new Float64Array(${nStates + 1});`);
  lines.push(`export const derivatives = new Float64Array(${nStates + 1});`);
  lines.push(`export let modelTime: f64 = 0.0;`);
  lines.push(`export let isInitPhase: boolean = true;`);
  lines.push(`export let terminate: boolean = false;`);
  lines.push("");

  lines.push("export function initModel(): void {");
  lines.push("  isInitPhase = true;");
  lines.push("  modelTime = 0.0;");
  lines.push("  terminate = false;");

  // Initial parameters
  for (const sv of result.scalarVariables) {
    if (sv.start !== undefined) {
      lines.push(`  vars[${sv.valueReference}] = ${sv.start};`);
    }
  }

  lines.push("}");
  lines.push("");

  lines.push("export function getDerivatives(): void {");

  // Extract state variables and mapping
  const derVRs = result.modelStructure.derivatives;
  const stateVRs: number[] = [];
  const derVars = result.scalarVariables.filter((sv) => sv.name.startsWith("der("));

  for (const dv of derVars) {
    if (dv.derivative !== undefined) {
      stateVRs.push(dv.derivative);
    }
  }

  for (let i = 0; i < stateVRs.length; i++) {
    lines.push(`  states[${i}] = vars[${stateVRs[i]}];`);
  }

  for (const eq of dae.equations) {
    if (eq instanceof ModelicaSimpleEquation && eq.expression1 instanceof ModelicaNameExpression) {
      lines.push(`  ${varToAs(eq.expression1.name)} = ${exprToAs(eq.expression2)};`);
    }
  }

  for (let i = 0; i < derVRs.length; i++) {
    lines.push(`  derivatives[${i}] = vars[${derVRs[i]}];`);
  }

  lines.push("}");
  lines.push("");

  lines.push("export function doStep(currentCommunicationPoint: f64, communicationStepSize: f64): void {");
  lines.push("  isInitPhase = false;");
  lines.push("  modelTime = currentCommunicationPoint;");
  lines.push("  let dt: f64 = communicationStepSize;");
  lines.push("  ");
  lines.push("  // Basic explicit forward Euler step in AssemblyScript");
  lines.push("  getDerivatives();");
  for (let i = 0; i < stateVRs.length; i++) {
    lines.push(`  vars[${stateVRs[i]}] = vars[${stateVRs[i]}] + derivatives[${i}] * dt;`);
  }
  lines.push("  modelTime += dt;");
  lines.push("  getDerivatives();");
  lines.push("}");
  lines.push("");

  lines.push("export function getVar(vr: i32): f64 {");
  lines.push("  return vars[vr];");
  lines.push("}");
  lines.push("");

  lines.push("export function setVar(vr: i32, value: f64): void {");
  lines.push("  vars[vr] = value;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
