// SPDX-License-Identifier: AGPL-3.0-or-later

import { type ArenaDAEBuilder, BinOp, EqKind, ExprKind, UnaryOp } from "@modelscript/compiler";

import type { FmuOptions, FmuResult } from "./fmi.js";
import { binaryOpToJs, mapFunctionNameJs, sanitizeIdentifier } from "./transpiler-utils.js";

/**
 * Generate AssemblyScript compatible source file from a DAE and FMU result.
 * This can be compiled directly in the browser to WebAssembly using the AssemblyScript compiler.
 */
export function generateFmuAsSources(dae: ArenaDAEBuilder, fmuResult: FmuResult, options: FmuOptions): string {
  const id = options.modelIdentifier;
  const vars = fmuResult.scalarVariables;
  const nStates = fmuResult.modelStructure.derivatives.length;
  const nVars = vars.length;

  return generateModelAs(id, nVars, nStates, dae, fmuResult);
}

function exprToAs(dae: ArenaDAEBuilder, id: number): string {
  if (id < 0) return "0.0";
  switch (dae.getExprKind(id)) {
    case ExprKind.RealLiteral: {
      const val = dae.getExprRealValue(id);
      const s = val.toString();
      if (!s.includes(".") && !s.includes("e") && !s.includes("E")) return s + ".0";
      return s;
    }
    case ExprKind.IntLiteral:
      return `${dae.getExprData1(id)}.0`; // Cast to f64 implicitly via float string
    case ExprKind.BoolLiteral:
      return dae.getExprData1(id) !== 0 ? "1.0" : "0.0";
    case ExprKind.StringLiteral:
      return `0.0 /* string literals unsupported in AS f64 return */`;
    case ExprKind.Name:
      return varToAs(dae.interner.resolve(dae.getExprData1(id)));
    case ExprKind.Unary: {
      const uop = dae.getExprData1(id) as UnaryOp;
      const op = uop === UnaryOp.Negate ? "-" : "!";
      return `(${op}${exprToAs(dae, dae.getExprLeft(id))})`;
    }
    case ExprKind.Negate:
      return `(-${exprToAs(dae, dae.getExprLeft(id))})`;
    case ExprKind.Binary: {
      const op = dae.getExprData1(id) as BinOp;
      const lhs = exprToAs(dae, dae.getExprLeft(id));
      const rhs = exprToAs(dae, dae.getExprRight(id));
      const opStr = binaryOpToJs(op);
      if (opStr === "pow") return `Math.pow(${lhs}, ${rhs})`;
      return `(${lhs} ${opStr} ${rhs})`;
    }
    case ExprKind.Call: {
      const fname = dae.interner.resolve(dae.getExprData1(id));
      const argCount = dae.getExprRight(id);
      if (fname === "initial") return "(isInitPhase ? 1.0 : 0.0)";
      if (fname === "terminal") return "0.0";
      if (fname === "assert" && argCount >= 2) {
        const cond = exprToAs(dae, dae.getExprLeft(id));
        return `((${cond}) ? 0.0 : (terminate = true, 0.0))`;
      }
      const args: string[] = [];
      for (let i = 0; i < argCount; i++) {
        args.push(exprToAs(dae, dae.getExprLeft(id + i)));
      }
      const mappedName = mapFunctionNameJs(fname);
      return `${mappedName}(${args.join(", ")})`;
    }
    case ExprKind.IfElse: {
      const cond = exprToAs(dae, dae.getExprData1(id));
      const then = exprToAs(dae, dae.getExprLeft(id));
      const els = exprToAs(dae, dae.getExprRight(id));
      return `((${cond}) != 0.0 ? ${then} : ${els})`;
    }
    default:
      return "0.0";
  }
}

function varToAs(name: string): string {
  if (name === "time") return "modelTime";
  return `vars[VR_${sanitizeIdentifier(name).toUpperCase()}]`;
}

function conditionToZeroCrossingAs(dae: ArenaDAEBuilder, id: number): string {
  if (id < 0) return "0.0";
  if (dae.getExprKind(id) === ExprKind.Binary) {
    const op = dae.getExprData1(id) as BinOp;
    if (op === BinOp.Lt || op === BinOp.Lte) {
      const lhs = exprToAs(dae, dae.getExprLeft(id));
      const rhs = exprToAs(dae, dae.getExprRight(id));
      return `(${rhs}) - (${lhs})`;
    } else if (op === BinOp.Gt || op === BinOp.Gte) {
      const lhs = exprToAs(dae, dae.getExprLeft(id));
      const rhs = exprToAs(dae, dae.getExprRight(id));
      return `(${lhs}) - (${rhs})`;
    }
  }
  return `(${exprToAs(dae, id)} != 0.0 ? 1.0 : -1.0)`;
}

function extractAssignmentTarget(dae: ArenaDAEBuilder, id: number): string | null {
  if (id >= 0 && dae.getExprKind(id) === ExprKind.Name) {
    return dae.interner.resolve(dae.getExprData1(id));
  }
  return null;
}

function generateModelAs(id: string, nVars: number, nStates: number, dae: ArenaDAEBuilder, result: FmuResult): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by ModelScript — AssemblyScript FMI");
  lines.push("");

  // Variable Constants
  for (const sv of result.scalarVariables) {
    const cName = sanitizeIdentifier(sv.name).toUpperCase();
    lines.push(`const VR_${cName}: i32 = ${sv.valueReference};`);
  }

  lines.push("");
  lines.push(`export const vars = new Float64Array(${nVars + 1});`);
  lines.push(`export const states = new Float64Array(${nStates + 1});`);
  lines.push(`export const derivatives = new Float64Array(${nStates + 1});`);
  lines.push(`export let modelTime: f64 = 0.0;`);
  lines.push(`export let isInitPhase: boolean = true;`);
  lines.push(`export let terminate: boolean = false;`);
  lines.push(`export let h: f64 = 1e-6;`);
  lines.push(``);
  for (let i = 0; i < 7; i++) {
    lines.push(`const k${i}: Float64Array = new Float64Array(${nStates + 1});`);
  }
  lines.push(`const yTemp: Float64Array = new Float64Array(${nStates + 1});`);
  lines.push(`const yNew: Float64Array = new Float64Array(${nStates + 1});`);

  const nEventIndicators = dae.eventIndicatorExprIds.length;
  let nWhenConditions = 0;
  for (let idx = 0; idx < dae.eqCount; idx++) {
    if (dae.getEqKind(idx) === EqKind.When) {
      const meta = dae.getWhenEquationMeta(idx);
      if (meta) nWhenConditions += 1 + meta.elseWhenClauses.length;
    }
  }
  lines.push(`export const eventIndicators = new Float64Array(${nEventIndicators + 1});`);
  lines.push(`export const zPrev = new Float64Array(${nEventIndicators + 1});`);
  lines.push(`export const whenPrev = new Float64Array(${nWhenConditions + 1});`);
  lines.push(``);

  lines.push("export function initModel(): void {");
  lines.push("  isInitPhase = true;");
  lines.push("  modelTime = 0.0;");
  lines.push("  terminate = false;");

  // Initial parameters
  for (const sv of result.scalarVariables) {
    if (sv.start !== undefined) {
      lines.push(`  vars[${sv.valueReference}] = ${sv.start};`);
    }
  }

  lines.push("}");
  lines.push("");

  lines.push("export function getDerivatives(): void {");

  // Extract state variables and mapping
  const derVRs = result.modelStructure.derivatives;
  const stateVRs: number[] = [];
  const derVars = result.scalarVariables.filter((sv) => sv.name.startsWith("der("));

  for (const dv of derVars) {
    if (dv.derivative !== undefined) {
      stateVRs.push(dv.derivative);
    }
  }

  for (let i = 0; i < stateVRs.length; i++) {
    lines.push(`  states[${i}] = vars[${stateVRs[i]}];`);
  }

  for (let idx = 0; idx < dae.eqCount; idx++) {
    if (dae.getEqKind(idx) !== EqKind.Simple) continue;
    const lhs = dae.getEqLhs(idx);
    const rhs = dae.getEqRhs(idx);
    if (dae.getExprKind(lhs) === ExprKind.Name) {
      const name = dae.interner.resolve(dae.getExprData1(lhs));
      lines.push(`  ${varToAs(name)} = ${exprToAs(dae, rhs)};`);
    }
  }

  for (let i = 0; i < derVRs.length; i++) {
    lines.push(`  derivatives[${i}] = vars[${derVRs[i]}];`);
  }

  lines.push("}");
  lines.push("");

  lines.push("export function getEventIndicators(): void {");
  for (let i = 0; i < dae.eventIndicatorExprIds.length; i++) {
    const indicator = dae.eventIndicatorExprIds[i];
    if (indicator !== undefined && indicator >= 0) {
      lines.push(`  eventIndicators[${i}] = ${exprToAs(dae, indicator)};`);
    }
  }
  lines.push("}");
  lines.push("");

  lines.push("export function eventUpdate(): void {");
  const whenEqIdxs: number[] = [];
  for (let idx = 0; idx < dae.eqCount; idx++) {
    if (dae.getEqKind(idx) === EqKind.When) whenEqIdxs.push(idx);
  }
  let whenIdx = 0;
  for (const eqIdx of whenEqIdxs) {
    const weq = dae.getWhenEquationMeta(eqIdx);
    if (!weq) continue;

    const processBlock = (condExprId: number, bodyEqs: { kind: EqKind; lhsExprId: number; rhsExprId: number }[]) => {
      const condAs = conditionToZeroCrossingAs(dae, condExprId);
      lines.push(`  if (${condAs} > 0.0 && whenPrev[${whenIdx}] <= 0.0) {`);
      for (const bodyEq of bodyEqs) {
        if (bodyEq.kind === EqKind.Simple) {
          const lhsName = extractAssignmentTarget(dae, bodyEq.lhsExprId);
          if (lhsName) lines.push(`    ${varToAs(lhsName)} = ${exprToAs(dae, bodyEq.rhsExprId)};`);
        } else if (bodyEq.kind === EqKind.FunctionCall) {
          if (dae.getExprKind(bodyEq.lhsExprId) === ExprKind.Call) {
            const fname = dae.interner.resolve(dae.getExprData1(bodyEq.lhsExprId));
            if (fname === "reinit") {
              const stateName = dae.interner.resolve(dae.getExprData1(dae.getExprLeft(bodyEq.lhsExprId)));
              lines.push(`    ${varToAs(stateName)} = ${exprToAs(dae, dae.getExprLeft(bodyEq.lhsExprId + 1))};`);
            }
          }
        }
      }
      lines.push(`  }`);
      lines.push(`  whenPrev[${whenIdx}] = ${condAs};`);
      whenIdx++;
    };

    processBlock(weq.conditionExprId, weq.bodyEquations);
    for (const clause of weq.elseWhenClauses) {
      processBlock(clause.conditionExprId, clause.bodyEquations);
    }
  }
  lines.push("}");
  lines.push("");

  lines.push("export function doStep(currentCommunicationPoint: f64, communicationStepSize: f64): void {");
  lines.push("  isInitPhase = false;");
  lines.push("  let t: f64 = currentCommunicationPoint;");
  lines.push("  let tEnd: f64 = t + communicationStepSize;");
  lines.push("  ");
  if (nEventIndicators > 0) {
    lines.push("  getEventIndicators();");
    lines.push(`  for (let i = 0; i < ${nEventIndicators}; i++) zPrev[i] = eventIndicators[i];`);
  }
  lines.push("  while (t < tEnd - 1e-15) {");
  lines.push("    if (t + h > tEnd) h = tEnd - t;");
  lines.push("    if (h < 1e-15) break;");
  lines.push("    ");
  lines.push("    modelTime = t;");
  lines.push("    getDerivatives();");
  for (let i = 0; i < stateVRs.length; i++) {
    lines.push(`    k0[${i}] = derivatives[${i}];`);
  }

  const A = [
    [],
    [1.0 / 5.0],
    [3.0 / 40.0, 9.0 / 40.0],
    [44.0 / 45.0, -56.0 / 15.0, 32.0 / 9.0],
    [19372.0 / 6561.0, -25360.0 / 2187.0, 64448.0 / 6561.0, -212.0 / 729.0],
    [9017.0 / 3168.0, -355.0 / 33.0, 46732.0 / 5247.0, 49.0 / 176.0, -5103.0 / 18656.0],
    [35.0 / 384.0, 0.0, 500.0 / 1113.0, 125.0 / 192.0, -2187.0 / 6784.0, 11.0 / 84.0],
  ];
  const C = [0.0, 1.0 / 5.0, 3.0 / 10.0, 4.0 / 5.0, 8.0 / 9.0, 1.0, 1.0];
  const B5 = [35.0 / 384.0, 0.0, 500.0 / 1113.0, 125.0 / 192.0, -2187.0 / 6784.0, 11.0 / 84.0, 0.0];
  const B4 = [5179.0 / 57600.0, 0.0, 7571.0 / 16695.0, 393.0 / 640.0, -92097.0 / 339200.0, 187.0 / 2100.0, 1.0 / 40.0];

  for (let s = 1; s < 7; s++) {
    for (let i = 0; i < stateVRs.length; i++) {
      let sum = `vars[${stateVRs[i]}]`;
      const As = A[s] as number[];
      for (let j = 0; j < As.length; j++) {
        if (As[j] !== 0) sum += ` + h * ${As[j]} * k${j}[${i}]`;
      }
      lines.push(`    yTemp[${i}] = ${sum};`);
    }
    for (let i = 0; i < stateVRs.length; i++) {
      lines.push(`    vars[${stateVRs[i]}] = yTemp[${i}];`);
    }
    lines.push(`    modelTime = t + ${C[s]} * h;`);
    lines.push(`    getDerivatives();`);
    for (let i = 0; i < stateVRs.length; i++) {
      lines.push(`    k${s}[${i}] = derivatives[${i}];`);
    }
  }

  lines.push("    let err: f64 = 0.0;");
  for (let i = 0; i < stateVRs.length; i++) {
    let y5 = `vars[${stateVRs[i]}]`;
    for (let s = 0; s < 7; s++) {
      if (B5[s] !== 0) y5 += ` + h * ${B5[s]} * k${s}[${i}]`;
    }
    lines.push(`    yNew[${i}] = ${y5};`);

    let errI = `0.0`;
    for (let s = 0; s < 7; s++) {
      const e_s = (B5[s] as number) - (B4[s] as number);
      if (e_s !== 0) errI += ` + h * ${e_s} * k${s}[${i}]`;
    }
    lines.push(`    let errI_${i}: f64 = ${errI};`);
    lines.push(`    let sc_${i}: f64 = 1e-6 + 1e-6 * Math.max(Math.abs(vars[${stateVRs[i]}]), Math.abs(yNew[${i}]));`);
    lines.push(`    err = Math.max(err, Math.abs(errI_${i}) / sc_${i});`);
  }

  lines.push("    if (err <= 1.0) {");
  if (nEventIndicators > 0) {
    lines.push("      let crossing: boolean = false;");
    lines.push("      modelTime = t + h;");
    for (let i = 0; i < stateVRs.length; i++) lines.push(`      vars[${stateVRs[i]}] = yNew[${i}];`);
    lines.push("      getEventIndicators();");
    lines.push(`      for (let i = 0; i < ${nEventIndicators}; i++) {`);
    lines.push("        if (zPrev[i] * eventIndicators[i] < 0.0) { crossing = true; break; }");
    lines.push("      }");
    lines.push("      if (crossing && h > 1e-7) {");
    lines.push("        h *= 0.5;");
    lines.push("        continue;");
    lines.push("      }");
  }
  lines.push("      t += h;");
  for (let i = 0; i < stateVRs.length; i++) {
    lines.push(`      vars[${stateVRs[i]}] = yNew[${i}];`);
  }
  lines.push("      modelTime = t;");
  lines.push("      eventUpdate();");
  if (nEventIndicators > 0) {
    lines.push("      getEventIndicators();");
    lines.push(`      for (let i = 0; i < ${nEventIndicators}; i++) zPrev[i] = eventIndicators[i];`);
  }
  lines.push("      let factor: f64 = err > 0.0 ? Math.min(5.0, Math.max(0.2, 0.9 * Math.pow(err, -0.2))) : 5.0;");
  lines.push("      h = Math.min(h * factor, communicationStepSize);");
  lines.push("    } else {");
  lines.push("      let factor: f64 = Math.max(0.2, 0.9 * Math.pow(err, -0.2));");
  lines.push("      h = h * factor;");
  lines.push("    }");
  lines.push("  }"); // end while

  lines.push("  modelTime = tEnd;");
  lines.push("  getDerivatives();");
  lines.push("}");
  lines.push("");

  lines.push("export function getVar(vr: i32): f64 {");
  lines.push("  return vars[vr];");
  lines.push("}");
  lines.push("");

  lines.push("export function setVar(vr: i32, value: f64): void {");
  lines.push("  vars[vr] = value;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
