// SPDX-License-Identifier: AGPL-3.0-or-later

import { type ArenaDAEBuilder, BinOp, EqKind, ExprKind, UnaryOp } from "@modelscript/compiler";

import type { FmuOptions, FmuResult } from "./fmi.js";
import { binaryOpToJs, mapFunctionNameJs, sanitizeIdentifier } from "./transpiler-utils.js";

/**
 * Generate AssemblyScript compatible source file from a DAE and FMU result.
 * This can be compiled directly in the browser to WebAssembly using the AssemblyScript compiler.
 */
export function generateFmuAsSources(dae: ArenaDAEBuilder, fmuResult: FmuResult, options: FmuOptions): string {
  const id = options.modelIdentifier;
  const vars = fmuResult.scalarVariables;
  const nStates = fmuResult.modelStructure.derivatives.length;
  const nVars = vars.length;

  return generateModelAs(id, nVars, nStates, dae, fmuResult);
}

function exprToAs(dae: ArenaDAEBuilder, id: number): string {
  if (id < 0) return "0.0";
  switch (dae.getExprKind(id)) {
    case ExprKind.RealLiteral: {
      const val = dae.getExprRealValue(id);
      const s = val.toString();
      if (!s.includes(".") && !s.includes("e") && !s.includes("E")) return s + ".0";
      return s;
    }
    case ExprKind.IntLiteral:
      return `${dae.getExprData1(id)}.0`; // Cast to f64 implicitly via float string
    case ExprKind.BoolLiteral:
      return dae.getExprData1(id) !== 0 ? "1.0" : "0.0";
    case ExprKind.StringLiteral:
      return `0.0 /* string literals unsupported in AS f64 return */`;
    case ExprKind.Name:
      return varToAs(dae.interner.resolve(dae.getExprData1(id)));
    case ExprKind.Unary: {
      const uop = dae.getExprData1(id) as UnaryOp;
      const op = uop === UnaryOp.Negate ? "-" : "!";
      return `(${op}${exprToAs(dae, dae.getExprLeft(id))})`;
    }
    case ExprKind.Negate:
      return `(-${exprToAs(dae, dae.getExprLeft(id))})`;
    case ExprKind.Binary: {
      const op = dae.getExprData1(id) as BinOp;
      const lhs = exprToAs(dae, dae.getExprLeft(id));
      const rhs = exprToAs(dae, dae.getExprRight(id));
      const opStr = binaryOpToJs(op);
      if (opStr === "pow") return `Math.pow(${lhs}, ${rhs})`;
      return `(${lhs} ${opStr} ${rhs})`;
    }
    case ExprKind.Call: {
      const fname = dae.interner.resolve(dae.getExprData1(id));
      const argCount = dae.getExprRight(id);
      if (fname === "initial") return "(isInitPhase ? 1.0 : 0.0)";
      if (fname === "terminal") return "0.0";
      if (fname === "assert" && argCount >= 2) {
        const cond = exprToAs(dae, dae.getExprLeft(id));
        return `((${cond}) ? 0.0 : (terminate = true, 0.0))`;
      }
      const args: string[] = [];
      for (let i = 0; i < argCount; i++) {
        args.push(exprToAs(dae, dae.getExprLeft(id + i)));
      }
      const mappedName = mapFunctionNameJs(fname);
      return `${mappedName}(${args.join(", ")})`;
    }
    case ExprKind.IfElse: {
      const cond = exprToAs(dae, dae.getExprData1(id));
      const then = exprToAs(dae, dae.getExprLeft(id));
      const els = exprToAs(dae, dae.getExprRight(id));
      return `((${cond}) != 0.0 ? ${then} : ${els})`;
    }
    default:
      return "0.0";
  }
}

function varToAs(name: string): string {
  if (name === "time") return "modelTime";
  return `vars[VR_${sanitizeIdentifier(name).toUpperCase()}]`;
}

function generateModelAs(id: string, nVars: number, nStates: number, dae: ArenaDAEBuilder, result: FmuResult): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by ModelScript — AssemblyScript FMI");
  lines.push("");

  // Variable Constants
  for (const sv of result.scalarVariables) {
    const cName = sanitizeIdentifier(sv.name).toUpperCase();
    lines.push(`const VR_${cName}: i32 = ${sv.valueReference};`);
  }

  lines.push("");
  lines.push(`export const vars = new Float64Array(${nVars + 1});`);
  lines.push(`export const states = new Float64Array(${nStates + 1});`);
  lines.push(`export const derivatives = new Float64Array(${nStates + 1});`);
  lines.push(`export let modelTime: f64 = 0.0;`);
  lines.push(`export let isInitPhase: boolean = true;`);
  lines.push(`export let terminate: boolean = false;`);
  lines.push("");

  lines.push("export function initModel(): void {");
  lines.push("  isInitPhase = true;");
  lines.push("  modelTime = 0.0;");
  lines.push("  terminate = false;");

  // Initial parameters
  for (const sv of result.scalarVariables) {
    if (sv.start !== undefined) {
      lines.push(`  vars[${sv.valueReference}] = ${sv.start};`);
    }
  }

  lines.push("}");
  lines.push("");

  lines.push("export function getDerivatives(): void {");

  // Extract state variables and mapping
  const derVRs = result.modelStructure.derivatives;
  const stateVRs: number[] = [];
  const derVars = result.scalarVariables.filter((sv) => sv.name.startsWith("der("));

  for (const dv of derVars) {
    if (dv.derivative !== undefined) {
      stateVRs.push(dv.derivative);
    }
  }

  for (let i = 0; i < stateVRs.length; i++) {
    lines.push(`  states[${i}] = vars[${stateVRs[i]}];`);
  }

  for (let idx = 0; idx < dae.eqCount; idx++) {
    if (dae.getEqKind(idx) !== EqKind.Simple) continue;
    const lhs = dae.getEqLhs(idx);
    const rhs = dae.getEqRhs(idx);
    if (dae.getExprKind(lhs) === ExprKind.Name) {
      const name = dae.interner.resolve(dae.getExprData1(lhs));
      lines.push(`  ${varToAs(name)} = ${exprToAs(dae, rhs)};`);
    }
  }

  for (let i = 0; i < derVRs.length; i++) {
    lines.push(`  derivatives[${i}] = vars[${derVRs[i]}];`);
  }

  lines.push("}");
  lines.push("");

  lines.push("export function doStep(currentCommunicationPoint: f64, communicationStepSize: f64): void {");
  lines.push("  isInitPhase = false;");
  lines.push("  modelTime = currentCommunicationPoint;");
  lines.push("  let dt: f64 = communicationStepSize;");
  lines.push("  ");
  lines.push("  // Basic explicit forward Euler step in AssemblyScript");
  lines.push("  getDerivatives();");
  for (let i = 0; i < stateVRs.length; i++) {
    lines.push(`  vars[${stateVRs[i]}] = vars[${stateVRs[i]}] + derivatives[${i}] * dt;`);
  }
  lines.push("  modelTime += dt;");
  lines.push("  getDerivatives();");
  lines.push("}");
  lines.push("");

  lines.push("export function getVar(vr: i32): f64 {");
  lines.push("  return vars[vr];");
  lines.push("}");
  lines.push("");

  lines.push("export function setVar(vr: i32, value: f64): void {");
  lines.push("  vars[vr] = value;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
