// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * RS-274X Gerber and Excellon Drill Export.
 *
 * Generates standard manufacturing files from PCB layout data:
 *   - Gerber (RS-274X) for copper layers, silkscreen, solder mask
 *   - Excellon for drill files (vias, through-hole pads)
 *
 * Each layer produces a separate file matching standard Gerber conventions.
 *
 * Reference: IPC-D-356, RS-274X specification.
 */

import type { NetlistComponent, NetlistGraph } from "./netlist.js";

// ── Public types ──

/** PCB trace segment for Gerber export. */
export interface TraceSegment {
  /** Start point [x, y] in mm. */
  start: [number, number];
  /** End point [x, y] in mm. */
  end: [number, number];
  /** Trace width in mm. */
  width: number;
  /** Layer name (e.g., "TopCopper"). */
  layer: string;
  /** Net name. */
  net: string;
}

/** PCB pad for Gerber export. */
export interface PadDefinition {
  /** Center position [x, y] in mm. */
  center: [number, number];
  /** Pad shape. */
  shape: "circle" | "rect" | "oval" | "roundrect";
  /** Pad width in mm. */
  width: number;
  /** Pad height in mm. */
  height: number;
  /** Drill diameter (0 = SMD). */
  drill: number;
  /** Layer name. */
  layer: string;
  /** Net name. */
  net: string;
  /** Component name. */
  component: string;
}

/** Via definition for Gerber/Excellon export. */
export interface ViaDefinition {
  /** Position [x, y] in mm. */
  center: [number, number];
  /** Drill diameter in mm. */
  drill: number;
  /** Annular ring width in mm. */
  annularRing: number;
  /** Net name. */
  net: string;
}

/** Board outline polygon. */
export interface BoardOutline {
  /** Polygon vertices [[x1,y1], [x2,y2], ...] in mm. */
  vertices: [number, number][];
}

/** Complete PCB layout data for export. */
export interface PCBLayout {
  traces: TraceSegment[];
  pads: PadDefinition[];
  vias: ViaDefinition[];
  outline: BoardOutline | null;
  netlist: NetlistGraph;
}

/** Generated manufacturing file. */
export interface ManufacturingFile {
  filename: string;
  content: string;
  layer: string;
}

// ── Gerber RS-274X generation ──

const MM_TO_GERBER = 1e6; // Gerber uses 6 decimal places in mm mode

/**
 * Generate all manufacturing files from a PCB layout.
 */
export function generateManufacturingFiles(layout: PCBLayout): ManufacturingFile[] {
  const files: ManufacturingFile[] = [];

  // Copper layers
  const copperLayers = ["TopCopper", "BottomCopper", "InnerCopper1", "InnerCopper2"];
  for (const layer of copperLayers) {
    const layerTraces = layout.traces.filter((t) => t.layer === layer);
    const layerPads = layout.pads.filter((p) => p.layer === layer);
    if (layerTraces.length === 0 && layerPads.length === 0) continue;
    files.push({
      filename: `${layer}.gbr`,
      content: generateCopperGerber(layerTraces, layerPads, layer),
      layer,
    });
  }

  // Silkscreen layers
  for (const layer of ["TopSilkscreen", "BottomSilkscreen"]) {
    const content = generateSilkscreenGerber(layout.netlist.components, layer);
    if (content) {
      files.push({ filename: `${layer}.gbr`, content, layer });
    }
  }

  // Solder mask layers
  for (const layer of ["TopSolderMask", "BottomSolderMask"]) {
    const copperLayer = layer === "TopSolderMask" ? "TopCopper" : "BottomCopper";
    const layerPads = layout.pads.filter((p) => p.layer === copperLayer);
    if (layerPads.length === 0) continue;
    files.push({
      filename: `${layer}.gbr`,
      content: generateSolderMaskGerber(layerPads, layer),
      layer,
    });
  }

  // Board outline
  if (layout.outline) {
    files.push({
      filename: "BoardOutline.gbr",
      content: generateOutlineGerber(layout.outline),
      layer: "BoardOutline",
    });
  }

  // Drill file (Excellon)
  const drillPads = layout.pads.filter((p) => p.drill > 0);
  if (drillPads.length > 0 || layout.vias.length > 0) {
    files.push({
      filename: "drill.xln",
      content: generateExcellonDrill(drillPads, layout.vias),
      layer: "Drill",
    });
  }

  return files;
}

/**
 * Generate RS-274X Gerber content for a copper layer.
 */
function generateCopperGerber(traces: TraceSegment[], pads: PadDefinition[], layer: string): string {
  const lines: string[] = [];

  // Header
  lines.push("%FSLAX46Y46*%"); // Format: leading zeros omitted, 4.6 format
  lines.push("%MOIN*%"); // Units: millimeters (encoded as integer × 10⁻⁶)
  lines.push("%MOMM*%");
  lines.push(`G04 Layer: ${layer}*`);
  lines.push("G04 Generated by ModelScript ECAD*");

  // Aperture definitions
  const apertures = new Map<string, number>();
  let apertureIdx = 10; // Gerber apertures start at D10

  // Collect unique aperture sizes
  for (const trace of traces) {
    const key = `C,${trace.width.toFixed(4)}`;
    if (!apertures.has(key)) {
      apertures.set(key, apertureIdx++);
      lines.push(`%ADD${apertures.get(key)}${key}*%`);
    }
  }

  for (const pad of pads) {
    const key = padApertureKey(pad);
    if (!apertures.has(key)) {
      apertures.set(key, apertureIdx++);
      lines.push(`%ADD${apertures.get(key)}${key}*%`);
    }
  }

  // Draw traces
  for (const trace of traces) {
    const key = `C,${trace.width.toFixed(4)}`;
    const dCode = apertures.get(key);
    if (dCode === undefined) continue;
    lines.push(`D${dCode}*`);
    lines.push(`X${toGerberCoord(trace.start[0])}Y${toGerberCoord(trace.start[1])}D02*`); // Move
    lines.push(`X${toGerberCoord(trace.end[0])}Y${toGerberCoord(trace.end[1])}D01*`); // Draw
  }

  // Flash pads
  for (const pad of pads) {
    const key = padApertureKey(pad);
    const dCode = apertures.get(key);
    if (dCode === undefined) continue;
    lines.push(`D${dCode}*`);
    lines.push(`X${toGerberCoord(pad.center[0])}Y${toGerberCoord(pad.center[1])}D03*`); // Flash
  }

  // End of file
  lines.push("M02*");

  return lines.join("\n");
}

/**
 * Generate silkscreen Gerber (component reference designators).
 */
function generateSilkscreenGerber(components: NetlistComponent[], layer: string): string | null {
  if (components.length === 0) return null;

  const lines: string[] = [];
  lines.push("%FSLAX46Y46*%");
  lines.push("%MOMM*%");
  lines.push(`G04 Layer: ${layer}*`);
  lines.push("G04 Generated by ModelScript ECAD*");

  // Thin line aperture for text outlines
  lines.push("%ADD10C,0.150*%");
  lines.push("D10*");

  // Simple reference designator placement
  for (const comp of components) {
    if (!comp.placement) continue;
    const targetLayer = layer === "TopSilkscreen" ? "TopCopper" : "BottomCopper";
    if (comp.placement.layer !== targetLayer) continue;

    const x = comp.placement.x;
    const y = comp.placement.y + 2; // Offset text above component
    // Simple cross-hair marker at component origin
    lines.push(`X${toGerberCoord(x - 0.5)}Y${toGerberCoord(y)}D02*`);
    lines.push(`X${toGerberCoord(x + 0.5)}Y${toGerberCoord(y)}D01*`);
    lines.push(`X${toGerberCoord(x)}Y${toGerberCoord(y - 0.5)}D02*`);
    lines.push(`X${toGerberCoord(x)}Y${toGerberCoord(y + 0.5)}D01*`);
  }

  lines.push("M02*");
  return lines.join("\n");
}

/**
 * Generate solder mask Gerber (pad openings).
 */
function generateSolderMaskGerber(pads: PadDefinition[], layer: string): string {
  const lines: string[] = [];
  lines.push("%FSLAX46Y46*%");
  lines.push("%MOMM*%");
  lines.push(`G04 Layer: ${layer}*`);
  lines.push("G04 Generated by ModelScript ECAD*");
  lines.push("%IPNEG*%"); // Negative polarity for mask openings

  const apertures = new Map<string, number>();
  let apertureIdx = 10;

  // Mask openings are slightly larger than pads (0.1mm expansion)
  for (const pad of pads) {
    const expanded = { ...pad, width: pad.width + 0.1, height: pad.height + 0.1 };
    const key = padApertureKey(expanded);
    if (!apertures.has(key)) {
      apertures.set(key, apertureIdx++);
      lines.push(`%ADD${apertures.get(key)}${key}*%`);
    }
    const dCode = apertures.get(key);
    if (dCode === undefined) continue;
    lines.push(`D${dCode}*`);
    lines.push(`X${toGerberCoord(pad.center[0])}Y${toGerberCoord(pad.center[1])}D03*`);
  }

  lines.push("M02*");
  return lines.join("\n");
}

/**
 * Generate board outline Gerber.
 */
function generateOutlineGerber(outline: BoardOutline): string {
  const lines: string[] = [];
  lines.push("%FSLAX46Y46*%");
  lines.push("%MOMM*%");
  lines.push("G04 Layer: BoardOutline*");
  lines.push("G04 Generated by ModelScript ECAD*");

  // Thin line for outline
  lines.push("%ADD10C,0.100*%");
  lines.push("D10*");

  if (outline.vertices.length >= 2) {
    const first = outline.vertices[0]!; // eslint-disable-line @typescript-eslint/no-non-null-assertion
    lines.push(`X${toGerberCoord(first[0])}Y${toGerberCoord(first[1])}D02*`);
    for (let i = 1; i < outline.vertices.length; i++) {
      const v = outline.vertices[i]!; // eslint-disable-line @typescript-eslint/no-non-null-assertion
      lines.push(`X${toGerberCoord(v[0])}Y${toGerberCoord(v[1])}D01*`);
    }
    // Close the polygon
    lines.push(`X${toGerberCoord(first[0])}Y${toGerberCoord(first[1])}D01*`);
  }

  lines.push("M02*");
  return lines.join("\n");
}

// ── Excellon drill generation ──

/**
 * Generate Excellon drill file for through-hole pads and vias.
 */
function generateExcellonDrill(pads: PadDefinition[], vias: ViaDefinition[]): string {
  const lines: string[] = [];

  // Header
  lines.push("M48"); // Header start
  lines.push("; Generated by ModelScript ECAD");
  lines.push("METRIC,TZ"); // Metric, trailing zeros

  // Collect unique drill sizes
  const drillSizes = new Map<number, number>(); // diameter → tool number
  let toolNum = 1;

  for (const pad of pads) {
    if (pad.drill > 0 && !drillSizes.has(pad.drill)) {
      drillSizes.set(pad.drill, toolNum++);
    }
  }
  for (const via of vias) {
    if (!drillSizes.has(via.drill)) {
      drillSizes.set(via.drill, toolNum++);
    }
  }

  // Tool definitions
  for (const [size, num] of drillSizes) {
    lines.push(`T${String(num).padStart(2, "0")}C${size.toFixed(3)}`);
  }

  lines.push("%"); // End of header

  // Drill hits grouped by tool
  for (const [size, num] of drillSizes) {
    lines.push(`T${String(num).padStart(2, "0")}`);

    // Pad drill hits
    for (const pad of pads) {
      if (pad.drill === size) {
        lines.push(`X${toExcellonCoord(pad.center[0])}Y${toExcellonCoord(pad.center[1])}`);
      }
    }

    // Via drill hits
    for (const via of vias) {
      if (via.drill === size) {
        lines.push(`X${toExcellonCoord(via.center[0])}Y${toExcellonCoord(via.center[1])}`);
      }
    }
  }

  lines.push("M30"); // End of program

  return lines.join("\n");
}

// ── Helpers ──

function toGerberCoord(mm: number): string {
  return Math.round(mm * MM_TO_GERBER).toString();
}

function toExcellonCoord(mm: number): string {
  return (mm * 1000).toFixed(0); // Excellon uses microns with METRIC,TZ
}

function padApertureKey(pad: PadDefinition | { shape: string; width: number; height: number }): string {
  switch (pad.shape) {
    case "circle":
      return `C,${pad.width.toFixed(4)}`;
    case "rect":
      return `R,${pad.width.toFixed(4)}X${pad.height.toFixed(4)}`;
    case "oval":
      return `O,${pad.width.toFixed(4)}X${pad.height.toFixed(4)}`;
    case "roundrect":
      return `R,${pad.width.toFixed(4)}X${pad.height.toFixed(4)}`; // Approximate
    default:
      return `C,${pad.width.toFixed(4)}`;
  }
}
